//! Tests for D3 — *partition generates layout*.
//!
//! The cpu tests are always runnable and carry the whole construction: the generated tables, the
//! adjoint identity, the assembly identity against a **directly assembled matrix**, the two scatter
//! receipts and their refusals, the colouring and its properness, and the hostile-declaration
//! refusals.  The device tests are `#[ignore]`d and assert bit-for-bit agreement with the exact cpu
//! reference on the three declared cases, reporting honestly separated costs.
//!
//! **`mount` cannot depend on `holonic-engine`**: the engine already depends on `mount`
//! (`crates/holonic-engine/Cargo.toml:16`), so a dependency either way — including a
//! dev-dependency — would be a cycle through the crate this owner lives in.  Case (c) therefore
//! builds an *equivalent* irregular incidence in the test rather than importing
//! `physical_constraint_grading`'s contact complex: ragged region widths, non-monotone address
//! order inside a region, high and uneven address multiplicity, and regions sharing addresses with
//! several others at once.  That is stated rather than implied.

use super::*;
use crate::launch_law::{LaunchClause, LaunchLimits, ScatterLaw};
use crate::Dim3;

// ---------------------------------------------------------------------------------------------
// Fixtures — every one deterministic and exact; no float and no random source anywhere.
// ---------------------------------------------------------------------------------------------

/// **Case (a): a 1D chain of overlapping tiles.**  Region `r` covers `width` consecutive addresses
/// beginning at `r * (width - overlap)`, so consecutive regions share `overlap` addresses.
fn chain_1d(regions: usize, width: usize, overlap: usize) -> IncidenceDeclaration {
    assert!(regions > 0 && width > overlap, "a chain overlaps by less than its width");
    let stride = width - overlap;
    let global_extent = (regions - 1) * stride + width;
    let mut addresses = Vec::with_capacity(regions * width);
    for region in 0..regions {
        for slot in 0..width {
            addresses.push((region * stride + slot) as u32);
        }
    }
    IncidenceDeclaration::uniform(global_extent, width, addresses).expect("a lawful chain")
}

/// **Case (b): a 2D grid with 4-neighbour overlap.**  One region per interior cell, incident to the
/// cell and its four neighbours; adjacent regions therefore share addresses.
fn grid_2d(rows: usize, columns: usize) -> IncidenceDeclaration {
    assert!(rows > 2 && columns > 2, "a 4-neighbour stencil needs an interior");
    let global_extent = rows * columns;
    let mut addresses = Vec::new();
    for row in 1..(rows - 1) {
        for column in 1..(columns - 1) {
            let at = row * columns + column;
            addresses.push(at as u32);
            addresses.push((at - columns) as u32);
            addresses.push((at + columns) as u32);
            addresses.push((at - 1) as u32);
            addresses.push((at + 1) as u32);
        }
    }
    IncidenceDeclaration::uniform(global_extent, 5, addresses).expect("a lawful grid")
}

/// **Case (c): an irregular contact incidence**, structurally equivalent to a contact complex's
/// cell-to-vertex incidence: ragged widths between 2 and 6, addresses not in ascending order inside
/// a region, and an uneven address multiplicity so that some addresses are reached by one region
/// and others by five.  Generated by an exact integer recurrence, so it is reproducible and carries
/// no float.
fn irregular_contact(regions: usize, global_extent: usize) -> IncidenceDeclaration {
    assert!(regions > 0 && global_extent >= 8);
    let mut offsets = Vec::with_capacity(regions + 1);
    let mut addresses: Vec<u32> = Vec::new();
    // An exact linear congruential walk over the address space: deterministic, integral, and with
    // no arithmetic that could leave its wire (every operand is below 2^32 and the modulus is
    // applied before the next step).
    let mut state: u64 = 0x9E37_79B9;
    offsets.push(0usize);
    for region in 0..regions {
        let width = 2 + (region % 5);
        for _ in 0..width {
            state = (state.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407))
                >> 1;
            addresses.push((state % global_extent as u64) as u32);
        }
        offsets.push(addresses.len());
    }
    IncidenceDeclaration::new(global_extent, offsets, addresses).expect("a lawful irregular table")
}

/// A symmetric dense local operator over the device's own ring: `L[j][k] = 1 + j + k + j·k`,
/// canonical in `Z/(2^61 - 1)`.  Symmetric by construction, so
/// `SectionLayout.Incidence.assembled_symm` applies.
fn symmetric_operator(width: usize) -> LocalOperator<u64> {
    let ring = ModularWords::DEVICE;
    let mut entries = Vec::with_capacity(width * width);
    for row in 0..width {
        for column in 0..width {
            let value = 1 + row as u64 + column as u64 + (row as u64) * (column as u64);
            entries.push(ring.canonical(value));
        }
    }
    LocalOperator::dense(width, entries).expect("a lawful dense operator")
}

/// A deterministic exact global field.
fn field(extent: usize) -> Vec<u64> {
    let ring = ModularWords::DEVICE;
    (0..extent)
        .map(|at| ring.canonical(3 + 7 * at as u64 + (at as u64) * (at as u64)))
        .collect()
}

fn accumulated() -> ScatterRequest {
    ScatterRequest::Accumulated(AccumulationLaw::ModularAdd {
        modulus: section_cuda::MODULUS,
    })
}

// ---------------------------------------------------------------------------------------------
// The declaration and what it generates
// ---------------------------------------------------------------------------------------------

#[test]
fn a_uniform_declaration_generates_its_tile_extents_and_a_uniform_gather_partition() {
    let layout = SectionLayout::generate(chain_1d(6, 4, 2), accumulated()).expect("generated");
    let tile = layout.tile();
    assert_eq!(tile.regions(), 6);
    assert_eq!(tile.slots(), 24);
    assert_eq!(tile.max_width(), 4);
    assert_eq!(tile.uniform_width(), Some(4));
    // Generated, not authored: four exact 64-bit words.
    assert_eq!(tile.tile_bytes(), 32);

    let partition = layout.gather_partition().expect("a generated partition");
    assert_eq!(partition.regions(), 6);
    assert_eq!(partition.elements(), 24);
    assert_eq!(partition.region(0), Some(0..4));
    assert_eq!(partition.region(5), Some(20..24));
    partition
        .verify_pairwise_disjoint()
        .expect("the generated gather partition is disjoint");
}

#[test]
fn a_ragged_declaration_generates_an_offsets_gather_partition() {
    let layout = SectionLayout::generate(irregular_contact(9, 32), accumulated()).expect("generated");
    assert_eq!(layout.tile().uniform_width(), None);
    let partition = layout.gather_partition().expect("a generated partition");
    assert_eq!(partition.regions(), layout.regions());
    assert_eq!(partition.elements(), layout.slots());
    partition
        .verify_pairwise_disjoint()
        .expect("the generated gather partition is disjoint");
    // Every region's partition region is exactly its declared slot span.
    for region in 0..layout.regions() {
        let span = partition.region(region).expect("a region");
        assert_eq!(span.start, layout.incidence().offsets()[region]);
        assert_eq!(span.end, layout.incidence().offsets()[region + 1]);
    }
}

#[test]
fn the_generated_transpose_is_the_transpose_of_the_generated_gather() {
    let layout = SectionLayout::generate(grid_2d(5, 5), accumulated()).expect("generated");
    let transpose = layout.transpose();
    // Every (address, slot) of the gather table appears exactly once in the transpose.
    let mut seen = 0usize;
    for at in 0..transpose.touched().len() {
        let address = transpose.touched()[at];
        for slot in transpose.fibre(at).expect("a fibre") {
            assert_eq!(layout.gather_index()[*slot as usize], address);
            seen += 1;
        }
    }
    assert_eq!(seen, layout.slots());
    assert!(transpose.max_multiplicity() > 1, "the grid overlaps");
}

// ---------------------------------------------------------------------------------------------
// Hostile declarations — every one a typed refusal naming exactly one clause
// ---------------------------------------------------------------------------------------------

#[test]
fn a_zero_global_extent_is_refused() {
    let refusal = IncidenceDeclaration::new(0, vec![0, 1], vec![0]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::PositiveGlobalExtent);
}

#[test]
fn a_global_extent_past_the_index_wire_is_refused_rather_than_truncated() {
    let refusal = IncidenceDeclaration::new(u32::MAX as usize + 1, vec![0, 1], vec![0])
        .expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::GlobalExtentWire);
}

#[test]
fn an_address_past_the_declared_extent_is_refused_naming_the_slot() {
    let refusal = IncidenceDeclaration::new(4, vec![0, 2], vec![1, 9]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::AddressWithinExtent);
    assert!(refusal.detail.contains("slot 1"), "{}", refusal.detail);
}

#[test]
fn a_descending_offsets_table_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![0, 3, 2], vec![0, 1, 2]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::RegionWidth);
}

#[test]
fn an_empty_region_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![0, 2, 2], vec![0, 1]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::RegionWidth);
}

#[test]
fn an_offsets_table_not_starting_at_zero_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![1, 3], vec![0, 1, 2]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::OffsetsLength);
}

#[test]
fn an_offsets_table_that_does_not_end_at_the_address_table_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![0, 2], vec![0, 1, 2]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::OffsetsEnd);
}

#[test]
fn a_uniform_width_that_does_not_divide_the_address_table_is_refused() {
    let refusal = IncidenceDeclaration::uniform(8, 3, vec![0, 1, 2, 3]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::OffsetsEnd);
}

#[test]
fn a_local_operator_whose_table_is_not_its_declared_square_is_refused() {
    let refusal = LocalOperator::dense(3, vec![1u64; 8]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::LocalOperatorWidth);
}

// ---------------------------------------------------------------------------------------------
// The scatter receipt: exactly one of two, never neither
// ---------------------------------------------------------------------------------------------

#[test]
fn a_colliding_incidence_claiming_injectivity_is_refused_naming_the_colliding_slots() {
    let incidence = IncidenceDeclaration::new(8, vec![0, 2, 4], vec![1, 2, 5, 2]).expect("lawful");
    let refusal =
        SectionLayout::generate(incidence, ScatterRequest::Injective).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::ScatterReceipt);
    assert!(refusal.detail.contains("slots 1 and 3"), "{}", refusal.detail);
    assert!(refusal.detail.contains("global address 2"), "{}", refusal.detail);
}

#[test]
fn the_same_colliding_incidence_is_admitted_under_a_declared_exact_accumulation() {
    let incidence = IncidenceDeclaration::new(8, vec![0, 2, 4], vec![1, 2, 5, 2]).expect("lawful");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    assert!(matches!(
        layout.receipt(),
        ScatterReceipt::Accumulated(AccumulationLaw::ModularAdd { .. })
    ));
    assert_eq!(layout.receipt().scatter_law(), ScatterLaw::Accumulated);
}

#[test]
fn an_injective_incidence_generates_the_injective_scatter_partition() {
    let incidence = IncidenceDeclaration::uniform(8, 2, vec![0, 1, 4, 5]).expect("lawful");
    let layout = SectionLayout::generate(incidence, ScatterRequest::Injective).expect("generated");
    assert_eq!(layout.receipt(), ScatterReceipt::Injective);
    let partition = layout.scatter_partition().expect("an injective partition");
    assert_eq!(partition.scatter_law(), Some(ScatterLaw::Injective));
    partition
        .verify_pairwise_disjoint()
        .expect("an injective scatter is disjoint");
}

#[test]
fn an_accumulating_receipt_has_no_whole_scatter_partition_and_says_why() {
    let layout = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    let refusal = layout.scatter_partition().expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::ScatterReceipt);
    assert!(refusal.detail.contains("colour"), "{}", refusal.detail);
}

#[test]
fn an_injective_receipt_refuses_the_accumulating_launch_requirement_and_the_reverse() {
    let injective = SectionLayout::generate(
        IncidenceDeclaration::uniform(8, 2, vec![0, 1, 4, 5]).expect("lawful"),
        ScatterRequest::Injective,
    )
    .expect("generated");
    assert_eq!(
        injective.scatter_add_requirement(1).expect_err("refused").clause,
        SectionClause::ScatterReceipt
    );
    let accumulating = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    assert_eq!(
        accumulating.scatter_store_requirement().expect_err("refused").clause,
        SectionClause::ScatterReceipt
    );
}

#[test]
fn a_degenerate_modulus_does_not_name_a_ring() {
    let refusal = SectionLayout::generate(
        chain_1d(4, 4, 2),
        ScatterRequest::Accumulated(AccumulationLaw::ModularAdd { modulus: 1 }),
    )
    .expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::AccumulationLaw);
    assert_eq!(
        ModularWords::new(0).expect_err("refused").clause,
        SectionClause::AccumulationLaw
    );
}

// ---------------------------------------------------------------------------------------------
// The exact arithmetic
// ---------------------------------------------------------------------------------------------

#[test]
fn the_device_ring_agrees_with_the_general_modular_path_over_the_same_modulus() {
    // `ModularWords::DEVICE` dispatches to `soma_abi::section_layout_cuda`, the same code the nvptx
    // kernels compile.  This holds it against the ordinary 128-bit remainder path.
    let device = ModularWords::DEVICE;
    let modulus = section_cuda::MODULUS;
    let probes: [u64; 9] = [
        0,
        1,
        2,
        modulus - 1,
        modulus / 2,
        modulus / 3,
        1 << 60,
        (1 << 61) - 3,
        1_234_567_890_123_456_789,
    ];
    for left in probes {
        let left = left % modulus;
        for right in probes {
            let right = right % modulus;
            let general_sum = (((left as u128) + (right as u128)) % (modulus as u128)) as u64;
            let general_product = (((left as u128) * (right as u128)) % (modulus as u128)) as u64;
            assert_eq!(device.add(left, right), Some(general_sum), "{left} + {right}");
            assert_eq!(device.mul(left, right), Some(general_product), "{left} * {right}");
        }
    }
}

#[test]
fn the_device_ring_is_associative_and_commutative_on_its_probes() {
    // The property an accumulating scatter depends on, witnessed executably.  It is what a float
    // accumulation does not have and why `AccumulationLaw` carries no float variant.
    let ring = ModularWords::DEVICE;
    let probes: [u64; 5] = [0, 1, 7, section_cuda::MODULUS - 1, 1 << 59];
    for a in probes {
        for b in probes {
            assert_eq!(ring.add(a, b), ring.add(b, a));
            for c in probes {
                let left = ring.add(ring.add(a, b).unwrap(), c);
                let right = ring.add(a, ring.add(b, c).unwrap());
                assert_eq!(left, right);
            }
        }
    }
}

#[test]
fn a_checked_integer_sum_past_its_wire_is_refused_rather_than_wrapped() {
    let ring = CheckedIntegers;
    assert_eq!(ring.add(i64::MAX, 1), None);
    assert_eq!(ring.mul(i64::MAX, 2), None);
    // And the refusal reaches the operator, rather than a wrapped value reaching the result.
    let layout = SectionLayout::generate(
        chain_1d(3, 2, 1),
        ScatterRequest::Accumulated(AccumulationLaw::IntegerAdd),
    )
    .expect("generated");
    let operator = LocalOperator::dense(2, vec![i64::MAX, 1, 1, 1]).expect("lawful");
    let x = vec![i64::MAX; layout.global_extent()];
    let refusal = layout
        .apply_reference(&ring, &operator, &x)
        .expect_err("the exact product leaves the wire");
    assert_eq!(refusal.clause, SectionClause::ExactArithmetic);
}

// ---------------------------------------------------------------------------------------------
// The adjoint and the assembly identity
// ---------------------------------------------------------------------------------------------

#[test]
fn scatter_is_the_transpose_of_gather_on_every_declared_case() {
    let ring = ModularWords::DEVICE;
    for layout in [
        SectionLayout::generate(chain_1d(7, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(11, 24), accumulated()).expect("generated"),
    ] {
        let x = field(layout.global_extent());
        let y: Vec<u64> = (0..layout.slots())
            .map(|slot| ring.canonical(5 + 11 * slot as u64))
            .collect();
        let (left, right) = layout.verify_adjoint(&ring, &x, &y).expect("witnessed");
        assert_eq!(
            left, right,
            "<gather x, y> and <x, scatterAdd y> disagree on a {}-region declaration",
            layout.regions()
        );
    }
}

#[test]
fn the_generated_operator_equals_the_directly_assembled_matrix() {
    let ring = ModularWords::DEVICE;
    for layout in [
        SectionLayout::generate(chain_1d(7, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(11, 24), accumulated()).expect("generated"),
    ] {
        let operator = symmetric_operator(layout.tile().max_width());
        let x = field(layout.global_extent());
        let generated = layout
            .apply_reference(&ring, &operator, &x)
            .expect("the generated operator applies");
        let matrix = layout
            .assemble_dense(&ring, &operator, 1 << 20)
            .expect("the direct assembly fits the declared ceiling");
        let assembled = layout
            .apply_assembled(&ring, &matrix, &x)
            .expect("the assembled matrix applies");
        assert_eq!(
            generated, assembled,
            "scatterAdd . applyLocal . gather is not the assembled operator on a {}-region \
             declaration",
            layout.regions()
        );
    }
}

#[test]
fn a_symmetric_local_operator_assembles_to_a_symmetric_global_matrix() {
    let ring = ModularWords::DEVICE;
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let operator = symmetric_operator(layout.tile().max_width());
    assert!(operator.is_symmetric());
    let extent = layout.global_extent();
    let matrix = layout
        .assemble_dense(&ring, &operator, 1 << 20)
        .expect("assembled");
    for row in 0..extent {
        for column in 0..extent {
            assert_eq!(
                matrix[row * extent + column],
                matrix[column * extent + row],
                "the assembled matrix is asymmetric at ({row}, {column})"
            );
        }
    }
}

#[test]
fn a_dense_assembly_past_the_declared_entry_ceiling_is_refused_before_it_allocates() {
    let ring = ModularWords::DEVICE;
    let layout = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    let operator = symmetric_operator(layout.tile().max_width());
    let refusal = layout
        .assemble_dense(&ring, &operator, 4)
        .expect_err("the ceiling refuses it");
    assert_eq!(refusal.clause, SectionClause::WorkCeiling);
}

#[test]
fn an_injective_scatter_reference_agrees_with_the_accumulating_one() {
    // `SectionLayout.Incidence.scatterAdd_of_injective`: through an injective incidence the
    // accumulation degenerates to a store, so the two device arms compute the same field.
    let ring = ModularWords::DEVICE;
    let addresses: Vec<u32> = (0..12u32).collect();
    let injective = SectionLayout::generate(
        IncidenceDeclaration::uniform(12, 3, addresses.clone()).expect("lawful"),
        ScatterRequest::Injective,
    )
    .expect("generated");
    let accumulating = SectionLayout::generate(
        IncidenceDeclaration::uniform(12, 3, addresses).expect("lawful"),
        accumulated(),
    )
    .expect("generated");
    let operator = symmetric_operator(3);
    let x = field(12);
    assert_eq!(
        injective.apply_reference(&ring, &operator, &x).expect("applies"),
        accumulating.apply_reference(&ring, &operator, &x).expect("applies")
    );
}

// ---------------------------------------------------------------------------------------------
// The colouring
// ---------------------------------------------------------------------------------------------

#[test]
fn the_scatter_reference_refuses_a_field_that_is_not_the_declared_extent() {
    // The public scatter mouth takes the destination field rather than allocating one, so this
    // owner never allocates from the *declared* global extent; the length is checked instead.
    let ring = ModularWords::DEVICE;
    let layout = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    let tile = vec![0u64; layout.slots()];
    let mut short = vec![0u64; layout.global_extent() - 1];
    assert_eq!(
        layout
            .scatter_reference(&ring, &tile, &mut short)
            .expect_err("refused")
            .clause,
        SectionClause::SpanExtent
    );
    let narrow_tile = vec![0u64; layout.slots() - 1];
    let mut field = vec![0u64; layout.global_extent()];
    assert_eq!(
        layout
            .scatter_reference(&ring, &narrow_tile, &mut field)
            .expect_err("refused")
            .clause,
        SectionClause::SpanExtent
    );
}

#[test]
fn the_generated_colouring_is_proper_on_every_declared_case() {
    for layout in [
        SectionLayout::generate(chain_1d(9, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(7, 6), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(17, 24), accumulated()).expect("generated"),
    ] {
        let colouring = layout.colouring(1 << 20).expect("a colouring");
        colouring
            .verify_proper(&layout)
            .expect("the greedy colouring is proper");
        assert!(colouring.colour_count() >= 1);
        // Every region carries exactly one colour and every colour class is non-empty.
        let mut counted = 0usize;
        for colour in 0..colouring.colour_count() {
            let class = colouring.class(colour).expect("a class");
            assert!(!class.is_empty());
            counted += class.len();
            for region in class {
                assert_eq!(colouring.colour_of(*region as usize), Some(colour as u32));
            }
        }
        assert_eq!(counted, layout.regions());
    }
}

#[test]
fn a_chain_of_overlapping_tiles_is_two_coloured() {
    // Consecutive tiles overlap and non-consecutive ones do not, so the conflict graph is a path
    // and greedy colouring alternates.  Stated as a fact about this fixture, not as a claim that
    // the greedy colouring is optimal in general.
    let layout = SectionLayout::generate(chain_1d(8, 4, 2), accumulated()).expect("generated");
    let colouring = layout.colouring(1 << 20).expect("a colouring");
    assert_eq!(colouring.colour_count(), 2);
    colouring.verify_proper(&layout).expect("proper");
}

#[test]
fn table_provenance_refuses_equal_size_different_incidence_and_offsets() {
    let operator = symmetric_operator(2);
    let layout_a = SectionLayout::generate(
        IncidenceDeclaration::uniform(4, 2, vec![0, 1, 2, 3]).expect("layout A incidence"),
        ScatterRequest::Injective,
    )
    .expect("layout A");
    let layout_b = SectionLayout::generate(
        IncidenceDeclaration::uniform(4, 2, vec![1, 0, 3, 2]).expect("layout B incidence"),
        ScatterRequest::Injective,
    )
    .expect("layout B");
    let staged = SectionTableProvenance {
        layout: &layout_a,
        _operator: &operator,
        colouring: None,
    };
    let refusal = staged
        .verify(&layout_b, None)
        .expect_err("equal-sized incidence tables must not be interchangeable");
    assert_eq!(refusal.clause, SectionClause::TableProvenance);

    let ragged_a = SectionLayout::generate(
        IncidenceDeclaration::new(4, vec![0, 1, 4], vec![0, 1, 2, 3]).expect("ragged A"),
        ScatterRequest::Injective,
    )
    .expect("ragged layout A");
    let ragged_b = SectionLayout::generate(
        IncidenceDeclaration::new(4, vec![0, 3, 4], vec![0, 1, 2, 3]).expect("ragged B"),
        ScatterRequest::Injective,
    )
    .expect("ragged layout B");
    let staged = SectionTableProvenance {
        layout: &ragged_a,
        _operator: &operator,
        colouring: None,
    };
    let refusal = staged
        .verify(&ragged_b, None)
        .expect_err("equal-sized offset tables must not be interchangeable");
    assert_eq!(refusal.clause, SectionClause::TableProvenance);
}

#[test]
fn table_provenance_refuses_a_different_proper_colouring() {
    let layout = SectionLayout::generate(chain_1d(3, 2, 1), accumulated()).expect("layout");
    let operator = symmetric_operator(2);
    let staged_colouring = RegionColouring {
        colours: vec![0, 1, 0],
        classes: vec![vec![0, 2], vec![1]],
        conflict_work: 0,
    };
    let presented_colouring = RegionColouring {
        colours: vec![1, 0, 1],
        classes: vec![vec![1], vec![0, 2]],
        conflict_work: 0,
    };
    staged_colouring
        .verify_proper(&layout)
        .expect("staged colouring is proper");
    presented_colouring
        .verify_proper(&layout)
        .expect("presented colouring is also proper");
    let staged = SectionTableProvenance {
        layout: &layout,
        _operator: &operator,
        colouring: Some(&staged_colouring),
    };
    let refusal = staged
        .verify(&layout, Some(&presented_colouring))
        .expect_err("proper colourings with different class assignments must not mix");
    assert_eq!(refusal.clause, SectionClause::TableProvenance);
}

#[test]
fn staging_refuses_an_improper_colouring_before_device_allocation() {
    let layout = SectionLayout::generate(chain_1d(3, 2, 1), accumulated()).expect("layout");
    let operator = symmetric_operator(2);
    let improper = RegionColouring {
        colours: vec![0, 1],
        classes: vec![vec![0], vec![1]],
        conflict_work: 0,
    };
    let refusal = SectionDeviceTables::stage(&layout, &operator, Some(&improper))
        .err().expect("staging must verify the colouring before allocating tables");
    assert_eq!(refusal.context, SectionClause::ColouringProper.name());
}

#[test]
fn colouring_refuses_an_incidence_past_the_declared_work_ceiling_before_it_colours() {
    // Every slot on one address: the conflict work is quadratic in the slot population, and the
    // ceiling refuses it *before* the colouring loop runs.
    let slots = 64usize;
    let incidence =
        IncidenceDeclaration::uniform(4, 1, vec![0u32; slots]).expect("a lawful hostile table");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    let refusal = layout.colouring(16).expect_err("the ceiling refuses it");
    assert_eq!(refusal.clause, SectionClause::WorkCeiling);
    // With a ceiling that admits the work, the same declaration colours and is proper.
    let colouring = layout.colouring(slots * slots).expect("a colouring");
    colouring.verify_proper(&layout).expect("proper");
    assert_eq!(colouring.colour_count(), slots, "every region conflicts with every other");
    assert_eq!(colouring.conflict_work(), slots * slots);
}

#[test]
fn every_colour_partition_is_an_injective_scatter_and_the_classes_cover_the_incidence() {
    let layout = SectionLayout::generate(grid_2d(7, 6), accumulated()).expect("generated");
    let colouring = layout.colouring(1 << 20).expect("a colouring");
    let mut covered = 0usize;
    for colour in 0..colouring.colour_count() {
        let partition = layout
            .colour_partition(&colouring, colour)
            .expect("a generated colour partition");
        assert_eq!(partition.scatter_law(), Some(ScatterLaw::Injective));
        partition
            .verify_pairwise_disjoint()
            .expect("a colour class scatters injectively");
        covered += colouring.class(colour).expect("a class").len();
    }
    assert_eq!(covered, layout.regions());
    assert_eq!(
        layout.colour_partition(&colouring, colouring.colour_count()).expect_err("refused").clause,
        SectionClause::ColourClass
    );
}

#[test]
fn the_colour_by_colour_scatter_equals_the_sequential_scatter() {
    // The executable witness of `SectionLayout.Incidence.colour_schedule`: accumulating one colour
    // class at a time into a running field leaves exactly what the whole scatter leaves.
    let ring = ModularWords::DEVICE;
    for layout in [
        SectionLayout::generate(chain_1d(9, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(7, 6), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(17, 24), accumulated()).expect("generated"),
    ] {
        let colouring = layout.colouring(1 << 20).expect("a colouring");
        let tile: Vec<u64> = (0..layout.slots())
            .map(|slot| ring.canonical(13 + 17 * slot as u64))
            .collect();
        let mut sequential = vec![0u64; layout.global_extent()];
        layout
            .scatter_reference(&ring, &tile, &mut sequential)
            .expect("the whole scatter");

        let mut running = vec![0u64; layout.global_extent()];
        for colour in 0..colouring.colour_count() {
            for region in colouring.class(colour).expect("a class") {
                let lo = layout.incidence().offsets()[*region as usize];
                let hi = layout.incidence().offsets()[*region as usize + 1];
                for (address, value) in layout.gather_index()[lo..hi].iter().zip(&tile[lo..hi]) {
                    let at = *address as usize;
                    running[at] = ring.add(running[at], *value).expect("exact");
                }
            }
        }
        assert_eq!(running, sequential);
    }
}

// ---------------------------------------------------------------------------------------------
// The generated launch requirements
// ---------------------------------------------------------------------------------------------

/// Synthetic device limits, `cfg(test)` only, so no production path can author a device bound.
fn synthetic_limits(warp: u32, block_cap: u32, shared: u32) -> LaunchLimits {
    LaunchLimits::synthetic(
        block_cap,
        Some(block_cap),
        Some(Dim3 {
            x: 2_147_483_647,
            y: 65_535,
            z: 65_535,
        }),
        Some(Dim3 {
            x: block_cap,
            y: block_cap,
            z: 64,
        }),
        Some(shared),
        Some(warp),
    )
}

#[test]
fn the_apply_requirement_generates_its_block_and_shared_extent_from_the_tile_and_the_card() {
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let limits = synthetic_limits(32, 1024, 49_152);
    let requirement = layout
        .apply_requirement(&limits, layout.tile().max_width())
        .expect("a generated requirement");
    // Tile width 5, rounded up to one 32-lane warp; shared is five exact words.
    assert_eq!(requirement.block.exact, Some(Dim3::x(32)));
    assert!(requirement.block.warp_multiple);
    assert_eq!(requirement.shared.per_block_bytes, 40);
    assert_eq!(requirement.shared.per_thread_bytes, 0);
    assert_eq!(requirement.extent, layout.regions() as u64 * 32);
    assert!(matches!(requirement.coverage, Coverage::Exact));

    // The derived shape is submitted to the same proof any caller-authored shape faces.
    let shape = requirement.cover_with(&limits).expect("a derived shape");
    assert_eq!(shape.grid, Dim3::x(layout.regions() as u32));
    assert_eq!(shape.block, Dim3::x(32));
    assert_eq!(shape.shared_bytes, 40);
}

#[test]
fn a_tile_wider_than_the_block_cap_generates_the_widest_lawful_warp_multiple() {
    let incidence = IncidenceDeclaration::uniform(
        4096,
        300,
        (0..(300u32 * 3)).map(|at| at % 4096).collect(),
    )
    .expect("lawful");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    let limits = synthetic_limits(32, 128, 49_152);
    let requirement = layout
        .apply_requirement(&limits, 300)
        .expect("a generated requirement");
    assert_eq!(requirement.block.exact, Some(Dim3::x(128)));
    assert_eq!(requirement.shared.per_block_bytes, 2400);
}

#[test]
fn the_apply_requirement_refuses_a_local_operator_of_the_wrong_width() {
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let limits = synthetic_limits(32, 1024, 49_152);
    let refusal = layout.apply_requirement(&limits, 4).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::LocalOperatorWidth);
}

#[test]
fn the_apply_requirement_refuses_evidence_that_carries_no_warp() {
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let limits = LaunchLimits::synthetic(1024, Some(1024), None, None, None, None);
    let refusal = layout.apply_requirement(&limits, 5).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::LaunchDerivation);
    assert!(refusal.detail.contains("LaunchEvidence::Device"), "{}", refusal.detail);
}

#[test]
fn a_shared_extent_past_the_card_is_refused_by_the_launch_law_rather_than_clipped() {
    // A 8192-slot tile wants 65_536 shared octets; the card in this fixture has 49_152.
    let width = 8192usize;
    let incidence = IncidenceDeclaration::uniform(
        65_536,
        width,
        (0..(width as u32 * 2)).map(|at| at % 65_536).collect(),
    )
    .expect("lawful");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    let limits = synthetic_limits(32, 1024, 49_152);
    let requirement = layout.apply_requirement(&limits, width).expect("a requirement");
    assert_eq!(requirement.shared.per_block_bytes, 65_536);
    let shape = requirement.cover_with(&limits).expect("a derived shape");
    let refusal = crate::launch_law::LawfulLaunch::prove(&requirement, &limits, shape, &[])
        .expect_err("the shared extent exceeds the card");
    assert_eq!(refusal.clause, LaunchClause::SharedWithinDevice);
}

#[test]
fn the_gather_and_scatter_requirements_declare_the_entry_symbols_and_extents_they_generate() {
    let layout = SectionLayout::generate(chain_1d(5, 4, 2), accumulated()).expect("generated");
    let gather = layout.gather_requirement();
    assert_eq!(gather.kernel, section_cuda::GATHER_ENTRY_SYMBOL);
    assert_eq!(gather.extent, layout.slots() as u64);
    assert_eq!(gather.arguments.len(), 3);
    assert_eq!(gather.scalars.len(), 1);
    assert!(matches!(gather.stream, StreamRequirement::Ordered));

    let colouring = layout.colouring(1 << 20).expect("a colouring");
    let class = colouring.class(0).expect("a class");
    let scatter = layout
        .scatter_add_requirement(class.len())
        .expect("a requirement");
    assert_eq!(scatter.kernel, section_cuda::SCATTER_ADD_ENTRY_SYMBOL);
    assert_eq!(scatter.extent, class.len() as u64);
    assert_eq!(scatter.arguments.len(), 5);
    assert_eq!(
        layout.scatter_add_requirement(0).expect_err("refused").clause,
        SectionClause::ColourClass
    );
}

#[test]
fn the_declared_entry_population_matches_the_shared_abi() {
    let symbols = section_entry_symbols();
    assert_eq!(symbols.len(), 4);
    assert_eq!(symbols.get("section_gather"), Some(&7));
    assert_eq!(symbols.get("section_apply"), Some(&8));
    assert_eq!(symbols.get("section_scatter_store"), Some(&7));
    assert_eq!(symbols.get("section_scatter_add"), Some(&11));
}

// ---------------------------------------------------------------------------------------------
// The device
// ---------------------------------------------------------------------------------------------

#[test]
#[ignore = "requires a CUDA device visible to the test process"]
fn device_enact_refuses_tables_from_a_different_equal_size_layout() -> crate::Result<()> {
    crate::cuda::init()?;
    let device = crate::Device::get(0)?;
    let _context = crate::Context::create(&device)?;
    let module = crate::cuda::Module::load_ptx(crate::SOMA_PTX)?;
    let kernels = SectionKernels::resolve(&module)?;
    let stream = crate::Stream::create()?;
    let layout_a = SectionLayout::generate(
        IncidenceDeclaration::uniform(4, 2, vec![0, 1, 2, 3]).expect("layout A incidence"),
        ScatterRequest::Injective,
    )
    .expect("layout A");
    let layout_b = SectionLayout::generate(
        IncidenceDeclaration::uniform(4, 2, vec![1, 0, 3, 2]).expect("layout B incidence"),
        ScatterRequest::Injective,
    )
    .expect("layout B");
    let operator = symmetric_operator(2);
    let tables = SectionDeviceTables::stage(&layout_a, &operator, None)?;
    let source = crate::DeviceBuffer::<u64>::alloc_zeroed(layout_b.global_extent())?;
    let mut local = crate::DeviceBuffer::<u64>::alloc_zeroed(layout_b.slots())?;
    let mut target = crate::DeviceBuffer::<u64>::alloc_zeroed(layout_b.global_extent())?;
    let error = kernels
        .enact(
            &device,
            &stream,
            &layout_b,
            &tables,
            None,
            &source,
            &mut local,
            &mut target,
        )
        .expect_err("the staged table provenance must be checked before launch");
    assert_eq!(error.context, SectionClause::TableProvenance.name());
    Ok(())
}

/// The three declared cases plus an injective control, each enacted on the card and compared
/// **bit for bit** against the exact cpu reference, with the four clocks reported separately.
///
/// Named clocks, all host `Instant` wall time:
///
/// * **setup** — context, module load, entry resolution, colouring, table staging and the source
///   upload: everything before the first section launch.
/// * **resident execution** — `SectionKernels::enact`, which is the three arms and, for an
///   accumulating scatter, one scatter launch per colour class.  Each arm's
///   `PartitionedWrite::scope` synchronizes the stream before returning, so this clock includes the
///   device work and the per-arm synchronization, and excludes the readback.
/// * **readout** — the device-to-host copy of the global field.
/// * **end to end** — the whole of the above, one clock across all of it.
#[test]
#[ignore = "requires a CUDA device visible to the test process"]
fn the_generated_triple_matches_the_exact_reference_on_the_card() -> crate::Result<()> {
    use std::time::Instant;

    crate::cuda::init()?;
    let device = crate::Device::get(0)?;
    let context = crate::Context::create(&device)?;
    let ring = ModularWords::DEVICE;

    let cases: Vec<(&str, IncidenceDeclaration, ScatterRequest)> = vec![
        ("1d-chain-of-overlapping-tiles", chain_1d(512, 16, 6), accumulated()),
        ("2d-grid-4-neighbour-overlap", grid_2d(64, 64), accumulated()),
        ("irregular-contact-incidence", irregular_contact(1024, 4096), accumulated()),
        (
            "injective-control",
            IncidenceDeclaration::uniform(4096, 8, (0..4096u32).collect()).expect("lawful"),
            ScatterRequest::Injective,
        ),
    ];

    for (name, incidence, request) in cases {
        let whole = Instant::now();
        let setup = Instant::now();
        let module = crate::cuda::Module::load_ptx(crate::SOMA_PTX)?;
        let apparatus = SectionApparatus::resolve(&module)?;
        let stream = crate::Stream::create()?;

        let layout = SectionLayout::generate(incidence, request)?;
        let operator = symmetric_operator(layout.tile().max_width());
        let colouring = match layout.receipt() {
            ScatterReceipt::Accumulated(_) => {
                let colouring = layout.colouring(1 << 24)?;
                colouring.verify_proper(&layout)?;
                Some(colouring)
            }
            ScatterReceipt::Injective => None,
        };
        let tables = SectionDeviceTables::stage(&layout, &operator, colouring.as_ref())?;
        let x = field(layout.global_extent());
        let source = crate::DeviceBuffer::<u64>::alloc(x.len())?;
        source.copy_from_slice(&x)?;
        let mut local = crate::DeviceBuffer::<u64>::alloc_zeroed(layout.slots())?;
        let mut target = crate::DeviceBuffer::<u64>::alloc_zeroed(layout.global_extent())?;
        context.synchronize()?;
        let setup = setup.elapsed();

        let resident = Instant::now();
        let receipts = apparatus.kernels().enact(
            &device,
            &stream,
            &layout,
            &tables,
            colouring.as_ref(),
            &source,
            &mut local,
            &mut target,
        )?;
        let resident = resident.elapsed();

        let readout = Instant::now();
        let mut produced = vec![0u64; layout.global_extent()];
        target.copy_to_slice(&mut produced)?;
        let readout = readout.elapsed();
        let end_to_end = whole.elapsed();

        // Every receipt is completely proved: `LaunchEvidence::Device` defers nothing.
        assert!(receipts.gather.receipt().is_fully_proved());
        assert!(receipts.apply.receipt().is_fully_proved());
        assert!(receipts.apply.receipt().proves(LaunchClause::BlockWarpMultiple));
        assert!(receipts.apply.receipt().proves(LaunchClause::SharedWithinDevice));
        assert!(receipts.apply.receipt().proves(LaunchClause::BlockDimensionWithinDevice));
        for scatter in &receipts.scatter {
            assert!(scatter.receipt().is_fully_proved());
        }
        assert_eq!(
            receipts.scatter.len(),
            colouring.as_ref().map_or(1, RegionColouring::colour_count)
        );

        let expected = layout.apply_reference(&ring, &operator, &x)?;
        assert_eq!(
            produced, expected,
            "{name}: the device result and the exact cpu reference disagree"
        );
        // And the reference is itself held against the directly assembled matrix wherever the
        // dense assembly fits; the big cases are covered by the cpu test above.
        if layout.global_extent() <= 512 {
            let matrix = layout.assemble_dense(&ring, &operator, 1 << 20)?;
            assert_eq!(produced, layout.apply_assembled(&ring, &matrix, &x)?);
        }

        // The convenience mouth is exercised too, on one case, so no public entry point of this
        // owner goes untested: it stages nothing new, allocates its own source/local/target and
        // reads the field back, and must produce the same exact field.
        if name == "injective-control" {
            let (once, once_receipts) = apparatus.apply_once(
                &device,
                &context,
                &stream,
                &layout,
                &tables,
                colouring.as_ref(),
                &x,
            )?;
            assert_eq!(once, expected, "{name}: apply_once left a different field");
            assert!(once_receipts.gather.receipt().is_fully_proved());
        }

        eprintln!(
            "{name}: regions={} slots={} extent={} tile={} shared={}B colours={} \
             setup={:?} resident={:?} readout={:?} end-to-end={:?}",
            layout.regions(),
            layout.slots(),
            layout.global_extent(),
            layout.tile().max_width(),
            layout.tile().tile_bytes(),
            colouring.as_ref().map_or(0, RegionColouring::colour_count),
            setup,
            resident,
            readout,
            end_to_end,
        );
        eprintln!("  gather  {}", receipts.gather.receipt());
        eprintln!("  apply   {}", receipts.apply.receipt());
        eprintln!("  scatter {}", receipts.scatter[0].receipt());

        drop(tables);
        drop(source);
    }

    context.destroy()?;
    Ok(())
}

/// The device refuses a declared accumulation it cannot realize, rather than wrapping silently.
#[test]
#[ignore = "requires a CUDA device visible to the test process"]
fn the_device_arm_refuses_an_accumulation_it_cannot_realize() -> crate::Result<()> {
    crate::cuda::init()?;
    let device = crate::Device::get(0)?;
    let context = crate::Context::create(&device)?;
    let module = crate::cuda::Module::load_ptx(crate::SOMA_PTX)?;
    let kernels = SectionKernels::resolve(&module)?;
    let stream = crate::Stream::create()?;

    let layout = SectionLayout::generate(
        chain_1d(8, 4, 2),
        ScatterRequest::Accumulated(AccumulationLaw::IntegerAdd),
    )?;
    let operator = LocalOperator::dense(4, vec![1u64; 16]).expect("lawful");
    let tables = SectionDeviceTables::stage(&layout, &operator, None)?;
    let source = crate::DeviceBuffer::<u64>::alloc_zeroed(layout.global_extent())?;
    let mut local = crate::DeviceBuffer::<u64>::alloc_zeroed(layout.slots())?;
    let mut target = crate::DeviceBuffer::<u64>::alloc_zeroed(layout.global_extent())?;
    let error = kernels
        .enact(
            &device,
            &stream,
            &layout,
            &tables,
            None,
            &source,
            &mut local,
            &mut target,
        )
        .expect_err("an integer-add law has no device arm");
    assert_eq!(error.context, SectionClause::AccumulationOnDevice.name());

    drop(tables);
    context.destroy()?;
    Ok(())
}

// ---------------------------------------------------------------------------------------------
// The canonicality boundary
// ---------------------------------------------------------------------------------------------

/// A coefficient table lawful in its width and everywhere canonical **except one named index**.
/// Built through the generic [`LocalOperator::dense`], which carries no representation clause — that
/// is the point: the representation clause lives at the device boundary, and this fixture is what
/// the boundary is held against.
fn operator_with_one_non_canonical_entry(width: usize, at: usize, word: u64) -> LocalOperator<u64> {
    let mut entries = symmetric_operator(width).entries().to_vec();
    entries[at] = word;
    LocalOperator::dense(width, entries).expect("the width clause is untouched")
}

/// An **independent** exact reference for `Z/(2^61 - 1)`: a plain 128-bit remainder sharing no code
/// with `soma_abi::section_layout_cuda`.
///
/// `ModularWords::DEVICE` dispatches *into* the very code the card runs, which is exactly what makes
/// it the right reference for a transcription question and the wrong one for an arithmetic
/// question: a fold that is wrong on both sides agrees with itself. This ring is the second
/// witness, and the device assertions below compare against it.
#[derive(Debug, Clone, Copy)]
struct IndependentModulus;

impl ExactRing for IndependentModulus {
    type Value = u64;

    fn zero(&self) -> u64 {
        0
    }

    fn add(&self, left: u64, right: u64) -> Option<u64> {
        Some((((left as u128) + (right as u128)) % (section_cuda::MODULUS as u128)) as u64)
    }

    fn mul(&self, left: u64, right: u64) -> Option<u64> {
        Some((((left as u128) * (right as u128)) % (section_cuda::MODULUS as u128)) as u64)
    }

    fn law(&self) -> AccumulationLaw {
        AccumulationLaw::ModularAdd {
            modulus: section_cuda::MODULUS,
        }
    }
}

#[test]
fn a_non_canonical_coefficient_is_refused_at_the_staging_boundary_naming_its_first_index() {
    let layout = SectionLayout::generate(chain_1d(6, 4, 2), accumulated()).expect("generated");
    let width = layout.tile().max_width();
    let ring = ModularWords::DEVICE;

    // A lawful declaration passes every mouth of the boundary.
    let lawful = symmetric_operator(width);
    lawful.verify_canonical(&ring).expect("a canonical operator is admitted");
    LocalOperator::dense_canonical(width, lawful.entries().to_vec(), &ring)
        .expect("a canonical operator is admitted at construction");
    ring.verify_canonical(&field(layout.global_extent()), "global field")
        .expect("a canonical field is admitted");

    // `p` itself is the first non-canonical word and `u64::MAX` the widest; the refusal names the
    // offending index and the offending word, and it is raised through all three mouths.
    for (at, word) in [
        (0usize, section_cuda::MODULUS),
        (9, section_cuda::MODULUS + 1),
        (width * width - 1, u64::MAX),
    ] {
        let operator = operator_with_one_non_canonical_entry(width, at, word);
        let refusal = operator.verify_canonical(&ring).expect_err("refused");
        assert_eq!(refusal.clause, SectionClause::CanonicalWord);
        assert!(
            refusal.detail.contains(&format!("entry {at} is {word}")),
            "{}",
            refusal.detail
        );

        let constructed = LocalOperator::dense_canonical(width, operator.entries().to_vec(), &ring)
            .expect_err("refused at construction");
        assert_eq!(constructed.clause, SectionClause::CanonicalWord);

        // And through `stage`, which raises it **before any driver call**: this assertion runs on a
        // host with no CUDA context created and no device touched.
        let error = match SectionDeviceTables::stage(&layout, &operator, None) {
            Ok(_) => panic!("the staging boundary admitted a non-canonical coefficient"),
            Err(error) => error,
        };
        assert_eq!(error.context, SectionClause::CanonicalWord.name());
        assert!(
            error.message.contains(&format!("entry {at} is {word}")),
            "{}",
            error.message
        );
    }

    // Two offending entries: the refusal names the **first**, so the caller is pointed at a place
    // rather than told that a place exists.
    let mut entries = symmetric_operator(width).entries().to_vec();
    entries[3] = section_cuda::MODULUS + 17;
    entries[11] = u64::MAX;
    let operator = LocalOperator::dense(width, entries).expect("the width clause is untouched");
    let refusal = operator.verify_canonical(&ring).expect_err("refused");
    assert!(
        refusal.detail.contains("entry 3 is 2305843009213693968"),
        "{}",
        refusal.detail
    );

    // The same clause holds the global-field mouth, which is the other host table that crosses.
    let mut x = field(layout.global_extent());
    x[2] = section_cuda::MODULUS;
    let refusal = ring.verify_canonical(&x, "global field").expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::CanonicalWord);
    assert!(
        refusal.detail.contains("global field entry 2 is"),
        "{}",
        refusal.detail
    );

    // The clause is the declaration's, not the arithmetic's: the arithmetic is total regardless,
    // and this is the assertion that says so on the host path the card shares.
    assert_eq!(
        ring.mul(17_678_129_737_304_986_966, 2_305_843_009_213_693_949),
        Some(1_537_228_672_809_129_284)
    );
    assert_eq!(ring.add(u64::MAX, u64::MAX), IndependentModulus.add(u64::MAX, u64::MAX));
}

#[test]
fn the_device_ring_agrees_with_an_independent_reference_over_non_canonical_words() {
    // `the_device_ring_agrees_with_the_general_modular_path_over_the_same_modulus` reduces every
    // probe first, so it can say nothing about a word outside `[0, p)`. This one does not reduce.
    let device = ModularWords::DEVICE;
    let probes: [u64; 12] = [
        0,
        1,
        section_cuda::MODULUS - 1,
        section_cuda::MODULUS,
        section_cuda::MODULUS + 1,
        1 << 61,
        (1 << 61) + 1,
        1 << 62,
        1 << 63,
        u64::MAX,
        17_678_129_737_304_986_966,
        2_305_843_009_213_693_949,
    ];
    for left in probes {
        assert_eq!(
            device.canonical(left),
            ((left as u128) % (section_cuda::MODULUS as u128)) as u64,
            "canonical({left})"
        );
        for right in probes {
            assert_eq!(
                device.add(left, right),
                IndependentModulus.add(left, right),
                "{left} + {right}"
            );
            assert_eq!(
                device.mul(left, right),
                IndependentModulus.mul(left, right),
                "{left} * {right}"
            );
        }
    }
}

/// Stage the device tables **around** the canonicality clause, so the four entries can be driven
/// with coefficients no public mouth would let through. Reachable only from this test module —
/// `SectionDeviceTables`' fields are private, and `stage` stays the only public way to fill them.
fn stage_around_the_canonicality_clause<'a>(
    layout: &'a SectionLayout,
    operator: &'a LocalOperator<u64>,
    colouring: Option<&'a RegionColouring>,
) -> crate::Result<SectionDeviceTables<'a>> {
    let index = crate::DeviceBuffer::<u32>::alloc(layout.slots())?;
    index.copy_from_slice(layout.gather_index())?;
    let offsets = crate::DeviceBuffer::<u32>::alloc(layout.regions() + 1)?;
    offsets.copy_from_slice(layout.device_offsets())?;
    let coefficients = crate::DeviceBuffer::<u64>::alloc(operator.entries().len())?;
    coefficients.copy_from_slice(operator.entries())?;
    let mut colour_regions = Vec::new();
    if let Some(colouring) = colouring {
        for colour in 0..colouring.colour_count() {
            let class = colouring.class(colour).expect("colour below the count");
            let buffer = crate::DeviceBuffer::<u32>::alloc(class.len())?;
            buffer.copy_from_slice(class)?;
            colour_regions.push(buffer);
        }
    }
    Ok(SectionDeviceTables {
        index,
        offsets,
        coefficients,
        colour_regions,
        provenance: SectionTableProvenance {
            layout,
            _operator: operator,
            colouring,
        },
    })
}

/// **The canonicality boundary and the total arithmetic, on the card.**
///
/// Three things are asserted, in the order the law holds them:
///
/// 1. a non-canonical coefficient and a non-canonical global field are refused at the host mouths,
///    naming the first offending index, with the card present and nothing staged;
/// 2. what those mouths admit is exact against the **independent** 128-bit reference, not merely
///    against `ModularWords::DEVICE`, which is the same code the card runs;
/// 3. driven *around* the refusal — the only way to reach it — the four entries run `mul` and `add`
///    on words outside `[0, p)`, including an accumulation target seeded non-canonical, and still
///    produce the exact residue. That is the arithmetic being total rather than guarded, and it is
///    the assertion the narrowing fold fails.
#[test]
#[ignore = "requires a CUDA device visible to the test process"]
fn the_device_boundary_refuses_non_canonical_declarations_and_its_arithmetic_is_total() -> crate::Result<()> {
    crate::cuda::init()?;
    let device = crate::Device::get(0)?;
    let context = crate::Context::create(&device)?;
    let module = crate::cuda::Module::load_ptx(crate::SOMA_PTX)?;
    let apparatus = SectionApparatus::resolve(&module)?;
    let stream = crate::Stream::create()?;

    let layout = SectionLayout::generate(chain_1d(48, 6, 2), accumulated())?;
    let width = layout.tile().max_width();
    let colouring = layout.colouring(1 << 20)?;
    colouring.verify_proper(&layout)?;
    let ring = ModularWords::DEVICE;
    let x = field(layout.global_extent());

    // --- (1) the two host mouths refuse -----------------------------------------------------
    let hostile = operator_with_one_non_canonical_entry(width, 7, section_cuda::MODULUS + 3);
    let error = match SectionDeviceTables::stage(&layout, &hostile, Some(&colouring)) {
        Ok(_) => panic!("a non-canonical coefficient reached the card"),
        Err(error) => error,
    };
    assert_eq!(error.context, SectionClause::CanonicalWord.name());
    assert!(error.message.contains("entry 7 is"), "{}", error.message);

    let lawful = LocalOperator::dense_canonical(
        width,
        symmetric_operator(width).entries().to_vec(),
        &ring,
    )?;
    let tables = SectionDeviceTables::stage(&layout, &lawful, Some(&colouring))?;

    let mut hostile_field = x.clone();
    hostile_field[5] = u64::MAX;
    let error = apparatus
        .apply_once(
            &device,
            &context,
            &stream,
            &layout,
            &tables,
            Some(&colouring),
            &hostile_field,
        )
        .expect_err("a non-canonical global field does not reach the card");
    assert_eq!(error.context, SectionClause::CanonicalWord.name());
    assert!(
        error.message.contains("global field entry 5 is"),
        "{}",
        error.message
    );

    // --- (2) what is admitted is exact against the independent reference ---------------------
    let (produced, receipts) = apparatus.apply_once(
        &device,
        &context,
        &stream,
        &layout,
        &tables,
        Some(&colouring),
        &x,
    )?;
    assert_eq!(
        produced,
        layout.apply_reference(&IndependentModulus, &lawful, &x)?,
        "the admitted declaration disagrees with the independent 128-bit reference"
    );
    assert_eq!(produced, layout.apply_reference(&ring, &lawful, &x)?);
    assert!(receipts.gather.receipt().is_fully_proved());

    // --- (3) the arithmetic itself is total --------------------------------------------------
    let mut entries = lawful.entries().to_vec();
    entries[0] = u64::MAX;
    entries[width + 1] = section_cuda::MODULUS + 11;
    entries[width * width - 1] = 17_678_129_737_304_986_966;
    let non_canonical = LocalOperator::dense(width, entries)?;
    non_canonical
        .verify_canonical(&ring)
        .expect_err("the fixture is genuinely non-canonical");
    let hostile_tables =
        stage_around_the_canonicality_clause(&layout, &non_canonical, Some(&colouring))?;

    // The accumulating target starts non-canonical too: `section_scatter_add` folds whatever the
    // global field already holds, which is the second place `add` met a word it was not promised.
    let seed: Vec<u64> = (0..layout.global_extent())
        .map(|at| {
            if at % 3 == 0 {
                u64::MAX - at as u64
            } else {
                section_cuda::MODULUS + at as u64
            }
        })
        .collect();
    let source = crate::DeviceBuffer::<u64>::alloc(x.len())?;
    source.copy_from_slice(&x)?;
    let mut local = crate::DeviceBuffer::<u64>::alloc_zeroed(layout.slots())?;
    let mut target = crate::DeviceBuffer::<u64>::alloc(layout.global_extent())?;
    target.copy_from_slice(&seed)?;
    apparatus.kernels().enact(
        &device,
        &stream,
        &layout,
        &hostile_tables,
        Some(&colouring),
        &source,
        &mut local,
        &mut target,
    )?;
    context.synchronize()?;
    let mut produced = vec![0u64; layout.global_extent()];
    target.copy_to_slice(&mut produced)?;

    let mut touched = vec![false; layout.global_extent()];
    for address in layout.incidence().addresses() {
        touched[*address as usize] = true;
    }
    let mut expected = layout.apply_reference(&IndependentModulus, &non_canonical, &x)?;
    for (at, word) in expected.iter_mut().enumerate() {
        *word = if touched[at] {
            IndependentModulus.add(*word, seed[at]).expect("total")
        } else {
            // An address no region names keeps exactly what the caller seeded, verbatim.
            seed[at]
        };
    }
    assert_eq!(
        produced, expected,
        "the device arithmetic is not total over words outside [0, p)"
    );
    // And the one-mouth property survives it: the host reference that *is* the device's own code
    // lands on the same field.
    let mut host = layout.apply_reference(&ring, &non_canonical, &x)?;
    for (at, word) in host.iter_mut().enumerate() {
        *word = if touched[at] {
            ring.add(*word, seed[at]).expect("total")
        } else {
            seed[at]
        };
    }
    assert_eq!(produced, host);

    eprintln!(
        "canonicality boundary: regions={} slots={} extent={} tile={} colours={} \
         · staging refusal EXACT · field refusal EXACT · total arithmetic EXACT",
        layout.regions(),
        layout.slots(),
        layout.global_extent(),
        width,
        colouring.colour_count(),
    );

    drop(tables);
    drop(hostile_tables);
    drop(source);
    context.destroy()?;
    Ok(())
}
