import ElementaryHolonics.Physics.FourTorusCurrentChart
import ElementaryHolonics.Physics.ConstitutiveCurrentReduction

/-!
# Two active four-torus face currents

The current chart exposes four rational cut coordinates and a complete all-face boundary map. This
owner selects the actual base-zero faces `F01` and `F02` as the active constitutive face. The face
map is their rational linear span, while `twoFaceTranspose` is the finite branch pairing with those
two currents. The Gram and cut-face identities are proved from four-edge pairings at grains one and two.
These certificates instantiate the shared constitutive chart without extra matrix assumptions.
-/

namespace Soma.Holonics.Physics.FourTorusTwoFace

noncomputable section

open scoped BigOperators
open Soma.Holonics
open Soma.Holonics.Physics.FourTorusCurrentChart
open Soma.Holonics.Physics.TwoFaceConstitutive
open Soma.Holonics.Millennium.HolonicFourTorusCarrier

abbrev TwoFace := Fin 2 → ℚ

/-- The active two-face current map generated by the actual `F01` and `F02` currents. -/
def twoFace (grain : ℕ) : TwoFace →ₗ[ℚ] RationalCurrent grain where
  toFun z := z 0 • c0 grain + z 1 • c1 grain
  map_add' left right := by
    funext edge
    simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul, add_mul]
    ring
  map_smul' scalar z := by
    funext edge
    simp only [Pi.smul_apply, smul_eq_mul, Pi.add_apply]
    simp only [RingHom.id_apply]
    ring

/-- The finite transpose receiver pairing an arbitrary branch current with `c0,c1`. -/
def twoFaceTranspose (grain : ℕ) : RationalCurrent grain →ₗ[ℚ] TwoFace where
  toFun current := ![
    ∑ edge : Edge grain, current edge * c0 grain edge,
    ∑ edge : Edge grain, current edge * c1 grain edge]
  map_add' left right := by
    funext coordinate
    fin_cases coordinate <;> simp [Pi.add_apply, add_mul, Finset.sum_add_distrib]
  map_smul' scalar current := by
    funext coordinate
    fin_cases coordinate
    · simp only [Pi.smul_apply, smul_eq_mul]
      simp [Finset.mul_sum, mul_assoc]
    · simp only [Pi.smul_apply, smul_eq_mul]
      simp [Finset.mul_sum, mul_assoc]

open Soma.Holonics.Physics.ConstitutiveCurrentReduction

theorem twoFace_cut_zero (grain : ℕ) (z : TwoFace) :
    axisReceiver grain (twoFace grain z) = 0 := by
  change axisReceiver grain (z 0 • c0 grain + z 1 • c1 grain) = 0
  rw [map_add, map_smul, map_smul, C_c0_eq_zero, C_c1_eq_zero]
  simp

/-- A square receiver is exactly its four oriented edge evaluations. -/
theorem pair_faceBoundary (grain : ℕ) (j : RationalCurrent grain) (face : Face grain) :
 (∑ e : Edge grain, j e * (faceBoundary face e : ℚ)) =
 j ⟨face.first, face.base⟩ + j ⟨face.second, stepVertex face.first face.base⟩ -
 j ⟨face.first, stepVertex face.second face.base⟩ - j ⟨face.second, face.base⟩ := by
 classical
 simp [faceBoundary, Finsupp.single_apply, mul_sub, mul_add, mul_ite,
   Finset.sum_sub_distrib, Finset.sum_add_distrib]

theorem twoFace_gram_one (z : TwoFace) : twoFaceTranspose 1 (twoFace 1 z) = faceMetric z := by
 funext k
 fin_cases k <;>
  simp only [twoFaceTranspose, LinearMap.coe_mk, AddHom.coe_mk, c0, c1, faceBoundaryCurrent, pair_faceBoundary] <;>
  norm_num [twoFace, c0, c1, faceBoundaryCurrent, faceBoundary, F01, F02,
   Finsupp.single_apply, Edge.mk.injEq, funext_iff, Fin.forall_fin_succ,
   stepVertex, axisNext, faceMetric] <;>
  norm_num [Function.update_apply, Fin.reduceFinMk, Fin.reduceAdd, Fin.ext_iff] <;> ring

theorem twoFace_axis_one (q : RationalLattice) : twoFaceTranspose 1 (axisRealization 1 q) = cutFaceCoupling q := by
 funext k
 fin_cases k <;>
  simp only [twoFaceTranspose, LinearMap.coe_mk, AddHom.coe_mk,
    c0, c1, faceBoundaryCurrent, pair_faceBoundary] <;>
  norm_num [axisRealization, rationalAxisWinding, axisWindingChain, Fin.sum_univ_succ,
    Finsupp.single_apply, Edge.mk.injEq, funext_iff, Fin.forall_fin_succ,
    F01, F02, stepVertex, axisNext, axisVertex, cutFaceCoupling] <;>
  norm_num [Function.update_apply, Fin.reduceFinMk, Fin.reduceAdd, Fin.ext_iff]

theorem twoFace_gram_two (z : TwoFace) : twoFaceTranspose 2 (twoFace 2 z) = faceMetric z := by
 funext k
 fin_cases k <;>
  simp only [twoFaceTranspose, LinearMap.coe_mk, AddHom.coe_mk, c0, c1, faceBoundaryCurrent, pair_faceBoundary] <;>
  norm_num [twoFace, c0, c1, faceBoundaryCurrent, faceBoundary, F01, F02,
   Finsupp.single_apply, Edge.mk.injEq, funext_iff, Fin.forall_fin_succ,
   stepVertex, axisNext, faceMetric] <;>
  norm_num [Function.update_apply, Fin.reduceFinMk, Fin.reduceAdd, Fin.ext_iff] <;> ring

theorem twoFace_axis_two (q : RationalLattice) : twoFaceTranspose 2 (axisRealization 2 q) = cutFaceCoupling q := by
 funext k
 fin_cases k <;>
  simp only [twoFaceTranspose, LinearMap.coe_mk, AddHom.coe_mk,
    c0, c1, faceBoundaryCurrent, pair_faceBoundary] <;>
  norm_num [axisRealization, rationalAxisWinding, axisWindingChain, Fin.sum_univ_succ,
    Finsupp.single_apply, Edge.mk.injEq, funext_iff, Fin.forall_fin_succ,
    F01, F02, stepVertex, axisNext, axisVertex, cutFaceCoupling] <;>
  norm_num [Function.update_apply, Fin.reduceFinMk, Fin.reduceAdd, Fin.ext_iff]

/-- A nonzero closed current invisible to both active receiver families. -/
def blindCurrent (grain : ℕ) : RationalCurrent grain :=
 faceBoundaryCurrent (⟨1, 2, by decide, 0⟩ : Face grain) +
 (1/3 : ℚ) • c0 grain - (1/3 : ℚ) • c1 grain

theorem blindCurrent_cut_zero (grain : ℕ) : axisReceiver grain (blindCurrent grain) = 0 := by
 simp [blindCurrent, map_add, map_sub, map_smul, axisReceiver_faceBoundaryCurrent_eq_zero,
  C_c0_eq_zero, C_c1_eq_zero]

theorem blindCurrent_vertexBoundary_zero (grain : ℕ) :
    vertexBoundary grain (blindCurrent grain) = 0 := by
  simp [blindCurrent, map_add, map_sub, map_smul, vertexBoundary_faceBoundaryCurrent_eq_zero,
    vertexBoundary_c0_eq_zero, vertexBoundary_c1_eq_zero]

theorem blindCurrent_face_zero_one : twoFaceTranspose 1 (blindCurrent 1) = 0 := by
 funext k
 fin_cases k <;>
  simp only [twoFaceTranspose, LinearMap.coe_mk, AddHom.coe_mk,
    c0, c1, faceBoundaryCurrent, pair_faceBoundary] <;>
  norm_num [blindCurrent, c0, c1, faceBoundaryCurrent, faceBoundary, F01, F02,
   Finsupp.single_apply, Edge.mk.injEq, funext_iff, Fin.forall_fin_succ,
   stepVertex, axisNext, faceMetric] <;>
  norm_num [Function.update_apply, Fin.reduceFinMk, Fin.reduceAdd, Fin.ext_iff]

theorem blindCurrent_separating_edge_one : blindCurrent 1 ⟨0, stepVertex 1 0⟩ = -1/3 := by
 norm_num [blindCurrent, c0, c1, faceBoundaryCurrent, faceBoundary, F01, F02,
   Finsupp.single_apply, Edge.mk.injEq, funext_iff, Fin.forall_fin_succ,
   stepVertex, axisNext, faceMetric] <;>
  norm_num [Function.update_apply, Fin.reduceFinMk, Fin.reduceAdd, Fin.ext_iff]

/-- The concrete torus chart for the two verified grains, with no caller-supplied matrices. -/
def constitutiveChart (grain : ℕ) (admitted : grain = 1 ∨ grain = 2) :
    ConstitutiveChart (RationalCurrent grain) where
  C := axisReceiver grain
  J := axisRealization grain
  D := twoFace grain
  Dt := twoFaceTranspose grain
  CJ := LinearMap.ext (axisReceiver_axisRealization grain)
  CD := LinearMap.ext (twoFace_cut_zero grain)
  DtJ := LinearMap.ext (fun q ↦ by
    rcases admitted with rfl | rfl
    · exact twoFace_axis_one q
    · exact twoFace_axis_two q)
  DtD := LinearMap.ext (fun z ↦ by
    rcases admitted with rfl | rfl
    · exact twoFace_gram_one z
    · exact twoFace_gram_two z)

theorem twoFace_explicitUpdate_solves_fine
    (grain : ℕ) (admitted : grain = 1 ∨ grain = 2)
    {tau mu nu : ℚ} (htau : 0 ≤ tau)
    (hplus : 0 ≤ mu + nu) (hminus : 0 ≤ mu - nu)
    (q u : RationalLattice) (z f : TwoFace) (r : RationalCurrent grain)
    (hDtR : twoFaceTranspose grain r = 0) :
    fineLaw tau mu nu (axisRealization grain) (twoFace grain) (twoFaceTranspose grain)
      (decodedCurrent (axisRealization grain) (twoFace grain) q z r)
      (decodedCurrent (axisRealization grain) (twoFace grain) (q + u)
        (compactExplicitUpdate tau mu nu (q + u) z f) r) u f := by
  exact decodedCurrent_explicitUpdate_solves_fine htau hplus hminus
    (axisRealization grain) (twoFace grain) (twoFaceTranspose grain) q u z f r
    (constitutiveChart grain admitted).DtJ (constitutiveChart grain admitted).DtD hDtR

end

#print axioms pair_faceBoundary
#print axioms twoFace_gram_one
#print axioms twoFace_axis_one
#print axioms twoFace_gram_two
#print axioms twoFace_axis_two
#print axioms blindCurrent_cut_zero
#print axioms blindCurrent_face_zero_one
#print axioms blindCurrent_separating_edge_one
#print axioms constitutiveChart
#print axioms twoFace_explicitUpdate_solves_fine

end Soma.Holonics.Physics.FourTorusTwoFace
