import ElementaryHolonics.Millennium.HolonicYangMillsVariationInvariance

/-!
# Gauge-orbit directions: the first variation vanishes along them

An infinitesimal gauge transformation generated by a section `ξ` moves the connection in the
direction `D_A ξ`.  By the Ricci identity the covariant variation of the curvature along that
direction is the bracket `[F, ξ]`, and an invariant pairing annihilates `B([F, ξ], F)`; hence the
first variation of the Yang--Mills energy along every gauge-orbit direction is zero.  Critical
points are therefore a condition on the orbit space, and the Yang--Mills direction is orthogonal
to the orbit.
-/

noncomputable section

namespace Soma.Holonics.Millennium.HolonicYangMillsOrbitDirection

open Set MeasureTheory
open Soma.Holonics.Millennium.HolonicConnectionCurvature
open Soma.Holonics.Millennium.HolonicConnectionVariation
open Soma.Holonics.Millennium.HolonicYangMillsFlow
open Soma.Holonics.Millennium.HolonicYangMillsEnergy
open Soma.Holonics.Millennium.HolonicPeriodicBoxDivergence
open Soma.Holonics.Millennium.HolonicYangMillsDescent
open Soma.Holonics.Millennium.HolonicYangMillsHessian

variable {n : ℕ} {𝔤 : Type*} [NormedRing 𝔤] [NormedAlgebra ℝ 𝔤]

/-- The gauge-orbit direction generated by `ξ`: `(D_A ξ)_i`. -/
def orbitDirection (A : Connection n 𝔤) (ξ : Base n → 𝔤) : Connection n 𝔤 :=
  fun i => covariantDerivative A i ξ

/-- **Along an orbit direction the covariant variation is the bracket of the curvature with the
generator.** -/
theorem covariantVariation_orbitDirection (A : Connection n 𝔤)
    (hA : ∀ i x, DifferentiableAt ℝ (A i) x) (ξ : Base n → 𝔤) (hξ : ContDiff ℝ 2 ξ)
    (i j : Fin n) (x : Base n) :
    covariantVariation A (orbitDirection A ξ) i j x = bracket (curvature A i j x) (ξ x) := by
  unfold covariantVariation orbitDirection
  exact ricci A hA ξ hξ i j x

/-- An invariant pairing annihilates `B([F, ξ], F)`. -/
theorem pairing_bracket_self (P : InvariantPairing 𝔤) (F ξ : 𝔤) : P.B (bracket F ξ) F = 0 := by
  have h := P.invariant F ξ F
  have hFF : bracket F F = 0 := by
    unfold bracket
    exact sub_self _
  rw [hFF, map_zero, add_zero] at h
  exact h

/-- **The first variation vanishes along every gauge-orbit direction.** -/
theorem firstVariation_orbitDirection (P : SymmetricPairing 𝔤) (A : Connection (n + 1) 𝔤)
    (hA : ∀ i x, DifferentiableAt ℝ (A i) x) (ξ : Base (n + 1) → 𝔤) (hξ : ContDiff ℝ 2 ξ) :
    firstVariation P A (orbitDirection A ξ) = 0 := by
  unfold firstVariation
  have hzero : ∀ x, ∑ i, ∑ j,
      P.B (covariantVariation A (orbitDirection A ξ) i j x) (curvature A i j x) = 0 := by
    intro x
    apply Finset.sum_eq_zero
    intro i _
    apply Finset.sum_eq_zero
    intro j _
    rw [covariantVariation_orbitDirection A hA ξ hξ i j x]
    exact pairing_bracket_self P.toInvariantPairing _ _
  simp only [hzero, integral_zero]

end Soma.Holonics.Millennium.HolonicYangMillsOrbitDirection
