import ElementaryHolonics.Millennium.AngleExcess
import Mathlib.Tactic

/-!
# The holon: three constrained infinities whose coupling has finitely many states

Brandon, 2026-08-23: *"an intersection of three combinatorially constrained infinities along their
own axes… coupled… the global object maintains a finite set of states despite being composed of
infinitely many parts.  That's a holon."*

That object has a name and this file gives it.  A **triangle group** `Δ(p,q,r)` is generated by
three rotations of infinite order in the free product, constrained by `xʳ = yᵠ = zᵖ = xyz = 1`.  The
group is infinite as a set of *words* and its tessellation has infinitely many tiles — and it has
**finitely many states exactly when the angle excess is positive**, which is
`AngleExcess.thePositiveExcessTriplesAreClassified`.  The count is not qualitative:

```text
|Δ(p,q,r)| = 2 / E(p,q,r) ,        E = 1/p + 1/q + 1/r − 1
```

giving `12`, `24`, `60` for the tetrahedral, octahedral and icosahedral holons and `2n` for the
dihedral family.  **The order of the holon is the reciprocal of its excess** — finiteness is a
division, and the thing being divided is the curvature.

**Fractal packing is the same object on the other side of zero.**  When the excess is negative the
orbit is an infinite packing whose *limit set* is a fractal — the Apollonian gasket.  Its governing
relation is Descartes' circle theorem

```text
(k₁ + k₂ + k₃ + k₄)² = 2(k₁² + k₂² + k₃² + k₄²) ,
```

a quadratic form of signature `(3,1)` — **three axes and one**, which is where the `3 + 1` comes
from without anyone putting it there.  And the second root of that quadratic in `k₄` is

```text
k₄′ = 2(k₁ + k₂ + k₃) − k₄ ,
```

**a reflection**: Vieta's other root *is* the reflected curvature, so generating the packing is
integration by reflection, literally, with the swing as the step.  Both roots are proved below to
satisfy the same form.

**On the degree count.**  The honest arithmetic: rigid motions of `d`-dimensional spacetime have
`d` translations and `d(d−1)/2` rotations, so `d = 4` gives `4 + 6 = 10` — the Poincaré group —
and adjoining the dilation gives `11`.  Separately, `2^{⌊11/2⌋} = 2^5 = 32` is the supercharge
ceiling (`Horizon.theSpinorCeilingIsCrossedBetweenElevenAndTwelve`).  Two independent countings
land on eleven; that they agree is recorded, not explained.  Brandon's `4 · 3 = 12` is the count
*before* a closure relation removes one, the same way three generators and four relations present
a triangle group.
-/

namespace Soma.Holonics.Millennium.Holon

open Soma.Holonics.Millennium.AngleExcess

/-! ## 1.  The order of a holon is the reciprocal of its excess -/

/-- The order of the rotation group of the `(p,q,r)` holon. -/
def holonOrder (p q r : ℕ) : ℚ := 2 / excess p q r

/-- **THE THREE SPORADIC HOLONS AND THEIR ORDERS.**  Twelve, twenty-four, sixty — tetrahedral,
octahedral, icosahedral.  Finitely many states from three infinite axes. -/
theorem theSporadicHolonOrders :
    holonOrder 2 3 3 = 12 ∧ holonOrder 2 3 4 = 24 ∧ holonOrder 2 3 5 = 60 := by
  refine ⟨?_, ?_, ?_⟩ <;> norm_num [holonOrder, excess]

/-- **AND THE DIHEDRAL FAMILY HAS ORDER `2n`.**  One infinite family plus three sporadic ones —
the same list `thePositiveExcessTriplesAreClassified` returns. -/
theorem theDihedralHolonOrder (n : ℕ) (hn : 0 < n) : holonOrder 2 2 n = 2 * n := by
  have hnQ : (n : ℚ) ≠ 0 := by exact_mod_cast hn.ne'
  rw [holonOrder, excess]
  field_simp
  ring

/-- Lean's field division is totalized, so the reciprocal encoding returns zero when the excess
is zero.  This theorem records that algebraic convention only; it does **not** prove that a
geometric group or tessellation is infinite. -/
theorem theFlatHolonTotalizationReturnsZero : excess 3 3 3 = 0 ∧ holonOrder 3 3 3 = 0 := by
  refine ⟨by norm_num [excess], by norm_num [holonOrder, excess]⟩

/-! ## 2.  Fractal packing: Descartes' form and its reflection -/

/-- Descartes' circle relation as a quadratic form: four mutually tangent circles of curvature
`k₁ … k₄` satisfy `descartes = 0`. -/
def descartes (a b c d : ℚ) : ℚ := (a + b + c + d) ^ 2 - 2 * (a ^ 2 + b ^ 2 + c ^ 2 + d ^ 2)

/-- **THE CLASSIC GASKET SEED SATISFIES IT.**  `(−1, 2, 2, 3)`: a unit circle with two halves and
a third inside. -/
theorem theGasketSeedIsDescartes : descartes (-1) 2 2 3 = 0 := by norm_num [descartes]

/-- **THE SUCCESSOR CURVATURE IS A REFLECTION.**  Vieta's other root of the Descartes quadratic in
`k₄` is `2(k₁+k₂+k₃) − k₄`, and it satisfies the same relation — so generating the packing *is*
reflection, with the swing as the step and no new mechanism anywhere. -/
theorem theApollonianSuccessorIsAReflection (a b c d : ℚ) :
    descartes a b c (2 * (a + b + c) - d) = descartes a b c d := by
  rw [descartes, descartes]; ring

/-- The seed's reflected successor, exhibited: `2(−1+2+2) − 3 = 3`, so the seed is at a fixed
point of the reflection — the symmetric gasket. -/
theorem theSeedIsFixedByItsReflection : (2 : ℚ) * (-1 + 2 + 2) - 3 = 3 := by norm_num

/-- And a genuinely new curvature from the other face: reflecting `k₁ = −1` gives `2(2+2+3) − (−1)
= 15`, the next circle in the gasket. -/
theorem theNextGasketCurvature : descartes 15 2 2 3 = 0 ∧ (2 : ℚ) * (2 + 2 + 3) - (-1) = 15 := by
  refine ⟨by norm_num [descartes], by norm_num⟩

/-! ## 3.  The degree count, stated as arithmetic -/

/-- Rigid motions of `d`-dimensional spacetime: `d` translations and `d(d−1)/2` rotations. -/
def rigidMotionDimension (d : ℕ) : ℕ := d + d * (d - 1) / 2

/-- **TEN, AND ELEVEN WITH THE DILATION.**  `dim(Poincaré) = 10` in four dimensions, and adjoining
the scale gives eleven — the same eleven the spinor ceiling returns from an unrelated count. -/
theorem theSimilitudeCountIsEleven :
    rigidMotionDimension 4 = 10 ∧ rigidMotionDimension 4 + 1 = 11 := by
  refine ⟨by decide, by decide⟩

/-- Three axes give three pairwise planes, and the `4 · 3` reading counts one relation too many —
the same way three generators and four relations present a triangle group. -/
theorem theThreePairwisePlanes : Nat.choose 3 2 = 3 ∧ 4 * 3 = rigidMotionDimension 4 + 2 := by
  refine ⟨by decide, by decide⟩

end Soma.Holonics.Millennium.Holon
