import Mathlib.RingTheory.DedekindDomain.SelmerGroup
import ElementaryHolonics.Millennium.Descent
import Mathlib.Tactic

/-!
# SelmerLanding: the four computed square classes land in mathlib's own Selmer group

`Descent` computed a four-element population by hand — the descent face of `y² = x³ − x` sends the
four rational two-torsion points to the square classes of `1`, `−1`, `2`, `−2` — and carried the
square-class relation as a bespoke predicate `SqCls`.  **This file lands that population inside
`IsDedekindDomain.selmerGroup`, mathlib's own object**, for `R = ℤ`, `K = ℚ`, `n = 2` and the
aperture `S = {(2)}`, and shows the hand-rolled relation and the library quotient are the same
relation.

What is proved, all exact and all through mathlib's carriers:

* the height-one prime `(2)` of `ℤ` is constructed, and it is the **only** height-one prime of `ℤ`
  containing `2`;
* the `v`-adic valuation of an integer is trivial at every prime avoiding it, so `±1` is trivial
  everywhere and `±2` is trivial away from `(2)`;
* **membership**: each of `1`, `−1`, `2`, `−2`, as a class in `ℚˣ ⧸ (ℚˣ)²`, lies in
  `ℚ⟮{(2)}, 2⟯`;
* **the aperture is load-bearing and is measured, not authored**: the valuation of `2` at `(2)` is
  the inverse uniformizer, its exponent is odd, and therefore the class of `2` is **refused** by
  the Selmer group of the empty aperture.  A declared input that could not fail would carry no
  evidence; this one fails when `(2)` is removed;
* **the bridge**: `Descent.SqCls` between two nonzero rationals is *exactly* equality of their
  images in `ℚˣ ⧸ (ℚˣ)²`, and `Descent`'s eight computed slot values are the values of the four
  unit representatives named here;
* **the four classes are pairwise distinct**, so the landed population is a Klein four-group and
  not a collapsed one — carried by `−1`, `2`, `−2` failing to be rational squares, three of the six
  separations reusing `Descent`'s own refusals;
* **the image is a subgroup**: the four classes are closed under multiplication — the six products
  among the three nontrivial classes are named with their square witnesses, and the whole
  sixteen-entry table is discharged in the subgroup construction — every element is its own
  inverse, the resulting `faceClassGroup` is generated by the classes of `−1` and `2`, and it lies
  inside the Selmer group;
* **the descent image proper**: the face returns a *pair* of classes, so the object a two-descent
  injects into is `ℚ⟮S,2⟯ × ℚ⟮S,2⟯`.  `Descent`'s four computed pairs `(1,1)`, `(−1,−1)`, `(1,2)`,
  `(−1,−2)` are built as a subgroup of that pair group, they are proved to be exactly the pairs
  `Descent` computed, and the subgroup is proved **strictly smaller** than the pair Selmer group —
  the pair `(2,1)` is admitted by the valuation condition in both slots and is not a face pair.
  That gap is where a Tate–Shafarevich class would live.

What is **refused**, and refused on purpose:

* no local solvability is computed anywhere in this file — no completion, no `ℚ_p`, no local point
  search, no Hasse condition.  The locally admissible population is therefore a **declared
  parameter**, never an authored partition;
* the Tate–Shafarevich statement is a named-open `Prop` about the parameter, not a theorem.  It is
  shown to be **satisfiable** (by the computed image itself) and shown to **fail** for the pair
  Selmer group itself, so it is a real constraint on its argument and not `True` wearing a name;
* nothing here computes or claims the rank, the analytic rank, an L-function, a height pairing, or
  a regulator.

Classical provenance, cited and not proved here: the descent argument on `y² = x³ − x` is Fermat's
right-triangle theorem and his infinite descent (Fermat, c. 1640); the finite generation the
descent serves is Mordell (1922) and Weil (1929); the Selmer group is named for Selmer (1951); the
Tate–Shafarevich group is Shafarevich (1959) and Tate; the conjecture the vanishing of `Ш[2]`
serves is Birch and Swinnerton-Dyer (1965); the identification of `H¹(K, μₙ)` with `Kˣ/(Kˣ)ⁿ` used
by mathlib's definition is Kummer theory with Hilbert's theorem 90.  For this curve the classical
two-descent returns the Selmer group *of the curve* — the locally admissible subgroup of the pair
group, which is a different object from `ℚ⟮{(2)}, 2⟯` — equal to the computed image, hence
`Ш(E/ℚ)[2] = 0`; imported as prose, never as a `theorem`.

**Measured 2026-08-21** over the pinned Mathlib (`v4.27.0`, revision `a3a10db0e9`) at
`.lake/packages/mathlib`: `grep -rli "selmer" Mathlib --include="*.lean"` → **2 files**
(`RingTheory/DedekindDomain/SelmerGroup.lean`, and `RingTheory/Polynomial/Selmer.lean`, which is
Selmer's trinomials and unrelated); `grep -rli "shafarevich" Mathlib --include="*.lean"` → **0**;
`grep -rli "mordell" Mathlib --include="*.lean"` → **0**; `grep -rli "congruent number" Mathlib
--include="*.lean"` → **0**.  Those commands measure those names over that scope; they are not a
claim that no related content exists under another name.

Every theorem is discharged and none depends on sorryAx.

**One containment is proved and its converse is imported, and the two must not be confused.**
Below it is proved that `faceClassGroup ≤ ℚ⟮{(2)}, 2⟯`.  The reverse containment is **true and not
proved here**: the fundamental exact sequence
`1 → ℤ_S^× / (ℤ_S^×)² → ℚ⟮S,2⟯ → Cl_S(ℤ)[2] → 0`, with `Cl(ℤ)` trivial and `ℤ_S^× = ⟨−1, 2⟩`,
gives `ℚ⟮{(2)}, 2⟯ = {±1, ±2}` exactly — equivalently, a squarefree integer with an odd prime
factor has odd valuation there.  Proving that in Lean needs the factorization of a rational into
its height-one valuations, which no theorem below performs, so the equality is carried as imported
prose.  **This is why the Tate–Shafarevich statement below is posed over the *pair* group**: over
one coordinate the Selmer group and the face-value group coincide and the statement would have no
room in it, while over pairs the image is proved strictly smaller than the Selmer group and the gap
is exhibited.

**Boundary.**  This file does not claim the Birch–Swinnerton-Dyer conjecture, any part of it, or
any movement on it.  It does not claim `Ш(E/ℚ)[2] = 0`, and it computes no local condition of any
kind.  It does not construct the descent map from `E(ℚ)/2E(ℚ)` into the Selmer group; `Descent`
carries that map's multiplicativity and kernel as its own named-open propositions and they stay
open, so nothing below establishes that the four pairs are the *whole* image of the point group.
It does not prove that `ℚ⟮{(2)}, 2⟯` equals the four classes, only that it contains them.  What is
owned here is the **landing** — the four classes and the four pairs, in mathlib's group, with the
aperture measured — and the **closure** of that population under the group law.
-/

namespace Soma.Holonics.Millennium.SelmerLanding

open IsDedekindDomain

/-! ## 1. The height-one prime `(2)` of `ℤ`, and the aperture it spans -/

/-- The height-one prime `(2)` of `ℤ`: the ideal `2ℤ`, prime because `2` is prime in `ℤ`, and
nonzero because `2 ≠ 0`. -/
noncomputable def primeTwo : HeightOneSpectrum ℤ where
  asIdeal := Ideal.span {2}
  isPrime := (Ideal.span_singleton_prime (by norm_num)).mpr Int.prime_two
  ne_bot := by simp [Ideal.span_singleton_eq_bot]

/-- The declared aperture: the one-element set of height-one primes at which a valuation is
allowed to be odd. -/
noncomputable def apertureAtTwo : Set (HeightOneSpectrum ℤ) := {primeTwo}

/-- **The only height-one prime of `ℤ` containing `2` is `(2)`.**  The ideal `2ℤ` is maximal, so
any prime ideal above it is equal to it, and a height-one point is determined by its ideal. -/
theorem theOnlyPrimeContainingTwoIsThePrimeTwo (v : HeightOneSpectrum ℤ)
    (h : (2 : ℤ) ∈ v.asIdeal) : v = primeTwo := by
  have hle : primeTwo.asIdeal ≤ v.asIdeal := by
    simpa [primeTwo, Ideal.span_singleton_le_iff_mem] using h
  exact HeightOneSpectrum.ext (primeTwo.isMaximal.eq_of_le v.isPrime.ne_top hle).symm

/-- `1` lies in no height-one prime: a prime ideal is proper. -/
theorem theUnitAvoidsEveryPrime (v : HeightOneSpectrum ℤ) : (1 : ℤ) ∉ v.asIdeal := by
  simpa [Ideal.eq_top_iff_one] using v.isPrime.ne_top

/-- `−1` lies in no height-one prime, because an ideal containing `−1` contains `1`. -/
theorem theNegativeUnitAvoidsEveryPrime (v : HeightOneSpectrum ℤ) : (-1 : ℤ) ∉ v.asIdeal := by
  simpa [Ideal.neg_mem_iff, Ideal.eq_top_iff_one] using v.isPrime.ne_top

/-- `2` lies in no height-one prime other than `(2)`. -/
theorem theTwoAvoidsEveryOtherPrime (v : HeightOneSpectrum ℤ) (hv : v ≠ primeTwo) :
    (2 : ℤ) ∉ v.asIdeal := fun h => hv (theOnlyPrimeContainingTwoIsThePrimeTwo v h)

/-- `−2` lies in no height-one prime other than `(2)`. -/
theorem theNegativeTwoAvoidsEveryOtherPrime (v : HeightOneSpectrum ℤ) (hv : v ≠ primeTwo) :
    (-2 : ℤ) ∉ v.asIdeal := by
  simpa [Ideal.neg_mem_iff] using theTwoAvoidsEveryOtherPrime v hv

/-! ## 2. The square-class carrier and its algebra

Mathlib's Selmer group lives in `Kˣ ⧸ (powMonoidHom n).range`.  For `K = ℚ` and `n = 2` that is
the square-class group of `ℚ`, and the class map is the quotient map. -/

/-- The square-class group of `ℚ`: units modulo squares, in exactly the shape mathlib's Selmer
group is a subgroup of. -/
abbrev SquareClass : Type := ℚˣ ⧸ (powMonoidHom 2 : ℚˣ →* ℚˣ).range

/-- The class of a nonzero rational in the square-class group. -/
def cls (x : ℚˣ) : SquareClass := QuotientGroup.mk x

/-- **The class map is multiplicative** — `rfl`, because the quotient map of a group by a subgroup
is defined by transport of the multiplication. -/
theorem theClassMapIsMultiplicative (a b : ℚˣ) : cls (a * b) = cls a * cls b := rfl

/-- The class of a square is the identity. -/
theorem theClassOfASquareIsTrivial (c : ℚˣ) : cls (c ^ 2) = 1 :=
  (QuotientGroup.eq_one_iff _).mpr ⟨c, rfl⟩

/-- A square factor does not move the class. -/
theorem theClassIsUnchangedByASquareFactor {a b c : ℚˣ} (h : a = c ^ 2 * b) : cls a = cls b := by
  rw [h, theClassMapIsMultiplicative, theClassOfASquareIsTrivial, one_mul]

/-- **Class equality is exactly a square factor** — the quotient relation unfolded, in both
directions. -/
theorem theClassEqualityIsASquareFactor (a b : ℚˣ) :
    cls a = cls b ↔ ∃ c : ℚˣ, a = c ^ 2 * b := by
  constructor
  · intro h
    have h' : (QuotientGroup.mk a : SquareClass) = QuotientGroup.mk b := h
    obtain ⟨c, hc⟩ := QuotientGroup.eq_iff_div_mem.mp h'
    refine ⟨c, ?_⟩
    rw [powMonoidHom_apply] at hc
    rw [hc]
    simp
  · rintro ⟨c, rfl⟩
    exact theClassIsUnchangedByASquareFactor rfl

/-! ## 3. The four representatives -/

/-- The representative `1`. -/
def unitOne : ℚˣ := 1

/-- The representative `−1`. -/
def unitNegOne : ℚˣ := -1

/-- The representative `2`. -/
noncomputable def unitTwo : ℚˣ := Units.mk0 2 (by norm_num)

/-- The representative `−2`. -/
noncomputable def unitNegTwo : ℚˣ := Units.mk0 (-2) (by norm_num)

/-- **The four representatives carry the four values** `1`, `−1`, `2`, `−2` — every component
`rfl`, since each unit is built directly on its value. -/
theorem theFourRepresentativesCarryTheirValues :
    ((unitOne : ℚ) = 1 ∧ (unitNegOne : ℚ) = -1) ∧
    ((unitTwo : ℚ) = 2 ∧ (unitNegTwo : ℚ) = -2) :=
  ⟨⟨rfl, rfl⟩, ⟨rfl, rfl⟩⟩

/-- The class of `1` is the identity of the square-class group. -/
theorem theClassOfOneIsTheIdentity : cls unitOne = 1 := QuotientGroup.mk_one _

/-! ## 4. Valuations away from the aperture -/

/-- **The `v`-adic valuation of an integer avoiding `v` is trivial.**  This is mathlib's
`intValuation_eq_one_iff` transported along the fraction field. -/
theorem theValuationOfAnAvoidingIntegerIsTrivial (v : HeightOneSpectrum ℤ) {m : ℤ}
    (hm : m ∉ v.asIdeal) : v.valuation ℚ (m : ℚ) = 1 := by
  have h : ((m : ℚ)) = algebraMap ℤ ℚ m := by simp
  rw [h, HeightOneSpectrum.valuation_of_algebraMap]
  exact HeightOneSpectrum.intValuation_eq_one_iff.mpr hm

/-- The multiplicative valuation on `ℚˣ` is trivial wherever the valuation on `ℚ` is. -/
theorem theUnitValuationIsTrivialWhereTheValuationIs (v : HeightOneSpectrum ℤ) (x : ℚˣ)
    (h : v.valuation ℚ (x : ℚ) = 1) : v.valuationOfNeZero (K := ℚ) x = 1 := by
  have hx := v.valuationOfNeZero_eq (K := ℚ) x
  rw [h] at hx
  exact_mod_cast hx

/-! ## 5. The Selmer group, and the landing -/

/-- The Selmer group `ℚ⟮{(2)}, 2⟯`: mathlib's `selmerGroup` at `R = ℤ`, `K = ℚ`, the aperture
`{(2)}`, and `n = 2`. -/
noncomputable def selmerAtTwo : Subgroup SquareClass :=
  IsDedekindDomain.selmerGroup (R := ℤ) (K := ℚ) (S := apertureAtTwo) (n := 2)

/-- **The landing criterion**: a class lands in the Selmer group as soon as its representative has
trivial valuation at every height-one prime other than `(2)`. -/
theorem theClassLandsWhenEveryOtherValuationIsTrivial {x : ℚˣ}
    (h : ∀ v : HeightOneSpectrum ℤ, v ≠ primeTwo → v.valuation ℚ (x : ℚ) = 1) :
    cls x ∈ selmerAtTwo := by
  intro v hv
  have hv' : v ≠ primeTwo := by simpa [apertureAtTwo] using hv
  have h1 : v.valuationOfNeZero (K := ℚ) x = 1 :=
    theUnitValuationIsTrivialWhereTheValuationIs v x (h v hv')
  show v.valuationOfNeZeroMod 2 (QuotientGroup.mk x) = 1
  erw [HeightOneSpectrum.valuationOfNeZeroMod, MonoidHom.comp_apply, ← QuotientGroup.coe_mk',
    QuotientGroup.map_mk' (G := ℚˣ) (N := MonoidHom.range (powMonoidHom 2)), h1,
    QuotientGroup.mk_one, map_one]

/-- The landing criterion specialised to an integer representative. -/
theorem theIntegerClassLandsWhenTheIntegerAvoidsEveryOtherPrime {x : ℚˣ} {m : ℤ}
    (hxm : (x : ℚ) = (m : ℚ))
    (h : ∀ v : HeightOneSpectrum ℤ, v ≠ primeTwo → m ∉ v.asIdeal) :
    cls x ∈ selmerAtTwo :=
  theClassLandsWhenEveryOtherValuationIsTrivial fun v hv => by
    rw [hxm]; exact theValuationOfAnAvoidingIntegerIsTrivial v (h v hv)

/-- **The four computed classes lie in `ℚ⟮{(2)}, 2⟯`.**  The classes of `±1` land because a unit of
`ℤ` has trivial valuation everywhere; the classes of `±2` land because `2` is odd only at `(2)`,
which the aperture admits. -/
theorem theFourClassesLieInTheSelmerGroup :
    cls unitOne ∈ selmerAtTwo ∧ cls unitNegOne ∈ selmerAtTwo ∧
    cls unitTwo ∈ selmerAtTwo ∧ cls unitNegTwo ∈ selmerAtTwo := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact theIntegerClassLandsWhenTheIntegerAvoidsEveryOtherPrime
      (m := 1) (by norm_num [unitOne]) fun v _ => theUnitAvoidsEveryPrime v
  · exact theIntegerClassLandsWhenTheIntegerAvoidsEveryOtherPrime
      (m := -1) (by norm_num [unitNegOne]) fun v _ => theNegativeUnitAvoidsEveryPrime v
  · exact theIntegerClassLandsWhenTheIntegerAvoidsEveryOtherPrime
      (m := 2) (by norm_num [unitTwo]) fun v hv => theTwoAvoidsEveryOtherPrime v hv
  · exact theIntegerClassLandsWhenTheIntegerAvoidsEveryOtherPrime
      (m := -2) (by norm_num [unitNegTwo]) fun v hv => theNegativeTwoAvoidsEveryOtherPrime v hv

/-! ## 6. The aperture is load-bearing, and the refusal is exhibited

A declared input whose variation cannot move the result carries no evidence.  Here the aperture
can be varied: remove `(2)` and the class of `2` is refused, because the valuation of `2` at `(2)`
has odd exponent. -/

/-- **The valuation of `2` at the prime `(2)` is the inverse uniformizer** — exponent `−1`, which
is odd.  This is mathlib's `intValuation_singleton` at a generator of the ideal. -/
theorem theValuationOfTwoAtThePrimeTwoIsTheInverseUniformizer :
    primeTwo.valuationOfNeZero (K := ℚ) unitTwo = Multiplicative.ofAdd (-1 : ℤ) := by
  have h1 := primeTwo.valuationOfNeZero_eq (K := ℚ) unitTwo
  have h2 : primeTwo.valuation ℚ ((unitTwo : ℚ)) = WithZero.exp (-1 : ℤ) := by
    have hcast : ((unitTwo : ℚ)) = algebraMap ℤ ℚ (2 : ℤ) := by norm_num [unitTwo]
    rw [hcast, HeightOneSpectrum.valuation_of_algebraMap]
    exact primeTwo.intValuation_singleton (by norm_num) rfl
  rw [h2] at h1
  exact WithZero.coe_inj.mp h1

/-- **The class of `2` is refused by the Selmer group of the empty aperture.**  Its valuation
exponent at `(2)` is `−1`, which is not divisible by `2`; the falsifier of the landing above is
therefore live, and the aperture `{(2)}` is measured rather than declared for convenience. -/
theorem theTwoClassIsRefusedWhenThePrimeTwoIsRemoved :
    cls unitTwo ∉
      IsDedekindDomain.selmerGroup (R := ℤ) (K := ℚ)
        (S := (∅ : Set (HeightOneSpectrum ℤ))) (n := 2) := by
  intro hmem
  have h := hmem primeTwo (Set.notMem_empty _)
  rw [show cls unitTwo = QuotientGroup.mk unitTwo from rfl] at h
  erw [HeightOneSpectrum.valuationOfNeZeroMod, MonoidHom.comp_apply, ← QuotientGroup.coe_mk',
    QuotientGroup.map_mk' (G := ℚˣ) (N := MonoidHom.range (powMonoidHom 2)),
    theValuationOfTwoAtThePrimeTwoIsTheInverseUniformizer] at h
  have h2 := (map_eq_one_iff _ (MulEquiv.injective _)).mp h
  have h2' : (Multiplicative.ofAdd (-1 : ℤ) : Multiplicative ℤ) ∈
      (AddSubgroup.zmultiples (2 : ℤ)).toSubgroup := by
    exact (QuotientGroup.eq_one_iff _).mp h2
  have h2 : (-1 : ℤ) ∈ AddSubgroup.zmultiples (2 : ℤ) := h2'
  simp only [Multiplicative.mem_toSubgroup, AddSubgroup.mem_zmultiples_iff, smul_eq_mul] at h2
  obtain ⟨k, hk⟩ := h2
  omega

/-! ## 7. The bridge: `Descent`'s hand-rolled relation is the library quotient -/

/-- **`Descent.SqCls` on the values of two units is exactly equality of their classes.**  The
bespoke predicate and mathlib's quotient are the same relation; nothing was invented by carrying
the relation by hand, and nothing is lost by moving to the library object. -/
theorem theSquareClassRelationIsQuotientEquality (a b : ℚˣ) :
    Descent.SqCls (a : ℚ) (b : ℚ) ↔ cls a = cls b := by
  constructor
  · rintro ⟨c, hc, h⟩
    refine theClassIsUnchangedByASquareFactor (c := Units.mk0 c hc) ?_
    apply Units.val_injective
    push_cast
    simpa using h
  · intro h
    obtain ⟨c, hc⟩ := (theClassEqualityIsASquareFactor a b).mp h
    refine ⟨(c : ℚ), c.ne_zero, ?_⟩
    have := congrArg (Units.val) hc
    push_cast at this
    simpa using this

/-- **`Descent`'s eight computed slot values are the values of the four representatives named
here.**  The face `P ↦ (x, x − 1)` returned `(1,1)`, `(−1,−1)`, `(1,2)`, `(−1,−2)`; those are
exactly `unitOne`, `unitNegOne`, `unitTwo`, `unitNegTwo` read as rationals. -/
theorem theDescentFaceValuesAreTheFourRepresentatives :
    (Descent.slotOne 0 = (unitOne : ℚ) ∧ Descent.slotTwo 0 = (unitOne : ℚ)) ∧
    (Descent.slotOne Descent.P00 = (unitNegOne : ℚ) ∧
      Descent.slotTwo Descent.P00 = (unitNegOne : ℚ)) ∧
    (Descent.slotOne Descent.P10 = (unitOne : ℚ) ∧
      Descent.slotTwo Descent.P10 = (unitTwo : ℚ)) ∧
    (Descent.slotOne Descent.Pm10 = (unitNegOne : ℚ) ∧
      Descent.slotTwo Descent.Pm10 = (unitNegTwo : ℚ)) := by
  obtain ⟨⟨e1, e2⟩, ⟨a1, a2⟩, ⟨b1, b2⟩, ⟨c1, c2⟩⟩ := Descent.theFourFaceValues
  refine ⟨⟨?_, ?_⟩, ⟨?_, ?_⟩, ⟨?_, ?_⟩, ⟨?_, ?_⟩⟩ <;>
    first
      | (rw [e1]; rfl) | (rw [e2]; rfl)
      | (rw [a1]; rfl) | (rw [a2]; rfl)
      | (rw [b1]; rfl) | (rw [b2]; rfl)
      | (rw [c1]; rfl) | (rw [c2]; rfl)

/-! ## 8. The four classes are pairwise distinct

Three of the six separations are `Descent`'s own refusals, reused rather than restated; three are
new and are proved the same way — by sign, or by two not being a rational square. -/

/-- `−2` is not a square times `1`: a square is non-negative. -/
theorem theNegativeTwoClassIsNotTheTrivialClass : ¬ Descent.SqCls (-2) 1 := by
  rintro ⟨c, -, h⟩
  nlinarith [sq_nonneg c]

/-- `2` is not a square times `−1`: it would force a negative square. -/
theorem theTwoClassIsNotTheNegativeUnitClass : ¬ Descent.SqCls 2 (-1) := by
  rintro ⟨c, -, h⟩
  nlinarith [sq_nonneg c]

/-- `−2` is not a square times `2`: it would force a negative square. -/
theorem theNegativeTwoClassIsNotTheTwoClass : ¬ Descent.SqCls (-2) 2 := by
  rintro ⟨c, -, h⟩
  nlinarith [sq_nonneg c]

/-- **The four classes are pairwise distinct.**  The landed population has exactly four elements,
so it is a Klein four-group and not a collapsed image: the arithmetic that pays for the geometry is
`−1`, `2` and `−2` each failing to be a rational square. -/
theorem theFourClassesArePairwiseDistinct :
    cls unitNegOne ≠ cls unitOne ∧ cls unitTwo ≠ cls unitOne ∧
    cls unitNegTwo ≠ cls unitOne ∧ cls unitTwo ≠ cls unitNegOne ∧
    cls unitNegTwo ≠ cls unitNegOne ∧ cls unitNegTwo ≠ cls unitTwo := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;> intro h
  · exact Descent.theNegativeUnitClassIsNotTheTrivialClass
      ((theSquareClassRelationIsQuotientEquality unitNegOne unitOne).mpr h)
  · exact Descent.theTwoClassIsNotTheTrivialClass
      ((theSquareClassRelationIsQuotientEquality unitTwo unitOne).mpr h)
  · exact theNegativeTwoClassIsNotTheTrivialClass
      ((theSquareClassRelationIsQuotientEquality unitNegTwo unitOne).mpr h)
  · exact theTwoClassIsNotTheNegativeUnitClass
      ((theSquareClassRelationIsQuotientEquality unitTwo unitNegOne).mpr h)
  · exact Descent.theNegativeTwoClassIsNotTheNegativeUnitClass
      ((theSquareClassRelationIsQuotientEquality unitNegTwo unitNegOne).mpr h)
  · exact theNegativeTwoClassIsNotTheTwoClass
      ((theSquareClassRelationIsQuotientEquality unitNegTwo unitTwo).mpr h)

/-! ## 9. The image is a subgroup

Every product of two of the four representatives lies back in the four, with its square witness
exhibited.  The six products among the three nontrivial representatives are named below: the three
whose value is already one of the four carry the square witness `1`, and the three whose value is
`4` or `−4` carry the square witness `2`, which is where the square class does the work.  The
remaining seven entries of the sixteen-entry table are the identity's row and column, and they are
discharged inside the subgroup construction from `theClassOfOneIsTheIdentity`. -/

private lemma negOneTimesNegOne : cls unitNegOne * cls unitNegOne = cls unitOne :=
  (theClassMapIsMultiplicative _ _).symm.trans <|
    theClassIsUnchangedByASquareFactor (c := 1) (by apply Units.val_injective; norm_num
      [unitNegOne, unitOne])

private lemma negOneTimesTwo : cls unitNegOne * cls unitTwo = cls unitNegTwo :=
  (theClassMapIsMultiplicative _ _).symm.trans <|
    theClassIsUnchangedByASquareFactor (c := 1) (by apply Units.val_injective; norm_num
      [unitNegOne, unitTwo, unitNegTwo])

private lemma negOneTimesNegTwo : cls unitNegOne * cls unitNegTwo = cls unitTwo :=
  (theClassMapIsMultiplicative _ _).symm.trans <|
    theClassIsUnchangedByASquareFactor (c := 1) (by apply Units.val_injective; norm_num
      [unitNegOne, unitTwo, unitNegTwo])

private lemma twoTimesTwo : cls unitTwo * cls unitTwo = cls unitOne :=
  (theClassMapIsMultiplicative _ _).symm.trans <|
    theClassIsUnchangedByASquareFactor (c := unitTwo) (by apply Units.val_injective; norm_num
      [unitTwo, unitOne])

private lemma twoTimesNegTwo : cls unitTwo * cls unitNegTwo = cls unitNegOne :=
  (theClassMapIsMultiplicative _ _).symm.trans <|
    theClassIsUnchangedByASquareFactor (c := unitTwo) (by apply Units.val_injective; norm_num
      [unitTwo, unitNegTwo, unitNegOne])

private lemma negTwoTimesNegTwo : cls unitNegTwo * cls unitNegTwo = cls unitOne :=
  (theClassMapIsMultiplicative _ _).symm.trans <|
    theClassIsUnchangedByASquareFactor (c := unitTwo) (by apply Units.val_injective; norm_num
      [unitTwo, unitNegTwo, unitOne])

/-- **The four classes are closed under multiplication**, with every product named: the three
squares return the identity, and the three cross products permute the other three classes.  This is
the multiplication table of `(ℤ/2)²`. -/
theorem theFourClassesAreClosedUnderMultiplication :
    (cls unitNegOne * cls unitNegOne = cls unitOne ∧
      cls unitTwo * cls unitTwo = cls unitOne ∧
      cls unitNegTwo * cls unitNegTwo = cls unitOne) ∧
    (cls unitNegOne * cls unitTwo = cls unitNegTwo ∧
      cls unitNegOne * cls unitNegTwo = cls unitTwo ∧
      cls unitTwo * cls unitNegTwo = cls unitNegOne) :=
  ⟨⟨negOneTimesNegOne, twoTimesTwo, negTwoTimesNegTwo⟩,
   ⟨negOneTimesTwo, negOneTimesNegTwo, twoTimesNegTwo⟩⟩


/-- The face-value class group: the four computed square classes, carried as an honest subgroup of
the square-class group of `ℚ`.  Closure under multiplication is the table above; closure under
inversion is that every element is its own inverse.

This is the **coordinate** object — the classes that appear in either slot of the descent face.  It
is not the descent image itself, which lives in the *pair* group and is built further below. -/
noncomputable def faceClassGroup : Subgroup SquareClass where
  carrier := {cls unitOne, cls unitNegOne, cls unitTwo, cls unitNegTwo}
  one_mem' := Or.inl theClassOfOneIsTheIdentity.symm
  mul_mem' := by
    rintro x y (rfl | rfl | rfl | rfl) (rfl | rfl | rfl | rfl) <;>
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff, theClassOfOneIsTheIdentity, one_mul,
        mul_one, negOneTimesNegOne, negOneTimesTwo, negOneTimesNegTwo, twoTimesTwo, twoTimesNegTwo,
        negTwoTimesNegTwo, mul_comm (cls unitTwo) (cls unitNegOne),
        mul_comm (cls unitNegTwo) (cls unitNegOne), mul_comm (cls unitNegTwo) (cls unitTwo)] <;>
      tauto
  inv_mem' := by
    rintro x (rfl | rfl | rfl | rfl)
    · simp only [theClassOfOneIsTheIdentity, inv_one]
      exact Or.inl theClassOfOneIsTheIdentity.symm
    · exact Or.inr (Or.inl (by
        rw [inv_eq_of_mul_eq_one_right (negOneTimesNegOne.trans theClassOfOneIsTheIdentity)]))
    · exact Or.inr (Or.inr (Or.inl (by
        rw [inv_eq_of_mul_eq_one_right (twoTimesTwo.trans theClassOfOneIsTheIdentity)])))
    · refine Or.inr (Or.inr (Or.inr ?_))
      rw [inv_eq_of_mul_eq_one_right (negTwoTimesNegTwo.trans theClassOfOneIsTheIdentity)]
      exact rfl

/-- Membership in the face-value class group is exactly being one of the four classes. -/
theorem theFaceClassGroupIsTheFourClasses (x : SquareClass) :
    x ∈ faceClassGroup ↔
      x = cls unitOne ∨ x = cls unitNegOne ∨ x = cls unitTwo ∨ x = cls unitNegTwo := Iff.rfl

/-- **Every element of the face-value class group is its own inverse** — it is elementary abelian
of exponent two, as a subgroup of a square-class group must be. -/
theorem theFaceClassGroupHasExponentTwo (x : SquareClass) (hx : x ∈ faceClassGroup) :
    x * x = 1 := by
  rcases hx with rfl | rfl | rfl | rfl
  · rw [theClassOfOneIsTheIdentity, one_mul]
  · rw [negOneTimesNegOne, theClassOfOneIsTheIdentity]
  · rw [twoTimesTwo, theClassOfOneIsTheIdentity]
  · rw [negTwoTimesNegTwo, theClassOfOneIsTheIdentity]

/-- **The face-value class group is generated by the classes of `−1` and `2`** — two generators for
a group of order four, which is the shape of the two-torsion population it came from. -/
theorem theFaceClassGroupIsGeneratedByTheNegativeAndTwoClasses :
    faceClassGroup = Subgroup.closure {cls unitNegOne, cls unitTwo} := by
  refine le_antisymm ?_ (Subgroup.closure_le _ |>.mpr ?_)
  · rintro x (rfl | rfl | rfl | rfl)
    · rw [theClassOfOneIsTheIdentity]; exact one_mem _
    · exact Subgroup.subset_closure (Or.inl rfl)
    · exact Subgroup.subset_closure (Or.inr rfl)
    · rw [← negOneTimesTwo]
      exact mul_mem (Subgroup.subset_closure (Or.inl rfl)) (Subgroup.subset_closure (Or.inr rfl))
  · rintro x (rfl | rfl)
    · exact Or.inr (Or.inl rfl)
    · exact Or.inr (Or.inr (Or.inl rfl))

/-- **The face-value class group lands inside the Selmer group** `ℚ⟮{(2)}, 2⟯` — the whole computed
class population of `Descent`, as a subgroup, inside mathlib's object. -/
theorem theFaceClassGroupLandsInTheSelmerGroup : faceClassGroup ≤ selmerAtTwo := by
  obtain ⟨h1, hm1, h2, hm2⟩ := theFourClassesLieInTheSelmerGroup
  rintro x (rfl | rfl | rfl | rfl)
  exacts [h1, hm1, h2, hm2]

/-! ## 10. The descent image lives in the pair group, and it is a proper subgroup

The descent face returns a **pair** of square classes, so the object a two-descent injects into is
`ℚ⟮S,2⟯ × ℚ⟮S,2⟯`, not one copy.  `Descent` computed the four pairs `(1,1)`, `(−1,−1)`, `(1,2)`,
`(−1,−2)`; they are built here as a subgroup of the pair group, and that subgroup is proved
**strictly smaller** than the pair group the Selmer group spans.  The gap between them is where a
Tate–Shafarevich class would live, which is why the statement below is worth making. -/

/-- The descent image: the four computed face pairs of `Descent`, as a subgroup of the pair
square-class group.  Multiplication is componentwise, so the table of the previous section
discharges the whole sixteen-entry closure. -/
noncomputable def descentImage : Subgroup (SquareClass × SquareClass) where
  carrier :=
    {(cls unitOne, cls unitOne), (cls unitNegOne, cls unitNegOne),
      (cls unitOne, cls unitTwo), (cls unitNegOne, cls unitNegTwo)}
  one_mem' := Or.inl (by rw [theClassOfOneIsTheIdentity]; rfl)
  mul_mem' := by
    rintro x y (rfl | rfl | rfl | rfl) (rfl | rfl | rfl | rfl) <;>
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Prod.mk_mul_mk, Prod.mk.injEq,
        theClassOfOneIsTheIdentity, one_mul, mul_one, negOneTimesNegOne, negOneTimesTwo,
        negOneTimesNegTwo, twoTimesTwo, twoTimesNegTwo, negTwoTimesNegTwo,
        mul_comm (cls unitTwo) (cls unitNegOne), mul_comm (cls unitNegTwo) (cls unitNegOne),
        mul_comm (cls unitNegTwo) (cls unitTwo)] <;>
      tauto
  inv_mem' := by
    rintro x (rfl | rfl | rfl | rfl) <;>
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff, Prod.inv_mk, Prod.mk.injEq,
        inv_eq_of_mul_eq_one_right (negOneTimesNegOne.trans theClassOfOneIsTheIdentity),
        inv_eq_of_mul_eq_one_right (twoTimesTwo.trans theClassOfOneIsTheIdentity),
        inv_eq_of_mul_eq_one_right (negTwoTimesNegTwo.trans theClassOfOneIsTheIdentity),
        theClassOfOneIsTheIdentity, inv_one] <;>
      tauto

/-- Membership in the descent image is exactly being one of the four computed face pairs. -/
theorem theDescentImageIsTheFourFacePairs (x : SquareClass × SquareClass) :
    x ∈ descentImage ↔
      x = (cls unitOne, cls unitOne) ∨ x = (cls unitNegOne, cls unitNegOne) ∨
        x = (cls unitOne, cls unitTwo) ∨ x = (cls unitNegOne, cls unitNegTwo) := Iff.rfl

/-- **The four members of the descent image are the four pairs `Descent` computed** — the identity
goes to `(1,1)`, `(0,0)` to `(−1,−1)`, `(1,0)` to `(1,2)`, `(−1,0)` to `(−1,−2)`, and each of those
rational pairs is the pair of values of the representatives generating the image. -/
theorem theDescentImageCarriesTheComputedFacePairs :
    ((Descent.slotOne 0, Descent.slotTwo 0) = ((unitOne : ℚ), (unitOne : ℚ))) ∧
    ((Descent.slotOne Descent.P00, Descent.slotTwo Descent.P00)
      = ((unitNegOne : ℚ), (unitNegOne : ℚ))) ∧
    ((Descent.slotOne Descent.P10, Descent.slotTwo Descent.P10)
      = ((unitOne : ℚ), (unitTwo : ℚ))) ∧
    ((Descent.slotOne Descent.Pm10, Descent.slotTwo Descent.Pm10)
      = ((unitNegOne : ℚ), (unitNegTwo : ℚ))) := by
  obtain ⟨⟨e1, e2⟩, ⟨a1, a2⟩, ⟨b1, b2⟩, ⟨c1, c2⟩⟩ := theDescentFaceValuesAreTheFourRepresentatives
  exact ⟨by rw [e1, e2], by rw [a1, a2], by rw [b1, b2], by rw [c1, c2]⟩

/-- **The descent image lands inside the pair Selmer group** `ℚ⟮{(2)},2⟯ × ℚ⟮{(2)},2⟯` — the object
a complete two-descent injects `E(ℚ)/2E(ℚ)` into. -/
theorem theDescentImageLandsInTheSelmerPairGroup :
    descentImage ≤ selmerAtTwo.prod selmerAtTwo := by
  obtain ⟨h1, hm1, h2, hm2⟩ := theFourClassesLieInTheSelmerGroup
  rintro x (rfl | rfl | rfl | rfl)
  exacts [⟨h1, h1⟩, ⟨hm1, hm1⟩, ⟨h1, h2⟩, ⟨hm1, hm2⟩]

/-- The pair `(2, 1)` lies in the pair Selmer group. -/
theorem theTwoOnePairLiesInTheSelmerPairGroup :
    (cls unitTwo, cls unitOne) ∈ selmerAtTwo.prod selmerAtTwo :=
  ⟨theFourClassesLieInTheSelmerGroup.2.2.1, theFourClassesLieInTheSelmerGroup.1⟩

/-- The pair `(2, 1)` is **not** in the descent image: its first slot is the class of `2`, which is
neither the trivial class nor the class of `−1`, and every member of the image has one of those two
in its first slot. -/
theorem theTwoOnePairIsOutsideTheDescentImage :
    (cls unitTwo, cls unitOne) ∉ descentImage := by
  obtain ⟨-, hTwoOne, -, hTwoNegOne, -, -⟩ := theFourClassesArePairwiseDistinct
  rintro (h | h | h | h)
  exacts [hTwoOne (congrArg Prod.fst h), hTwoNegOne (congrArg Prod.fst h),
    hTwoOne (congrArg Prod.fst h), hTwoNegOne (congrArg Prod.fst h)]

/-- **The descent image is a proper subgroup of the pair Selmer group.**  The pair `(2, 1)` is
admitted by the valuation condition in both slots and is not a computed face pair.  This gap is the
whole reason a Tate–Shafarevich statement has content: the Selmer side is larger than the image
until something rules the extra classes out, and nothing below rules them out. -/
theorem theDescentImageIsProperInTheSelmerPairGroup :
    descentImage < selmerAtTwo.prod selmerAtTwo :=
  lt_of_le_of_ne theDescentImageLandsInTheSelmerPairGroup fun h =>
    theTwoOnePairIsOutsideTheDescentImage (h ▸ theTwoOnePairLiesInTheSelmerPairGroup)

/-! ## 11. The Tate–Shafarevich statement, made statable and left open

The vanishing of `Ш(E/ℚ)[2]` for this curve says the locally admissible population inside the pair
Selmer group is exactly the image of the rational points.  Computing the locally admissible side
requires local solvability at every place — no completion, no `ℚ_p`, and no local point search
appears anywhere above — so that side enters as a **declared parameter**.  Declaring it and then
proving the equality would author the partition being tested. -/

/-- **`Ш(E/ℚ)[2] = 0` for `y² = x³ − x`, as a statement about a declared locally admissible
population.**  Given a subgroup `locallyAdmissible` of the pair square-class group of `ℚ` — the one
cut out by local solvability at every place, which this file does **not** compute — the vanishing
of the two-part of the Tate–Shafarevich group says it sits inside the pair Selmer group and is
exactly the descent image of the rational points.

*Aside: classical for this curve, by Fermat's descent; open here, and never discharged below.  The
two propositions that would supply the other half of the descent — that the face is a homomorphism
everywhere, and that its kernel is the doubled population — are `Descent`'s own named-open
statements and remain open there.* -/
def ShaTwoOfTheCongruentCurveVanishes
    (locallyAdmissible : Subgroup (SquareClass × SquareClass)) : Prop :=
  locallyAdmissible ≤ selmerAtTwo.prod selmerAtTwo ∧ locallyAdmissible = descentImage

/-- The statement is **satisfiable**: the computed image itself satisfies it.  This is a
non-vacuity check on the shape of the proposition and nothing more — the content of the conjecture
is that the *locally cut out* population is this one, and no local condition is computed here. -/
theorem theShaStatementIsSatisfiedByTheComputedImage :
    ShaTwoOfTheCongruentCurveVanishes descentImage :=
  ⟨theDescentImageLandsInTheSelmerPairGroup, rfl⟩

/-- The statement is **not** `True` in disguise: it fails for the pair Selmer group itself, which
is the population a two-descent starts from before any local condition is imposed.  A declared
population that could not fail the test would carry no evidence; this one can, and the separating
witness is the pair `(2, 1)`. -/
theorem theShaStatementFailsForTheWholeSelmerPairGroup :
    ¬ ShaTwoOfTheCongruentCurveVanishes (selmerAtTwo.prod selmerAtTwo) := by
  rintro ⟨-, hEq⟩
  exact absurd hEq theDescentImageIsProperInTheSelmerPairGroup.ne'

end Soma.Holonics.Millennium.SelmerLanding
