// ===== app3.js — pass 3/4 scenes: receivers all the way down, the Minkowski chart, the electrical atlas, Bord components; the receiver convention =====
(function (HR) {
  const { R, Rat } = HR; const { SCENES, state, paperFor, setReceipts, gaugeReceipt, drawGlyph, rgb, fmt, $ } = HR.App; const A2 = HR.Affine2;
  // the chart gauge: a class is a receiver coordinate carried by a ground tint AND a cell-mark direction (colour is never the only carrier)
  const CLASS_TINT = ['#f6f7f4', '#eef2f7', '#f4efe5', '#eef4ee']; const CLASS_DIR = ['r0', 'r90', 'd1', 'd2']; const DIRV = { r0: [1, 0], r90: [0, 1], d1: [1, 1], d2: [1, -1] };
  const rs = (x) => (x instanceof Rat ? x.toString() : String(x));
  function num(x) { return x instanceof Rat ? x.toNumber() : x; }
  const INK = [16, 18, 20];
  // ground of a receiver on the map: tint by class, hairline boundary, its own cells marked at exact corners with the class's D4 direction
  function drawGround(p, corners, cls, marks, opts = {}) { if (!opts.frameOnly) p.fill(corners, CLASS_TINT[cls % 4], 1, 'chart-ground'); p.line([...corners, corners[0]], { width: 1, role: 'chart-boundary' });
    const d = DIRV[CLASS_DIR[cls % 4]]; const L = opts.tick || 3; for (const m of marks) { const [x, y] = [num(m[0]), num(m[1])]; p.line([[x - d[0] * L / p.unit / 2, y - d[1] * L / p.unit / 2], [x + d[0] * L / p.unit / 2, y + d[1] * L / p.unit / 2]], { width: 1, role: 'cell-mark', alpha: 0.55 }); } }
  // the receiver convention for any scene: a chart rectangle in paper coordinates, its own cells marked every `step`, a class, a label
  function chartGround(p, rect, opts = {}) { const [x0, x1, y0, y1] = [rect.x0, rect.x1, rect.y0, rect.y1].map(num); const corners = [[x0, y0], [x1, y0], [x1, y1], [x0, y1]]; const step = opts.step || 1; const marks = [];
    if (opts.frameOnly) { for (let x = Math.ceil(x0 / step) * step; x <= x1; x += step) { marks.push([x, y0]); marks.push([x, y1]); } for (let y = Math.ceil(y0 / step) * step; y <= y1; y += step) { marks.push([x0, y]); marks.push([x1, y]); } }
    else for (let x = Math.ceil(x0 / step) * step; x <= x1; x += step) for (let y = Math.ceil(y0 / step) * step; y <= y1; y += step) marks.push([x, y]);
    drawGround(p, corners, opts.cls || 0, marks, { frameOnly: opts.frameOnly }); if (opts.label) p.text([x0, y1], opts.label, { size: 8.5, color: '#5d6470', dx: 3, dy: 8 }); return corners; }
  HR.App.chartGround = chartGround; HR.App.CLASS_TINT = CLASS_TINT;
  // ---------- scene: receivers ----------
  SCENES.receivers = {
    title: 'Receivers · monitor → window → element',
    doc: () => ({ schema: HR.Codec.SCHEMA, scene: 'receivers', generators: { object: { use: 'lattice.Z3', params: { g: 1, offset: ['0', '0', '3'] } }, chart: { use: 'chart.split3+1', params: { shown: [0, 1, 2], folded: 3, fold: ['0', '0', '0'], law: { kind: 'perspective', distance: '2' } } }, tree: { use: 'receiver.tree', params: { elements: ['header', '#tabs', '.sheet', '#doc', '#receipts'], probe: ['1', '1', '3'], marksAcross: 14 } } },
      mounts: [{ object: 'object', receiver: '.sheet', chart: 'chart' }], motion: { beta: '3/5', axis: 0 }, relations: { declared: { from: '#doc', to: '.sheet', map: null } }, gauge: { frame: '1/3' }, colour: { aperture: '1/2' } }),
    init(doc) { state.inst = HR.Codec.instantiate(doc); },
    render(doc) {
      const dpr = window.devicePixelRatio || 1, sw = screen.width, sh = screen.height, iw = innerWidth, ih = innerHeight; const aL = screen.availLeft || 0, aT = screen.availTop || 0; const ox = window.screenX - aL + (outerWidth - iw) / 2, oy = window.screenY - aT + (outerHeight - ih);
      const dev = new HR.Receiver('device', { w: Math.round(sw * dpr), h: Math.round(sh * dpr) }, null, null, { source: 'screen × devicePixelRatio' });
      const css = new HR.Receiver('monitor', { w: sw, h: sh }, A2.scale(dpr), dev, { source: 'window.screen' }); const vp = new HR.Receiver('viewport', { w: iw, h: ih }, A2.translate(ox, oy), css, { source: 'screenX/Y + chrome (testimony)' });
      const de = document.documentElement; const page = new HR.Receiver('page', { w: de.scrollWidth, h: de.scrollHeight }, A2.translate(-window.scrollX, -window.scrollY), vp, { source: 'scroll' });
      const T = doc.generators.tree.params; const els = T.elements.map((sel) => { const e = document.querySelector(sel); const r = e.getBoundingClientRect(); return new HR.Receiver(sel, { w: r.width, h: r.height }, A2.translate(r.left + window.scrollX, r.top + window.scrollY), page, { source: 'getBoundingClientRect + scroll (exact dyadic)' }); });
      const sheetR = els.find((e) => e.name === '.sheet'), docR = els.find((e) => e.name === '#doc');
      const W = sheetR.grain.w.toNumber(), H = sheetR.grain.h.toNumber(); const s = Math.floor(Math.min((W - 60) / sw, (H - 60) / sh) * 256) / 256; const ORG = [30, Math.floor((H - sh * s) / 2)]; const p = paperFor(s, ORG); p.clear();
      const paperR = new HR.Receiver('paper', { w: sw, h: sh }, new A2([[s, 0], [0, -s]], [ORG[0], H - ORG[1]]), sheetR, { source: 'Paper.px' });
      // the mounted object through its chart; motion: the object moves at a Pythagorean β along an axis relative to the sheet, so its rest lengths along that axis are contracted by γ⁻¹ — a dilating factor, exact
      const L = state.inst.object.value, C = state.inst.chart.value; const beta = R(doc.motion ? doc.motion.beta : 0), axis = doc.motion ? doc.motion.axis : 0; const gam = HR.Relativity.gamma(beta); if (gam === null) throw new Error('β is not Pythagorean');
      const rest = (c) => c.map((v, i) => (i === axis ? v.div(gam) : v)); const pts = L.V.map((v) => C.project(rest(v.coords)));
      let mnx = null, mxx = null, mny = null, mxy = null; for (const q of pts) { mnx = mnx === null ? q.xy[0] : Rat.min(mnx, q.xy[0]); mxx = mxx === null ? q.xy[0] : Rat.max(mxx, q.xy[0]); mny = mny === null ? q.xy[1] : Rat.min(mny, q.xy[1]); mxy = mxy === null ? q.xy[1] : Rat.max(mxy, q.xy[1]); }
      const toPaper = (r, c) => { const q = r.to(css).apply(c); return [q[0], R(sh).sub(q[1])]; }; const sheetCorners = sheetR.corners().map((c) => toPaper(sheetR, c)); const sx = sheetCorners.map((c) => c[0]), sy = sheetCorners.map((c) => c[1]);
      const cx = sx.reduce((a, b) => a.add(b)).div(4), cy = sy.reduce((a, b) => a.add(b)).div(4); const span = Rat.max(mxx.sub(mnx), mxy.sub(mny)); const kRaw = Rat.min(sx.reduce((a, b) => Rat.max(a, b)).sub(sx.reduce((a, b) => Rat.min(a, b))), sy.reduce((a, b) => Rat.max(a, b)).sub(sy.reduce((a, b) => Rat.min(a, b)))).mul(R('3/5')).div(span); const k = R(kRaw.mul(64).floor()).div(64).isZero() ? R('1/64') : R(kRaw.mul(64).floor()).div(64);
      const mount = A2.translate(cx.sub(mnx.add(mxx).div(2).mul(k)), cy.sub(mny.add(mxy).div(2).mul(k))).compose(A2.scale(k));
      const modelR = new HR.Receiver('model', { w: span.floor() + 1n, h: span.floor() + 1n }, mount.compose(A2.translate(mnx, mny)), paperR, { source: 'mount' });
      const all = [css, vp, page, ...els, modelR]; const at = HR.Receivers.atlas(all);
      const drawR = (r, i) => { const corners = r.corners().map((c) => toPaper(r, c)); const stride = Math.max(1, Math.ceil(r.grain.w.toNumber() / T.marksAcross)); const marks = []; for (let c = 0; c <= r.grain.w.toNumber(); c += stride) for (let row = 0; row <= r.grain.h.toNumber(); row += stride) marks.push(toPaper(r, [c, row])); drawGround(p, corners, at.classes[i], marks); p.text(corners[3], `${r.name} ${rs(r.grain.w)}×${rs(r.grain.h)}`, { size: 8.5, color: '#5d6470', dx: 3, dy: 8 }); };
      all.forEach((r, i) => { if (r !== modelR) drawR(r, i); });
      const toMap = (xy) => modelR.to(paperR).apply([xy[0].sub(mnx), xy[1].sub(mny)]);
      const segs = L.E.map((e) => ({ a: pts[e.from].xy, b: pts[e.to].xy, depthA: pts[e.from].depth, depthB: pts[e.to].depth, source: { edge: e.id } })); const map = HR.PlanarMap.build(segs);
      for (const e of L.E) p.line([toMap(pts[e.from].xy), toMap(pts[e.to].xy)], { width: 1, role: 'edge' }); for (const c of map.crossings) if (c.over !== null) p.ring(toMap(c.point), 2, '#8a4b6a');
      // THE DIFFERENTIAL OF THE CHART, RENDERED: at every site the images J·e_x, J·e_y, J·e_z of the lattice's unit directions (exact rationals
      // for the perspective law: J e_x = (f/(f+z), 0), J e_y = (0, f/(f+z)), J e_z = (−f x/(f+z)², −f y/(f+z)²)), scaled by the declared frame gauge.
      const frame = R(doc.gauge ? doc.gauge.frame : '1/3'); const law = C.law;
      for (const v of L.V) { const c = rest(v.coords); const p3 = C.to3(c); const [x, y, z] = p3; let J;
        if (law.kind === 'perspective') { const f = R(law.distance); const den = f.add(z); if (den.sign() <= 0) continue; const q = f.div(den); J = [[q, Rat.ZERO], [Rat.ZERO, q], [f.mul(x).neg().div(den.mul(den)), f.mul(y).neg().div(den.mul(den))]]; }
        else J = [[Rat.ONE, Rat.ZERO], [Rat.ZERO, Rat.ONE], [R(law.a), R(law.b)]];
        const base = toMap(pts[v.id].xy); const cols = ['#1d3f6e', '#2f6f4e', '#8a4b6a'];
        J.forEach((d, i) => { const dd = d.map((q) => q.mul(frame).mul(i === axis ? Rat.ONE.div(gam) : Rat.ONE)); const tip = toMap([pts[v.id].xy[0].add(dd[0]), pts[v.id].xy[1].add(dd[1])]); p.line([base, tip], { width: 1, color: cols[i], role: 'jacobian-' + 'xyz'[i], source: `J e_${'xyz'[i]} = (${d[0]}, ${d[1]}) at (${c.join(',')})` }); });
        p.dot(base, 1.2); }
      const probe = T.probe.map(R); const pq = C.project(rest(probe)); const pm = toMap(pq.xy); p.ring(pm, 4, '#8a4b6a');
      const chain = [['model (chart)', pq.xy], ['paper', pm]]; let cur = pm; for (const r of [paperR, sheetR, page, vp, css]) { cur = r.toParent.apply(cur); chain.push([r.parent.name, cur]); }
      const cells = dev.address(cur); const seam = cells.length > 1;
      const measured = docR.to(sheetR); const decl = doc.relations && doc.relations.declared && doc.relations.declared.map ? new A2(doc.relations.declared.map.m, doc.relations.declared.map.t) : null;
      const cycle = HR.Receivers.cycleDeficit([sheetR.toParent, docR.toParent.inverse(), decl || measured]); const cycleId = HR.Receivers.cycleDeficit([sheetR.toParent, docR.toParent.inverse(), A2.identity()]);
      if (!cycle.flat) { const c0 = toPaper(docR, [0, 0]); const c1 = toPaper(docR, cycle.map.apply([0, 0])); p.line([c0, c1], { width: 1, color: '#8a4b6a', role: 'deficit' }); const hm = HR.Glyphs.handMark(c0, c1, 1, R(6 / p.unit)); if (hm) p.line(hm, { width: 1, color: '#8a4b6a', role: 'hand' }); }
      const G = paperR.toRoot().gram(); const PG = HR.Receivers.pullbackGram(C.law, C.to3(rest(probe)));
      // DILATED EXPRESSIONS: a rest length ℓ₀ along the axis of motion, as seen on the device, is ℓ₀ × named exact factors
      const z = C.to3(rest(probe))[2]; const persp = law.kind === 'perspective' ? R(law.distance).div(R(law.distance).add(z)) : Rat.ONE; const factors = [['γ⁻¹ (contraction, β = ' + rs(beta) + ')', Rat.ONE.div(gam)], [law.kind === 'perspective' ? 'f/(f+z) at the probe' : 'oblique (no dilation)', persp], ['k (mount)', k], ['s (map)', R(s)], ['DPR', R(dpr)]]; const product = factors.reduce((acc, [, v]) => acc.mul(v), Rat.ONE);
      const inMon = ox >= 0 && oy >= 0 && ox + iw <= sw && oy + ih <= sh;
      setReceipts([['device', `${rs(dev.grain.w)}×${rs(dev.grain.h)} cells = screen ${sw}×${sh} css px × DPR ${dpr} (exact dyadic)`], ['viewport', `${iw}×${ih} at (${rs(vp.toParent.t[0])}, ${rs(vp.toParent.t[1])}) in the monitor — screenX/Y − availLeft/Top plus the window chrome: testimony${inMon ? '' : '; the platform places this window outside its own screen, so the map is drawn as declared'}`, inMon ? 'ok' : 'warn'],
        ['page', `${rs(page.grain.w)}×${rs(page.grain.h)} scrolled to (${window.scrollX}, ${window.scrollY}) in the viewport`], ...els.map((r) => [r.name, `${rs(r.grain.w)}×${rs(r.grain.h)} at (${rs(r.toParent.t[0])}, ${rs(r.toParent.t[1])}) in the page`]),
        ['charts', `${all.length} receivers · ${at.edges} adjacencies · ${at.chromatic} class${at.chromatic > 1 ? 'es' : ''}${at.exact ? '' : ' (greedy)'} — tint + cell-mark direction per class; adjacent charts never share a class`, at.chromatic <= 4 ? 'ok' : 'bad'],
        ['mount', `ℤ³ [−${L.g},${L.g}]³ at offset (${doc.generators.object.params.offset.join(', ')}) through ${law.kind}${law.kind === 'perspective' ? ' f = ' + law.distance : ''}, moving at β = ${rs(beta)} along ${'xyz'[axis]} (γ = ${rs(gam)}), mounted by ${mount.toString()}`],
        ['differential', `at every site the chart's Jacobian applied to the lattice's unit directions — J e_x (blue), J e_y (green), J e_z (plum) — scaled by the frame gauge ${rs(frame)}; ${law.kind === 'perspective' ? 'they shrink with z and tilt with (x, y): the curvature of the image between receiver and object, rendered from the chart\'s own differential' : 'constant: an oblique chart has no curvature'}`],
        ['dilated expression', `ℓ_device = ℓ₀ · ${factors.map(([, v]) => `[${rs(v)}]`).join(' · ')} = ℓ₀ · ${rs(product)} — ${factors.map(([n, v]) => n + ' = ' + rs(v)).join('; ')}`],
        ['probe (' + T.probe.join(', ') + ')', chain.map(([n, q]) => `${n}: (${rs(q[0])}, ${rs(q[1])})`).join(' → ')], ['device address', `${cells.map((c) => c.join(':')).join(' ')}${seam ? ' — on a seam: ' + cells.length + ' cells, none chosen by array convention' : ''}`, seam ? 'warn' : 'ok'],
        ['metric', `paper→device Gram MᵀM = [[${rs(G[0][0])}, ${rs(G[0][1])}], [${rs(G[1][0])}, ${rs(G[1][1])}]] · hand ${paperR.toRoot().hand()} · chart pullback JᵀJ at the probe: diag (${PG ? PG.map((r, i) => rs(r[i])).join(', ') : 'open'})`],
        ['holonomy', `sheet → viewport → #doc → sheet: ${decl ? 'declared relation' : 'measured relation'} ⇒ ${cycle.flat ? 'flat, deficit 0' : 'deficit ' + rs(cycle.deficit.t[0]) + ', ' + rs(cycle.deficit.t[1])} · declaring identity instead ⇒ deficit (${rs(cycleId.deficit.t[0])}, ${rs(cycleId.deficit.t[1])}) — a layout's curvature is what a cycle of its relations fails to close by`, cycle.flat ? 'ok' : 'warn'],
        ['planar map', `${map.nodes.length} nodes · ${map.edges.length} edges · ${map.faces.length} faces · Euler ${map.nodes.length - map.edges.length + map.faces.length}`, map.nodes.length - map.edges.length + map.faces.length === 2 ? 'ok' : 'warn'], ['exact', 'grains, relations, addresses, Jacobian frames, Gram, deficit, dilation factors, crossings: ℚ (browser floats admitted as exact dyadics)'], gaugeReceipt(p)]);
    },
  };
  // ---------- scene: Minkowski ----------
  SCENES.minkowski = {
    title: 'Minkowski · two objects, one receiver',
    doc: () => ({ schema: HR.Codec.SCHEMA, scene: 'minkowski', generators: { chart: { use: 'chart.minkowski', params: { window: { t0: '-2', t1: '6', x0: '-4', x1: '4' }, receiver: ['5', '0'], beta: '3/5', objects: [{ name: 'A', at: ['0', '0'], u: '0' }, { name: 'B', at: ['0', '1'], u: '3/5' }], hyperbolae: ['1', '2'], grid: 32, bisections: 6, properStep: '1' } } }, units: { c: '1 cell per tick' }, gauge: { tick: '1/6' } }),
    init(doc) { state.inst = HR.Codec.instantiate(doc); },
    render(doc) {
      const M = state.inst.chart.value; const win = doc.generators.chart.params.window; const [t0, t1, x0, x1] = [win.t0, win.t1, win.x0, win.x1].map((v) => R(v).toNumber());
      const cv = $('#canvas'); const W = cv.parentElement.clientWidth, H = cv.parentElement.clientHeight; const unit = Math.floor(Math.min((W - 80) / (x1 - x0), (H - 70) / (t1 - t0))); const p = paperFor(unit, [40 - x0 * unit, Math.floor((H - (t1 - t0) * unit) / 2) - t0 * unit]); p.clear();
      const P = (e) => [e[1], e[0]]; // paper: x horizontal, t vertical
      chartGround(p, { x0, x1, y0: t0, y1: t1 }, { cls: 1, step: 1, label: 'Minkowski receiver · x cells, t ticks' });
      for (const c of M.contours) for (const s of c.iso.segs) p.line([P(s.a), P(s.b)], { width: 1, role: 'contour', alpha: 0.9, source: `x²−t²=${c.level} iso t∈[${s.ta.join(',')}]→[${s.tb.join(',')}]` }); for (const c of M.contours) for (const st of c.iso.stations) p.dot(P(st), 1.6);
      const style = { worldline: { color: null }, 'cone-past': { color: '#8a4b6a' }, 'cone-future': { color: '#8a4b6a', dash: [2, 3] }, 'axis-t': { color: '#6a717b' }, 'axis-x': { color: '#6a717b' }, 'axis-t-prime': { color: '#1d3f6e' }, 'axis-x-prime': { color: '#1d3f6e' }, 'simultaneity-prime': { color: '#1d3f6e', dash: [1, 3] } };
      for (const l of M.lines) { const st = style[l.role] || {}; p.line([P(l.a), P(l.b)], { width: 1, color: st.color || undefined, dash: st.dash, role: l.role }); if (l.role === 'worldline') p.text(P(l.b), l.name, { size: 9, color: '#5d6470', dx: 4, dy: -2 }); }
      // proper-time ticks: each object's own axis of time crosses the receiver's; a tick every unit of τ is a tick every γ of t
      const tk = R(doc.gauge.tick); [M.A, M.B].forEach((w, i) => { const t = M.ticks[i]; for (const q of t.ticks) { const e = q.event; const n = [tk.mul(w.u), tk]; p.line([P([e[0].sub(n[0].div(2)), e[1].sub(n[1].div(2))]), P([e[0].add(n[0].div(2)), e[1].add(n[1].div(2))])], { width: 1, role: 'proper-tick', source: `${w.name} τ=${rs(q.tau)} at t=${rs(e[0])}` }); if (q.tau.eq(R(1))) p.text(P(e), `τ${w.name} = 1`, { size: 8, color: '#5d6470', dx: 6, dy: 0 }); } });
      p.ring(P(M.E), 4, '#8a4b6a'); p.ring(P(M.E), 1.5, '#8a4b6a'); for (const list of M.retarded) for (const r of list) { p.dot(P(r.event), 2.5, '#8a4b6a'); p.ring(P(r.event), 4, '#8a4b6a'); }
      if (M.boost) { p.dot(P(M.boost.unitT), 2.5, '#1d3f6e'); p.dot(P(M.boost.unitX), 2.5, '#1d3f6e'); p.text(P(M.boost.unitT), '1′ (t)', { size: 8.5, color: '#1d3f6e', dx: 5, dy: -4 }); p.text(P(M.boost.unitX), '1′ (x)', { size: 8.5, color: '#1d3f6e', dx: 5, dy: 6 }); }
      const stations = M.contours.reduce((s, c) => s + c.iso.stations.length, 0); const segs = M.contours.reduce((s, c) => s + c.iso.segs.length, 0); const wx = M.contours[0].iso.width; const rel = M.relation;
      setReceipts([['chart', `x ∈ [${win.x0}, ${win.x1}] cells, t ∈ [${win.t0}, ${win.t1}] ticks, c = 1 cell/tick — a chart of the relation between the two objects, not a property of either`], ['objects', `A: x = ${rs(M.A.at[1])} + ${rs(M.A.u)}·t · B: x = ${rs(M.B.at[1])} + ${rs(M.B.u)}·(t − ${rs(M.B.at[0])})`],
        ['dilated expressions', `relative speed u = (u_B − u_A)/(1 − u_A u_B) = ${rs(rel.u)} ⇒ γ = ${rel.gamma ? rs(rel.gamma) : 'not rational'}, D = √((1−u)/(1+u)) = ${rel.doppler ? rs(rel.doppler) : 'not rational'}: Δt = [${rel.gamma ? rs(rel.gamma) : 'γ'}]·Δτ, ℓ = [${rel.gamma ? rs(Rat.ONE.div(rel.gamma)) : 'γ⁻¹'}]·ℓ₀, ν_received = [${rel.doppler ? rs(rel.doppler) : 'D'}]·ν_emitted — every factor exact for a Pythagorean speed`, rel.gamma ? 'ok' : 'warn'],
        ['proper time', `ticks every ${doc.generators.chart.params.properStep || 1} of τ on each worldline: t = t₀ + γ·τ; A ${M.ticks[0].ticks.length} ticks (γ = ${rs(M.A.gamma)}), B ${M.ticks[1].ticks.length} ticks (γ = ${rs(M.B.gamma)}) — two axes of time crossing in one chart`],
        ['interval A₀B₀', `s² = Δt² − Δx² = ${rs(M.interval.s2)} → ${M.interval.kind}`], ['receiver event', `E = (t ${rs(M.E[0])}, x ${rs(M.E[1])}); past cone solid, future dotted — three regions, the null boundary returns exactly zero`],
        ...M.retarded.map((list, i) => [`retarded ${i ? 'B' : 'A'}`, list.map((r) => `(t ${rs(r.event[0])}, x ${rs(r.event[1])}) on the ${r.leg > 0 ? 'right' : 'left'} leg, s² = ${rs(r.check.s2)} (${r.check.kind})`).join(' · ') || 'none in the past (the receiver sits on this worldline)', 'ok']),
        ['boost', M.boost ? `β = ${rs(M.boost.beta)} ⇒ γ = ${rs(M.boost.gamma)}, D = ${rs(M.boost.doppler)}; primed axes x = βt, t = βx; unit points (${rs(M.boost.unitT[0])}, ${rs(M.boost.unitT[1])}) and (${rs(M.boost.unitX[0])}, ${rs(M.boost.unitX[1])}); γ²(1 − β²) = ${rs(M.boost.calibration)}` : 'β is not Pythagorean: refused', M.boost ? 'ok' : 'bad'],
        ['calibration', `hyperbolae x² − t² = ${M.levels.map(rs).join(', ')} as ${segs} isolated brackets (interval width ${rs(wx.x)} × ${rs(wx.y)} after ${doc.generators.chart.params.bisections} bisections) with ${stations} exact stations`],
        ['colour', 'no current is present in this chart; nothing is chromatic (the tint is the chart class)'], ['exact', 'events, legs, retarded events, boost, unit points, proper ticks, dilation factors, isolating intervals: ℚ'], gaugeReceipt(p)]);
    },
  };
  // ---------- scene: circuit (one object, two receivers) ----------
  SCENES.circuit = {
    title: 'Circuit · electrical atlas of ℤ³',
    doc: () => ({ schema: HR.Codec.SCHEMA, scene: 'circuit', generators: { circuit: { use: 'circuit.lattice', params: { g: 3, admittance: { x: '1', y: '1/2', z: { re: '0', im: '1/3' } }, sources: [{ node: [0, 0, 0], current: { re: '1', im: '0' } }, { node: [2, 2, 2], current: { re: '-1', im: '0' } }], ground: [2, 2, 2] } }, chart: { use: 'chart.split3+1', params: { shown: [0, 1, 2], folded: 3, fold: ['0', '0', '0'], law: { kind: 'oblique', a: '2/5', b: '2/7' } } } },
      mounts: [{ object: 'circuit', receiver: 'geometry', chart: 'chart' }, { object: 'circuit', receiver: 'schematic', chart: 'chart' }], gauge: { stroke: { unit: '1/4', gap: '1/6' } }, colour: { aperture: '1/2' } }),
    init(doc) { state.inst = HR.Codec.instantiate(doc); },
    render(doc) {
      const circ = state.inst.circuit.value, C = state.inst.chart.value; const t0 = performance.now();
      const plan = HR.Circuit.schematicPlan(circ, C, { unit: doc.gauge.stroke.unit, gap: doc.gauge.stroke.gap, aperture: doc.colour.aperture });
      let mnx = null, mxx = null, mny = null, mxy = null; for (const n of plan.nodes) { const q = n.p; mnx = mnx === null ? q[0] : Rat.min(mnx, q[0]); mxx = mxx === null ? q[0] : Rat.max(mxx, q[0]); mny = mny === null ? q[1] : Rat.min(mny, q[1]); mxy = mxy === null ? q[1] : Rat.max(mxy, q[1]); }
      const q4 = R('1/4'); const bx0 = mnx.sub(q4), bx1 = mxx.add(q4), by0 = mny.sub(q4), by1 = mxy.add(q4); const bw = bx1.sub(bx0).toNumber(), bh = by1.sub(by0).toNumber(); const cv = $('#canvas'); const W = cv.parentElement.clientWidth, H = cv.parentElement.clientHeight; const unit = Math.floor(Math.min((W / 2 - 70) / bw, (H - 90) / bh)); const p = paperFor(unit, [0, 0]); p.clear();
      const sheet = new HR.Receiver('sheet', { w: W, h: H }); const halves = [{ name: 'geometry', ox: 35 - bx0.toNumber() * unit }, { name: 'schematic', ox: W / 2 + 35 - bx0.toNumber() * unit }]; const oy = Math.floor((H - bh * unit) / 2) - by0.toNumber() * unit;
      const recs = halves.map((h) => new HR.Receiver(h.name, { w: bw * unit, h: bh * unit }, A2.translate(h.ox + bx0.toNumber() * unit, H - oy - by1.toNumber() * unit), sheet)); const at = HR.Receivers.atlas([sheet, ...recs]);
      halves.forEach((h, i) => { p.origin = [h.ox, oy]; chartGround(p, { x0: bx0, x1: bx1, y0: by0, y1: by1 }, { cls: at.classes[i + 1], step: 1, label: h.name + ' receiver' });
        if (i === 0) { for (const e of plan.edges) p.line([e.a, e.b], { width: 1, role: 'edge' }); for (const n of plan.nodes) p.dot(n.p, 1.5); for (const c of plan.map.crossings) if (c.over !== null) p.ring(c.point, 2.5, '#8a4b6a'); }
        else { for (const e of plan.edges) { for (const piece of e.pieces) p.line(piece, { width: e.width, color: HR.Colour.css(HR.Colour.toRGB(e.response, INK)), role: 'transport' }); const [s, t] = e.hand >= 0 ? [e.a, e.b] : [e.b, e.a]; const hm = HR.Glyphs.handMark(s, t, 1, R('1/8')); if (hm) p.line(hm, { width: 1, role: 'hand' }); }
          for (const n of plan.nodes) { if (n.pump) drawGlyph(p, HR.Glyphs.place('pump', n.p, 'r0', '1/2'), { unit: R(doc.gauge.stroke.unit), q: rs(circ.J[n.node.id].abs2()) }); else if (n.ground) drawGlyph(p, HR.Glyphs.place('exterior', n.p, 'r270', '1/2'), {}); else p.dot(n.p, 2.5, HR.Colour.css(HR.Colour.toRGB(n.response, INK))); } } });
      const pg = HR.Polygraphs.fromLattice3(circ.g); const pm = HR.Polygraphs.fromPlanarMap(plan.map); const maxDeg = Math.max(...circ.incidence.map((l) => l.length)); const ms = performance.now() - t0;
      const Ptot = circ.power; const widths = plan.edges.map((e) => e.width); const wmax = Math.max(...widths);
      setReceipts([['object', `ℤ³ [0,${circ.g})³ · ${circ.nodes.length} nodes · ${circ.edges.length} edges · admittance x ${doc.generators.circuit.params.admittance.x}, y ${doc.generators.circuit.params.admittance.y}, z ${rs(circ.edges.find((e) => e.direction === 2).y)} (reactive)`], ['polygraph', `Σ = ${pg.polygraph.counts().join(' / ')} (nodes / edges / commuting squares / cubes) · Σ(−1)ᵏ|Σₖ| = ${pg.polygraph.euler()} · ${pg.polygraph.obstructions.length} globular obstructions`, pg.polygraph.obstructions.length ? 'bad' : 'ok'],
        ['solve', `G = BᵀMB over ℚ(i), ${circ.unknowns} unknowns, Gauss–Jordan with BigInt in ${circ.solveMs} ms`], ['KCL', `outflow − inflow − injection at every node: worst |r|² = ${rs(circ.kclWorst)} (exact zero)`, circ.kclWorst.isZero() ? 'ok' : 'bad'], ['complex power', `Σ conj(I)(φ_from − φ_to) = ${Ptot.re.toNumber().toFixed(4)} + ${Ptot.im.toNumber().toFixed(4)}i (float face of an exact ℚ(i) value)`],
        ['nets', `stored as node × edge incidence (max degree ${maxDeg}: a hyperedge); the vertex–vertex matrix A = MMᵀ − diag(MMᵀ) is never the store — it forgets which terminals share a net`], ['two receivers', 'the same object read twice: the geometry receiver keeps the lattice as edges with crossings ringed; the schematic receiver keeps currents as symbols'],
        ['crossings', `${plan.crossings} over/under by exact depth, the under strand cut ±${doc.gauge.stroke.gap} (parameter ≤ the declared gap, computed without a float) · ${plan.openCrossings} open · ${plan.discriminants.length} discriminants`, plan.openCrossings || plan.discriminants.length ? 'warn' : 'ok'], ['receiver planar map', `${plan.map.nodes.length} / ${plan.map.edges.length} / ${plan.map.faces.length} · Euler ${plan.map.nodes.length - plan.map.edges.length + plan.map.faces.length} · as a 2-polygraph: ${pm.polygraph.counts().slice(0, 3).join(' / ')}`],
        ['stroke law', `width = ⌈|I| / ${doc.gauge.stroke.unit}⌉ px via the integer ceiling of √(|I|²) — ${[...new Set(widths)].sort().join(', ')} px present, max ${wmax}`], ['hand law', 'tick on the + side at the end the real current flows to; sign(Im I) when Re I = 0; no arrowheads'], ['colour', `each edge: transduction of I = Re + i Im (κ = ${doc.colour.aperture}) composited over the ink, since the stroke is present whatever the current; each node: transduction of φ; no palette anywhere`],
        ['charts', `${at.chromatic} classes for the two receivers on one sheet (tint + cell-mark direction)`], ['exact', 'potentials, currents, KCL, incidence, projection, crossings, widths, responses: ℚ(i) and ℚ'], ['time', `${ms.toFixed(0)} ms`], gaugeReceipt(p)]);
    },
  };
  // ---------- scene: Bord components — isolated contours and intaglio hatching ----------
  SCENES.bord = {
    title: 'Bord · 2-cells with corners',
    doc: () => ({ schema: HR.Codec.SCHEMA, scene: 'bord', generators: { pants: { use: 'bord.cell', params: { kind: 'pants', slices: 28, grid: 36, bisections: 7 } }, saddle: { use: 'bord.cell', params: { kind: 'saddle', slices: 24, grid: 30, bisections: 7 } }, cylinder: { use: 'bord.cell', params: { kind: 'cylinder', slices: 20, grid: 26, bisections: 7 } }, cap: { use: 'bord.cell', params: { kind: 'cap', slices: 24, grid: 26, bisections: 7 } }, chart: { use: 'chart.split3+1', params: { shown: [0, 1, 2], folded: 3, fold: ['0', '0', '0'], law: { kind: 'oblique', a: '2/5', b: '2/7' } } } },
      intaglio: { stride: 3, sliceStride: 2, length: '1/8', tone: '1/6' }, notation: 'N : M ⇒ M′ with corners L = L′ (Leinster, math/0106240 p.8)' }),
    init(doc) { state.inst = HR.Codec.instantiate(doc); },
    render(doc) {
      const C = state.inst.chart.value; const names = ['pants', 'saddle', 'cylinder', 'cap']; const t0 = performance.now(); const I = doc.intaglio; const view = ['-' + doc.generators.chart.params.law.a, '-' + doc.generators.chart.params.law.b, '1'];
      const plans = names.map((n) => { const s = state.inst[n].value; const h = HR.Bord.hatches(s, { stride: I.stride, sliceStride: I.sliceStride, length: R(I.length).toNumber(), view, tone: I.tone }); const pr = HR.Bord.project(s, C, h); let mnx = null, mxx = null, mny = null, mxy = null; const acc = (q) => { mnx = mnx === null ? q[0] : Rat.min(mnx, q[0]); mxx = mxx === null ? q[0] : Rat.max(mxx, q[0]); mny = mny === null ? q[1] : Rat.min(mny, q[1]); mxy = mxy === null ? q[1] : Rat.max(mxy, q[1]); }; for (const r of pr.slab) for (const q of r) acc(q); return { name: n, s, h, pr, bbox: [mnx, mxx, mny, mxy] }; });
      const bw = Math.max(...plans.map((q) => q.bbox[1].sub(q.bbox[0]).toNumber())), bh = Math.max(...plans.map((q) => q.bbox[3].sub(q.bbox[2]).toNumber()));
      const cv = $('#canvas'); const W = cv.parentElement.clientWidth, H = cv.parentElement.clientHeight; const unit = Math.floor(Math.min((W / 4 - 30) / bw, (H - 110) / bh)); const p = paperFor(unit, [0, 0]); p.clear(); const oy = Math.floor((H - bh * unit) / 2) + 20;
      const sheet = new HR.Receiver('sheet', { w: W, h: H }); const recs = plans.map((q, i) => new HR.Receiver(q.name, { w: Math.ceil(bw * unit), h: Math.ceil(bh * unit) }, A2.translate(W / 4 * i + 20, H - oy - bh * unit), sheet)); const at = HR.Receivers.atlas([sheet, ...recs]);
      plans.forEach((q, i) => { p.origin = [W / 4 * i + 20 - q.bbox[0].toNumber() * unit + (W / 4 - 40 - q.bbox[1].sub(q.bbox[0]).toNumber() * unit) / 2, oy - q.bbox[2].toNumber() * unit];
        chartGround(p, { x0: q.bbox[0].sub(R('1/5')), x1: q.bbox[1].add(R('1/5')), y0: q.bbox[2].sub(R('4/5')), y1: q.bbox[3].add(R('1/5')) }, { cls: at.classes[i + 1], step: 1, label: q.name + ' receiver' });
        for (const r of q.pr.slab) p.line([...r, r[0]], { width: 1, dash: [3, 3], role: 'slab' });
        for (const s of q.pr.segs) p.line([s.a, s.b], { width: 1, role: s.role, color: s.role === 'corner' ? '#8a4b6a' : undefined, source: s.source });
        for (const hs of q.pr.hatch) p.line([hs.a, hs.b], { width: 1, role: 'hatch-' + hs.family, alpha: hs.family === 'cross' ? 0.7 : 0.9, source: hs.source });
        p.text([q.bbox[0], q.bbox[2].sub(R('3/10'))], `${q.name}: M = ${q.s.notation.M}, M′ = ${q.s.notation.Mprime}`, { size: 9, color: '#5d6470' }); p.text([q.bbox[0], q.bbox[2].sub(R('3/5'))], `${q.s.components.bottom} → ${q.s.components.top} boundary component${q.s.components.top === 1 ? '' : 's'} · K>0 ${q.h.elliptic} · K<0 ${q.h.hyperbolic} · K=0 ${q.h.parabolic}`, { size: 9, color: '#5d6470' }); });
      const ms = performance.now() - t0;
      setReceipts([['components', 'Leinster p.8: 0-cells are finite point sets, 1-cells are 1-manifolds with corners, 2-cells N : M ⇒ M′ are 2-manifolds with corners in a slab whose top and bottom carry M′ and M and whose side walls carry L = L′'],
        ...plans.map((q) => [q.name, `g = ${q.s.poly.toString()} on ${q.s.box.x.join('…')} × ${q.s.box.y.join('…')} × ${q.s.box.z.join('…')} · ${q.s.horizontal.length} slices · ${q.pr.segs.length} isolated brackets (${q.s.evaluations} exact evaluations, ${q.s.ambiguous} saddle cells decided by the centre sign) · ${q.pr.hatch.length} hatch strokes · bottom ${q.s.components.bottom} → top ${q.s.components.top}`]),
        ['isolation', `every contour vertex is the midpoint of an isolating interval of width h/2^${doc.generators.pants.params.bisections} on a grid edge (certified_face.rs count == 1 → isolate; presentation_gauge.rs: the midpoint is a chart convenience, the interval travels with the mark) — the picture is continuous because the witnesses are dense, not because anything was interpolated`],
        ['intaglio', `at every ${I.stride}rd contour station of every ${I.sliceStride}nd slice: n = ∇g, H = Hess g, tangent basis (n×e, n×(n×e)), A = I⁻¹II, principal directions in ℚ(√Δ), Δ = tr² − 4det per station; the stroke follows the direction more transverse to the slices (length ${I.length}); cross-hatch admitted where (n·v)² ≤ ${I.tone}·(n·n)(v·v) for the chart's viewing direction v = (${view.join(', ')}) — tone is an exact predicate`],
        ['curvature', plans.map((q) => `${q.name}: K>0 ${q.h.elliptic}, K<0 ${q.h.hyperbolic}, K=0 ${q.h.parabolic}, cross-hatched ${q.h.crossed}, singular ${q.h.singular}`).join(' · ') + ' — sign of det II, exact'],
        ['orientation', 'hands only; Leinster\'s arrowheads are not reproduced — the 1-cells of the symbol sheet (cup, cap, circle) carry the hand'], ['chart', `oblique a = ${doc.generators.chart.params.law.a}, b = ${doc.generators.chart.params.law.b}; slab planes dashed as the chart's own faces; ${at.chromatic} classes for the four receivers`], ['exact', 'polynomial values, gradients, Hessians, signs, isolating intervals, principal directions (ℚ(√Δ)), projection: ℚ · float face: the drawn endpoints of hatch strokes'], ['time', `${ms.toFixed(0)} ms`], gaugeReceipt(p)]);
    },
  };
})(HR);
