const HR = require('./core.js'); require('./colour.js'); require('./quadfield.js'); require('./poly.js'); require('./fields.js'); require('./models.js'); require('./brackets.js'); require('./hatch.js'); require('./bord.js'); require('./minkowski.js');
const { R, Rat, Poly3 } = HR; const t0 = Date.now();
// poly: g = x² + y² − 1; grad at (3/5,4/5) = (6/5, 8/5); hessian diag 2
const g = Poly3.x().sq().add(Poly3.y().sq()).sub(1); console.log('poly', g.toString(), 'eval(3/5,4/5)=', g.eval('3/5', '4/5').toString(), 'grad', g.grad().map((d) => d.eval('3/5', '4/5', 0).toString()).join(','), 'H00', g.hessian()[0][0].toString());
// isolate: circle x²+y²=1 on [-2,2]² grid 16, 6 bisections
let t = Date.now(); const iso = HR.Brackets.isolate((x, y) => g.eval(x, y, 0), { x0: -2, x1: 2, y0: -2, y1: 2 }, 16, 0, 6); console.log('isolate circle segs', iso.segs.length, 'vertices', iso.vertices, 'ambiguous', iso.ambiguous, 'evals', iso.evaluations, 'width', iso.width.x.toString(), 'ms', Date.now() - t, 'components', HR.Brackets.components(iso.segs));
// every vertex's isolating interval contains a sign change: check residual |g| at midpoint small
let worst = 0; for (const s of iso.segs) for (const p of [s.a, s.b]) worst = Math.max(worst, Math.abs(g.eval(p[0], p[1], 0).toNumber())); console.log('max |g| at contour vertices', worst.toExponential(2));
// saddle ambiguity: f = x·y on [-1,1]², grid 2 → the centre cell has all four crossings
const sad = HR.Brackets.isolate((x, y) => x.mul(y), { x0: -1, x1: 1, y0: -1, y1: 1 }, 2, 0, 4); console.log('saddle ambiguous cells', sad.ambiguous, 'segs', sad.segs.length, 'stations', sad.stations.length);
// hatch: sphere x²+y²+z²−1 at (3/5, 0, 4/5): K > 0; saddle z = x² − y² at (1/2,1/3,·): K < 0
const sph = Poly3.x().sq().add(Poly3.y().sq()).add(Poly3.z().sq()).sub(1); const st = HR.Hatch.station(sph, ['3/5', '0', '4/5'], { view: ['-2/5', '-2/7', '1'], tone: '1/4' }); console.log('sphere station gauss', st.gaussSign, 'delta', st.delta.toString(), 'umbilic', st.umbilic, 'grazing', st.grazing, 'dir0', st.dirs[0].map(String).join(' | '));
const sadS = Poly3.x().sq().sub(Poly3.y().sq()).sub(Poly3.z()); const st2 = HR.Hatch.station(sadS, ['1/2', '1/3', R('1/4').sub(R('1/9')).toString()], { view: ['-2/5', '-2/7', '1'] }); console.log('saddle station gauss', st2.gaussSign, 'delta', st2.delta.toString(), 'dirs', st2.dirs.map((d) => d.map((q) => q.toNumber().toFixed(3)).join(',')).join(' ; '), 'transverse', HR.Hatch.transverse(st2).map((q) => q.toNumber().toFixed(3)).join(','));
// bord: slices with isolation + hatches, timing
for (const [k, n, m] of [['pants', 40, 24], ['saddle', 32, 24], ['cylinder', 28, 16], ['cap', 28, 20]]) { t = Date.now(); const s = HR.Bord.slices(k, { slices: m, grid: n, bisections: 7 }); const h = HR.Bord.hatches(s, { stride: 3, sliceStride: 2 }); const chart = HR.Models.Chart({ shown: [0, 1, 2], folded: 3, fold: ['0', '0', '0'], law: { kind: 'oblique', a: '2/5', b: '2/7' } }); const pr = HR.Bord.project(s, chart, h); console.log(k, 'ms', Date.now() - t, 'bottom', s.components.bottom, 'top', s.components.top, 'segs', pr.segs.length, 'hatch', pr.hatch.length, 'evals', s.evaluations, 'ambiguous', s.ambiguous, 'singular', h.singular, 'K+/K-/K0', h.elliptic, h.hyperbolic, h.parabolic, 'crossed', h.crossed); }
// minkowski with isolated hyperbolae, proper ticks, relation
t = Date.now(); const mp = HR.Minkowski.plan({ window: { t0: -2, t1: 6, x0: -4, x1: 4 }, receiver: [5, 0], beta: '3/5', objects: [{ at: [0, 0], u: '0', name: 'A' }, { at: [0, 1], u: '3/5', name: 'B' }], hyperbolae: ['1', '2'], grid: 32, bisections: 6 });
console.log('mink ms', Date.now() - t, 'contours', mp.contours.map((c) => c.level + ':' + c.iso.segs.length).join(' '), 'doppler boost', mp.boost.doppler.toString(), 'ticks A/B', mp.ticks.map((tk) => tk.ticks.length).join('/'), 'B γ', mp.B.gamma.toString(), 'relation u,γ,D', [mp.relation.u, mp.relation.gamma, mp.relation.doppler].map(String).join(' '));
// NS dissipation
const f = new HR.NavierStokes(32, { nu: 0.001, dt: 0.5 }); f.seedVortices([{ x: 10, y: 16, gamma: 1, r: 3 }, { x: 22, y: 16, gamma: -1, r: 3 }]); const d0 = f.dissipation(); const z0 = f.receipts().enstrophy; f.step(); const z1 = f.receipts().enstrophy; console.log('NS dissipation total', d0.total.toExponential(3), 'dZ/dt', ((z1 - z0) / f.dt).toExponential(3), '(−2·ε expected sign)');
console.log('total ms', Date.now() - t0);
