//! Run with `cargo run -p holonics --example helical_duplex`.
//!
//! This is a known-truth calibration of the accepted helical duplex consumer. The passage is
//! generated by a fixed `SteppedTerrain`; the key, transport and truth are supplied to the
//! demonstration harness. Nothing here locates a learned key or claims learned repair.
//!
//! The `(3, 4)` helix, advances, labels and pairing reuse the exact hand-crafted carry regression
//! in `compression::keys::duplex::tests::the_supports_keep_the_carry_and_the_class_reads_the_winding`.
//! This small calibration displays that regression's carried ambiguity; it is not one of the
//! scanned acceptance charts.

use holonics::compression::keys::duplex::{
    Absorption, Damage, Decoded, Decoder, Duplex, Fit, Member, Pairing, Receiver, ReceiverClass,
    Template, carried_shift,
};
use holonics::compression::keys::transport::{CarryHelix, LocatedTransport, SteppedTerrain};

fn class_text(class: &ReceiverClass) -> String {
    let readings = class
        .readings()
        .iter()
        .map(|reading| {
            reading
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ")
        })
        .map(|reading| format!("[{reading}]"))
        .collect::<Vec<_>>()
        .join("; ");
    format!(
        "readings=[{readings}], terminal winding={}",
        class.winding()
    )
}

fn member_text(member: &Member, period: u64) -> String {
    let terminal = member.lifts.last().copied().unwrap_or(0);
    format!(
        "letters={:?}, lifts={:?}, terminal winding={}",
        member.letters,
        member.lifts,
        terminal / period
    )
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let helix = CarryHelix::new(vec![3, 4])?;
    let terrain = SteppedTerrain::new(helix, vec![9, 4, 10, 3], vec![0, 3, 2, 1])?;
    let transport = LocatedTransport::of_terrain(&terrain);
    let pairing = Pairing::new(vec![1, 0, 3, 2])?;

    // The receiver's openings are separate from the known-truth passage at key 1.
    let receiver = Receiver::found(&transport, &[0, 5])?;
    let decoder = Decoder::new(&receiver, &transport, &pairing)?;

    let key = 1;
    let passage = terrain.passage(key, 2);
    let duplex = Duplex::place(&transport, &pairing, key, &passage)?;
    let truth = receiver.class(duplex.lifts())?;

    println!("Helical duplex — known-truth calibration; no learned-repair claim");
    println!(
        "Navigator: periods={:?}, joint period={}, advances={:?}, cell labels={:?}",
        terrain.helix().periods(),
        terrain.helix().period(),
        terrain.advances(),
        terrain.labels()
    );
    println!(
        "Input passage: supplied key={key}, letters={passage:?}, absolute lifts={:?}",
        duplex.lifts()
    );
    println!(
        "Paired representation: partner={:?}, absolute lifts={:?}",
        duplex.partner(),
        duplex.partner_lifts()
    );
    println!("Receiver result: {}", class_text(&truth));

    match decoder.decode(
        key,
        duplex.strand(),
        duplex.partner(),
        Template::Unmarked,
        Fit::Free,
    )? {
        Decoded::Released { class, receipt } => println!(
            "Intact decode: Released; members={}, diameter={}, {}",
            receipt.members,
            receipt.diameter,
            class_text(&class)
        ),
        Decoded::Held { held, receipt } => println!(
            "Intact decode: Held; members={}, diameter={}, differing coordinate={}",
            receipt.members, receipt.diameter, held.coordinate
        ),
    }

    let one_sided = Damage::new(vec![(0, 1)], Vec::new());
    let (damaged_strand, damaged_partner) = one_sided.apply(&duplex, &pairing)?;
    let shift = carried_shift(&transport, passage[0], 1)?;
    println!(
        "One-sided damage: strand contact 0 changes {} to 1; partner={damaged_partner:?}; carried shift={shift}",
        passage[0]
    );
    match decoder.decode(
        key,
        &damaged_strand,
        &damaged_partner,
        Template::Unmarked,
        Fit::Free,
    )? {
        Decoded::Released { class, receipt } => {
            println!(
                "One-sided decode: Released; members={}, diameter={}, {}",
                receipt.members,
                receipt.diameter,
                class_text(&class)
            );
            println!(
                "Harness-only truth comparison: {:?}",
                Absorption::between(&truth, &class)
            );
        }
        Decoded::Held { held, receipt } => {
            println!(
                "One-sided decode: Held; members={}, diameter={}, reached supports={:?}, differing coordinate={}",
                receipt.members, receipt.diameter, receipt.reached, held.coordinate
            );
            for (index, witness) in held.witnesses.iter().enumerate() {
                println!(
                    "  witness {}: {}",
                    index + 1,
                    member_text(witness, transport.helix().period())
                );
            }
            let truth_is_supported = held
                .witnesses
                .iter()
                .any(|witness| witness.letters == passage);
            println!(
                "Harness-only known-truth check: source is among these witnesses={truth_is_supported}; no class was released, so no residual label is assigned."
            );
        }
    }

    // This complementary two-sided change has no slipped contact. The decoder therefore releases
    // the observed singleton; only the harness, which knows the source, can call it a residual.
    let coordinated = Damage::coordinated(&pairing, &[(0, 1)])?;
    let (coordinated_strand, coordinated_partner) = coordinated.apply(&duplex, &pairing)?;
    let slipped = pairing.slipped(&coordinated_strand, &coordinated_partner)?;
    let coordinated_result = decoder.decode(
        key,
        &coordinated_strand,
        &coordinated_partner,
        Template::Unmarked,
        Fit::Free,
    )?;
    println!(
        "Coordinated damage (outside one-sided coverage): strand={coordinated_strand:?}, partner={coordinated_partner:?}, slipped contacts={slipped:?}"
    );
    match &coordinated_result {
        Decoded::Released { class, receipt } => {
            println!(
                "Coordinated decode: Released; members={}, diameter={}, {}",
                receipt.members,
                receipt.diameter,
                class_text(class)
            );
            println!(
                "Harness-only known-truth result: {:?}",
                Absorption::between(&truth, class)
            );
        }
        Decoded::Held { held, receipt } => println!(
            "Coordinated decode: Held; members={}, diameter={}, differing coordinate={}; no residual class is assigned",
            receipt.members, receipt.diameter, held.coordinate
        ),
    }

    Ok(())
}

// An ordinary exterior status return, never `std::process::exit` (guard 7: no process inside the
// machinery): the error is printed as before and the status returned, so the boundary receipt and
// the owned resources end normally.
fn main() -> std::process::ExitCode {
    if let Err(error) = run() {
        eprintln!("helical duplex demonstration failed: {error}");
        return std::process::ExitCode::FAILURE;
    }
    std::process::ExitCode::SUCCESS
}
