//! The founding plan: what founded what, out of what material.
//!
//! The archived C++ depositor took a packed single-line record —
//! `founding|executable|mount+mount|return+return` — generated by CMake at configure time
//! (`archive/cpp-engine/cmake/HolonicDeposit.cmake:45-54`). Here the plan is a line-oriented text
//! file a human writes or a driver emits, because the plan is itself the deposit's provenance and
//! an unreadable provenance is not one.
//!
//! ```text
//! # comments and blank lines are ignored
//! founding    <name>     opens a founding; names are unique within a plan
//! executable  <path>     at most one per founding, optional
//! mount       <path>     zero or more; ORDER IS LOAD-BEARING, the closure folds them in order
//! return      <path>     zero or more; deposited into the standing
//! derived     <path>     zero or more; declared and deliberately NOT deposited
//! ```
//!
//! `derived` exists because the C++ depositor classified returns by filename pattern
//! (`HolonicDeposit.cmake:35-37`: suffixes `.rest`/`.lean`, patterns `/receipts/`, `POST_SEAL`,
//! `DOSSIER`, refusals `STDOUT`/`STDERR`/`OPEN_PATHS`). A pattern silently reclassifies anything
//! renamed. Here the refusal is declared per artifact and counted, so
//! `derived_returns_not_deposited` names a decision instead of recording a coincidence of spelling.

use std::fmt;
use std::path::Path;

use crate::frame::{FoundingName, FrameRefusal, RelPath};

#[derive(Debug, Clone)]
pub struct Founding {
    pub name: FoundingName,
    pub executable: Option<RelPath>,
    pub mounts: Vec<RelPath>,
    pub returns: Vec<RelPath>,
    pub derived: Vec<RelPath>,
}

impl Founding {
    /// The closure material, in the order the closure hash folds it: executable then mounts.
    pub fn material(&self) -> Vec<RelPath> {
        let mut material = Vec::with_capacity(self.mounts.len() + 1);
        material.extend(self.executable.clone());
        material.extend(self.mounts.iter().cloned());
        material
    }
}

#[derive(Debug, Clone, Default)]
pub struct Plan {
    pub foundings: Vec<Founding>,
}

impl Plan {
    pub fn parse(text: &str) -> Result<Self, PlanRefusal> {
        let mut foundings: Vec<Founding> = Vec::new();
        for (index, raw) in text.lines().enumerate() {
            let line = index + 1;
            let trimmed = raw.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let mut fields = trimmed.split_whitespace();
            let tag = fields.next().unwrap_or_default();
            let operand = fields.next();
            if fields.next().is_some() {
                return Err(PlanRefusal::at(line, PlanFault::TrailingFields));
            }
            let Some(operand) = operand else {
                return Err(PlanRefusal::at(line, PlanFault::MissingOperand(tag.into())));
            };

            if tag == "founding" {
                let name = FoundingName::parse(operand)
                    .map_err(|refusal| PlanRefusal::at(line, PlanFault::Frame(refusal)))?;
                if foundings.iter().any(|f| f.name == name) {
                    return Err(PlanRefusal::at(line, PlanFault::DuplicateFounding(name)));
                }
                foundings.push(Founding {
                    name,
                    executable: None,
                    mounts: Vec::new(),
                    returns: Vec::new(),
                    derived: Vec::new(),
                });
                continue;
            }

            let path = RelPath::parse(operand)
                .map_err(|refusal| PlanRefusal::at(line, PlanFault::Frame(refusal)))?;
            let Some(current) = foundings.last_mut() else {
                return Err(PlanRefusal::at(
                    line,
                    PlanFault::BeforeAnyFounding(tag.into()),
                ));
            };
            match tag {
                "executable" => {
                    if current.executable.is_some() {
                        return Err(PlanRefusal::at(line, PlanFault::SecondExecutable));
                    }
                    current.executable = Some(path);
                }
                "mount" => current.mounts.push(path),
                "return" => current.returns.push(path),
                "derived" => current.derived.push(path),
                other => return Err(PlanRefusal::at(line, PlanFault::UnknownTag(other.into()))),
            }
        }

        // A deposited path is a manifest key. Two foundings claiming one path would write one file
        // twice and leave the second row unverifiable against the first.
        let mut claimed: Vec<(&RelPath, &FoundingName)> = Vec::new();
        for founding in &foundings {
            for returned in &founding.returns {
                if let Some((_, first)) = claimed.iter().find(|(path, _)| *path == returned) {
                    return Err(PlanRefusal::at(
                        0,
                        PlanFault::DuplicateDeposit(returned.clone(), (*first).clone()),
                    ));
                }
                claimed.push((returned, &founding.name));
            }
        }

        Ok(Self { foundings })
    }

    pub fn read(path: &Path) -> Result<Self, PlanRefusal> {
        let text = std::fs::read_to_string(path)
            .map_err(|error| PlanRefusal::at(0, PlanFault::Unreadable(error.to_string())))?;
        Self::parse(&text)
    }
}

#[derive(Debug)]
pub struct PlanRefusal {
    pub line: usize,
    pub fault: PlanFault,
}

impl PlanRefusal {
    fn at(line: usize, fault: PlanFault) -> Self {
        Self { line, fault }
    }
}

#[derive(Debug)]
pub enum PlanFault {
    Unreadable(String),
    UnknownTag(String),
    MissingOperand(String),
    TrailingFields,
    BeforeAnyFounding(String),
    SecondExecutable,
    DuplicateFounding(FoundingName),
    DuplicateDeposit(RelPath, FoundingName),
    Frame(FrameRefusal),
}

impl fmt::Display for PlanRefusal {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.line > 0 {
            write!(formatter, "plan line {}: ", self.line)?;
        } else {
            write!(formatter, "plan: ")?;
        }
        match &self.fault {
            PlanFault::Unreadable(why) => write!(formatter, "unreadable ({why})"),
            PlanFault::UnknownTag(tag) => write!(
                formatter,
                "unknown tag `{tag}`; expected founding, executable, mount, return, derived"
            ),
            PlanFault::MissingOperand(tag) => write!(formatter, "`{tag}` carries no operand"),
            PlanFault::TrailingFields => {
                write!(formatter, "a plan line is exactly a tag and one operand")
            }
            PlanFault::BeforeAnyFounding(tag) => {
                write!(formatter, "`{tag}` appears before any founding is opened")
            }
            PlanFault::SecondExecutable => {
                write!(formatter, "a founding has one executable or none")
            }
            PlanFault::DuplicateFounding(name) => {
                write!(formatter, "founding `{name}` is declared twice")
            }
            PlanFault::DuplicateDeposit(path, first) => write!(
                formatter,
                "`{path}` is returned by two foundings; first was `{first}`"
            ),
            PlanFault::Frame(refusal) => write!(formatter, "{refusal}"),
        }
    }
}

impl std::error::Error for PlanRefusal {}

#[cfg(test)]
mod tests {
    use super::Plan;

    const SAMPLE: &str = "\
# a founding and its material
founding lean.proof-production
executable target/debug/examples/eros_lean_proof_production
mount soma/life/examples/eros_lean_proof_production.rs
mount soma/life/src/lean_mathematics.rs
return output/lean-proof-production/carrier-transport-00000.lean
derived output/lean-proof-production/STDOUT.txt
";

    #[test]
    fn a_plan_reads_into_one_founding_with_ordered_material() {
        let plan = Plan::parse(SAMPLE).expect("plan parses");
        assert_eq!(plan.foundings.len(), 1);
        let founding = &plan.foundings[0];
        assert_eq!(founding.name.as_str(), "lean.proof-production");
        assert_eq!(founding.mounts.len(), 2);
        assert_eq!(founding.returns.len(), 1);
        assert_eq!(founding.derived.len(), 1);
        let material = founding.material();
        assert_eq!(material.len(), 3);
        assert_eq!(
            material[0].as_str(),
            "target/debug/examples/eros_lean_proof_production"
        );
        assert_eq!(
            material[1].as_str(),
            "soma/life/examples/eros_lean_proof_production.rs"
        );
    }

    #[test]
    fn the_plan_refuses_an_absolute_mount() {
        let refusal = Plan::parse("founding f\nmount /etc/passwd\n").unwrap_err();
        assert!(refusal.to_string().contains("is absolute"), "{refusal}");
    }

    #[test]
    fn the_plan_refuses_one_path_returned_by_two_foundings() {
        let refusal =
            Plan::parse("founding a\nreturn x.lean\nfounding b\nreturn x.lean\n").unwrap_err();
        assert!(
            refusal.to_string().contains("returned by two foundings"),
            "{refusal}"
        );
    }

    #[test]
    fn the_plan_refuses_material_before_a_founding_is_opened() {
        let refusal = Plan::parse("mount a.rs\n").unwrap_err();
        assert!(
            refusal.to_string().contains("before any founding"),
            "{refusal}"
        );
    }
}
