//! **Confirming a deposited law on this material rather than re-deriving it.**
//!
//! `research/records/2026-08-16_THE_WITNESS_HAS_NO_ADDRESS_AND_REPETITION_EXPLORES_ONLY_A_CYCLIC_SUBGROUP.md`:
//!
//! > *"Repeating `gamma` `n` times returns `hol(gamma)^n`, so repetition explores at most the
//! > **cyclic subgroup generated by that one element**, and after `ord(hol(gamma))` passes every
//! > further repetition returns something already seen."*
//! > *"Repetition generates a cyclic subgroup; breadth generates the group."*
//!
//! The degraded emission at a tight context bound — `` ` ` ` ** Authority :** ` line ; the
//! ** Karhunen `` repeating — is that law, not a defect to diagnose. This measures the **order** of
//! the cycle it saturates into, on this material, so the identification is checked rather than
//! asserted.
//!
//! **And it also repairs a real error.** `bounded` climbed while `extent(class) > L`, using the
//! class's `maxlen` alone. A class covers `[minlen, maxlen]`, so a class whose interval is
//! `2..17550` already represents contexts as short as 2 and must not be climbed past for `L = 5`.
//! The condition is on `minlen`. Both readings are run so the difference is exhibited.

use std::collections::{BTreeMap, BTreeSet};

use body::num::Cog;
use life::causal_language::{
    fiber_bytes, lexical_tokens, CausalLanguageEcology, CausalLanguagePassage,
};
use soma_abi::active::ActionCurrent;

const MATERIAL: &[(&str, u64)] = &[
    ("canon/THE_DOCUMENT_LAW.md", 1),
    ("canon/TABLET_THE_OPERATIONS.md", 2),
    ("canon/THE_RECOVERED_LAW.md", 3),
    ("canon/TABLET_THE_COMPRESSION.md", 4),
];
const PROMPTS: &[&str] = &["a compression is", "the receiver", "the machine"];
const BOUNDS: [u32; 3] = [8, 5, 3];
const TOKENS: usize = 120;

fn main() {
    if let Err(reason) = run() {
        eprintln!("REFUSED: {reason}");
        std::process::exit(1);
    }
}

fn current() -> Result<ActionCurrent, String> {
    ActionCurrent::new(Cog::lit(1)).ok_or_else(|| "the action current is dark".to_owned())
}

struct Body {
    indptr: Vec<u32>,
    germ: Vec<u16>,
    target: Vec<u32>,
    suffix: Vec<u32>,
    minimum: Vec<u32>,
    maximum: Vec<u32>,
    standing: Vec<u64>,
    surfaces: Vec<String>,
    index_of: BTreeMap<String, u16>,
}

impl Body {
    fn carry(&self, state: u32, germ: u16) -> u32 {
        let mut at = state;
        loop {
            let from = self.indptr[at as usize] as usize;
            let to = self.indptr[at as usize + 1] as usize;
            if let Some(slot) = (from..to).find(|slot| self.germ[*slot] == germ) {
                return self.target[slot];
            }
            let parent = self.suffix[at as usize];
            if parent == at {
                return 0;
            }
            at = parent;
        }
    }
    fn population(&self, state: u32) -> Vec<(u16, u64)> {
        let from = self.indptr[state as usize] as usize;
        let to = self.indptr[state as usize + 1] as usize;
        (from..to)
            .map(|slot| (self.germ[slot], self.standing[self.target[slot] as usize]))
            .collect()
    }
    /// **The defective reading**: climb while the class's LONGEST substring exceeds the bound.
    fn by_maximum(&self, state: u32, bound: u32) -> u32 {
        let mut at = state;
        while self.maximum[at as usize] > bound {
            let parent = self.suffix[at as usize];
            if parent == at {
                break;
            }
            at = parent;
        }
        at
    }
    /// **The correct reading**: a class covers `[minlen, maxlen]`, so it already represents the
    /// bound whenever `minlen <= bound`. Climb only while the class's SHORTEST substring is longer.
    fn by_minimum(&self, state: u32, bound: u32) -> u32 {
        let mut at = state;
        while self.minimum[at as usize] > bound {
            let parent = self.suffix[at as usize];
            if parent == at {
                break;
            }
            at = parent;
        }
        at
    }
}

fn run() -> Result<(), String> {
    let mut passages = Vec::new();
    for (path, receiver) in MATERIAL {
        let text = std::fs::read_to_string(path).map_err(|error| format!("{path}: {error}"))?;
        passages.push(CausalLanguagePassage::new(*path, *receiver, text));
    }
    let ecology = CausalLanguageEcology::condition(&passages, current()?, 8)
        .map_err(|error| format!("conditioning refused: {error:?}"))?;
    let atlas = ecology.global_suffix();
    let classes = atlas.state_count();

    let mut index_of: BTreeMap<String, u16> = BTreeMap::new();
    let mut surfaces: Vec<String> = Vec::new();
    {
        let mut seen: BTreeSet<String> = BTreeSet::new();
        for state in 0..classes as u32 {
            for (germ, _) in atlas.outgoing(state) {
                seen.insert(fiber_bytes(germ.identity()).map_err(|e| format!("{e:?}"))?);
            }
        }
        for (at, token) in seen.into_iter().enumerate() {
            index_of.insert(token.clone(), at as u16);
            surfaces.push(token);
        }
    }
    let mut indptr: Vec<u32> = vec![0];
    let mut germ: Vec<u16> = Vec::new();
    let mut target: Vec<u32> = Vec::new();
    let mut suffix: Vec<u32> = Vec::with_capacity(classes);
    let mut minimum: Vec<u32> = Vec::with_capacity(classes);
    let mut maximum: Vec<u32> = Vec::with_capacity(classes);
    let mut standing: Vec<u64> = Vec::with_capacity(classes);
    for state in 0..classes as u32 {
        let mut rows: Vec<(u16, u32)> = atlas
            .outgoing(state)
            .into_iter()
            .map(|(g, t)| (index_of[&fiber_bytes(g.identity()).unwrap_or_default()], t))
            .collect();
        rows.sort();
        for (at, reaches) in rows {
            germ.push(at);
            target.push(reaches);
        }
        indptr.push(germ.len() as u32);
        suffix.push(atlas.suffix_link(state).unwrap_or(0));
        let (low, high) = atlas.class_interval(state).unwrap_or((0, 0));
        minimum.push(low as u32);
        maximum.push(high as u32);
        standing.push(atlas.standing_at(state).unwrap_or(0));
    }
    let body = Body { indptr, germ, target, suffix, minimum, maximum, standing, surfaces, index_of };

    println!("REPETITION SATURATES INTO ITS CYCLIC SUBGROUP — measuring the order\n");
    for prompt in PROMPTS {
        println!("═══ {prompt:?}");
        for bound in BOUNDS {
            for (reading, coarsen) in [
                ("maxlen (defective)", true),
                ("minlen (correct)", false),
            ] {
                let mut state = 0u32;
                for token in &lexical_tokens(prompt) {
                    state = match body.index_of.get(token) {
                        Some(index) => body.carry(state, *index),
                        None => 0,
                    };
                }
                let mut visited: BTreeMap<u32, usize> = BTreeMap::new();
                let mut emitted: Vec<String> = Vec::new();
                let mut order: Option<(usize, usize)> = None;
                for step in 0..TOKENS {
                    let read = if coarsen {
                        body.by_maximum(state, bound)
                    } else {
                        body.by_minimum(state, bound)
                    };
                    if let Some(first) = visited.get(&read) {
                        order = Some((*first, step - first));
                        break;
                    }
                    visited.insert(read, step);
                    let population = body.population(read);
                    if population.is_empty() {
                        break;
                    }
                    let (chosen, _) = population
                        .iter()
                        .copied()
                        .max_by_key(|(g, s)| (*s, std::cmp::Reverse(*g)))
                        .expect("non-empty");
                    emitted.push(body.surfaces[chosen as usize].clone());
                    state = body.carry(read, chosen);
                }
                match order {
                    Some((entered, period)) => println!(
                        "  ≤{bound} {reading:<20} SATURATED: entered at step {entered}, ORDER {period}"
                    ),
                    None => println!(
                        "  ≤{bound} {reading:<20} no repeat in {TOKENS} steps, {} tokens",
                        emitted.len()
                    ),
                }
                if !coarsen {
                    let shown: Vec<&String> = emitted.iter().take(28).collect();
                    println!(
                        "       {}",
                        shown.iter().map(|s| s.as_str()).collect::<Vec<_>>().join(" ")
                    );
                }
            }
        }
        println!();
    }
    println!("The order is `ord(hol(gamma))` from the 2026-08-16 deposit: after that many passes");
    println!("every further repetition returns something already seen. Breadth generates the group;");
    println!("repetition explores one cyclic subgroup of it.");
    Ok(())
}
