import Holonics.Geometry.AffineSwing
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Tactic.Positivity
import Holonics.Millennium.Chronology

/-!
# Navigation — when a chart change turns a long computation into two swings

The source families here are affine Swing words, reciprocal splitting and cost-exponent pairs.
For the declared positive reciprocal split, the involution's fixed point gives the cheapest
split. The oriented Riccati passage approaches that face through a reversible matrix relation.
These statements do not make every fixed point an optimum of an arbitrary objective.

Four sections.

**The grading.**  An odd word of swings *is a swing*; an even word is a translation.  So the group
the swings generate carries a `ℤ/2` grading, and the grading is the orientation class — a circuit
of odd length returns the body with its hand reversed, which is what a band with one side is.

**The split.**  When a computation of size `T` factors into two pieces of sizes `x` and `T/x`, the
map `x ↦ T/x` is an involution, its fixed point is `√T`, and **the fixed point is exactly the
cheapest split.**  Two independent characterizations — the symmetric one and the cheap one —
coincide.  That is the placement law arriving in computational cost.

*Aside: this is the shape of the approximate functional equation for the Riemann comb.  Its
reflection `s ↦ 1 − s` splits one sum of length `≈ t` into two of length `≈ √(t/2π)`, cut at
exactly the balanced point.  The naive evaluation costs `O(t)`; the split costs `O(√t)`; the
saving factor is the same half as the seam.*

**The alphabet.**  The classical machinery for bounding such sums is generated by two moves on a
pair of exponents: a **frequency swing** (an involution) and a **difference contraction** (which
fixes the trivial pair).  They do not commute, so by `orderBlind_iff_commute` a word in them is a
genuine chronology and its order is irreducible information.

**The passage.** The matrix return retains signed separation, the undivided quadratic, source
reconstruction and the exact work difference. Its root chart has an explicit contraction factor;
the generating operation does not evaluate a square root or scan a set of candidate values.

Every `theorem` here is discharged.
-/

namespace Holonics.Millennium.Navigation

open Holonics.Millennium.Swing
open Holonics.Geometry.AffineSwing Holonics.Millennium.Chronology

/-! ## 1. The swings are graded by parity, and the grading is the orientation class -/

variable {G : Type*} [AddCommGroup G]

/-- **An odd word of swings is itself a swing** — about the alternating sum of its anchors.

Three crossings do not accumulate into something new: they collapse back to one crossing, about a
new anchor built from the three by alternating signs.  The alternation is the hand. -/
theorem theOddCircuitIsASwingAboutTheAlternatingSum (b₁ b₂ b₃ a : G) :
    swing b₁ (swing b₂ (swing b₃ a)) = swing (b₁ - b₂ + b₃) a := by
  simp only [swing]; abel

/-- **An even word of swings is a translation.**  Already the composition law; restated here so the
grading is visible as a pair. -/
theorem theEvenCircuitIsATranslation (b₁ b₂ a : G) :
    swing b₁ (swing b₂ a) = a + ((b₁ + b₁) - (b₂ + b₂)) :=
  twoSwingsAreADoubledTranslation b₁ b₂ a

/-- **A four-letter word is a translation too**, so the grading is by parity and not by length. -/
theorem theFourLetterCircuitIsATranslation (b₁ b₂ b₃ b₄ a : G) :
    swing b₁ (swing b₂ (swing b₃ (swing b₄ a))) =
      a + ((b₁ + b₁) - (b₂ + b₂) + ((b₃ + b₃) - (b₄ + b₄))) := by
  simp only [swing]; abel

/-- **An odd circuit that returns the body reverses the hand it returns with.**

The body comes home; the orientation does not.  A word of odd length about one anchor is exactly
the situation, and the returned hand is the word's parity.

*Aside: this is what a band with one side is.  The orientation class of a circuit is a `ℤ/2`, and
here it is the parity of the word — the same `ℤ/2` that the address orientation carries on the
integers.* -/
theorem theOddReturningCircuitReversesTheHand (a b c : Site) {n : ℕ} (hn : Odd n)
    (hret : (swing b)^[n] a = a) :
    orientedSpan a b c = - orientedSpan a b c := by
  have := theOddWordReversesTheHand a b c hn
  rwa [hret] at this

/-- And therefore an odd returning circuit can only exist where the span already vanishes: the
body must sit on the line the two constraints span.  A hand that reverses and stays equal is a
hand that was never there. -/
theorem theOddReturningCircuitLiesOnTheConstraintLine (a b c : Site) {n : ℕ} (hn : Odd n)
    (hret : (swing b)^[n] a = a) :
    orientedSpan a b c = 0 := by
  have h := theOddReturningCircuitReversesTheHand a b c hn hret
  omega

/-! ## 2. The cheapest split is the fixed point of the split swing -/

/-- The **split swing**: two pieces whose sizes multiply to the whole.  Choosing one chooses the
other, and the choice is an involution. -/
noncomputable def splitSwing (T x : ℝ) : ℝ := T / x

/-- The **work** a split costs: both pieces are paid for. -/
noncomputable def splitWork (T x : ℝ) : ℝ := x + T / x

/-! ## 3. An oriented Riccati passage through the same split target -/

/-- The projective passage represented by `[[1, h*T], [h, 1]]`. -/
noncomputable def riccatiPassage (T x h : ℝ) : ℝ := (x + h * T) / (1 + h * x)

/-- The homogeneous two-coordinate matrix behind `riccatiPassage`. -/
noncomputable def riccatiMatrix (T h : ℝ) : Matrix (Fin 2) (Fin 2) ℝ := !![1, h * T; h, 1]

/-- The undivided quadratic residual carried by the projective pair. -/
theorem riccatiPair_residual (T h u v : ℝ) :
    (u + h * T * v) ^ 2 - T * (h * u + v) ^ 2 =
      (1 - h ^ 2 * T) * (u ^ 2 - T * v ^ 2) := by
  ring

theorem riccatiMatrix_det (T h : ℝ) :
    (riccatiMatrix T h).det = 1 - h ^ 2 * T := by
  simp [riccatiMatrix, Matrix.det_fin_two]
  ring

theorem riccatiPassage_denominator_pos {x h : ℝ} (hx : 0 < x) (hh : 0 ≤ h) :
    0 < 1 + h * x := by
  positivity

theorem riccatiPassage_pos {T x h : ℝ} (hT : 0 < T) (hx : 0 < x) (hh : 0 ≤ h) :
    0 < riccatiPassage T x h := by
  unfold riccatiPassage
  positivity

/-- The signed passage step is proportional to the split residual `T - x²`. -/
theorem riccatiPassage_step {T x h : ℝ} (hx : 0 < x) (hh : 0 ≤ h) :
    riccatiPassage T x h - x = h * (T - x ^ 2) / (1 + h * x) := by
  unfold riccatiPassage
  field_simp [ne_of_gt (riccatiPassage_denominator_pos hx hh)]
  ring

/-- The signed square residual transforms by the positive projective determinant factor. -/
theorem riccatiPassage_residual {T x h : ℝ} (hx : 0 < x) (hh : 0 ≤ h) :
    riccatiPassage T x h ^ 2 - T =
      (1 - h ^ 2 * T) * (x ^ 2 - T) / (1 + h * x) ^ 2 := by
  unfold riccatiPassage
  field_simp [ne_of_gt (riccatiPassage_denominator_pos hx hh)]
  ring

/-- Two source values retain their signed separation under the same projective passage. -/
theorem riccatiPassage_difference {T x y h : ℝ}
    (hx : 0 < x) (hy : 0 < y) (hh : 0 ≤ h) :
    riccatiPassage T x h - riccatiPassage T y h =
      (1 - h ^ 2 * T) * (x - y) /
        ((1 + h * x) * (1 + h * y)) := by
  have hxden : 1 + h * x ≠ 0 :=
    ne_of_gt (riccatiPassage_denominator_pos hx hh)
  have hyden : 1 + h * y ≠ 0 :=
    ne_of_gt (riccatiPassage_denominator_pos hy hh)
  unfold riccatiPassage
  field_simp [hxden, hyden]
  ring

/-- The projective passage preserves orientation when `h²T < 1`. -/
theorem riccatiPassage_orientation_preserving {T x h : ℝ}
    (_hT : 0 < T) (_hx : 0 < x) (_hh : 0 ≤ h) (hdet : h ^ 2 * T < 1) :
    0 < 1 - h ^ 2 * T := by
  linarith

/-- In the positive-determinant regime, the passage preserves strict source order. -/
theorem riccatiPassage_strictMono {T h x y : ℝ}
    (hT : 0 < T) (hh : 0 ≤ h) (hdet : h ^ 2 * T < 1)
    (hx : 0 < x) (hy : 0 < y) (hxy : x < y) :
    riccatiPassage T x h < riccatiPassage T y h := by
  have hdetpos : 0 < 1 - h ^ 2 * T := riccatiPassage_orientation_preserving hT hx hh hdet
  have hdiff := riccatiPassage_difference (T := T) (x := y) (y := x) hy hx hh
  have hden : 0 < (1 + h * y) * (1 + h * x) := by positivity
  have hsep : 0 < (1 - h ^ 2 * T) * (y - x) /
      ((1 + h * y) * (1 + h * x)) := by
    exact div_pos (mul_pos hdetpos (sub_pos.mpr hxy)) hden
  have hgap : 0 < riccatiPassage T y h - riccatiPassage T x h := by
    rw [hdiff]
    exact hsep
  linarith

/-- The split work decreases by the exact squared residual of the passage. -/
theorem riccatiPassage_work {T x h : ℝ}
    (hT : 0 < T) (hx : 0 < x) (hh : 0 ≤ h) :
    splitWork T (riccatiPassage T x h) - splitWork T x =
      -h * (x ^ 2 - T) ^ 2 / (x * (x + h * T) * (1 + h * x)) := by
  have hden : 1 + h * x ≠ 0 :=
    ne_of_gt (riccatiPassage_denominator_pos hx hh)
  have hnum : 0 < x + h * T := by positivity
  have hpass : riccatiPassage T x h ≠ 0 :=
    ne_of_gt (riccatiPassage_pos hT hx hh)
  unfold splitWork riccatiPassage
  field_simp [hden, hpass, hx.ne', hnum.ne']
  ring

theorem riccatiPassage_work_nonincreasing {T x h : ℝ}
    (hT : 0 < T) (hx : 0 < x) (hh : 0 ≤ h) :
    splitWork T (riccatiPassage T x h) ≤ splitWork T x := by
  apply sub_nonpos.mp
  rw [riccatiPassage_work hT hx hh]
  have hden : 0 < x * (x + h * T) * (1 + h * x) := by
    positivity
  have hnum : -h * (x ^ 2 - T) ^ 2 ≤ 0 := by
    nlinarith [sq_nonneg (x ^ 2 - T)]
  have hquot : -h * (x ^ 2 - T) ^ 2 /
      (x * (x + h * T) * (1 + h * x)) ≤ 0 :=
    div_nonpos_of_nonpos_of_nonneg hnum hden.le
  linarith

/-- The inverse passage uses the opposite oriented parameter. -/
theorem riccatiPassage_inverse {T x h : ℝ}
    (hT : 0 < T) (hx : 0 < x) (hh : 0 ≤ h) (hdet : h ^ 2 * T < 1) :
    riccatiPassage T (riccatiPassage T x h) (-h) = x := by
  have hden : 1 + h * x ≠ 0 :=
    ne_of_gt (riccatiPassage_denominator_pos hx hh)
  have hdetpos : 0 < 1 - h ^ 2 * T := riccatiPassage_orientation_preserving hT hx hh hdet
  have hxp : 0 < riccatiPassage T x h := riccatiPassage_pos hT hx hh
  have hinvden : 1 - h * riccatiPassage T x h ≠ 0 := by
    rw [show 1 - h * riccatiPassage T x h =
        (1 - h ^ 2 * T) / (1 + h * x) by
      unfold riccatiPassage
      field_simp [hden]
      ring]
    exact div_ne_zero hdetpos.ne' hden
  simp only [riccatiPassage]
  have hnum : (x + h * T) / (1 + h * x) + -h * T =
      x * (1 - h ^ 2 * T) / (1 + h * x) := by
    field_simp [hden]
    ring
  have hden' : 1 + -h * ((x + h * T) / (1 + h * x)) =
      (1 - h ^ 2 * T) / (1 + h * x) := by
    field_simp [hden]
    ring
  rw [hnum, hden']
  field_simp [hden, hdetpos.ne']

/-- Cross-multiplication reconstructs the source without invoking a root choice. -/
theorem riccatiPassage_source_reconstruction {T x h : ℝ}
    (hx : 0 < x) (hh : 0 ≤ h) :
    (1 - h * riccatiPassage T x h) * x = riccatiPassage T x h - h * T := by
  have hden : 1 + h * x ≠ 0 :=
    ne_of_gt (riccatiPassage_denominator_pos hx hh)
  unfold riccatiPassage
  field_simp [hden]
  ring

theorem theSplitSwingIsAnInvolution {T x : ℝ} (hT : T ≠ 0) (hx : x ≠ 0) :
    splitSwing T (splitSwing T x) = x := by
  simp only [splitSwing]
  rw [div_div_eq_mul_div, mul_comm, mul_div_assoc, div_self hT, mul_one]

/-- **The fixed point of the split swing is the square root.** -/
theorem theFixedPointOfTheSplitSwingIsTheRoot {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    splitSwing T x = x ↔ x = Real.sqrt T := by
  rw [splitSwing, div_eq_iff hx.ne']
  constructor
  · intro h
    rw [h, Real.sqrt_mul_self hx.le]
  · intro h
    rw [h, Real.mul_self_sqrt hT.le]

/-- For a nonzero step size, the Riccati passage has exactly the same fixed-point face as the
split Swing. -/
theorem riccatiPassage_fixed_iff_splitSwing_fixed {T x h : ℝ}
    (hx : 0 < x) (hh : 0 ≤ h) (hpositive : 0 < h) :
    riccatiPassage T x h = x ↔ splitSwing T x = x := by
  have hden : 0 < 1 + h * x := riccatiPassage_denominator_pos hx hh
  constructor
  · intro hfix
    have hstep := riccatiPassage_step (T := T) hx hh
    rw [hfix, sub_self] at hstep
    have hmul : h * (T - x ^ 2) = 0 := by
      simpa using ((eq_div_iff hden.ne').mp hstep).symm
    have hres : T - x ^ 2 = 0 :=
      (mul_eq_zero.mp hmul).resolve_left hpositive.ne'
    unfold splitSwing
    field_simp [hx.ne']
    linarith
  · intro hfix
    have hres : T - x ^ 2 = 0 := by
      unfold splitSwing at hfix
      field_simp [hx.ne'] at hfix
      linarith
    have hstep := riccatiPassage_step (T := T) hx hh
    rw [hres] at hstep
    have hstep' : riccatiPassage T x h - x = 0 := by simpa using hstep
    exact sub_eq_zero.mp hstep'

/-- The common fixed point is the already-derived positive root of the split target. -/
theorem riccatiPassage_fixed_iff_root {T x h : ℝ}
    (hT : 0 < T) (hx : 0 < x) (hh : 0 ≤ h) (hpositive : 0 < h) :
    riccatiPassage T x h = x ↔ x = Real.sqrt T := by
  exact (riccatiPassage_fixed_iff_splitSwing_fixed hx hh hpositive).trans
    (theFixedPointOfTheSplitSwingIsTheRoot hT hx)

/-- In the root chart `z = (x - a) / (x + a)`, the passage acts by one signed projective
factor when `T = a²`. -/
theorem riccatiPassage_root_chart {T x a h : ℝ}
    (hT : 0 < T) (hx : 0 < x) (ha : 0 < a) (hh : 0 ≤ h) (hroot : T = a ^ 2) :
    (riccatiPassage T x h - a) / (riccatiPassage T x h + a) =
      ((1 - h * a) / (1 + h * a)) * ((x - a) / (x + a)) := by
  have hden : 0 < 1 + h * x := riccatiPassage_denominator_pos hx hh
  have hpass : 0 < riccatiPassage T x h := riccatiPassage_pos hT hx hh
  have hxa : 0 < x + a := by positivity
  have hpa : 0 < riccatiPassage T x h + a := by positivity
  have hha : 0 < 1 + h * a := by positivity
  unfold riccatiPassage
  field_simp [hden.ne', hxa.ne', hpa.ne', hha.ne']
  rw [hroot]
  ring

/-- A positive step smaller than the root scale gives a strict contraction factor in the root
chart. -/
theorem riccatiPassage_root_chart_factor_between_zero_one {a h : ℝ}
    (ha : 0 < a) (hh : 0 < h) (hha : h * a < 1) :
    0 < (1 - h * a) / (1 + h * a) ∧ (1 - h * a) / (1 + h * a) < 1 := by
  have hden : 0 < 1 + h * a := by positivity
  have hprod : 0 < h * a := mul_pos hh ha
  constructor
  · exact div_pos (by linarith) hden
  · apply (div_lt_one hden).2
    linarith

/-- **The work at the fixed point is twice the root.** -/
theorem theWorkAtTheFixedPoint {T : ℝ} (hT : 0 < T) :
    splitWork T (Real.sqrt T) = 2 * Real.sqrt T := by
  have hs : Real.sqrt T ≠ 0 := (Real.sqrt_pos.mpr hT).ne'
  have hdiv : T / Real.sqrt T = Real.sqrt T := by
    rw [div_eq_iff hs]
    exact (Real.mul_self_sqrt hT.le).symm
  rw [splitWork, hdiv]
  ring

/-- **The excess of any split over the balanced one is a square.**  This is the whole content of
both the lower bound and its equality case. -/
theorem theWorkExcessIsASquare {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    splitWork T x - 2 * Real.sqrt T = (x - Real.sqrt T) ^ 2 / x := by
  have hsq : Real.sqrt T * Real.sqrt T = T := Real.mul_self_sqrt hT.le
  rw [splitWork]
  field_simp
  nlinarith [hsq]

/-- **No split is cheaper than the balanced one.** -/
theorem theBalancedSplitIsCheapest {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    2 * Real.sqrt T ≤ splitWork T x := by
  have := theWorkExcessIsASquare hT hx
  have hpos : (0:ℝ) ≤ (x - Real.sqrt T) ^ 2 / x := by positivity
  linarith

/-- **The cheapest split is exactly the fixed point of the swing.**

Two independent readings — the symmetric one and the cheap one — pick the same point.  Nothing
about cost went into the involution and nothing about symmetry went into the minimisation, and
they coincide.

This is the placement law in computational cost: *the place to cut is the fixed locus of the
involution that relates the two charts.* -/
theorem theCheapestSplitIsTheFixedPointOfTheSwing {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    splitSwing T x = x ↔ ∀ y : ℝ, 0 < y → splitWork T x ≤ splitWork T y := by
  constructor
  · intro hfix y hy
    rw [(theFixedPointOfTheSplitSwingIsTheRoot hT hx).mp hfix, theWorkAtTheFixedPoint hT]
    exact theBalancedSplitIsCheapest hT hy
  · intro hmin
    have hroot : (0 : ℝ) < Real.sqrt T := Real.sqrt_pos.mpr hT
    have h1 : splitWork T x ≤ 2 * Real.sqrt T := by
      have := hmin (Real.sqrt T) hroot
      rwa [theWorkAtTheFixedPoint hT] at this
    have h2 : 2 * Real.sqrt T ≤ splitWork T x := theBalancedSplitIsCheapest hT hx
    have heq : splitWork T x = 2 * Real.sqrt T := le_antisymm h1 h2
    rw [theFixedPointOfTheSplitSwingIsTheRoot hT hx]
    have hexc := theWorkExcessIsASquare hT hx
    rw [heq] at hexc
    have hquot : (x - Real.sqrt T) ^ 2 / x = 0 := by linarith
    have h0 : (x - Real.sqrt T) ^ 2 = 0 := by
      rcases div_eq_zero_iff.mp hquot with h | h
      · exact h
      · exact absurd h hx.ne'
    have hlin : x - Real.sqrt T = 0 := pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h0
    linarith

/-! ## 4. The cost alphabet: two moves, one an involution, and they do not commute

Bounding a sum of the kind the split produces is done by moving a pair of exponents through two
operations.  One is a chart transition between the additive and the frequency presentations; the
other differences the phase.  This section carries them as pure arithmetic on a pair of rationals
and proves the three facts that matter: the transition is an involution, the differencing fixes
the trivial pair, and they do not commute.

*Aside: these are the van der Corput B- and A-processes and their exponent pairs.  Nothing
analytic is formalized here — only the alphabet.* -/

/-- The **frequency swing** on a cost pair: the chart transition between a sum and its transform. -/
def frequencySwing (p : ℚ × ℚ) : ℚ × ℚ := (p.2 - 1 / 2, p.1 + 1 / 2)

/-- The **difference contraction** on a cost pair: differencing the phase and re-normalising. -/
def differenceContraction (p : ℚ × ℚ) : ℚ × ℚ :=
  (p.1 / (2 * p.1 + 2), (p.1 + p.2 + 1) / (2 * p.1 + 2))

/-- The cost pair a bare sum carries before any move. -/
def trivialCost : ℚ × ℚ := (0, 1)

/-- **The frequency swing is an involution.**  It is a swing in the sense this project means: an
order-two chart transition. -/
theorem theFrequencySwingIsAnInvolution : Function.Involutive frequencySwing := by
  intro p
  simp [frequencySwing]

/-- The difference contraction fixes the trivial cost. This records a fixed point; a quantitative
convergence assertion additionally needs its own contraction/domain law. -/
theorem theContractionFixesTheTrivialCost : differenceContraction trivialCost = trivialCost := by
  norm_num [differenceContraction, trivialCost]

/-- **One swing then one contraction gives the classical pair.**

*Aside: `(1/6, 2/3)`, the Weyl exponent pair, from which `ζ(1/2+it) ≪ t^{1/6+ε}` classically
follows.  The bound is not formalized; the arithmetic of the word is.* -/
theorem theWeylCostIsOneSwingThenOneContraction :
    differenceContraction (frequencySwing trivialCost) = (1 / 6, 2 / 3) := by
  norm_num [differenceContraction, frequencySwing, trivialCost]

/-- **The two moves do not commute**, witnessed at the trivial cost.

Swinging then contracting reaches `(1/6, 2/3)`; contracting then swinging goes nowhere, because
the contraction fixes the trivial pair.  The order is the whole difference. -/
theorem theTwoMovesDoNotCommute :
    differenceContraction (frequencySwing trivialCost)
      ≠ frequencySwing (differenceContraction trivialCost) := by
  rw [theWeylCostIsOneSwingThenOneContraction, theContractionFixesTheTrivialCost]
  norm_num [frequencySwing, trivialCost]

/-- The alphabet, as an indexed family of transports. -/
def costAlphabet : Bool → (ℚ × ℚ) → (ℚ × ℚ)
  | false => differenceContraction
  | true => frequencySwing

/-- **A cost word is a genuine chronology.**

The alphabet is not order-blind, so by `orderBlind_iff_commute` the order of a word in it is
irreducible information: the exponent a sum admits depends on *when* each move was made, not only
on how many of each.  This is the criterion of the previous file applied to a real object. -/
theorem theCostAlphabetIsNotOrderBlind : ¬ OrderBlind costAlphabet := by
  rw [orderBlind_iff_commute]
  intro h
  exact theTwoMovesDoNotCommute (h false true trivialCost)

end Holonics.Millennium.Navigation
