//! Source-neutral relational incidence recovered at the UAR0 severing boundary.
//!
//! The rejected developmental body carried two different objects in one wrapper: a reversible
//! surface atlas and an oriented relational complex.  The surface atlas must leave.  The complex
//! must not leave with it.  This module quotients the latter by the coarsest stable incidence
//! partition generated by factor support, causal phase, cell orientation, and repeated
//! face--cell contact.  Source phrases, source occurrence hashes, delivery counters, linguistic
//! class names, and the inverse codec never enter the returned morphology.

use std::collections::{BTreeMap, BTreeSet};

use holonic_engine::{
    AddressedCurrentSection, cuda_refine::ResidentSparseRelationalCurrentAtlas,
    dimensional_wave::ExactComplexWaveCurrent,
};

use num_bigint::{BigInt, BigUint};
use num_rational::Ratio;
use num_traits::{One, Signed, Zero};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;

mod morphology;
mod realization;
pub const SOURCE_NEUTRAL_RELATIONAL_MORPHOLOGY_SCHEMA: &str =
    "soma-life.source-neutral-relational-morphology.v1";
pub const SOURCE_NEUTRAL_EXTERIOR_REALIZATION_MORPHOLOGY_SCHEMA: &str =
    "soma-life.source-neutral-exterior-realization-morphology.v3";
pub const SOURCE_NEUTRAL_EXTERIOR_REALIZATION_PASSAGE_SCHEMA: &str =
    "soma-life.source-neutral-exterior-realization-passage.v7";

/// Exact nonnegative current coordinate.  Normalization is a constitutive ratio, never a float,
/// tolerance, sampled probability, or scalar loss replacement.
pub type SourceNeutralPositiveCurrent = Ratio<BigUint>;

/// One addressed pre-locking native response face presented to the realization boundary.  Its
/// exact complex current and target-state incidence are productive; the positive norm is a later
/// receiver face.  `mode` is an anonymous native face address, not a word, token, or modality.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralNativeOrientedFace {
    pub mode: u32,
    pub source_state: Option<u32>,
    pub native_port: u32,
    pub native_generator: u32,
    pub target_states: Vec<u32>,
    /// Exact device-enacted local currents carried by this response face before their common
    /// target-site junction.  The enclosing resident passage retains radicals and both boundary
    /// maps; this population is its productive dependent factor fibre.
    pub local_currents: Vec<SourceNeutralNativeOrientedLocalCurrent>,
    pub oriented_current: ExactComplexWaveCurrent,
    /// The branchwise exterior complex return is retained beside the relational pairing.  It is
    /// reconstruction testimony and does not replace the oriented relational current.
    pub branch_returned_current: Option<ExactComplexWaveCurrent>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralNativeOrientedLocalCurrent {
    pub source_section: u32,
    pub selected_slot: u32,
    pub target_section: u32,
    pub factor_current: Vec<(u32, BigUint)>,
}

#[derive(Debug, Error)]
pub enum SourceNeutralRelationalError {
    #[error("the developmental relational complex is malformed")]
    Developmental,
    #[error("the source-neutral relational quotient exceeded its address space")]
    Extent,
    #[error("the source-neutral relational quotient is malformed")]
    Quotient,
}

/// One causal-phase population on a factor incidence.  It is retained as current testimony, not
/// as an exterior source occurrence.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralPhasePopulation {
    pub factor: u32,
    pub phase: u8,
    pub occurrence_population: u64,
}

/// One oriented incidence from a quotient face to a quotient cell.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralRelationalIncidence {
    pub cell: u32,
    /// Ordered boundary position.  It carries orientation but no linguistic role name.
    pub boundary_position: u8,
    pub incidence_population: u64,
}

/// One face of the stable source-neutral relational quotient.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralRelationalFace {
    pub address: String,
    pub factor_support: Vec<u32>,
    pub phase_population: Vec<SourceNeutralPhasePopulation>,
    pub cell_incidence: Vec<SourceNeutralRelationalIncidence>,
}

/// One oriented cell of the stable quotient.  Its ordered face boundary is the native geometry;
/// no subject/relation/modality/object label is retained.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralRelationalCell {
    pub address: String,
    pub oriented_boundary: Vec<u32>,
    pub factor_support: Vec<u32>,
    pub phase_population: Vec<SourceNeutralPhasePopulation>,
}

/// The productive relational organ after the source surface and inverse decoder have departed.
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralRelationalMorphology {
    pub(super) schema: String,
    pub(super) factor_population: u32,
    pub(super) factor_adjacency: Vec<(u32, u32)>,
    pub(super) faces: Vec<SourceNeutralRelationalFace>,
    pub(super) cells: Vec<SourceNeutralRelationalCell>,
    pub(super) obstructed_delivery_population: u64,
    pub(super) identity_sha256: String,
}

/// One factor-conditioned local edge in the source-neutral exterior boundary chart.  `source`
/// and `target` are universal boundary-port coordinates: opening is zero, an octet `b` is
/// `b + 1`, and closure is 257.  The population is a condensed developmental current.  No path,
/// surface variant, clause, word, source occurrence, or inverse source address survives here.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SourceNeutralExteriorRealizationTransition {
    /// Stable anonymous relational-face class which carried this local boundary incidence.
    pub face: u32,
    pub source: u16,
    pub target: u16,
    pub occurrence_population: u64,
}

// Eight million local incidences are legitimate standing on the current corpus.  Their named
// Rust fields are an apparatus convenience, not eight million repetitions of a wire ontology;
// serialize each occurrence as the exact ordered carrier `[site, source, target, population]`.
impl Serialize for SourceNeutralExteriorRealizationTransition {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        (
            self.face,
            self.source,
            self.target,
            self.occurrence_population,
        )
            .serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for SourceNeutralExteriorRealizationTransition {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let (face, source, target, occurrence_population) =
            <(u32, u16, u16, u64)>::deserialize(deserializer)?;
        Ok(Self {
            face,
            source,
            target,
            occurrence_population,
        })
    }
}

/// One addressed oriented face--cell incidence.  Its vector position is the realization-site
/// coordinate.  `successor_site` retains the joining equality to the next boundary incidence of
/// the same cell; a missing successor marks the exterior close of that oriented cell.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SourceNeutralExteriorRealizationSite {
    pub face: u32,
    pub cell: u32,
    pub boundary_position: u8,
    pub incidence_population: u64,
    pub successor_site: Option<u32>,
}

impl Serialize for SourceNeutralExteriorRealizationSite {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        (
            self.face,
            self.cell,
            self.boundary_position,
            self.incidence_population,
            self.successor_site,
        )
            .serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for SourceNeutralExteriorRealizationSite {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let (face, cell, boundary_position, incidence_population, successor_site) =
            <(u32, u32, u8, u64, Option<u32>)>::deserialize(deserializer)?;
        Ok(Self {
            face,
            cell,
            boundary_position,
            incidence_population,
            successor_site,
        })
    }
}

/// Source-neutral exterior realization standing founded at the one-way severing boundary.
///
/// The standing is deliberately not a trie, accepted-language automaton, phrase table, or face to
/// surface decoder. It retains the local exterior boundary incidence only after each occurrence
/// has descended to the stable anonymous relational-face class founded by factor, phase, and
/// oriented face/cell contact. It deliberately discards surface positions and complete paths;
/// consequently it admits recombination and cannot enumerate which developmental source strings
/// produced it. Later native current, site current, entered realization current, and exterior
/// chronology determine a continuation; developmental material cannot be consulted after rest.
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationMorphology {
    pub(super) schema: String,
    pub(super) relational_identity_sha256: String,
    pub(super) face_population: u32,
    pub(super) cell_population: u32,
    pub(super) sites: Vec<SourceNeutralExteriorRealizationSite>,
    pub(super) factor_population: u32,
    pub(super) transitions: Vec<SourceNeutralExteriorRealizationTransition>,
    pub(super) developmental_transition_population: u64,
    pub(super) identity_sha256: String,
}

/// The complete quadratic current carried by one native factor into the exterior realization
/// boundary.  It is derived from every reacted target section as `sum_s w_s x_s[f]^2`; therefore
/// it is a receiver of the already-returned rank-one ecology rather than a reconstructed linear
/// source vector.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationFactorCurrent {
    pub factor: u32,
    pub current: SourceNeutralPositiveCurrent,
}

/// Exact oriented basis current retained once per native factor. Realization-site coordinates
/// carry only the positive incidence coefficient of this basis, so the dependent complex carrier
/// is not redundantly materialized at every site.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationOrientedFactorCurrent {
    pub factor: u32,
    pub current: ExactComplexWaveCurrent,
}

/// One coordinate of the continuing realization current.  `site` is a stable relational
/// incidence class and `factor` is its local Complex-Parametron carrier.  Exterior ports act on
/// this population as generators; no emitted byte, word, path position, or source surface is a
/// state coordinate.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationSiteCurrent {
    /// Exact receiver/history class of the `(site, factor, phase)` carrier.  `site`, `factor`, and
    /// `phase` below are one execution representative retained for reconstruction; equality and
    /// aggregation use this class and the local boundary port.
    pub carrier: u32,
    pub site: u32,
    pub factor: u32,
    pub phase: u8,
    /// The local boundary state at this incidence.  It is reset to Opening only by an exact
    /// oriented face--cell successor, while the exterior recurrence still retains its own port.
    pub local_source_port: u16,
    pub current: SourceNeutralPositiveCurrent,
}

/// Productive oriented current on one realization carrier. Native face currents join only after
/// the addressed face-to-target-state-to-factor incidence presents them at this carrier; the
/// complete face population remains beside the joined current as reconstruction testimony.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationComplexSiteCurrent {
    pub carrier: u32,
    pub site: u32,
    pub factor: u32,
    pub phase: u8,
    pub local_source_port: u16,
    /// Exact nonnegative coefficient of `oriented_factor_current[factor]` at this incidence.
    pub incidence_coefficient: SourceNeutralPositiveCurrent,
}

/// Coarsest exact suffix quotient of the rested realization sites.  Two sites meet only when
/// their contemporary face class, incidence multiplicity, and complete successor suffix agree.
/// Because every local port transition is owned by the face and the sole spatial transition is
/// owned by `successor_site`, this structural quotient commutes with every admitted exterior
/// generator.  `site_to_class` is the complete reconstruction fibre; representatives are an
/// execution chart and never source identities.
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct SourceNeutralExteriorSiteHistoryQuotient {
    site_to_class: Vec<u32>,
    representatives: Vec<u32>,
    fibres: Vec<Vec<u32>>,
    carrier_addresses: BTreeMap<(u32, u32, u8), u32>,
    carrier_representatives: Vec<(u32, u32, u8)>,
    carrier_fibres: Vec<Vec<(u32, u32, u8)>>,
    identity_sha256: String,
}

impl SourceNeutralExteriorSiteHistoryQuotient {
    fn found(
        morphology: &SourceNeutralExteriorRealizationMorphology,
        relational: &SourceNeutralRelationalMorphology,
    ) -> Result<Self, SourceNeutralRelationalError> {
        if morphology.sites.is_empty() || relational.cells.is_empty() {
            return Err(SourceNeutralRelationalError::Quotient);
        }
        let mut site_to_class = vec![None::<u32>; morphology.sites.len()];
        let mut signatures = BTreeMap::<(u32, u64, Option<u32>), u32>::new();
        let mut representatives = Vec::<u32>::new();
        let mut unresolved = morphology.sites.len();
        while unresolved != 0 {
            let before = unresolved;
            for (site_at, site) in morphology.sites.iter().enumerate() {
                if site_to_class[site_at].is_some() {
                    continue;
                }
                let successor_class = match site.successor_site {
                    Some(successor) => {
                        match site_to_class.get(successor as usize).copied().flatten() {
                            Some(class) => Some(class),
                            None => continue,
                        }
                    }
                    None => None,
                };
                let signature = (site.face, site.incidence_population, successor_class);
                let class = if let Some(class) = signatures.get(&signature).copied() {
                    class
                } else {
                    let class = u32::try_from(representatives.len())
                        .map_err(|_| SourceNeutralRelationalError::Extent)?;
                    signatures.insert(signature, class);
                    representatives.push(
                        u32::try_from(site_at).map_err(|_| SourceNeutralRelationalError::Extent)?,
                    );
                    class
                };
                site_to_class[site_at] = Some(class);
                unresolved -= 1;
            }
            if unresolved == before {
                return Err(SourceNeutralRelationalError::Quotient);
            }
        }
        let site_to_class = site_to_class
            .into_iter()
            .collect::<Option<Vec<_>>>()
            .ok_or(SourceNeutralRelationalError::Quotient)?;
        let mut fibres = vec![Vec::<u32>::new(); representatives.len()];
        for (site, class) in site_to_class.iter().copied().enumerate() {
            fibres[class as usize]
                .push(u32::try_from(site).map_err(|_| SourceNeutralRelationalError::Extent)?);
        }
        if fibres.iter().any(Vec::is_empty) {
            return Err(SourceNeutralRelationalError::Quotient);
        }
        // Lift the spatial suffix quotient to the complete pre-locking carrier.  Factor and phase
        // names do not survive when their separator weight and complete successor carrier agree;
        // this is the exact weighted future-consequence quotient missing from the raw all-port
        // expansion.
        let mut carrier_addresses = BTreeMap::<(u32, u32, u8), u32>::new();
        let mut carrier_signatures = BTreeMap::<(u32, Option<(u32, BigUint)>), u32>::new();
        let mut carrier_representatives = Vec::<(u32, u32, u8)>::new();
        let mut carrier_fibres = Vec::<Vec<(u32, u32, u8)>>::new();
        for site_class in 0..representatives.len() {
            let representative_site = morphology.site(representatives[site_class])?;
            let mut factor_phases = BTreeSet::<(u32, u8)>::new();
            for site in &fibres[site_class] {
                let occurrence = morphology.site(*site)?;
                let cell = relational
                    .cells
                    .get(occurrence.cell as usize)
                    .ok_or(SourceNeutralRelationalError::Quotient)?;
                factor_phases.extend(
                    cell.phase_population
                        .iter()
                        .map(|population| (population.factor, population.phase)),
                );
            }
            for (factor, phase) in factor_phases {
                let successor = match representative_site.successor_site {
                    Some(successor_site) => {
                        let successor = morphology.site(successor_site)?;
                        let successor_site_class = site_to_class[successor_site as usize];
                        let successor_carrier = carrier_addresses
                            .get(&(successor_site_class, factor, phase))
                            .copied()
                            .ok_or(SourceNeutralRelationalError::Quotient)?;
                        let population = phase_population(
                            &relational.faces[successor.face as usize].phase_population,
                            factor,
                            phase,
                        )
                        .ok_or(SourceNeutralRelationalError::Quotient)?;
                        Some((
                            successor_carrier,
                            BigUint::from(successor.incidence_population)
                                * BigUint::from(population),
                        ))
                    }
                    None => None,
                };
                let signature = (representative_site.face, successor);
                let carrier = if let Some(carrier) = carrier_signatures.get(&signature).copied() {
                    carrier
                } else {
                    let carrier = u32::try_from(carrier_representatives.len())
                        .map_err(|_| SourceNeutralRelationalError::Extent)?;
                    carrier_signatures.insert(signature, carrier);
                    carrier_representatives.push((site_class as u32, factor, phase));
                    carrier_fibres.push(Vec::new());
                    carrier
                };
                carrier_addresses.insert((site_class as u32, factor, phase), carrier);
                carrier_fibres[carrier as usize].push((site_class as u32, factor, phase));
            }
        }
        if carrier_representatives.is_empty()
            || carrier_fibres.iter().any(Vec::is_empty)
            || carrier_addresses.len() != carrier_fibres.iter().map(Vec::len).sum::<usize>()
        {
            return Err(SourceNeutralRelationalError::Quotient);
        }
        let presented_carrier_addresses = carrier_addresses
            .iter()
            .map(|(address, class)| (*address, *class))
            .collect::<Vec<_>>();
        let identity_sha256 = digest(&(
            "soma-life.source-neutral-exterior-site-history-quotient.v1",
            morphology.identity_sha256.as_str(),
            relational.identity_sha256.as_str(),
            &site_to_class,
            &representatives,
            &fibres,
            &presented_carrier_addresses,
            &carrier_representatives,
            &carrier_fibres,
        ));
        Ok(Self {
            site_to_class,
            representatives,
            fibres,
            carrier_addresses,
            carrier_representatives,
            carrier_fibres,
            identity_sha256,
        })
    }

    fn class(&self, site: u32) -> Result<u32, SourceNeutralRelationalError> {
        self.site_to_class
            .get(site as usize)
            .copied()
            .ok_or(SourceNeutralRelationalError::Quotient)
    }

    fn representative(&self, class: u32) -> Result<u32, SourceNeutralRelationalError> {
        self.representatives
            .get(class as usize)
            .copied()
            .ok_or(SourceNeutralRelationalError::Quotient)
    }

    fn carrier(
        &self,
        site_class: u32,
        factor: u32,
        phase: u8,
    ) -> Result<u32, SourceNeutralRelationalError> {
        self.carrier_addresses
            .get(&(site_class, factor, phase))
            .copied()
            .ok_or(SourceNeutralRelationalError::Quotient)
    }

    fn carrier_representative(
        &self,
        carrier: u32,
    ) -> Result<(u32, u32, u8), SourceNeutralRelationalError> {
        self.carrier_representatives
            .get(carrier as usize)
            .copied()
            .ok_or(SourceNeutralRelationalError::Quotient)
    }

    pub(super) fn source_population(&self) -> usize {
        self.site_to_class.len()
    }

    pub(super) fn quotient_population(&self) -> usize {
        self.carrier_representatives.len()
    }

    pub(super) fn reconstruction_population(&self) -> usize {
        self.carrier_fibres.iter().map(Vec::len).sum()
    }

    pub(super) fn identity(&self) -> &str {
        &self.identity_sha256
    }
}

#[derive(Debug)]
struct SourceNeutralExteriorComplexSiteTransportContribution {
    exterior_target_port: u16,
    target_carrier: u32,
    target_local_source_port: u16,
    factor: u32,
    phase: u8,
    incidence_coefficient: SourceNeutralPositiveCurrent,
}

/// One exterior target-boundary current after the complete native factor section has crossed the
/// rested factor-conditioned incidence.  The port coordinate is a universal boundary chart, not
/// a token or semantic class.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationTargetCurrent {
    pub target_port: u16,
    pub current: SourceNeutralPositiveCurrent,
    pub supporting_transition_population: usize,
}

/// Exact native-section-to-exterior realization passage.
///
/// The entering phase is a separately caused projective current on `[0,1)`.  It meets the
/// complete target-current partition and returns the unique local phase inside the selected
/// half-open interval.  The returned factor section is the restriction of the entering section
/// through that selected incidence.  It therefore carries the entire realized prefix without a
/// caller-chosen history width, string, token, or private semantic echo.  No local maximum is
/// treated as an answer.  Both complete current sections, the interval, and the native lineage
/// remain beside the selected face as its reconstruction fibre.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceNeutralExteriorRealizationPassage {
    pub schema: String,
    pub morphology_identity_sha256: String,
    pub native_section_identity_sha256: String,
    pub native_current_passage_identity_sha256: String,
    pub source_port: u16,
    pub factor_current: Vec<SourceNeutralExteriorRealizationFactorCurrent>,
    pub oriented_factor_current: Vec<SourceNeutralExteriorRealizationOrientedFactorCurrent>,
    pub native_oriented_faces: Vec<SourceNeutralNativeOrientedFace>,
    pub site_current: Vec<SourceNeutralExteriorRealizationSiteCurrent>,
    pub complex_site_current: Vec<SourceNeutralExteriorRealizationComplexSiteCurrent>,
    pub target_current: Vec<SourceNeutralExteriorRealizationTargetCurrent>,
    pub total_target_current: SourceNeutralPositiveCurrent,
    pub entering_realization_current_identity_sha256: String,
    pub entering_phase_numerator: BigUint,
    pub entering_phase_denominator: BigUint,
    pub selected_target_port: u16,
    pub selected_interval_begin: SourceNeutralPositiveCurrent,
    pub selected_interval_end: SourceNeutralPositiveCurrent,
    /// Current returned after the selected local boundary incidence acts.  This projective
    /// section is the unbounded causal memory of the emitted prefix; no caller chooses an n-gram
    /// order or context width.
    pub returned_factor_current: Vec<SourceNeutralExteriorRealizationFactorCurrent>,
    pub returned_site_current: Vec<SourceNeutralExteriorRealizationSiteCurrent>,
    pub returned_complex_site_current: Vec<SourceNeutralExteriorRealizationComplexSiteCurrent>,
    pub returned_phase_numerator: BigUint,
    pub returned_phase_denominator: BigUint,
    pub returned_realization_current_identity_sha256: String,
    pub source_boundary_total: bool,
    pub target_boundary_total: bool,
    pub complete_reconstruction_fibre_retained: bool,
    pub source_codec_consulted: bool,
    pub source_surface_reachable: bool,
    pub identity_sha256: String,
}

impl SourceNeutralExteriorRealizationPassage {
    pub(crate) fn validate(&self) -> Result<(), SourceNeutralRelationalError> {
        let source_complex_shadow = positive_site_shadow(&self.complex_site_current)?;
        let returned_complex_shadow = positive_site_shadow(&self.returned_complex_site_current)?;
        let site_total = self
            .site_current
            .iter()
            .fold(Ratio::zero(), |sum, site| sum + &site.current);
        let target_total = self
            .target_current
            .iter()
            .fold(Ratio::zero(), |sum, target| sum + &target.current);
        let returned_site_total = self
            .returned_site_current
            .iter()
            .fold(Ratio::zero(), |sum, site| sum + &site.current);
        let returned_factor_projection = self.returned_site_current.iter().fold(
            BTreeMap::<u32, SourceNeutralPositiveCurrent>::new(),
            |mut projection, current| {
                *projection.entry(current.factor).or_default() += &current.current;
                projection
            },
        );
        let returned_factor_projection = returned_factor_projection
            .into_iter()
            .map(
                |(factor, current)| SourceNeutralExteriorRealizationFactorCurrent {
                    factor,
                    current,
                },
            )
            .collect::<Vec<_>>();
        let entering_phase = Ratio::new(
            self.entering_phase_numerator.clone(),
            self.entering_phase_denominator.clone(),
        );
        let phase_position = &entering_phase * &self.total_target_current;
        let selected_interval = self
            .target_current
            .iter()
            .try_fold((Ratio::zero(), None), |(begin, selected), target| {
                let end = &begin + &target.current;
                Ok::<_, SourceNeutralRelationalError>(
                    if target.target_port == self.selected_target_port {
                        (end.clone(), Some((begin, end)))
                    } else {
                        (end, selected)
                    },
                )
            })?
            .1;
        if self.schema != SOURCE_NEUTRAL_EXTERIOR_REALIZATION_PASSAGE_SCHEMA
            || !is_digest(&self.morphology_identity_sha256)
            || !is_digest(&self.native_section_identity_sha256)
            || !is_digest(&self.native_current_passage_identity_sha256)
            || !is_digest(&self.entering_realization_current_identity_sha256)
            || !is_digest(&self.returned_realization_current_identity_sha256)
            || self.source_port >= 257
            || self.factor_current.is_empty()
            || self
                .factor_current
                .windows(2)
                .any(|pair| pair[0].factor >= pair[1].factor)
            || self
                .factor_current
                .iter()
                .any(|factor| factor.current.is_zero())
            || self.oriented_factor_current.is_empty()
            || self
                .oriented_factor_current
                .windows(2)
                .any(|pair| pair[0].factor >= pair[1].factor)
            || self
                .oriented_factor_current
                .iter()
                .any(|factor| factor.current.is_zero())
            || self.native_oriented_faces.is_empty()
            || self
                .native_oriented_faces
                .windows(2)
                .any(|pair| pair[0].mode >= pair[1].mode)
            || self.native_oriented_faces.iter().any(|face| {
                face.target_states.is_empty()
                    || face.target_states.windows(2).any(|pair| pair[0] >= pair[1])
            })
            || self.site_current.is_empty()
            || self.site_current.windows(2).any(|pair| {
                (
                    pair[0].carrier,
                    pair[0].factor,
                    pair[0].phase,
                    pair[0].local_source_port,
                ) >= (
                    pair[1].carrier,
                    pair[1].factor,
                    pair[1].phase,
                    pair[1].local_source_port,
                )
            })
            || self.site_current.iter().any(|site| {
                site.phase > 2 || site.local_source_port >= 257 || site.current.is_zero()
            })
            || self.site_current != source_complex_shadow
            || self.complex_site_current.is_empty()
            || self.complex_site_current.windows(2).any(|pair| {
                (
                    pair[0].carrier,
                    pair[0].factor,
                    pair[0].phase,
                    pair[0].local_source_port,
                ) >= (
                    pair[1].carrier,
                    pair[1].factor,
                    pair[1].phase,
                    pair[1].local_source_port,
                )
            })
            || self.complex_site_current.iter().any(|site| {
                site.phase > 2
                    || site.local_source_port >= 257
                    || site.incidence_coefficient.is_zero()
            })
            || self.target_current.is_empty()
            || self
                .target_current
                .windows(2)
                .any(|pair| pair[0].target_port >= pair[1].target_port)
            || self.target_current.iter().any(|target| {
                target.target_port == 0
                    || target.target_port > 257
                    || target.current.is_zero()
                    || target.supporting_transition_population == 0
            })
            || site_total != Ratio::one()
            || target_total != self.total_target_current
            || self.total_target_current != Ratio::one()
            || self.total_target_current.is_zero()
            || self.entering_phase_denominator.is_zero()
            || self.entering_phase_numerator >= self.entering_phase_denominator
            || self.selected_target_port == 0
            || self.selected_target_port > 257
            || selected_interval.as_ref().is_none_or(|(begin, end)| {
                begin != &self.selected_interval_begin || end != &self.selected_interval_end
            })
            || phase_position < self.selected_interval_begin
            || phase_position >= self.selected_interval_end
            || self
                .target_current
                .iter()
                .find(|target| target.target_port == self.selected_target_port)
                .is_none_or(|target| {
                    &self.selected_interval_end - &self.selected_interval_begin != target.current
                })
            || self.returned_factor_current.is_empty()
            || self
                .returned_factor_current
                .windows(2)
                .any(|pair| pair[0].factor >= pair[1].factor)
            || self
                .returned_factor_current
                .iter()
                .any(|factor| factor.current.is_zero())
            || self.returned_site_current.is_empty()
            || self.returned_site_current.windows(2).any(|pair| {
                (
                    pair[0].carrier,
                    pair[0].factor,
                    pair[0].phase,
                    pair[0].local_source_port,
                ) >= (
                    pair[1].carrier,
                    pair[1].factor,
                    pair[1].phase,
                    pair[1].local_source_port,
                )
            })
            || self.returned_site_current.iter().any(|site| {
                site.phase > 2 || site.local_source_port > 257 || site.current.is_zero()
            })
            || self.returned_factor_current != returned_factor_projection
            || returned_site_total != Ratio::one()
            || self.returned_site_current != returned_complex_shadow
            || self.returned_complex_site_current.is_empty()
            || self.returned_complex_site_current.windows(2).any(|pair| {
                (
                    pair[0].carrier,
                    pair[0].factor,
                    pair[0].phase,
                    pair[0].local_source_port,
                ) >= (
                    pair[1].carrier,
                    pair[1].factor,
                    pair[1].phase,
                    pair[1].local_source_port,
                )
            })
            || self.returned_complex_site_current.iter().any(|site| {
                site.phase > 2
                    || site.local_source_port > 257
                    || site.incidence_coefficient.is_zero()
            })
            || self.returned_phase_denominator.is_zero()
            || self.returned_phase_numerator >= self.returned_phase_denominator
            || !self.source_boundary_total
            || !self.target_boundary_total
            || !self.complete_reconstruction_fibre_retained
            || self.source_codec_consulted
            || self.source_surface_reachable
            || self.identity_sha256 != self.rederived_identity()
        {
            return Err(SourceNeutralRelationalError::Quotient);
        }
        Ok(())
    }

    pub(crate) fn rederived_identity(&self) -> String {
        digest(&(
            (
                self.schema.as_str(),
                self.morphology_identity_sha256.as_str(),
                self.native_section_identity_sha256.as_str(),
                self.native_current_passage_identity_sha256.as_str(),
                self.source_port,
            ),
            (
                &self.factor_current,
                &self.oriented_factor_current,
                &self.native_oriented_faces,
                &self.site_current,
                &self.complex_site_current,
                &self.target_current,
                &self.total_target_current,
                self.entering_realization_current_identity_sha256.as_str(),
                &self.entering_phase_numerator,
                &self.entering_phase_denominator,
            ),
            (
                self.selected_target_port,
                &self.selected_interval_begin,
                &self.selected_interval_end,
                &self.returned_factor_current,
                &self.returned_site_current,
                &self.returned_complex_site_current,
                &self.returned_phase_numerator,
                &self.returned_phase_denominator,
                self.returned_realization_current_identity_sha256.as_str(),
            ),
            (
                self.source_boundary_total,
                self.target_boundary_total,
                self.complete_reconstruction_fibre_retained,
                self.source_codec_consulted,
                self.source_surface_reachable,
            ),
        ))
    }
}

fn gcd_biguint(mut left: BigUint, mut right: BigUint) -> BigUint {
    while !right.is_zero() {
        let remainder = &left % &right;
        left = right;
        right = remainder;
    }
    left
}

fn positive_complex_norm(
    current: &ExactComplexWaveCurrent,
) -> Result<SourceNeutralPositiveCurrent, SourceNeutralRelationalError> {
    let norm = current.norm_square();
    if norm.is_negative() || norm.denom().is_zero() {
        return Err(SourceNeutralRelationalError::Quotient);
    }
    Ok(Ratio::new(
        norm.numer().magnitude().clone(),
        norm.denom().magnitude().clone(),
    ))
}

fn positive_site_shadow(
    complex: &[SourceNeutralExteriorRealizationComplexSiteCurrent],
) -> Result<Vec<SourceNeutralExteriorRealizationSiteCurrent>, SourceNeutralRelationalError> {
    if complex.is_empty()
        || complex.windows(2).any(|pair| {
            (
                pair[0].carrier,
                pair[0].factor,
                pair[0].phase,
                pair[0].local_source_port,
            ) >= (
                pair[1].carrier,
                pair[1].factor,
                pair[1].phase,
                pair[1].local_source_port,
            )
        })
        || complex
            .iter()
            .any(|current| current.incidence_coefficient.is_zero())
    {
        return Err(SourceNeutralRelationalError::Quotient);
    }
    let total = complex.iter().fold(Ratio::zero(), |sum, current| {
        sum + &current.incidence_coefficient
    });
    if total.is_zero() {
        return Err(SourceNeutralRelationalError::Quotient);
    }
    // This is the conserved incidence-mass receiver of an already sorted unique dependent
    // section.  No second junction is needed: rebuilding the same keys through a map formerly
    // turned this linear projection into a costly rescan at every exterior order.
    Ok(complex
        .iter()
        .map(|current| SourceNeutralExteriorRealizationSiteCurrent {
            carrier: current.carrier,
            site: current.site,
            factor: current.factor,
            phase: current.phase,
            local_source_port: current.local_source_port,
            current: &current.incidence_coefficient / &total,
        })
        .collect())
}

fn reduce_fraction(
    numerator: &mut BigUint,
    denominator: &mut BigUint,
) -> Result<(), SourceNeutralRelationalError> {
    if denominator.is_zero() || *numerator >= *denominator {
        return Err(SourceNeutralRelationalError::Quotient);
    }
    let divisor = gcd_biguint(numerator.clone(), denominator.clone());
    if divisor.is_zero() {
        return Err(SourceNeutralRelationalError::Quotient);
    }
    *numerator /= &divisor;
    *denominator /= divisor;
    Ok(())
}

use holonic_engine::is_sha256_digest as is_digest;

fn phase_population(
    populations: &[SourceNeutralPhasePopulation],
    factor: u32,
    phase: u8,
) -> Option<u64> {
    populations
        .binary_search_by_key(&(factor, phase), |population| {
            (population.factor, population.phase)
        })
        .ok()
        .map(|at| populations[at].occurrence_population)
}

pub(super) fn invalid_support(support: &[u32], factor_population: u32) -> bool {
    support.is_empty()
        || support.windows(2).any(|pair| pair[0] >= pair[1])
        || support.iter().any(|factor| *factor >= factor_population)
}

pub(super) fn realization_sites_match_relational(
    sites: &[SourceNeutralExteriorRealizationSite],
    relational: &SourceNeutralRelationalMorphology,
) -> Result<bool, SourceNeutralRelationalError> {
    let expected_population = relational
        .cells
        .iter()
        .try_fold(0_usize, |sum, cell| {
            sum.checked_add(cell.oriented_boundary.len())
        })
        .ok_or(SourceNeutralRelationalError::Extent)?;
    if sites.len() != expected_population {
        return Ok(false);
    }
    for site in sites {
        let Some(cell) = relational.cells.get(site.cell as usize) else {
            return Ok(false);
        };
        let positions = relational_boundary_positions(cell.oriented_boundary.len())?;
        let Some(at) = positions
            .iter()
            .position(|position| *position == site.boundary_position)
        else {
            return Ok(false);
        };
        if cell.oriented_boundary.get(at).copied() != Some(site.face) {
            return Ok(false);
        }
        let Some(face) = relational.faces.get(site.face as usize) else {
            return Ok(false);
        };
        if !face.cell_incidence.iter().any(|incidence| {
            incidence.cell == site.cell
                && incidence.boundary_position == site.boundary_position
                && incidence.incidence_population == site.incidence_population
        }) {
            return Ok(false);
        }
        match (positions.get(at + 1), site.successor_site) {
            (None, None) => {}
            (Some(next_position), Some(successor_at)) => {
                let Some(successor) = sites.get(successor_at as usize) else {
                    return Ok(false);
                };
                if successor.cell != site.cell
                    || successor.boundary_position != *next_position
                    || cell.oriented_boundary.get(at + 1).copied() != Some(successor.face)
                {
                    return Ok(false);
                }
            }
            _ => return Ok(false),
        }
    }
    Ok(true)
}

pub(super) fn relational_boundary_positions(
    boundary_extent: usize,
) -> Result<&'static [u8], SourceNeutralRelationalError> {
    match boundary_extent {
        3 => Ok(&[0, 1, 3]),
        4 => Ok(&[0, 1, 2, 3]),
        _ => Err(SourceNeutralRelationalError::Quotient),
    }
}

pub(super) fn key(value: &impl Serialize) -> Result<Vec<u8>, SourceNeutralRelationalError> {
    serde_json::to_vec(value).map_err(|_| SourceNeutralRelationalError::Extent)
}

pub(super) fn partition(keys: Vec<Vec<u8>>) -> Result<Vec<u32>, SourceNeutralRelationalError> {
    if keys.is_empty() {
        return Err(SourceNeutralRelationalError::Developmental);
    }
    let mut order = (0..keys.len()).collect::<Vec<_>>();
    order.sort_unstable_by(|left, right| keys[*left].cmp(&keys[*right]));
    let mut classes = vec![0_u32; keys.len()];
    let mut class = 0_u32;
    for (at, item) in order.iter().copied().enumerate() {
        if at != 0 && keys[item] != keys[order[at - 1]] {
            class = class
                .checked_add(1)
                .ok_or(SourceNeutralRelationalError::Extent)?;
        }
        classes[item] = class;
    }
    Ok(classes)
}

pub(super) fn canonicalize_partition(
    classes: Vec<u32>,
) -> Result<Vec<u32>, SourceNeutralRelationalError> {
    partition(classes.iter().map(key).collect::<Result<Vec<_>, _>>()?)
}

pub(super) fn same_partition(left: &[u32], right: &[u32]) -> bool {
    if left.len() != right.len() {
        return false;
    }
    let mut mapping = std::collections::BTreeMap::<u32, u32>::new();
    let mut reverse = std::collections::BTreeMap::<u32, u32>::new();
    left.iter()
        .copied()
        .zip(right.iter().copied())
        .all(|(l, r)| {
            mapping.get(&l).is_none_or(|seen| *seen == r)
                && reverse.get(&r).is_none_or(|seen| *seen == l)
                && {
                    mapping.insert(l, r);
                    reverse.insert(r, l);
                    true
                }
        })
}

pub(super) fn face_address(class: u32, face: &SourceNeutralRelationalFace) -> String {
    digest(&(
        "soma-life.source-neutral-relational-face.v1",
        class,
        &face.factor_support,
        &face.phase_population,
        &face.cell_incidence,
    ))
}

pub(super) fn cell_address(class: u32, cell: &SourceNeutralRelationalCell) -> String {
    digest(&(
        "soma-life.source-neutral-relational-cell.v1",
        class,
        &cell.oriented_boundary,
        &cell.factor_support,
        &cell.phase_population,
    ))
}

fn digest(value: &impl Serialize) -> String {
    let bytes = serde_json::to_vec(value).expect("source-neutral relational identity serializes");
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}
