import ElementaryHolonics.Framework.Dynamics
import ElementaryHolonics.Physics.PhaseCarrier
import ElementaryHolonics.Physics.CoupledIncidence
import ElementaryHolonics.Physics.PortEnergyHeat
import ElementaryHolonics.Physics.ScatteringWaveHeat
import ElementaryHolonics.Physics.PhaseContactPassage
import ElementaryHolonics.Physics.ReactionCurrent
import ElementaryHolonics.Physics.ReceiverStressEnergy
import ElementaryHolonics.Physics.MechanicalReceiver
import ElementaryHolonics.Physics.FluidReceiverClosure
import ElementaryHolonics.Physics.ConstitutiveWorldTube
import ElementaryHolonics.Physics.FourTorusParametronCurrent
import ElementaryHolonics.Physics.AccumulatedNormalResponse
import ElementaryHolonics.Physics.InformationDifference
import ElementaryHolonics.Physics.TwoCellEntropyTransport
import ElementaryHolonics.Millennium.HolonicMembraneActionTransport
import ElementaryHolonics.Millennium.HolonicCurvedArcEinstein
import ElementaryHolonics.Millennium.HolonicTypedOriginDimensions
import ElementaryHolonics.Millennium.HolonicCosmologicalInference
import ElementaryHolonics.Millennium.HolonicFourForceSectorCarrier
import ElementaryHolonics.Millennium.HolonicMaxwellPropagation
import ElementaryHolonics.Computation.HolonicQuantumTransport
import ElementaryHolonics.Computation.HolonicPolarizedCrystalTransport
import ElementaryHolonics.Computation.HolonicEvolutionKinds

/-!
# Material, field, quantum, and cosmological charts

[definition] A subject entry point into existing owners. This module adds no axioms or
replacement structures. Each imported result keeps its exact hypotheses and receiver scope.
See `formal/elementary-holonics/README.md` and `docs/FORMAL_FRAMEWORK.md` for the reading path.
Historical declaration namespaces remain stable even where implementation owners were factored.
-/
