#let completed-theta-phase-current-bridge = (
  key: "theorem:completed-theta-phase-current-bridge",
  kind: [Theorem],
  title: [The shifted completed kernel is the Laplace pullback of one theta phase current],
  status: [
    Exact bilateral-Laplace bridge and infinitesimal RH reduction;
    positivity of the source phase-current kernel remains open
  ],
  depends: (
    "theorem:completed-return-flux",
    "theorem:completed-source-seam-regularization",
  ),
  claim: [
    Let
    $
      Xi(z)=xi(1/2+z)
    $
    and normalize the even positive Riemann theta kernel $Phi$ by
    $
      Xi(z)
      =
      c_Phi
      integral_RR Phi(t)e^(z t)dif t,
      quad c_Phi>0.
      quad "(BILATERAL THETA SOURCE)"
    $
    The super-exponential decay of $Phi$ makes this identity and every
    differentiation below absolutely convergent for all complex $z$.

    For $omega>0$ and $op("Re")p,op("Re")q>0$, define the completed
    shifted kernel
    $
      cal(L)_omega(p,q)
      =
      frac(
        Xi(p+omega)overline(Xi(q+omega))
        -
        Xi(p-omega)overline(Xi(q-omega)),
        p+overline(q)
      ).
      quad "(SHIFTED COMPLETED KERNEL)"
    $
    For real $a,b$, put
    $
      m=frac(a+b,2),
      quad
      d=frac(a-b,2),
    $
    and define the coordinate kernel
    $
      cal(D)_omega(a,b)
      =
      2c_Phi^2
      integral_(abs(m))^infinity
      Phi(y+d)Phi(y-d)sinh(2omega y)dif y.
      quad "(SWEPT COORDINATE KERNEL)"
    $
    Then the complete shifted kernel is its exact bilateral-Laplace
    pullback:
    $
      cal(L)_omega(p,q)
      =
      integral_RR integral_RR
      e^(p a)
      cal(D)_omega(a,b)
      e^(overline(q)b)
      dif a dif b.
      quad "(THETA-TO-COMPLETED PULLBACK)"
    $

    The coordinate kernel is generated by one source-native phase current.
    For $eta>=0$, define
    $
      cal(P)_eta(a,b)
      =
      frac(c_Phi^2,2)
      integral_(abs(m))^infinity
      y cosh(2eta y)
      Phi(y+d)Phi(y-d)
      dif y.
      quad "(THETA PHASE CURRENT)"
    $
    Then
    $
      partial_eta cal(D)_eta=8cal(P)_eta,
      quad
      cal(D)_0=0,
      quad
      cal(D)_omega
      =
      8integral_0^omega cal(P)_eta dif eta.
      quad "(NORMAL SWEEP)"
    $
    Consequently, positivity of $cal(P)_eta$ as a kernel for
    $0<=eta<=omega$ implies positivity of $cal(L)_omega$.  This implication
    uses no zero locations and no analytically continued Euler split.

    More sharply, the seam current alone carries the complete RH sign.  Put
    $
      cal(M)(p,q)
      =
      lim_(omega arrow.r 0^+)
      frac(cal(L)_omega(p,q),2omega).
    $
    Then
    $
      cal(M)(p,q)
      =
      frac(
        Xi'(p)overline(Xi(q))
        +
        Xi(p)overline(Xi'(q)),
        p+overline(q)
      )
      quad "(INFINITESIMAL COMPLETED KERNEL)"
    $
    and
    $
      cal(M)(p,q)
      =
      4integral_RR integral_RR
      e^(p a)
      cal(P)_0(a,b)
      e^(overline(q)b)
      dif a dif b.
      quad "(INFINITESIMAL SOURCE PULLBACK)"
    $
    Thus the following are equivalent:

    - RH;
    - $cal(M)$ is a positive-semidefinite kernel on the right half-plane;
    - $cal(P)_0$ is nonnegative on the receiver span generated by the
      bilateral exponentials $a mapsto e^(p a)$,
      $op("Re")p>0$.

    Positivity of $cal(P)_0$ on a larger closed function space is a
    sufficient strengthening, not an additional RH requirement.
  ],
  proof: [
    The half-plane Cauchy kernel has the causal representation
    $
      frac(1,p+overline(q))
      =
      integral_0^infinity
      e^(-(p+overline(q))r)
      dif r.
    $
    Substitute ("BILATERAL THETA SOURCE") into the numerator of
    ("SHIFTED COMPLETED KERNEL").  Its two orientations differ by
    $
      e^(omega(t+u))-e^(-omega(t+u))
      =
      2sinh(omega(t+u)).
    $
    After inserting the causal integral, set
    $
      a=t-r,
      quad b=u-r.
    $
    The coefficient of $e^(p a+overline(q)b)$ is
    $
      2c_Phi^2
      integral_0^infinity
      Phi(a+r)Phi(b+r)
      sinh(omega(a+b+2r))
      dif r.
    $
    With $y=m+r$, this is the integral from $m$ to infinity of
    $
      2c_Phi^2
      Phi(y+d)Phi(y-d)sinh(2omega y).
    $
    The product of the two theta faces is even in $y$, while $sinh(2omega
    y)$ is odd.  If $m<0$, the integral over $[m,-m]$ therefore vanishes.
    The lower boundary is consequently $abs(m)$ for either orientation.
    This proves ("SWEPT COORDINATE KERNEL") and
    ("THETA-TO-COMPLETED PULLBACK").

    Differentiation under the absolutely convergent integral gives
    $
      partial_eta cal(D)_eta(a,b)
      =
      4c_Phi^2
      integral_(abs(m))^infinity
      y cosh(2eta y)
      Phi(y+d)Phi(y-d)
      dif y
      =
      8cal(P)_eta(a,b).
    $
    Since the hyperbolic sine vanishes at $eta=0$, integration in $eta$
    proves ("NORMAL SWEEP").  Positive kernels remain positive under
    positive integration and under pullback, proving the first consequence.

    Differentiating the analytic numerator at $omega=0$ proves
    ("INFINITESIMAL COMPLETED KERNEL").  Dividing ("NORMAL SWEEP") by
    $2omega$ and taking the limit proves
    ("INFINITESIMAL SOURCE PULLBACK").

    Away from zeros, put $F=Xi'/Xi$.  Then
    $
      cal(M)(p,q)
      =
      Xi(p)overline(Xi(q))
      frac(
        F(p)+overline(F(q)),
        p+overline(q)
      ).
    $
    Under RH, `theorem:completed-return-flux` makes $F$ positive real.
    The positive-real kernel in the last display is positive semidefinite,
    and multiplication by $Xi(p)overline(Xi(q))$ is a congruence.  Hence
    $cal(M)>=0$.

    Conversely, on the diagonal $p=x+i y$,
    $
      cal(M)(p,p)
      =
      frac(
        abs(Xi(p))^2,
        x
      )
      op("Re")F(p).
      quad "(NORMAL PHASE ENERGY)"
    $
    A zero $rho$ of order $k$ in the open right half-plane would give,
    along $p=rho+epsilon$ with real $epsilon$,
    $
      cal(M)(p,p)
      tilde.op
      frac(
        k abs(c)^2,
        op("Re")rho
      )
      abs(epsilon)^(2k-2)epsilon,
    $
    where $Xi(p)=c epsilon^k+O(epsilon^(k+1))$.  This changes sign across
    the zero while both nearby points remain in the half-plane, contradicting
    positivity.  Thus $Xi$ is zero-free there, and ("NORMAL PHASE ENERGY")
    gives $op("Re")F>=0$.  The positive-real equivalence in
    `theorem:completed-return-flux` now gives RH.  Finally,
    ("INFINITESIMAL SOURCE PULLBACK") identifies positivity of $cal(M)$ with
    positivity of $cal(P)_0$ on the declared exponential receiver span.
  ],
  boundary: [
    This theorem replaces the unnecessarily large demand for an independently
    guessed Gram of every finite shift.  One exact source kernel remains:
    $
      cal(P)_0(a,b)
      =
      frac(c_Phi^2,2)
      integral_(abs((a+b)/2))^infinity
      y
      Phi(y+(a-b)/2)
      Phi(y-(a-b)/2)
      dif y.
      quad "(OPEN PHASE-CURRENT SIGN)"
    $
    Proving its nonnegativity on the exponential receiver span proves RH.
    Proving it on the whole coordinate space is a stronger sufficient
    theorem.

    Pointwise positivity of $Phi$ does not prove this sign.  The two theta
    factors are coupled through the difference coordinate, while the moving
    lower boundary is set by the sum coordinate.  A fixed-$y$ layer is not a
    rank-one square, and separating those coordinates discards the crossing
    which the kernel measures.  The required sign belongs to the integrated
    phase current.

    The same coordinate kernel, with the same $y cosh(2eta y)$ weight, is
    studied as a Weyl kernel in @freedman2026weyl.  That preprint records
    exact Volterra reductions and computational evidence but explicitly
    leaves its original all-parameter positivity and the RH-facing bridge
    open.  ("THETA-TO-COMPLETED PULLBACK") supplies the latter bridge at the
    level needed here; it does not supply the still-open sign of
    ("OPEN PHASE-CURRENT SIGN").
  ],
)
