#let knot-presentation-sameness = (
  key: "theorem:knot-presentation-sameness",
  kind: [Theorem],
  title: [Diagram, braid, closure, and prime-factor sameness are generated by different laws],
  status: [Classical synthesis: Reidemeister, Alexander, Markov, and Schubert],
  depends: (
    "definition:situated-knot-receiver",
    "definition:causal-soul",
  ),
  claim: [
    For tame oriented links in $S^3$:

    + two received link diagrams present ambient-isotopic links exactly when
      they are related by planar isotopy and finitely many Reidemeister
      moves;
    + every oriented link is the closure $hat(beta)$ of some braid
      $beta in B_n$;
    + two braids have ambient-isotopic oriented closures exactly when they
      are related by braid isotopy together with Markov stabilization and
      destabilization; in algebraic notation this includes conjugation
      $beta mapsto alpha beta alpha^(-1)$ and
      $beta in B_n mapsto beta sigma_n^(plus.minus 1) in B_(n+1)$; and
    + under connected sum, oriented knot types form a commutative monoid
      whose unit is the unknot and whose nonunit elements factor uniquely,
      up to ordering, into prime knots.

    Consequently a diagram, a braid word, a closed-link type, and a
    connected-sum factorization are presentations at different categorical
    levels.  No move theorem at one level identifies the complete data at
    another.
  ],
  proof: [
    The four clauses are the classical Reidemeister, Alexander, Markov, and
    Schubert theorems, respectively.  Their conjunction gives the stated
    hierarchy.  Reidemeister moves preserve a closure type while changing a
    diagram.  Alexander's theorem supplies braid presentations but not
    uniqueness.  Markov's theorem generates precisely the extra equivalence
    introduced by closure.  Schubert's theorem concerns the separate
    connected-sum monoid.
  ],
  boundary: [
    A prime knot is irreducible under connected sum; it is not a knot which
    cannot be changed into the unknot by crossing changes.  Every knot has a
    finite unknotting sequence, while a nontrivial knot cannot become the
    unknot through Reidemeister moves alone because those moves preserve its
    ambient-isotopy class.  None of the four theorems makes crossing number,
    unknotting number, runtime, or another cost additive over prime factors.
  ],
)
