#import "schema.typ": entry

#let algorithms = (
  entry(
    id: "H.0100",
    kind: "Definition",
    grade: "definition",
    title: [Situated parameterized algorithm],
    depends: ("H.0010", "H.0011", "H.0012", "H.0018"),
    statement: [
      A situated algorithm is
      $
        cal(A)
        =
        (Theta,I,S,O,iota,delta,omega,rho),
      $
      where $Theta$ is a parameter type; $I_theta,S_theta,O_theta$ are
      input, state, and output fibers;
      $
        iota_theta subset.eq I_theta times S_theta,
        quad
        delta_theta subset.eq S_theta times S_theta,
      $
      admit initialization and one transition;
      $omega_theta subset.eq S_theta$ marks completion; and
      $
        rho_theta subset.eq S_theta times O_theta
      $
      is the output receiver.
    ],
    receiver: [
      The ordinary input/output relation is derived from executions and
      $rho_theta$; it is not the complete identity of $cal(A)$.
    ],
    boundary: [
      Determinism, totality, termination, computability, reversibility, and
      complexity are separate predicates, not parts of the word “algorithm.”
    ],
    source: [
      Laboratory synthesis of transition systems, open systems, and receiver
      semantics.
    ],
  ),
  entry(
    id: "H.0101",
    kind: "Definition",
    grade: "definition",
    title: [Execution path and trace category],
    depends: ("H.0100",),
    statement: [
      At $theta$, an execution path is a finite word
      $
        s_0 arrow.r s_1 arrow.r dots.c arrow.r s_n
      $
      with $delta_theta(s_k,s_(k+1))$ for every $k<n$. Length-zero paths are
      identities; concatenation of paths is associative. These paths form the
      free category generated by the transition quiver $delta_theta$.
    ],
    derivation: [
      Concatenation is list concatenation with the common endpoint identified.
      List associativity proves categorical associativity; the singleton
      endpoint path gives each identity.
    ],
    transformations: [
      A path retains ordered interior occurrences. Relational composition
      retains only existence of some interior witness.
    ],
    boundary: [
      A trace is not automatically a physical chronology. Its order is the
      algorithm's declared transition order.
    ],
    source: [Standard free-category construction.],
  ),
  entry(
    id: "H.0102",
    kind: "Definition",
    grade: "definition",
    title: [Extensional semantics],
    depends: ("H.0100", "H.0101"),
    statement: [
      The extensional semantics of $cal(A)$ at $theta$ is
      $
        bracket.l cal(A) bracket.r_theta(i,o)
        arrow.l.r
        exists s_0,s_n:
        iota_theta(i,s_0)
        and
        s_0 delta_theta^* s_n
        and
        omega_theta(s_n)
        and
        rho_theta(s_n,o),
      $
      where $delta_theta^*$ is reflexive-transitive closure.
    ],
    boundary: [
      Equal extensional semantics does not imply equal executions, resource
      costs, reversible interiors, or causal attribution.
    ],
    source: [Standard operational-to-relational semantics.],
  ),
  entry(
    id: "H.0103",
    kind: "Theorem",
    grade: "proved-derived",
    title: [Functional face of a deterministic terminating algorithm],
    depends: ("H.0100", "H.0102"),
    statement: [
      If initialization, transition, and observation are single-valued; every
      initialized execution terminates; and completed states do not transition,
      then $bracket.l cal(A) bracket.r_theta$ is the graph of a partial
      function $I_theta arrow.r O_theta$. It is total when every input
      initializes and completes.
    ],
    derivation: [
      Single-valued initialization fixes $s_0$. Inductively, single-valued
      $delta_theta$ fixes every reachable successor. Termination supplies a
      completed $s_n$; terminality prevents a competing later completion; and
      single-valued $rho_theta$ fixes $o$.
    ],
    boundary: [
      The theorem derives a function face; it does not identify the algorithm
      with that function.
    ],
    source: [Elementary transition-system derivation.],
  ),
  entry(
    id: "H.0104",
    kind: "Definition",
    grade: "definition",
    title: [Lambda],
    depends: ("H.0100", "H.0101", "H.0102"),
    statement: [
      Choose typed ingress and egress boundary receivers
      $
        beta^-_theta : I_theta times S_theta arrow.r B^-_theta,
        quad
        beta^+_theta : "Path"(cal(A)_theta) arrow.r B^+_theta.
      $
      The boundary correspondence
      $
        Lambda_(cal(A),theta)^(beta^-,beta^+)
        subset.eq
        B^-_theta times B^+_theta
      $
      relates $b^-$ to $b^+$ exactly when an admitted execution begins at an
      initialized occurrence presented by $b^-$ and returns a path face
      presented by $b^+$. One-step, completed, and open-system Lambdas are
      explicit choices of path class and boundary receivers, not implicit
      changes in the symbol.
    ],
    transformations: [
      Changing $theta$ may change state fibers, admitted transitions,
      completion, or receiver. Such change is lawful only with explicit
      transport between the affected fibers. The historical expression
      $Lambda_F(Q ⊗ A ⊗ L) mapsto (P,pi_B)$ is one typed
      specialization when those boundary factors and their maps are supplied;
      it does not fix the general definition.
    ],
    boundary: [
      The symbol alone asserts no determinism, universality, optimization, or
      physical law. Omitting $cal(A),theta,beta^-,beta^+$ leaves an
      under-specified relation.
    ],
    source: [Derived from H.0100--H.0102; laboratory Lambda correction.],
  ),
  entry(
    id: "H.0105",
    kind: "Theorem",
    grade: "proved-derived",
    title: [Sequential composition],
    depends: ("H.0100", "H.0101", "H.0102"),
    statement: [
      Let $cal(A) : I arrow.r O$ and $cal(B) : O arrow.r P$ be situated
      algorithms whose exposed .local/artifacts/input boundary types agree. Gluing a
      completed $cal(A)$ path to an initialized $cal(B)$ path gives
      $
        bracket.l cal(B) circle cal(A) bracket.r
        =
        bracket.l cal(B) bracket.r
        circle
        bracket.l cal(A) bracket.r.
      $
    ],
    derivation: [
      Expand both sides. Each side is exactly the assertion that there exists
      an intermediate $o$ and an $cal(A)$ path ending at $o$ followed by an
      $cal(B)$ path beginning at $o$. Associativity is reassociation of the
      witnesses and path concatenation.
    ],
    transformations: [
      Sequential gluing shares one typed boundary. Monoidal co-presence instead
      forms a product/tensor state and does not impose temporal succession.
    ],
    boundary: [
      A merely equal serialized output is not a typed gluing boundary unless
      its identification map is supplied.
    ],
    source: [Relational composition and free-path concatenation.],
  ),
  entry(
    id: "H.0106",
    kind: "Theorem",
    grade: "proved-derived",
    title: [Invertible rebase is execution conjugacy],
    depends: ("H.0100", "H.0101", "H.0102"),
    statement: [
      Let $phi_theta : S_theta arrow.r S'_theta$ be a bijection and define
      $
        delta'_theta
        =
        phi_theta circle delta_theta circle phi_theta^(-1).
      $
      Transport initialization, completion, and receiver along $phi_theta$.
      Then
      $
        (s_0 arrow.r dots.c arrow.r s_n)
        mapsto
        (phi s_0 arrow.r dots.c arrow.r phi s_n)
      $
      is a length-preserving bijection of executions, and the extensional
      semantics is unchanged after the corresponding boundary rechart.
    ],
    derivation: [
      For each edge,
      $
        delta_theta(s_k,s_(k+1))
        arrow.l.r
        delta'_theta(phi s_k,phi s_(k+1))
      $
      by the definition of conjugacy. Apply this edgewise; $phi^(-1)$ gives the
      inverse path map. The transported boundary relations make the endpoint
      semantics commute.
    ],
    transformations: [
      State rebase is conjugacy. Integral change of variables additionally
      transports measure by a Jacobian and is treated separately.
    ],
    boundary: [
      A noninvertible map is not a rebase. It is a quotient, abstraction, or
      simulation and may erase paths.
    ],
    source: [Elementary conjugacy theorem.],
  ),
  entry(
    id: "H.0107",
    kind: "Theorem",
    grade: "proved-derived",
    title: [Receiver-exact algorithm quotient],
    depends: ("H.0016", "H.0100", "H.0102"),
    statement: [
      Let $q : S arrow.r Q$ be surjective. Suppose:
      (i) initialization factors through $q$;
      (ii) whenever $q(s)=q(t)$, every step from $s$ and $t$ has the same
      set of $q$-successor classes;
      (iii) completion is constant on $q$-fibers; and
      (iv) every future receiver factors through $q$.
      Then the quotient transition system has exactly the same extensional
      semantics for those receivers.
    ],
    derivation: [
      Map each source execution through $q$ to obtain a quotient execution.
      Conversely, lift quotient edges successively using (ii), beginning with
      an initialized representative from (i). Conditions (iii) and (iv)
      preserve completion and observation. Thus both semantic relations include
      each other.
    ],
    transformations: [
      This is the algorithmic form of receiver-exact compression. Bisimulation
      is a common sufficient carrier for condition (ii).
    ],
    boundary: [
      If only forward simulation is known, one obtains semantic inclusion, not
      equality. New receivers may invalidate the quotient.
    ],
    source: [Standard quotient/bisimulation argument with holonic receiver boundary.],
  ),
  entry(
    id: "H.0108",
    kind: "Definition",
    grade: "definition",
    title: [Recursion, iteration, and corecursion],
    depends: ("H.0100", "H.0101"),
    statement: [
      Well-founded recursion defines $f(x)$ from values $f(y)$ on a relation
      $y prec x$ admitting no infinite descending chain. Iteration is the orbit
      $
        x_(n+1)=T(x_n).
      $
      Corecursion defines an observable stream by repeatedly exposing one
      output and one successor state.
    ],
    transformations: [
      Each construction is an algorithmic path species. A recursive call graph,
      an orbit, and a generated stream can share a receiver value without being
      the same transition system.
    ],
    boundary: [
      A self-referential equation is not a recursion theorem until existence,
      uniqueness, or productivity is established.
    ],
    source: [Standard recursion and coalgebraic definitions.],
  ),
  entry(
    id: "H.0109",
    kind: "Definition",
    grade: "definition",
    title: [Series as execution lineage and receiver],
    depends: ("H.0108", "H.0017"),
    statement: [
      Given terms $a_n$ in an additive topological object, define partial states
      $
        S_0=0,
        quad
        S_(n+1)=S_n+a_n.
      $
      The finite series is the execution lineage $(S_n)$. An infinite sum
      $sum_(n=0)^infinity a_n=L$ means $S_n arrow.r L$ in a declared topology
      and receiver.
    ],
    transformations: [
      A generating function
      $
        G(z)=sum_(n>=0) a_n z^n
      $
      is a receiver of the coefficient lineage. It does not erase the recurrence
      unless its domain and inversion law are retained.
    ],
    boundary: [
      The glyph $L$ is not the series interior. Rearrangement, analytic
      continuation, and summability methods require their own hypotheses.
    ],
    source: [Standard series definition with laboratory lineage interpretation.],
  ),
  entry(
    id: "H.0110",
    kind: "Definition",
    grade: "definition",
    title: [Effective computational algorithm],
    depends: ("H.0100", "H.0103"),
    statement: [
      A computational algorithm is a situated algorithm with finitely or
      effectively presented state encodings and transition/receiver relations,
      together with a proved refinement from an executable implementation to
      the abstract semantics.
    ],
    receiver: [
      Source code, bytecode, circuits, and machine traces are distinct
      presentations connected by compiler, assembler, and hardware refinement
      maps.
    ],
    boundary: [
      Church--Turing is a thesis identifying effectively calculable numerical
      functions with a formal class such as Turing-computable functions. It is
      not derived merely by defining $cal(A)$.
    ],
    source: [Standard semantics/refinement boundary.],
  ),
  entry(
    id: "H.0111",
    kind: "Definition",
    grade: "definition",
    title: [Relative universal evaluator],
    depends: ("H.0110",),
    statement: [
      For an encoding $op("enc") : cal(C) arrow.r E$ of a class of algorithms and
      inputs, a universal evaluator $U$ satisfies
      $
        U(op("enc")(A,x)) = bracket.l A bracket.r(x)
      $
      wherever $A$ terminates. Universality is relative to $cal C$, its
      encoding, and the evaluator's operational semantics.
    ],
    boundary: [
      No finite evaluator is an absolute carrier of every mathematical
      transformation without a declared coding relation.
    ],
    source: [Standard universal-machine definition.],
  ),
)
