import Holonics.HNN.Moment

/-!
# Capacity of the source moment on an admitted ranged clock

The located source steps by a digit below the ring period plus its predecessor's carry.
The Boolean-fit clock in `HNN/Moment` is the identity specialization; its two-tick bound
does not bound arbitrary located digits. This file joins the actual digit/carry law to
the same source-state carrier, bin totals, offset totals and held-cell partition.

`capacityBoundWith rate` replaces only the lift factor by `rate g * n + period g`.
`rate = 2` recovers the existing identity count; `rate = period` admits every located
digit, including changes between admitted charts. The clock law and the capacity bound
are independent of the values generated by a terrain. Capacity is a source-state bound,
not a bound on learned constitutions, and the pigeonhole claim requires a total source
map on the declared alphabet's full `A^n`, not a restricted terrain family.

One opening, no re-key, a fixed alphabet and closing source rings. A stopping ingest
consumes a prefix: the count uses that prefix's length, never the requested suffix.
Formal checking of this new leaf is pending in the implementation receipt.
-/

noncomputable section

namespace Holonics.HNN.Moment

/-- The admitted digits of the actual located clock. Every digit fits its own ring. -/
structure RangedClock (A : Type*) (period : ℕ → ℕ) where
  digit : ℕ → A → ℕ
  digit_lt : ∀ g a, digit g a < period g

namespace RangedClock

variable {A : Type*} {period : ℕ → ℕ} (C : RangedClock A period)

/-- The predecessor's exact winding increment; ring zero receives no carry. -/
def carryIn (a : A) (τ : ℕ → ℕ) : ℕ → ℕ
  | 0 => 0
  | g + 1 => (τ g + C.digit g a + carryIn a τ g) / period g - τ g / period g

def advance (a : A) (τ : ℕ → ℕ) : ℕ → ℕ :=
  fun g => τ g + C.digit g a + C.carryIn a τ g

theorem carryIn_succ_eq_phase (a : A) (τ : ℕ → ℕ) (g : ℕ) :
    C.carryIn a τ (g + 1) =
      (τ g % period g + (C.digit g a + C.carryIn a τ g)) / period g := by
  rw [carryIn, ← SelectiveDecl.wraps_eq_phase, add_assoc]

/-- A digit below `d` plus one incoming carry crosses at most one ring section. -/
theorem carryIn_le_one (a : A) (τ : ℕ → ℕ) : ∀ g, C.carryIn a τ g ≤ 1
  | 0 => by simp [carryIn]
  | g + 1 => by
      rw [carryIn_succ_eq_phase]
      have hc := carryIn_le_one a τ g
      have hs := C.digit_lt g a
      have hd : 0 < period g := by omega
      have hm := Nat.mod_lt (τ g) hd
      rw [Nat.div_le_iff_le_mul_add_pred hd]
      omega

/-- The actual per-cell lift bound, with no two-tick assumption. -/
theorem advance_range (a : A) (τ : ℕ → ℕ) (g : ℕ) :
    τ g ≤ C.advance a τ g ∧ C.advance a τ g ≤ τ g + period g := by
  have hc := C.carryIn_le_one a τ g
  have hs := C.digit_lt g a
  unfold advance
  omega

end RangedClock

namespace SourceDecl

variable {A : Type*} (D : SourceDecl A)

/-- The existing source-state ingest with its lift update made explicit. Counts are placed
at the executed resulting phase; the offset uses the held preceding cell, exactly as in `ingest`.
There is one state carrier, `StreamState`, and no per-occurrence retained state. -/
def ingestWith (advance : A → (ℕ → ℕ) → (ℕ → ℕ)) (a : A) (s : D.StreamState) :
    D.StreamState :=
  { lift := advance a s.lift
    bins := fun g => if g ∈ D.sources then
        ((advance a s.lift g : ZMod (D.period g)), a) ::ₘ s.bins g else s.bins g
    pairBins := fun g δ => if g ∈ D.sources ∧ δ ∈ D.offsets then
        (s.window[δ - 1]?).elim (s.pairBins g δ)
          (fun b => ((advance a s.lift g : ZMod (D.period g)), a, b) ::ₘ s.pairBins g δ)
      else s.pairBins g δ
    window := (a :: s.window).take D.windowLength }

def streamWith (advance : A → (ℕ → ℕ) → (ℕ → ℕ)) (τ₀ : ℕ → ℕ) (l : List A) :
    D.StreamState := l.foldl (fun s a => D.ingestWith advance a s) (D.initial τ₀)

/-- The generalized book-keeping is literally the existing identity owner. -/
theorem ingestWith_identity (a : A) (s : D.StreamState) :
    D.ingestWith D.advance a s = ingest a s := rfl

theorem streamWith_identity (τ₀ : ℕ → ℕ) (l : List A) :
    D.streamWith D.advance τ₀ l = D.stream τ₀ l := rfl

variable {D} (advance : A → (ℕ → ℕ) → (ℕ → ℕ))

theorem streamWith_append_one (τ₀ : ℕ → ℕ) (l : List A) (a : A) :
    D.streamWith advance τ₀ (l ++ [a]) = D.ingestWith advance a (D.streamWith advance τ₀ l) := by
  simp [streamWith, List.foldl_append]

theorem streamWith_window (τ₀ : ℕ → ℕ) (l : List A) :
    (D.streamWith advance τ₀ l).window = l.reverse.take D.windowLength := by
  induction l using List.reverseRecOn with
  | nil => simp [streamWith, initial]
  | append_singleton l a ih =>
      rw [streamWith_append_one]
      change (a :: (D.streamWith advance τ₀ l).window).take D.windowLength = _
      rw [ih, List.reverse_append, List.reverse_singleton, List.singleton_append]
      cases D.windowLength with
      | zero => simp
      | succ m => simp [List.take_take]

/-- The bin total depends on consumed cells, not on their clock's digit sizes. -/
theorem streamWith_card_bins (τ₀ : ℕ → ℕ) {g : ℕ} (hg : g ∈ D.sources) (l : List A) :
    Multiset.card ((D.streamWith advance τ₀ l).bins g) = l.length := by
  induction l using List.reverseRecOn with
  | nil => simp [streamWith, initial]
  | append_singleton l a ih =>
      rw [streamWith_append_one]
      change Multiset.card (if g ∈ D.sources then
        ((advance a (D.streamWith advance τ₀ l).lift g : ZMod (D.period g)), a) ::ₘ
          (D.streamWith advance τ₀ l).bins g
        else (D.streamWith advance τ₀ l).bins g) = _
      rw [if_pos hg, Multiset.card_cons, ih, List.length_append, List.length_singleton]

/-- An offset is still a count of preceding cells; a carry never invents an offset pair. -/
theorem streamWith_card_pairBins (τ₀ : ℕ → ℕ) {g δ : ℕ} (hg : g ∈ D.sources)
    (hδ : δ ∈ D.offsets) (hδpos : 1 ≤ δ) (l : List A) :
    Multiset.card ((D.streamWith advance τ₀ l).pairBins g δ) = l.length - δ := by
  have hδW : δ ≤ D.windowLength := Finset.le_sup (f := id) hδ
  induction l using List.reverseRecOn with
  | nil => simp [streamWith, initial]
  | append_singleton l a ih =>
      rw [streamWith_append_one]
      change Multiset.card (if g ∈ D.sources ∧ δ ∈ D.offsets then
        ((D.streamWith advance τ₀ l).window[δ - 1]?).elim
          ((D.streamWith advance τ₀ l).pairBins g δ)
          (fun b => ((advance a (D.streamWith advance τ₀ l).lift g : ZMod (D.period g)), a, b) ::ₘ
            (D.streamWith advance τ₀ l).pairBins g δ)
        else (D.streamWith advance τ₀ l).pairBins g δ) = _
      rw [if_pos ⟨hg, hδ⟩, streamWith_window, List.length_append, List.length_singleton]
      by_cases hl : δ ≤ l.length
      · have hlt : δ - 1 < (l.reverse.take D.windowLength).length := by
          simp only [List.length_take, List.length_reverse]
          omega
        rw [List.getElem?_eq_getElem hlt, Option.elim_some, Multiset.card_cons, ih]
        omega
      · have hnone : (l.reverse.take D.windowLength)[δ - 1]? = none := by
          rw [List.getElem?_eq_none_iff]
          simp only [List.length_take, List.length_reverse]
          omega
        rw [hnone, Option.elim_none, ih]
        omega

theorem streamWith_lift_range (rate : ℕ → ℕ)
    (hrange : ∀ a τ g, τ g ≤ advance a τ g ∧ advance a τ g ≤ τ g + rate g)
    (τ₀ : ℕ → ℕ) (l : List A) (g : ℕ) :
    τ₀ g ≤ (D.streamWith advance τ₀ l).lift g ∧
      (D.streamWith advance τ₀ l).lift g ≤ τ₀ g + rate g * l.length := by
  induction l using List.reverseRecOn with
  | nil => simp [streamWith, initial]
  | append_singleton l a ih =>
      rw [streamWith_append_one]
      change τ₀ g ≤ advance a (D.streamWith advance τ₀ l).lift g ∧
        advance a (D.streamWith advance τ₀ l).lift g ≤ τ₀ g + rate g * (l ++ [a]).length
      have h := hrange a (D.streamWith advance τ₀ l).lift g
      simp only [List.length_append, List.length_singleton, Nat.mul_add, Nat.mul_one]
      omega

variable [Fintype A] [DecidableEq A] [hne : ∀ g, NeZero (D.period g)]
variable (D)

def boxWith (rate τ₀ : ℕ → ℕ) (G n : ℕ) : Finset (D.Persist G) :=
  Fintype.piFinset (fun g : Fin G => Finset.Icc (τ₀ g) (τ₀ g + rate g * n)) ×ˢ
    Fintype.piFinset (fun g : D.sources => (Finset.univ : Finset (Sym (ZMod (D.period g.1) × A) n)).map
      ⟨Sym.toMultiset, Sym.coe_injective⟩) ×ˢ
    Fintype.piFinset (fun p : D.sources × D.offsets =>
      (Finset.univ : Finset (Sym (ZMod (D.period p.1.1) × A × A) (n - p.2.1))).map
        ⟨Sym.toMultiset, Sym.coe_injective⟩) ×ˢ
    (Finset.univ : Finset (List.Vector A (min n D.windowLength))).map
      ⟨List.Vector.toList, List.Vector.toList_injective⟩

def capacityBoundWith (rate : ℕ → ℕ) (G alphabet n : ℕ) : ℕ :=
  alphabet ^ D.windowLength * (∏ g ∈ Finset.range G, (rate g * n + D.period g)) *
    ∏ g ∈ D.sources, (Nat.choose (n + D.period g * alphabet - 1) (D.period g * alphabet - 1) *
      ∏ δ ∈ D.offsets,
        Nat.choose (n - δ + D.period g * alphabet ^ 2 - 1) (D.period g * alphabet ^ 2 - 1))

theorem boxWith_identity (τ₀ : ℕ → ℕ) (G n : ℕ) :
    D.boxWith (fun _ => 2) τ₀ G n = D.box τ₀ G n := rfl

theorem capacityBoundWith_identity (G alphabet n : ℕ) :
    D.capacityBoundWith (fun _ => 2) G alphabet n = D.capacityBound G alphabet n := rfl

variable {D}

theorem persist_mem_boxWith (rate : ℕ → ℕ)
    (hrange : ∀ a τ g, τ g ≤ advance a τ g ∧ advance a τ g ≤ τ g + rate g)
    (hδpos : ∀ δ ∈ D.offsets, 1 ≤ δ) (τ₀ : ℕ → ℕ) (G : ℕ) (l : List A) :
    D.persist G (D.streamWith advance τ₀ l) ∈ D.boxWith rate τ₀ G l.length := by
  refine Finset.mem_product.mpr ⟨Fintype.mem_piFinset.mpr fun g => ?_,
    Finset.mem_product.mpr ⟨Fintype.mem_piFinset.mpr fun g => ?_,
      Finset.mem_product.mpr ⟨Fintype.mem_piFinset.mpr fun p => ?_, ?_⟩⟩⟩
  · show (D.streamWith advance τ₀ l).lift g ∈ _
    rw [Finset.mem_Icc]
    exact streamWith_lift_range advance rate hrange τ₀ l g
  · exact Finset.mem_map.mpr ⟨⟨(D.streamWith advance τ₀ l).bins g.1,
      streamWith_card_bins advance τ₀ g.2 l⟩, Finset.mem_univ _, rfl⟩
  · exact Finset.mem_map.mpr ⟨⟨(D.streamWith advance τ₀ l).pairBins p.1.1 p.2.1,
      streamWith_card_pairBins advance τ₀ p.1.2 p.2.2 (hδpos _ p.2.2) l⟩,
      Finset.mem_univ _, rfl⟩
  · refine Finset.mem_map.mpr ⟨(⟨(D.streamWith advance τ₀ l).window, ?_⟩ :
      List.Vector A (min l.length D.windowLength)), Finset.mem_univ _, rfl⟩
    rw [streamWith_window, List.length_take, List.length_reverse, min_comm]

theorem card_boxWith_le [Nonempty A] (rate τ₀ : ℕ → ℕ) (G n : ℕ) :
    (D.boxWith rate τ₀ G n).card ≤ D.capacityBoundWith rate G (Fintype.card A) n := by
  have hA : 1 ≤ Fintype.card A := Fintype.card_pos
  have hdpos : ∀ g, 1 ≤ D.period g := fun g => Nat.pos_of_ne_zero (hne g).out
  have hcard : (D.boxWith rate τ₀ G n).card =
      (∏ g : Fin G, (τ₀ g + rate g * n + 1 - τ₀ g)) *
      ((∏ g : D.sources, Nat.multichoose (D.period g.1 * Fintype.card A) n) *
        ((∏ p : D.sources × D.offsets,
          Nat.multichoose (D.period p.1.1 * Fintype.card A ^ 2) (n - p.2.1)) *
          Fintype.card A ^ min n D.windowLength)) := by
    rw [boxWith, Finset.card_product, Finset.card_product, Finset.card_product,
      Fintype.card_piFinset, Fintype.card_piFinset, Fintype.card_piFinset, Finset.card_map,
      Finset.card_univ, card_vector]
    simp only [Finset.card_map, Finset.card_univ, Nat.card_Icc, Sym.card_sym_eq_multichoose,
      card_slots, card_pairSlots]
  have hlift : (∏ g : Fin G, (τ₀ g + rate g * n + 1 - τ₀ g)) ≤
      ∏ g ∈ Finset.range G, (rate g * n + D.period g) := by
    rw [← Fin.prod_univ_eq_prod_range]
    exact Finset.prod_le_prod' fun g _ => by have := hdpos g; omega
  have hwin : Fintype.card A ^ min n D.windowLength ≤ Fintype.card A ^ D.windowLength :=
    Nat.pow_le_pow_right hA (min_le_right _ _)
  have hsrc : (∏ g : D.sources, Nat.multichoose (D.period g.1 * Fintype.card A) n) *
      (∏ p : D.sources × D.offsets,
        Nat.multichoose (D.period p.1.1 * Fintype.card A ^ 2) (n - p.2.1)) =
      ∏ g ∈ D.sources, (Nat.choose (n + D.period g * Fintype.card A - 1)
        (D.period g * Fintype.card A - 1) *
        ∏ δ ∈ D.offsets, Nat.choose (n - δ + D.period g * Fintype.card A ^ 2 - 1)
          (D.period g * Fintype.card A ^ 2 - 1)) := by
    rw [Fintype.prod_prod_type, ← Finset.prod_mul_distrib, ← Finset.prod_coe_sort D.sources]
    refine Finset.prod_congr rfl fun g _ => ?_
    have h1 : 1 ≤ D.period g.1 * Fintype.card A := Nat.one_le_iff_ne_zero.mpr
      (Nat.mul_ne_zero (hne g.1).out (by omega))
    have h2 : 1 ≤ D.period g.1 * Fintype.card A ^ 2 := Nat.one_le_iff_ne_zero.mpr
      (Nat.mul_ne_zero (hne g.1).out (by positivity))
    rw [multichoose_eq_choose h1, ← Finset.prod_coe_sort D.offsets]
    congr 1
    exact Finset.prod_congr rfl fun δ _ => multichoose_eq_choose h2
  rw [hcard]
  unfold capacityBoundWith
  calc (∏ g : Fin G, (τ₀ g + rate g * n + 1 - τ₀ g)) *
        ((∏ g : D.sources, Nat.multichoose (D.period g.1 * Fintype.card A) n) *
          ((∏ p : D.sources × D.offsets,
            Nat.multichoose (D.period p.1.1 * Fintype.card A ^ 2) (n - p.2.1)) *
            Fintype.card A ^ min n D.windowLength))
      = (∏ g : Fin G, (τ₀ g + rate g * n + 1 - τ₀ g)) *
          ((∏ g : D.sources, Nat.multichoose (D.period g.1 * Fintype.card A) n) *
            (∏ p : D.sources × D.offsets,
              Nat.multichoose (D.period p.1.1 * Fintype.card A ^ 2) (n - p.2.1))) *
            Fintype.card A ^ min n D.windowLength := by ac_rfl
    _ ≤ (∏ g ∈ Finset.range G, (rate g * n + D.period g)) *
          (∏ g ∈ D.sources, (Nat.choose (n + D.period g * Fintype.card A - 1)
            (D.period g * Fintype.card A - 1) *
            ∏ δ ∈ D.offsets, Nat.choose (n - δ + D.period g * Fintype.card A ^ 2 - 1)
              (D.period g * Fintype.card A ^ 2 - 1))) * Fintype.card A ^ D.windowLength := by
        rw [hsrc]
        exact Nat.mul_le_mul (Nat.mul_le_mul_right _ hlift) hwin
    _ = _ := by ac_rfl

/-- The native source-state count under a proved per-cell lift range. -/
theorem moment_capacityWith [Nonempty A] (rate : ℕ → ℕ)
    (hrange : ∀ a τ g, τ g ≤ advance a τ g ∧ advance a τ g ≤ τ g + rate g)
    (hδpos : ∀ δ ∈ D.offsets, 1 ≤ δ) (τ₀ : ℕ → ℕ) (G n : ℕ) :
    (∀ l : List A, l.length = n →
      D.persist G (D.streamWith advance τ₀ l) ∈ D.boxWith rate τ₀ G n) ∧
      (D.boxWith rate τ₀ G n).card ≤ D.capacityBoundWith rate G (Fintype.card A) n ∧
      (D.capacityBoundWith rate G (Fintype.card A) n < Fintype.card A ^ n →
        ¬ Function.Injective fun v : Fin n → A =>
          D.persist G (D.streamWith advance τ₀ (List.ofFn v))) := by
  refine ⟨fun l hl => hl ▸ persist_mem_boxWith advance rate hrange hδpos τ₀ G l,
    card_boxWith_le rate τ₀ G n, fun hlt hinj => ?_⟩
  let f' : (Fin n → A) → D.boxWith rate τ₀ G n := fun v =>
    ⟨D.persist G (D.streamWith advance τ₀ (List.ofFn v)), by
      simpa using persist_mem_boxWith advance rate hrange hδpos τ₀ G (List.ofFn v)⟩
  have hinj' : Function.Injective f' := fun v w h => hinj (congrArg Subtype.val h)
  have hcard := Fintype.card_le_of_injective f' hinj'
  rw [Fintype.card_fun, Fintype.card_fin, Fintype.card_coe] at hcard
  have := card_boxWith_le (D := D) rate τ₀ G n
  omega

/-- Located digits require the full-period lift factor `d_g*n + d_g`. -/
theorem located_moment_capacity [Nonempty A] (C : RangedClock A D.period)
    (hδpos : ∀ δ ∈ D.offsets, 1 ≤ δ) (τ₀ : ℕ → ℕ) (G n : ℕ) :
    (∀ l : List A, l.length = n →
      D.persist G (D.streamWith C.advance τ₀ l) ∈ D.boxWith D.period τ₀ G n) ∧
      (D.boxWith D.period τ₀ G n).card ≤ D.capacityBoundWith D.period G (Fintype.card A) n ∧
      (D.capacityBoundWith D.period G (Fintype.card A) n < Fintype.card A ^ n →
        ¬ Function.Injective fun v : Fin n → A =>
          D.persist G (D.streamWith C.advance τ₀ (List.ofFn v))) :=
  moment_capacityWith C.advance D.period C.advance_range hδpos τ₀ G n

/-- Stopping counts only the executed prefix; the discarded suffix contributes no bin or tick. -/
theorem located_prefix_lift_range (C : RangedClock A D.period) (τ₀ : ℕ → ℕ)
    (requested : List A) (consumed g : ℕ) :
    τ₀ g ≤ (D.streamWith C.advance τ₀ (requested.take consumed)).lift g ∧
      (D.streamWith C.advance τ₀ (requested.take consumed)).lift g ≤
        τ₀ g + D.period g * min consumed requested.length := by
  simpa only [List.length_take] using
    streamWith_lift_range C.advance D.period C.advance_range τ₀ (requested.take consumed) g

omit [Fintype A] [DecidableEq A] hne in
theorem capacityBoundWith_logConcave (rate : ℕ → ℕ) (hd1 : ∀ g, 1 ≤ D.period g)
    {alphabet : ℕ} (halphabet : 1 ≤ alphabet) (G : ℕ) :
    LogConcaveFrom D.windowLength (D.capacityBoundWith rate G alphabet) := by
  have hchoose : ∀ S, 1 ≤ S → ∀ δ, δ ≤ D.windowLength →
      LogConcaveFrom D.windowLength fun n => Nat.choose (n - δ + S - 1) (S - 1) := by
    intro S hS δ hδ n hn
    have h' := logConcave_shift (logConcave_choose (S - 1)) δ n (hδ.trans hn)
    simpa only [show ∀ k, k - δ + S - 1 = k - δ + (S - 1) from fun k => by omega] using h'
  have hS : ∀ g, 1 ≤ D.period g * alphabet := fun g =>
    Nat.one_le_iff_ne_zero.mpr (Nat.mul_ne_zero (by have := hd1 g; omega) (by omega))
  have hS2 : ∀ g, 1 ≤ D.period g * alphabet ^ 2 := fun g =>
    Nat.one_le_iff_ne_zero.mpr (Nat.mul_ne_zero (by have := hd1 g; omega) (by positivity))
  unfold capacityBoundWith
  refine ((logConcave_const _ _).mul (LogConcaveFrom.prod _ _ fun g _ => ?_)).mul
    (LogConcaveFrom.prod _ _ fun g _ => LogConcaveFrom.mul ?_
      (LogConcaveFrom.prod _ _ fun δ hδ => hchoose _ (hS2 g) δ (Finset.le_sup (f := id) hδ)))
  · exact logConcave_linear _ (rate g) (D.period g)
  · simpa using hchoose _ (hS g) 0 (Nat.zero_le _)

omit [Fintype A] [DecidableEq A] hne in
theorem capacityBoundWith_pos (rate : ℕ → ℕ) (hd1 : ∀ g, 1 ≤ D.period g)
    {alphabet : ℕ} (halphabet : 1 ≤ alphabet) (G n : ℕ) :
    0 < D.capacityBoundWith rate G alphabet n := by
  unfold capacityBoundWith
  refine Nat.mul_pos (Nat.mul_pos (by positivity) (Finset.prod_pos fun g _ => ?_))
    (Finset.prod_pos fun g _ => Nat.mul_pos (Nat.choose_pos (by omega))
      (Finset.prod_pos fun δ _ => Nat.choose_pos (by omega)))
  have := hd1 g
  omega

omit [DecidableEq A] hne in
theorem capacityWith_persists [Nonempty A] (rate : ℕ → ℕ) (hd1 : ∀ g, 1 ≤ D.period g)
    (G : ℕ) {nstar : ℕ} (hstar : D.windowLength + 1 ≤ nstar)
    (hbelow : D.capacityBoundWith rate G (Fintype.card A) nstar < Fintype.card A ^ nstar)
    (habove : Fintype.card A ^ (nstar - 1) ≤
      D.capacityBoundWith rate G (Fintype.card A) (nstar - 1)) :
    ∀ n, nstar ≤ n → D.capacityBoundWith rate G (Fintype.card A) n < Fintype.card A ^ n :=
  stays_below_of_logConcave (capacityBoundWith_logConcave rate hd1 Fintype.card_pos G)
    (capacityBoundWith_pos rate hd1 Fintype.card_pos G) hstar hbelow habove

end SourceDecl

section Audit
#print axioms RangedClock.carryIn_le_one
#print axioms RangedClock.advance_range
#print axioms SourceDecl.streamWith_card_bins
#print axioms SourceDecl.streamWith_card_pairBins
#print axioms SourceDecl.located_prefix_lift_range
#print axioms SourceDecl.located_moment_capacity
#print axioms SourceDecl.capacityWith_persists
end Audit

end Holonics.HNN.Moment
