import ElementaryHolonics.Millennium.HodgeConjecture
import ElementaryHolonics.Millennium.GeneralCollision

/-!
# CokernelCalculus: what an integral obstruction can and cannot witness

Two Millennium objects in this tree carry an obstruction of the **same species**, and
this file states the calculus once and instantiates it at both.

* **Birch–Swinnerton-Dyer.** The descent's obstruction lives in `E(ℚ)/2E(ℚ)`, the
  cokernel of doubling. `GeneralCollision` bounds it on every full-2-torsion curve.
* **Hodge.** The *integral* conjecture's obstruction lives in the cokernel of the
  cycle-class map — Kollár's classes with `p·α` algebraic and `α` not.

Both are **reachable only in a multiple**: some nonzero integer multiple lands in the
image while the class itself does not.  The calculus says exactly what that can do:

* **`theMultipleReachableClassIsTorsionInTheCokernel`** — such a class is torsion in
  the cokernel, so it is precisely an *integral* phenomenon.
* **`theMultipleReachableClassIsRationallyReachable`** — and therefore it is
  **invisible after tensoring with `ℚ`**: a class reachable in a nonzero multiple lies
  in the rational span of the image.

The second is a **bar**, and it is the point of the file.  The Millennium Hodge
statement is rational: if `p·α` is algebraic then `α = (1/p)·[p·α]` is already in the
rational span, so no obstruction of this species can ever witness the conjecture.  A
finite model that returns `ReachableOnlyInMultiple` has found an integral obstruction
and nothing more.  The same bar reads on the descent side: `E(ℚ)/2E(ℚ)` is killed by
`2`, hence entirely torsion, hence entirely invisible rationally — which is exactly
why descent bounds the rank and says nothing rational about `Ш`.

Every `theorem` is discharged and none depends on `sorryAx`.
-/

noncomputable section

namespace Soma.Holonics.Millennium.CokernelCalculus

open Soma.Holonics.Millennium

/-! ## 1. The obstruction species -/

/-- A class is **reachable only in a multiple** of a set when some nonzero integer
multiple of it lies in the subgroup the set generates, while the class itself does
not.  This is Kollár's shape on the Hodge side and the descent's shape on the
Birch–Swinnerton-Dyer side. -/
def ReachableOnlyInMultiple {V : Type*} [AddCommGroup V] (S : Set V) (α : V)
    (m : ℤ) : Prop :=
  m ≠ 0 ∧ m • α ∈ AddSubgroup.closure S ∧ α ∉ AddSubgroup.closure S

/-! ## 2. It is torsion in the cokernel -/

/-- **A MULTIPLE-REACHABLE CLASS IS TORSION IN THE COKERNEL**: its image in
`V ⧸ ⟨S⟩` is killed by the multiplicity, and is nonzero.  So the obstruction is an
integral one — it lives entirely in the torsion of the cokernel. -/
theorem theMultipleReachableClassIsTorsionInTheCokernel {V : Type*} [AddCommGroup V]
    {S : Set V} {α : V} {m : ℤ} (h : ReachableOnlyInMultiple S α m) :
    m • (QuotientAddGroup.mk' (AddSubgroup.closure S) α) = 0 ∧
      (QuotientAddGroup.mk' (AddSubgroup.closure S) α) ≠ 0 := by
  obtain ⟨hm, hmul, hnot⟩ := h
  constructor
  · rw [← map_zsmul]
    exact (QuotientAddGroup.eq_zero_iff _).mpr hmul
  · intro hc
    exact hnot ((QuotientAddGroup.eq_zero_iff _).mp hc)

/-! ## 3. The bar: it is invisible rationally -/

/-- **A MULTIPLE-REACHABLE CLASS IS RATIONALLY REACHABLE**: in any `ℚ`-vector space,
if a nonzero integer multiple of `α` lies in the subgroup generated by `S`, then `α`
itself lies in the **rational span** of `S`.

This is the bar.  An obstruction of this species is an integral phenomenon and can
never witness a rational statement. -/
theorem theMultipleReachableClassIsRationallyReachable {V : Type*} [AddCommGroup V]
    [Module ℚ V] (S : Set V) (α : V) (m : ℤ) (hm : m ≠ 0)
    (hmul : m • α ∈ AddSubgroup.closure S) :
    α ∈ Submodule.span ℚ S := by
  -- the integral subgroup sits inside the rational span
  have hsub : AddSubgroup.closure S ≤
      (Submodule.span ℚ S).toAddSubgroup := by
    refine AddSubgroup.closure_le _ |>.mpr ?_
    intro s hs
    exact Submodule.subset_span hs
  have hmem : m • α ∈ Submodule.span ℚ S := hsub hmul
  -- and the rational span is closed under dividing by a nonzero integer
  have hmQ : ((m : ℚ)) ≠ 0 := Int.cast_ne_zero.mpr hm
  have hcast : ((m : ℚ)) • α = m • α := Int.cast_smul_eq_zsmul ℚ m α
  have hdiv : ((m : ℚ))⁻¹ • (((m : ℚ)) • α) = α := by
    rw [smul_smul, inv_mul_cancel₀ hmQ, one_smul]
  rw [← hdiv, hcast]
  exact Submodule.smul_mem _ _ hmem

/-- **NO MULTIPLE-REACHABLE CLASS IS A RATIONAL COUNTEREXAMPLE**: the contrapositive,
stated as it is used.  If `α` is outside the rational span of `S`, then no nonzero
multiple of it is reachable at all. -/
theorem theRationalObstructionRefusesEveryMultiple {V : Type*} [AddCommGroup V]
    [Module ℚ V] (S : Set V) (α : V) (hα : α ∉ Submodule.span ℚ S) (m : ℤ)
    (hm : m ≠ 0) : m • α ∉ AddSubgroup.closure S := fun hc =>
  hα (theMultipleReachableClassIsRationallyReachable S α m hm hc)


/-! ## 4. The Hodge instance -/

open Soma.Holonics.Millennium.HodgeConjecture
open Soma.Holonics.Millennium.HodgeConjecture.Datum

/-- **THE INTEGRAL HODGE OBSTRUCTION CANNOT WITNESS THE MILLENNIUM STATEMENT**: if a
rational Hodge class is reachable only in a nonzero multiple of the algebraic cycle
classes, it is already in the algebraic span, so it is **not** a counterexample.

Kollár's classes — `p·α` algebraic with `α` not — refute the **integral** conjecture
and are silent on the rational one.  A finite model that returns a multiplicity has
found an integral obstruction and must be reported as one. -/
theorem theIntegralHodgeObstructionIsNotAMillenniumObstruction (D : Datum)
    (S : Set D.Cohomology) (hS : S ⊆ LinearMap.range D.cycleClass.hom)
    (α : D.Cohomology) (m : ℤ) (hm : m ≠ 0)
    (hmul : m • α ∈ AddSubgroup.closure S) :
    α ∈ D.algebraicSpan := by
  have h1 : α ∈ Submodule.span ℚ S :=
    theMultipleReachableClassIsRationallyReachable S α m hm hmul
  have h2 : Submodule.span ℚ S ≤ D.algebraicSpan :=
    Submodule.span_le.mpr hS
  exact h2 h1

/-- **A GENUINE HODGE COUNTEREXAMPLE REFUSES EVERY MULTIPLE**: the contrapositive, and
the shape any real counterexample must have. -/
theorem theGenuineHodgeCounterexampleRefusesEveryMultiple (D : Datum)
    (α : D.Cohomology) (hα : α ∉ D.algebraicSpan) (m : ℤ) (hm : m ≠ 0) :
    m • α ∉ AddSubgroup.closure (D.algebraicSpan : Set D.Cohomology) := fun hc =>
  hα (theIntegralHodgeObstructionIsNotAMillenniumObstruction D
    (D.algebraicSpan : Set D.Cohomology) (le_refl _) α m hm hc)

/-! ## 5. The Birch–Swinnerton-Dyer instance -/

open Soma.Holonics.Millennium.GeneralFace
open Soma.Holonics.Millennium.GeneralCollision

/-- **THE DESCENT OBSTRUCTION IS ENTIRELY TORSION**: every class in `E(ℚ)/2E(ℚ)` is
killed by `2`.  So the descent's obstruction is an integral phenomenon of exactly the
species above — which is why the two-descent bounds the **rank** and says nothing
rational about `Ш`. -/
theorem theDescentObstructionIsEntirelyTorsion {a b : ℚ}
    (c : (E a b).Point ⧸ twoE a b) : (2 : ℤ) • c = 0 := by
  induction c using QuotientAddGroup.induction_on with
  | H P =>
    rw [← QuotientAddGroup.mk_zsmul]
    refine (QuotientAddGroup.eq_zero_iff _).mpr ?_
    refine ⟨P, ?_⟩
    show P + P = (2 : ℤ) • P
    rw [two_zsmul]

/-- **ONE CALCULUS, TWO MILLENNIUM OBJECTS**: the descent obstruction and the integral
Hodge obstruction are the same species — torsion in a cokernel — and the bar applies
to both.  Neither can witness a rational statement; each bounds an integral one. -/
theorem theTwoObstructionsAreOneSpecies {a b : ℚ} {V : Type*} [AddCommGroup V]
    [Module ℚ V] (S : Set V) (α : V) (m : ℤ) (hm : m ≠ 0)
    (hmul : m • α ∈ AddSubgroup.closure S) :
    (∀ c : (E a b).Point ⧸ twoE a b, (2 : ℤ) • c = 0) ∧
      α ∈ Submodule.span ℚ S :=
  ⟨fun c => theDescentObstructionIsEntirelyTorsion c,
    theMultipleReachableClassIsRationallyReachable S α m hm hmul⟩

end Soma.Holonics.Millennium.CokernelCalculus
