import ElementaryHolonics.Millennium.FamilyTunnellBrandtDestinationClassification

/-!
# The single relation in the Brandt neighbor coordinate chart

Every actual odd-prime neighbor is returned by four integral coordinates in
`FamilyTunnellBrandtDestinationClassification`.  This file identifies the
complete redundancy of that presentation.  Once the adjusted direction is
written in the same polar-kernel chart, the zero fibre is generated by one
explicit integral relation: subtract the direction in the three kernel
coordinates and add one complete `p`-turn in the fractional coordinate.

The result is the exact quotient passage from the four-coordinate occurrence
carrier to its rank-three lattice image.  No cardinality, determinant, or
choice-defined inverse is used in place of the retained fibre.
-/

noncomputable section

namespace Soma.Holonics.Millennium.FamilyTunnellBrandtRelationKernel

open Soma.Holonics.Millennium.FamilyTunnellProjectiveNeighbors
open Soma.Holonics.Millennium.FamilyTunnellIntegralNeighbors
open Soma.Holonics.Millennium.FamilyTunnellBrandtTestVector
open Soma.Holonics.Millennium.FamilyTunnellBrandtNeighbors
open Soma.Holonics.Millennium.FamilyTunnellBrandtNeighborWorldTube
open Soma.Holonics.Millennium.FamilyTunnellBrandtDestinationClassification

variable {p : ℕ} [Fact p.Prime]

/-- The one relation in a first-pivot four-coordinate neighbor chart. -/
def firstPivotRelationGenerator (qv : ℤ) (v : IntTriple) : NeighborCoordinates :=
  (-qv, -v.2.1, -v.2.2, (p : ℤ))

/-- The one relation in a second-pivot four-coordinate neighbor chart. -/
def secondPivotRelationGenerator (qv : ℤ) (v : IntTriple) : NeighborCoordinates :=
  (-v.1, -qv, -v.2.2, (p : ℤ))

private theorem p_int_ne_zero : (p : ℤ) ≠ 0 := by
  exact_mod_cast (Fact.out : p.Prime).ne_zero

/-- A first-pivot kernel chart has no coordinate collision. -/
theorem firstPivotKernelPoint_injective (A B C : ℤ) :
    Function.Injective
      (fun u : ℤ × ℤ × ℤ =>
        firstPivotKernelPoint (p := p) A B C u.1 u.2.1 u.2.2) := by
  intro u w h
  have hx := congrArg Prod.fst h
  have hy := congrArg (fun x : IntTriple => x.2.1) h
  have hz := congrArg (fun x : IntTriple => x.2.2) h
  dsimp [firstPivotKernelPoint] at hy hz
  apply Prod.ext
  · dsimp [firstPivotKernelPoint] at hx
    rw [hy, hz] at hx
    have hp := p_int_ne_zero (p := p)
    have hmul : (p : ℤ) * u.1 = (p : ℤ) * w.1 := by
      calc
        (p : ℤ) * u.1 =
            ((p : ℤ) * u.1 + modularCorrection (p := p) A B * w.2.1 +
                modularCorrection (p := p) A C * w.2.2) -
              (modularCorrection (p := p) A B * w.2.1 +
                modularCorrection (p := p) A C * w.2.2) := by ring
        _ = ((p : ℤ) * w.1 + modularCorrection (p := p) A B * w.2.1 +
                modularCorrection (p := p) A C * w.2.2) -
              (modularCorrection (p := p) A B * w.2.1 +
                modularCorrection (p := p) A C * w.2.2) := by rw [hx]
        _ = (p : ℤ) * w.1 := by ring
    exact mul_left_cancel₀ hp hmul
  · apply Prod.ext <;> assumption

/-- A second-pivot kernel chart has no coordinate collision. -/
theorem secondPivotKernelPoint_injective (B C : ℤ) :
    Function.Injective
      (fun u : ℤ × ℤ × ℤ =>
        secondPivotKernelPoint (p := p) B C u.1 u.2.1 u.2.2) := by
  intro u w h
  have hx := congrArg Prod.fst h
  have hy := congrArg (fun x : IntTriple => x.2.1) h
  have hz := congrArg (fun x : IntTriple => x.2.2) h
  dsimp [secondPivotKernelPoint] at hx hz
  apply Prod.ext
  · exact hx
  · apply Prod.ext
    · dsimp [secondPivotKernelPoint] at hy
      rw [hz] at hy
      have hp := p_int_ne_zero (p := p)
      have hmul : (p : ℤ) * u.2.1 = (p : ℤ) * w.2.1 := by
        calc
          (p : ℤ) * u.2.1 =
              ((p : ℤ) * u.2.1 + modularCorrection (p := p) B C * w.2.2) -
                modularCorrection (p := p) B C * w.2.2 := by ring
          _ = ((p : ℤ) * w.2.1 + modularCorrection (p := p) B C * w.2.2) -
                modularCorrection (p := p) B C * w.2.2 := by rw [hy]
          _ = (p : ℤ) * w.2.1 := by ring
      exact mul_left_cancel₀ hp hmul
    · exact hz

/-- Complete one-generator zero-fibre theorem in a first-pivot chart. -/
theorem firstPivotNeighborHom_eq_zero_iff
    (A B C qv : ℤ) (v : IntTriple)
    (hv : v = firstPivotKernelPoint (p := p) A B C qv v.2.1 v.2.2)
    (hvnonzero : reduceTriple (p := p) v ≠ (0, 0, 0))
    (u : NeighborCoordinates) :
    firstPivotNeighborHom (p := p) A B C v u = 0 ↔
      ∃ k : ℤ, u = k • firstPivotRelationGenerator (p := p) qv v := by
  constructor
  · intro hzero
    have hdvd : (p : ℤ) ∣ u.2.2.2 := by
      apply fourthCoordinate_dvd_of_fractionalPoint_eq_zero (p := p)
        (m := firstPivotKernelPoint (p := p) A B C u.1 u.2.1 u.2.2.1)
        (v := v) (a := u.2.2.2)
      · exact hvnonzero
      · simpa [firstPivotNeighborHom, firstPivotNeighborPoint, Prod.mk_zero_zero] using hzero
    obtain ⟨k, hk⟩ := hdvd
    have hpQ : (p : ℚ) ≠ 0 := by
      exact_mod_cast (Fact.out : p.Prime).ne_zero
    have hx := congrArg Prod.fst hzero
    have hy := congrArg (fun x : RatTriple => x.2.1) hzero
    have hz := congrArg (fun x : RatTriple => x.2.2) hzero
    simp only [firstPivotNeighborHom, firstPivotNeighborPoint, ratTripleAdd,
      ratTripleScale, intTripleToRat, AddMonoidHom.coe_mk, ZeroHom.coe_mk] at hx hy hz
    rw [hk] at hx hy hz
    field_simp [hpQ] at hx hy hz
    norm_num at hx hy hz
    have hm :
        firstPivotKernelPoint (p := p) A B C u.1 u.2.1 u.2.2.1 =
          (-k * v.1, -k * v.2.1, -k * v.2.2) := by
      apply Prod.ext
      · have hxZ :
            (firstPivotKernelPoint (p := p) A B C u.1 u.2.1 u.2.2.1).1 *
                  (p : ℤ) + (p : ℤ) * k * v.1 = 0 := by
          exact_mod_cast hx
        have hfactor :
            (p : ℤ) *
                ((firstPivotKernelPoint (p := p) A B C
                    u.1 u.2.1 u.2.2.1).1 + k * v.1) = 0 := by
          calc
            _ = (firstPivotKernelPoint (p := p) A B C
                    u.1 u.2.1 u.2.2.1).1 * (p : ℤ) +
                  (p : ℤ) * k * v.1 := by ring
            _ = 0 := hxZ
        have hsum := (mul_eq_zero.mp hfactor).resolve_left (p_int_ne_zero (p := p))
        dsimp
        linarith
      · apply Prod.ext
        · have hyZ :
              (p : ℤ) *
                    (firstPivotKernelPoint (p := p) A B C
                      u.1 u.2.1 u.2.2.1).2.1 +
                  (p : ℤ) * k * v.2.1 = 0 := by
            exact_mod_cast hy
          have hfactor :
              (p : ℤ) *
                  ((firstPivotKernelPoint (p := p) A B C
                      u.1 u.2.1 u.2.2.1).2.1 + k * v.2.1) = 0 := by
            calc
              _ = (p : ℤ) *
                    (firstPivotKernelPoint (p := p) A B C
                      u.1 u.2.1 u.2.2.1).2.1 +
                    (p : ℤ) * k * v.2.1 := by ring
              _ = 0 := hyZ
          have hsum := (mul_eq_zero.mp hfactor).resolve_left (p_int_ne_zero (p := p))
          dsimp
          linarith
        · have hzZ :
              (p : ℤ) *
                    (firstPivotKernelPoint (p := p) A B C
                      u.1 u.2.1 u.2.2.1).2.2 +
                  (p : ℤ) * k * v.2.2 = 0 := by
            exact_mod_cast hz
          have hfactor :
              (p : ℤ) *
                  ((firstPivotKernelPoint (p := p) A B C
                      u.1 u.2.1 u.2.2.1).2.2 + k * v.2.2) = 0 := by
            calc
              _ = (p : ℤ) *
                    (firstPivotKernelPoint (p := p) A B C
                      u.1 u.2.1 u.2.2.1).2.2 +
                    (p : ℤ) * k * v.2.2 := by ring
              _ = 0 := hzZ
          have hsum := (mul_eq_zero.mp hfactor).resolve_left (p_int_ne_zero (p := p))
          dsimp
          linarith
    have hscaled :
        (-k * v.1, -k * v.2.1, -k * v.2.2) =
          firstPivotKernelPoint (p := p) A B C
            (-k * qv) (-k * v.2.1) (-k * v.2.2) := by
      have hvx := congrArg Prod.fst hv
      dsimp [firstPivotKernelPoint] at hvx
      apply Prod.ext
      · dsimp [firstPivotKernelPoint]
        rw [hvx]
        ring
      · rfl
    have hcoordinates :
        (u.1, u.2.1, u.2.2.1) =
          (-k * qv, -k * v.2.1, -k * v.2.2) :=
      firstPivotKernelPoint_injective (p := p) A B C (hm.trans hscaled)
    refine ⟨k, ?_⟩
    apply Prod.ext
    · have h := congrArg Prod.fst hcoordinates
      simpa [firstPivotRelationGenerator] using h
    · apply Prod.ext
      · have h := congrArg (fun x : ℤ × ℤ × ℤ => x.2.1) hcoordinates
        simpa [firstPivotRelationGenerator] using h
      · apply Prod.ext
        · have h := congrArg (fun x : ℤ × ℤ × ℤ => x.2.2) hcoordinates
          simpa [firstPivotRelationGenerator] using h
        · simpa [firstPivotRelationGenerator, mul_comm] using hk
  · rintro ⟨k, rfl⟩
    rw [map_zsmul]
    have hgenerator :
        firstPivotNeighborHom (p := p) A B C v
            (firstPivotRelationGenerator (p := p) qv v) = 0 := by
      have hpQ : (p : ℚ) ≠ 0 := by
        exact_mod_cast (Fact.out : p.Prime).ne_zero
      rw [hv]
      apply Prod.ext
      · simp [firstPivotNeighborHom, firstPivotRelationGenerator,
          firstPivotNeighborPoint, firstPivotKernelPoint, ratTripleAdd,
          ratTripleScale, intTripleToRat]
        field_simp [hpQ]
        ring
      · apply Prod.ext <;>
          simp [firstPivotNeighborHom, firstPivotRelationGenerator,
            firstPivotNeighborPoint, firstPivotKernelPoint, ratTripleAdd,
            ratTripleScale, intTripleToRat, hpQ]
    rw [hgenerator]
    simp

/-- Complete one-generator zero-fibre theorem in a second-pivot chart. -/
theorem secondPivotNeighborHom_eq_zero_iff
    (B C qv : ℤ) (v : IntTriple)
    (hv : v = secondPivotKernelPoint (p := p) B C v.1 qv v.2.2)
    (hvnonzero : reduceTriple (p := p) v ≠ (0, 0, 0))
    (u : NeighborCoordinates) :
    secondPivotNeighborHom (p := p) B C v u = 0 ↔
      ∃ k : ℤ, u = k • secondPivotRelationGenerator (p := p) qv v := by
  constructor
  · intro hzero
    have hdvd : (p : ℤ) ∣ u.2.2.2 := by
      apply fourthCoordinate_dvd_of_fractionalPoint_eq_zero (p := p)
        (m := secondPivotKernelPoint (p := p) B C u.1 u.2.1 u.2.2.1)
        (v := v) (a := u.2.2.2)
      · exact hvnonzero
      · simpa [secondPivotNeighborHom, secondPivotNeighborPoint, Prod.mk_zero_zero] using hzero
    obtain ⟨k, hk⟩ := hdvd
    have hpQ : (p : ℚ) ≠ 0 := by
      exact_mod_cast (Fact.out : p.Prime).ne_zero
    have hx := congrArg Prod.fst hzero
    have hy := congrArg (fun x : RatTriple => x.2.1) hzero
    have hz := congrArg (fun x : RatTriple => x.2.2) hzero
    simp only [secondPivotNeighborHom, secondPivotNeighborPoint, ratTripleAdd,
      ratTripleScale, intTripleToRat, AddMonoidHom.coe_mk, ZeroHom.coe_mk] at hx hy hz
    rw [hk] at hx hy hz
    field_simp [hpQ] at hx hy hz
    norm_num at hx hy hz
    have hm :
        secondPivotKernelPoint (p := p) B C u.1 u.2.1 u.2.2.1 =
          (-k * v.1, -k * v.2.1, -k * v.2.2) := by
      apply Prod.ext
      · have hxZ :
            (secondPivotKernelPoint (p := p) B C u.1 u.2.1 u.2.2.1).1 *
                  (p : ℤ) + (p : ℤ) * k * v.1 = 0 := by
          exact_mod_cast hx
        have hfactor :
            (p : ℤ) *
                ((secondPivotKernelPoint (p := p) B C
                    u.1 u.2.1 u.2.2.1).1 + k * v.1) = 0 := by
          calc
            _ = (secondPivotKernelPoint (p := p) B C
                    u.1 u.2.1 u.2.2.1).1 * (p : ℤ) +
                  (p : ℤ) * k * v.1 := by ring
            _ = 0 := hxZ
        have hsum := (mul_eq_zero.mp hfactor).resolve_left (p_int_ne_zero (p := p))
        dsimp
        linarith
      · apply Prod.ext
        · have hyZ :
              (p : ℤ) *
                    (secondPivotKernelPoint (p := p) B C
                      u.1 u.2.1 u.2.2.1).2.1 +
                  (p : ℤ) * k * v.2.1 = 0 := by
            exact_mod_cast hy
          have hfactor :
              (p : ℤ) *
                  ((secondPivotKernelPoint (p := p) B C
                      u.1 u.2.1 u.2.2.1).2.1 + k * v.2.1) = 0 := by
            calc
              _ = (p : ℤ) *
                    (secondPivotKernelPoint (p := p) B C
                      u.1 u.2.1 u.2.2.1).2.1 +
                    (p : ℤ) * k * v.2.1 := by ring
              _ = 0 := hyZ
          have hsum := (mul_eq_zero.mp hfactor).resolve_left (p_int_ne_zero (p := p))
          dsimp
          linarith
        · have hzZ :
              (p : ℤ) *
                    (secondPivotKernelPoint (p := p) B C
                      u.1 u.2.1 u.2.2.1).2.2 +
                  (p : ℤ) * k * v.2.2 = 0 := by
            exact_mod_cast hz
          have hfactor :
              (p : ℤ) *
                  ((secondPivotKernelPoint (p := p) B C
                      u.1 u.2.1 u.2.2.1).2.2 + k * v.2.2) = 0 := by
            calc
              _ = (p : ℤ) *
                    (secondPivotKernelPoint (p := p) B C
                      u.1 u.2.1 u.2.2.1).2.2 +
                    (p : ℤ) * k * v.2.2 := by ring
              _ = 0 := hzZ
          have hsum := (mul_eq_zero.mp hfactor).resolve_left (p_int_ne_zero (p := p))
          dsimp
          linarith
    have hscaled :
        (-k * v.1, -k * v.2.1, -k * v.2.2) =
          secondPivotKernelPoint (p := p) B C
            (-k * v.1) (-k * qv) (-k * v.2.2) := by
      have hvy := congrArg (fun x : IntTriple => x.2.1) hv
      dsimp [secondPivotKernelPoint] at hvy
      apply Prod.ext
      · rfl
      · apply Prod.ext
        · dsimp [secondPivotKernelPoint]
          rw [hvy]
          ring
        · rfl
    have hcoordinates :
        (u.1, u.2.1, u.2.2.1) =
          (-k * v.1, -k * qv, -k * v.2.2) :=
      secondPivotKernelPoint_injective (p := p) B C (hm.trans hscaled)
    refine ⟨k, ?_⟩
    apply Prod.ext
    · have h := congrArg Prod.fst hcoordinates
      simpa [secondPivotRelationGenerator] using h
    · apply Prod.ext
      · have h := congrArg (fun x : ℤ × ℤ × ℤ => x.2.1) hcoordinates
        simpa [secondPivotRelationGenerator] using h
      · apply Prod.ext
        · have h := congrArg (fun x : ℤ × ℤ × ℤ => x.2.2) hcoordinates
          simpa [secondPivotRelationGenerator] using h
        · simpa [secondPivotRelationGenerator, mul_comm] using hk
  · rintro ⟨k, rfl⟩
    rw [map_zsmul]
    have hgenerator :
        secondPivotNeighborHom (p := p) B C v
            (secondPivotRelationGenerator (p := p) qv v) = 0 := by
      have hpQ : (p : ℚ) ≠ 0 := by
        exact_mod_cast (Fact.out : p.Prime).ne_zero
      rw [hv]
      apply Prod.ext
      · simp [secondPivotNeighborHom, secondPivotRelationGenerator,
          secondPivotNeighborPoint, secondPivotKernelPoint, ratTripleAdd,
          ratTripleScale, intTripleToRat, hpQ]
      · apply Prod.ext
        · simp [secondPivotNeighborHom, secondPivotRelationGenerator,
            secondPivotNeighborPoint, secondPivotKernelPoint, ratTripleAdd,
            ratTripleScale, intTripleToRat]
          field_simp [hpQ]
          ring
        · simp [secondPivotNeighborHom, secondPivotRelationGenerator,
            secondPivotNeighborPoint, secondPivotKernelPoint, ratTripleAdd,
            ratTripleScale, intTripleToRat, hpQ]
    rw [hgenerator]
    simp

/-! ## Actual Tunnell--Brandt source lifts -/

private theorem relation_two_ne_zero (hp2 : p ≠ 2) : (2 : ZMod p) ≠ 0 := by
  apply Ring.two_ne_zero
  rw [ZMod.ringChar_zmod_n]
  exact hp2

private theorem relation_four_ne_zero (hp2 : p ≠ 2) : (4 : ZMod p) ≠ 0 := by
  rw [show (4 : ZMod p) = 2 ^ 2 by norm_num]
  exact pow_ne_zero 2 (relation_two_ne_zero (p := p) hp2)

/-- The adjusted first-class lift belongs to its own integral polar kernel.
This is the exact source hypothesis required by the generic relation theorem. -/
private theorem firstAdjustedLift_polar_dvd (hp2 : p ≠ 2)
    (d : FirstBrandtDirection (p := p)) :
    let v := adjustedDirectionLift 32 d
    (p : ℤ) ∣ 4 * v.1 * v.1 + 2 * v.2.1 * v.2.1 + 64 * v.2.2 * v.2.2 := by
  dsimp
  obtain ⟨t, ht⟩ :=
    prime_sq_dvd_adjustedDirectionLift_norm (p := p) hp2 32 d
  refine ⟨2 * (p : ℤ) * t, ?_⟩
  calc
    4 * (adjustedDirectionLift 32 d).1 * (adjustedDirectionLift 32 d).1 +
          2 * (adjustedDirectionLift 32 d).2.1 * (adjustedDirectionLift 32 d).2.1 +
        64 * (adjustedDirectionLift 32 d).2.2 * (adjustedDirectionLift 32 d).2.2 =
        2 * intTunnellQuadratic 32 (adjustedDirectionLift 32 d) := by
          simp [intTunnellQuadratic]
          ring
    _ = 2 * ((p : ℤ) ^ 2 * t) := by rw [ht]
    _ = (p : ℤ) * (2 * (p : ℤ) * t) := by ring

/-- The adjusted second-class lift likewise belongs to its cross-term polar
kernel. -/
private theorem secondAdjustedLift_polar_dvd (hp2 : p ≠ 2)
    (d : SecondBrandtDirection (p := p)) :
    let v := adjustedBrandtSecondDirectionLift hp2 d
    let A := 4 * v.1
    let B := 8 * v.2.1 + 4 * v.2.2
    let C := 4 * v.2.1 + 18 * v.2.2
    (p : ℤ) ∣ A * v.1 + B * v.2.1 + C * v.2.2 := by
  dsimp
  obtain ⟨t, ht⟩ :=
    prime_sq_dvd_adjustedBrandtSecondDirectionLift_norm (p := p) hp2 d
  refine ⟨2 * (p : ℤ) * t, ?_⟩
  calc
    4 * (adjustedBrandtSecondDirectionLift hp2 d).1 *
          (adjustedBrandtSecondDirectionLift hp2 d).1 +
        (8 * (adjustedBrandtSecondDirectionLift hp2 d).2.1 +
            4 * (adjustedBrandtSecondDirectionLift hp2 d).2.2) *
          (adjustedBrandtSecondDirectionLift hp2 d).2.1 +
        (4 * (adjustedBrandtSecondDirectionLift hp2 d).2.1 +
            18 * (adjustedBrandtSecondDirectionLift hp2 d).2.2) *
          (adjustedBrandtSecondDirectionLift hp2 d).2.2 =
        2 * brandtSecondQuadratic (adjustedBrandtSecondDirectionLift hp2 d) := by
          simp [brandtSecondQuadratic]
          ring
    _ = 2 * ((p : ℤ) ^ 2 * t) := by rw [ht]
    _ = (p : ℤ) * (2 * (p : ℤ) * t) := by ring

/-- **EVERY ACTUAL FIRST-CLASS BRANDT NEIGHBOR HAS ONE COMPLETE RELATION.**
The returned generator carries one full positive `p` turn in its fractional
coordinate, and its integer multiples are exactly the zero fibre. -/
theorem firstBrandtNeighbor_relationGenerator_exists (hp2 : p ≠ 2)
    (d : FirstBrandtDirection (p := p)) :
    ∃ g : NeighborCoordinates,
      g.2.2.2 = (p : ℤ) ∧
      ∀ u : NeighborCoordinates,
        firstBrandtNeighborHom hp2 d u = 0 ↔ ∃ k : ℤ, u = k • g := by
  let v := adjustedDirectionLift 32 d
  have hreduce := reduce_adjustedDirectionLift (p := p) hp2 32 d
  have hvnonzero : reduceTriple (p := p) v ≠ (0, 0, 0) := by
    rw [show reduceTriple (p := p) v = projectiveDirectionVector d.1 by
      simpa [v] using hreduce]
    exact projectiveDirectionVector_ne_zero d
  have hvpolar := firstAdjustedLift_polar_dvd (p := p) hp2 d
  rcases d with ⟨chart, hisotropic⟩
  cases chart with
  | inl yz =>
      have hvx : (v.1 : ZMod p) = 1 := by
        have h := congrArg Prod.fst hreduce
        simpa [v, projectiveDirectionVector, reduceTriple] using h
      have hA : ((4 * v.1 : ℤ) : ZMod p) ≠ 0 := by
        push_cast
        rw [hvx]
        simpa using relation_four_ne_zero (p := p) hp2
      obtain ⟨qv, hv⟩ :=
        (firstPivotKernel_iff (p := p) hA v).1 hvpolar
      refine ⟨firstPivotRelationGenerator (p := p) qv v, ?_, ?_⟩
      · simp [firstPivotRelationGenerator]
      · intro u
        simpa [firstBrandtNeighborHom] using
          (firstPivotNeighborHom_eq_zero_iff (p := p)
            (4 * v.1) (2 * v.2.1) (64 * v.2.2) qv v hv hvnonzero u)
  | inr z =>
      have hvx : (v.1 : ZMod p) = 0 := by
        have h := congrArg Prod.fst hreduce
        simpa [v, projectiveDirectionVector, reduceTriple] using h
      have hvy : (v.2.1 : ZMod p) = 1 := by
        have h := congrArg (fun w => w.2.1) hreduce
        simpa [v, reduceTriple, projectiveDirectionVector] using h
      have hA : ((4 * v.1 : ℤ) : ZMod p) = 0 := by
        push_cast
        rw [hvx]
        ring
      have hB : ((2 * v.2.1 : ℤ) : ZMod p) ≠ 0 := by
        push_cast
        rw [hvy]
        simpa using relation_two_ne_zero (p := p) hp2
      obtain ⟨qv, hv⟩ :=
        (secondPivotKernel_iff (p := p) hA hB v).1 hvpolar
      refine ⟨secondPivotRelationGenerator (p := p) qv v, ?_, ?_⟩
      · simp [secondPivotRelationGenerator]
      · intro u
        simpa [firstBrandtNeighborHom] using
          (secondPivotNeighborHom_eq_zero_iff (p := p)
            (2 * v.2.1) (64 * v.2.2) qv v hv hvnonzero u)

/-- **EVERY ACTUAL SECOND-CLASS BRANDT NEIGHBOR HAS ONE COMPLETE RELATION.** -/
theorem secondBrandtNeighbor_relationGenerator_exists (hp2 : p ≠ 2)
    (d : SecondBrandtDirection (p := p)) :
    ∃ g : NeighborCoordinates,
      g.2.2.2 = (p : ℤ) ∧
      ∀ u : NeighborCoordinates,
        secondBrandtNeighborHom hp2 d u = 0 ↔ ∃ k : ℤ, u = k • g := by
  let v := adjustedBrandtSecondDirectionLift hp2 d
  let A := 4 * v.1
  let B := 8 * v.2.1 + 4 * v.2.2
  let C := 4 * v.2.1 + 18 * v.2.2
  have hreduce := reduce_adjustedBrandtSecondDirectionLift (p := p) hp2 d
  have hvnonzero : reduceTriple (p := p) v ≠ (0, 0, 0) := by
    rw [show reduceTriple (p := p) v = brandtSecondDirectionVector hp2 d by
      simpa [v] using hreduce]
    exact brandtSecondDirectionVector_ne_zero hp2 d
  have hvpolar := secondAdjustedLift_polar_dvd (p := p) hp2 d
  rcases d with ⟨chart, hisotropic⟩
  cases chart with
  | inl yz =>
      have hvx : (v.1 : ZMod p) = 1 := by
        have h := congrArg Prod.fst hreduce
        simpa [v, reduceTriple, brandtSecondDirectionVector, thinToBrandtSecondMod,
          projectiveDirectionVector] using h
      have hA : (A : ZMod p) ≠ 0 := by
        dsimp [A]
        push_cast
        rw [hvx]
        simpa using relation_four_ne_zero (p := p) hp2
      obtain ⟨qv, hv⟩ :=
        (firstPivotKernel_iff (p := p) hA v).1 hvpolar
      refine ⟨firstPivotRelationGenerator (p := p) qv v, ?_, ?_⟩
      · simp [firstPivotRelationGenerator]
      · intro u
        simpa [secondBrandtNeighborHom, A, B, C] using
          (firstPivotNeighborHom_eq_zero_iff (p := p)
            A B C qv v hv hvnonzero u)
  | inr z =>
      have hvx : (v.1 : ZMod p) = 0 := by
        have h := congrArg Prod.fst hreduce
        simpa [v, reduceTriple, brandtSecondDirectionVector, thinToBrandtSecondMod,
          projectiveDirectionVector] using h
      have hA : (A : ZMod p) = 0 := by
        dsimp [A]
        push_cast
        rw [hvx]
        ring
      have hvy : (v.2.1 : ZMod p) = (1 - z) / 2 := by
        have h := congrArg (fun w => w.2.1) hreduce
        simpa [v, reduceTriple, brandtSecondDirectionVector,
          thinToBrandtSecondMod, projectiveDirectionVector] using h
      have hvz : (v.2.2 : ZMod p) = z := by
        have h := congrArg (fun w => w.2.2) hreduce
        simpa [v, reduceTriple, brandtSecondDirectionVector,
          thinToBrandtSecondMod, projectiveDirectionVector] using h
      have hBvalue : (B : ZMod p) = 4 := by
        dsimp [B]
        push_cast
        rw [hvy, hvz]
        field_simp [relation_two_ne_zero (p := p) hp2]
        ring
      have hB : (B : ZMod p) ≠ 0 := by
        rw [hBvalue]
        exact relation_four_ne_zero (p := p) hp2
      obtain ⟨qv, hv⟩ :=
        (secondPivotKernel_iff (p := p) hA hB v).1 hvpolar
      refine ⟨secondPivotRelationGenerator (p := p) qv v, ?_, ?_⟩
      · simp [secondPivotRelationGenerator]
      · intro u
        simpa [secondBrandtNeighborHom, A, B, C] using
          (secondPivotNeighborHom_eq_zero_iff (p := p)
            B C qv v hv hvnonzero u)

/-- The complete fused occurrence carrier retains one generated relation in
each source-addressed fibre. -/
theorem BrandtNeighborOccurrence.relationGenerator_exists (hp2 : p ≠ 2)
    (occurrence : BrandtNeighborOccurrence (p := p)) :
    ∃ g : NeighborCoordinates,
      g.2.2.2 = (p : ℤ) ∧
      ∀ u : NeighborCoordinates,
        brandtNeighborCoordinateHom hp2 occurrence u = 0 ↔
          ∃ k : ℤ, u = k • g := by
  cases occurrence with
  | inl d =>
      simpa [brandtNeighborCoordinateHom] using
        firstBrandtNeighbor_relationGenerator_exists hp2 d
  | inr d =>
      simpa [brandtNeighborCoordinateHom] using
        secondBrandtNeighbor_relationGenerator_exists hp2 d

#print axioms firstPivotNeighborHom_eq_zero_iff
#print axioms secondPivotNeighborHom_eq_zero_iff
#print axioms firstBrandtNeighbor_relationGenerator_exists
#print axioms secondBrandtNeighbor_relationGenerator_exists
#print axioms BrandtNeighborOccurrence.relationGenerator_exists

end Soma.Holonics.Millennium.FamilyTunnellBrandtRelationKernel
