import ElementaryHolonics.Millennium.MestreForcedSectionIncidence

/-!
# Mestre's completed square as a derived polynomial transport

The large coefficients displayed by a concrete Mestre surface are not primitive data.  They are a
receiver rendering of a triangular recurrence.  For a monic degree-twelve polynomial

`p(x) = x¹² + p₁₁x¹¹ + ⋯`,

the six downward equations in this file construct the unique monic degree-six polynomial `g`
whose square agrees with `p` in degrees `12` through `6`.  Consequently `g²-p` has outer degree at
most five; the two exact symmetric conditions on a Mestre sextuple subsequently remove degree five
and expose the elliptic quartic.

This is the algorithmic owner behind the concrete engine coefficients.  Source-specific integer
tables are codec receipts, not the definition of the surface.
-/

noncomputable section

namespace Soma.Holonics.Millennium.MestreCompletedSquare

open Soma.Holonics.Millennium.MestreForcedSectionIncidence

/-- [definition] Exact halving in the coefficient line.  This is scalar transport by the rational
`1/2`, not Euclidean division in the polynomial ring `ℚ[T]`. -/
def half (q : ParameterPolynomial) : ParameterPolynomial :=
  (1 / 2 : ℚ) • q

/-- [proved-derived; formal-checked] Exact halving reconstructs after the two oriented copies are
recombined. -/
@[simp] theorem half_add_half (q : ParameterPolynomial) : half q + half q = q := by
  ext n
  norm_num [half]
  ring

@[simp] theorem half_mul_two (q : ParameterPolynomial) : half q * 2 = q := by
  simpa [mul_two] using half_add_half q

/-- [definition] The coefficient of `x⁵`, obtained by matching `x¹¹` in `g²=p`. -/
def g5 (p : FamilyPolynomial) : ParameterPolynomial := half (p.coeff 11)

/-- [definition] The coefficient of `x⁴`, obtained by matching `x¹⁰`. -/
def g4 (p : FamilyPolynomial) : ParameterPolynomial :=
  half (p.coeff 10 - g5 p ^ 2)

/-- [definition] The coefficient of `x³`, obtained by matching `x⁹`. -/
def g3 (p : FamilyPolynomial) : ParameterPolynomial :=
  half (p.coeff 9 - 2 * g5 p * g4 p)

/-- [definition] The coefficient of `x²`, obtained by matching `x⁸`. -/
def g2 (p : FamilyPolynomial) : ParameterPolynomial :=
  half (p.coeff 8 - (2 * g5 p * g3 p + g4 p ^ 2))

/-- [definition] The coefficient of `x`, obtained by matching `x⁷`. -/
def g1 (p : FamilyPolynomial) : ParameterPolynomial :=
  half (p.coeff 7 - (2 * g5 p * g2 p + 2 * g4 p * g3 p))

/-- [definition] The constant coefficient, obtained by matching `x⁶`. -/
def g0 (p : FamilyPolynomial) : ParameterPolynomial :=
  half (p.coeff 6 - (2 * g5 p * g1 p + 2 * g4 p * g2 p + g3 p ^ 2))

/-- [definition] The monic degree-six completed-square polynomial generated by the recurrence. -/
def completedSquareRoot (p : FamilyPolynomial) : FamilyPolynomial :=
  Polynomial.monomial 6 1 +
  Polynomial.monomial 5 (g5 p) +
  Polynomial.monomial 4 (g4 p) +
  Polynomial.monomial 3 (g3 p) +
  Polynomial.monomial 2 (g2 p) +
  Polynomial.monomial 1 (g1 p) +
  Polynomial.C (g0 p)

/-- [definition] The remainder generated by the completed-square recurrence. -/
def completedRemainder (p : FamilyPolynomial) : FamilyPolynomial :=
  completedSquareRoot p ^ 2 - p

/-- [proved-derived; formal-checked] Each paired root contributes one monic quadratic layer in
the outer `x` chart. -/
theorem pairedFactor_monic (centres : Fin 6 → ℚ) (index : Fin 6) :
    (pairedFactor centres index).Monic := by
  unfold pairedFactor
  have squareMonic :
      ((Polynomial.X - Polynomial.C (Polynomial.C (centres index))) ^ 2).Monic :=
    (Polynomial.monic_X_sub_C _).pow 2
  apply squareMonic.sub_of_left
  apply Polynomial.degree_lt_degree
  rw [Polynomial.natDegree_pow, Polynomial.natDegree_C,
    (Polynomial.monic_X_sub_C _).natDegree_pow, Polynomial.natDegree_X_sub_C]
  norm_num

/-- [proved-derived; formal-checked] The six addressed quadratic layers compose into one monic
degree-twelve family product. -/
theorem familyProduct_monic (centres : Fin 6 → ℚ) :
    (familyProduct centres).Monic := by
  unfold familyProduct
  apply Polynomial.monic_prod_of_monic
  intro index _
  exact pairedFactor_monic centres index

theorem pairedFactor_natDegree (centres : Fin 6 → ℚ) (index : Fin 6) :
    (pairedFactor centres index).natDegree = 2 := by
  unfold pairedFactor
  rw [Polynomial.natDegree_sub_eq_left_of_natDegree_lt]
  · rw [(Polynomial.monic_X_sub_C _).natDegree_pow, Polynomial.natDegree_X_sub_C]
  · rw [Polynomial.natDegree_pow, Polynomial.natDegree_C,
      (Polynomial.monic_X_sub_C _).natDegree_pow, Polynomial.natDegree_X_sub_C]
    norm_num

theorem familyProduct_natDegree (centres : Fin 6 → ℚ) :
    (familyProduct centres).natDegree = 12 := by
  rw [familyProduct, Polynomial.natDegree_prod_of_monic]
  · simp [pairedFactor_natDegree]
  · intro index _
    exact pairedFactor_monic centres index

theorem familyProduct_coeff_twelve (centres : Fin 6 → ℚ) :
    (familyProduct centres).coeff 12 = 1 := by
  have h := familyProduct_monic centres
  rw [Polynomial.Monic.def, Polynomial.leadingCoeff, familyProduct_natDegree] at h
  exact h

/-- [proved-derived; formal-checked] The generated square root has no coefficient beyond its six
constructed layers. -/
theorem completedSquareRoot_natDegree_le (p : FamilyPolynomial) :
    (completedSquareRoot p).natDegree ≤ 6 := by
  apply Polynomial.natDegree_le_iff_coeff_eq_zero.mpr
  intro n hn
  have h0 : 0 ≠ n := by omega
  have h1 : 1 ≠ n := by omega
  have h2 : 2 ≠ n := by omega
  have h3 : 3 ≠ n := by omega
  have h4 : 4 ≠ n := by omega
  have h5 : 5 ≠ n := by omega
  have h6 : 6 ≠ n := by omega
  simp [completedSquareRoot, Polynomial.coeff_monomial, Polynomial.coeff_C, h0, h1, h2, h3,
    h4, h5, h6, Ne.symm h0]

/-- [proved-derived; formal-checked] The monic leading coefficient cancels at degree twelve. -/
theorem completedRemainder_coeff_twelve (p : FamilyPolynomial)
    (monicTwelve : p.coeff 12 = 1) :
    (completedRemainder p).coeff 12 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, monicTwelve]

/-- [proved-derived; formal-checked] The first recurrence equation cancels degree eleven. -/
theorem completedRemainder_coeff_eleven (p : FamilyPolynomial) :
    (completedRemainder p).coeff 11 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, g5]

/-- [proved-derived; formal-checked] The second recurrence equation cancels degree ten. -/
theorem completedRemainder_coeff_ten (p : FamilyPolynomial) :
    (completedRemainder p).coeff 10 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, g4]
  have h := half_add_half (p.coeff 10 - g5 p * g5 p)
  linear_combination h

/-- [proved-derived; formal-checked] The third recurrence equation cancels degree nine. -/
theorem completedRemainder_coeff_nine (p : FamilyPolynomial) :
    (completedRemainder p).coeff 9 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, g3]
  have h := half_add_half (p.coeff 9 - 2 * g5 p * g4 p)
  linear_combination h

/-- [proved-derived; formal-checked] The fourth recurrence equation cancels degree eight. -/
theorem completedRemainder_coeff_eight (p : FamilyPolynomial) :
    (completedRemainder p).coeff 8 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, g2]
  have h := half_add_half
    (p.coeff 8 - (2 * g5 p * g3 p + g4 p * g4 p))
  linear_combination h

/-- [proved-derived; formal-checked] The fifth recurrence equation cancels degree seven. -/
theorem completedRemainder_coeff_seven (p : FamilyPolynomial) :
    (completedRemainder p).coeff 7 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, g1]
  have h := half_add_half
    (p.coeff 7 - (2 * g5 p * g2 p + 2 * g4 p * g3 p))
  linear_combination h

/-- [proved-derived; formal-checked] The final recurrence equation cancels degree six. -/
theorem completedRemainder_coeff_six (p : FamilyPolynomial) :
    (completedRemainder p).coeff 6 = 0 := by
  simp [completedRemainder, completedSquareRoot, pow_two, mul_add, add_mul,
    Polynomial.monomial_mul_monomial, Polynomial.coeff_monomial, g0]
  have h := half_add_half
    (p.coeff 6 - (2 * g5 p * g1 p + 2 * g4 p * g2 p + g3 p * g3 p))
  linear_combination h

/-- [proved-derived; formal-checked] Every high layer from six through twelve is cancelled by the
same triangular construction. -/
theorem completedRemainder_coeff_eq_zero_of_six_le (p : FamilyPolynomial)
    (monicTwelve : p.coeff 12 = 1) (n : ℕ) (lower : 6 ≤ n) (upper : n ≤ 12) :
    (completedRemainder p).coeff n = 0 := by
  interval_cases n <;>
    simp_all only [completedRemainder_coeff_six, completedRemainder_coeff_seven,
      completedRemainder_coeff_eight, completedRemainder_coeff_nine,
      completedRemainder_coeff_ten, completedRemainder_coeff_eleven,
      completedRemainder_coeff_twelve]

/-- [proved-derived; formal-checked] For a monic degree-at-most-twelve source, the completed-square
remainder has degree at most five.  No expanded coefficient table enters the theorem. -/
theorem completedRemainder_natDegree_le_five (p : FamilyPolynomial)
    (sourceDegree : p.natDegree ≤ 12) (monicTwelve : p.coeff 12 = 1) :
    (completedRemainder p).natDegree ≤ 5 := by
  apply Polynomial.natDegree_le_iff_coeff_eq_zero.mpr
  intro n hn
  by_cases upper : n ≤ 12
  · exact completedRemainder_coeff_eq_zero_of_six_le p monicTwelve n (by omega) upper
  · rw [completedRemainder, Polynomial.coeff_sub,
      Polynomial.coeff_eq_zero_of_natDegree_lt,
      Polynomial.coeff_eq_zero_of_natDegree_lt]
    · simp
    · omega
    · have rootSquareDegree : (completedSquareRoot p ^ 2).natDegree ≤ 12 := by
        exact (Polynomial.natDegree_pow_le_of_le 2 (completedSquareRoot_natDegree_le p))
      omega

/-- [proved-derived; formal-checked] Every six-centre source therefore reaches the degree-five
receiver without any source-specific expanded coefficient table. -/
theorem familyCompletedRemainder_natDegree_le_five (centres : Fin 6 → ℚ) :
    (completedRemainder (familyProduct centres)).natDegree ≤ 5 :=
  completedRemainder_natDegree_le_five (familyProduct centres)
    (by rw [familyProduct_natDegree]) (familyProduct_coeff_twelve centres)

section Audit

#print axioms completedRemainder_coeff_twelve
#print axioms completedRemainder_coeff_eleven
#print axioms completedRemainder_coeff_ten
#print axioms completedRemainder_coeff_nine
#print axioms completedRemainder_coeff_eight
#print axioms completedRemainder_coeff_seven
#print axioms completedRemainder_coeff_six
#print axioms completedRemainder_coeff_eq_zero_of_six_le
#print axioms completedRemainder_natDegree_le_five

end Audit

end Soma.Holonics.Millennium.MestreCompletedSquare
