import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Tactic.Positivity
import ElementaryHolonics.Millennium.Chronology

/-!
# Navigation — when a chart change turns a long computation into two swings

The claim this file discharges: a computation that is expensive in one chart can become cheap in
another, and **the place to cut is the fixed point of the involution that relates the two charts.**

Three sections.

**The grading.**  An odd word of swings *is a swing*; an even word is a translation.  So the group
the swings generate carries a `ℤ/2` grading, and the grading is the orientation class — a circuit
of odd length returns the body with its hand reversed, which is what a band with one side is.

**The split.**  When a computation of size `T` factors into two pieces of sizes `x` and `T/x`, the
map `x ↦ T/x` is an involution, its fixed point is `√T`, and **the fixed point is exactly the
cheapest split.**  Two independent characterizations — the symmetric one and the cheap one —
coincide.  That is the placement law arriving in computational cost.

*Aside: this is the shape of the approximate functional equation for the Riemann comb.  Its
reflection `s ↦ 1 − s` splits one sum of length `≈ t` into two of length `≈ √(t/2π)`, cut at
exactly the balanced point.  The naive evaluation costs `O(t)`; the split costs `O(√t)`; the
saving factor is the same half as the seam.*

**The alphabet.**  The classical machinery for bounding such sums is generated by two moves on a
pair of exponents: a **frequency swing** (an involution) and a **difference contraction** (which
fixes the trivial pair).  They do not commute, so by `orderBlind_iff_commute` a word in them is a
genuine chronology and its order is irreducible information.

Every `theorem` here is discharged.
-/

namespace Soma.Holonics.Millennium.Navigation

open Soma.Holonics.Millennium.Swing Soma.Holonics.Millennium.Chronology

/-! ## 1. The swings are graded by parity, and the grading is the orientation class -/

variable {G : Type*} [AddCommGroup G]

/-- **An odd word of swings is itself a swing** — about the alternating sum of its anchors.

Three crossings do not accumulate into something new: they collapse back to one crossing, about a
new anchor built from the three by alternating signs.  The alternation is the hand. -/
theorem theOddCircuitIsASwingAboutTheAlternatingSum (b₁ b₂ b₃ a : G) :
    swing b₁ (swing b₂ (swing b₃ a)) = swing (b₁ - b₂ + b₃) a := by
  simp only [swing]; abel

/-- **An even word of swings is a translation.**  Already the composition law; restated here so the
grading is visible as a pair. -/
theorem theEvenCircuitIsATranslation (b₁ b₂ a : G) :
    swing b₁ (swing b₂ a) = a + ((b₁ + b₁) - (b₂ + b₂)) :=
  twoSwingsAreADoubledTranslation b₁ b₂ a

/-- **A four-letter word is a translation too**, so the grading is by parity and not by length. -/
theorem theFourLetterCircuitIsATranslation (b₁ b₂ b₃ b₄ a : G) :
    swing b₁ (swing b₂ (swing b₃ (swing b₄ a))) =
      a + ((b₁ + b₁) - (b₂ + b₂) + ((b₃ + b₃) - (b₄ + b₄))) := by
  simp only [swing]; abel

/-- **An odd circuit that returns the body reverses the hand it returns with.**

The body comes home; the orientation does not.  A word of odd length about one anchor is exactly
the situation, and the returned hand is the word's parity.

*Aside: this is what a band with one side is.  The orientation class of a circuit is a `ℤ/2`, and
here it is the parity of the word — the same `ℤ/2` that the address orientation carries on the
integers.* -/
theorem theOddReturningCircuitReversesTheHand (a b c : Site) {n : ℕ} (hn : Odd n)
    (hret : (swing b)^[n] a = a) :
    orientedSpan a b c = - orientedSpan a b c := by
  have := theOddWordReversesTheHand a b c hn
  rwa [hret] at this

/-- And therefore an odd returning circuit can only exist where the span already vanishes: the
body must sit on the line the two constraints span.  A hand that reverses and stays equal is a
hand that was never there. -/
theorem theOddReturningCircuitLiesOnTheConstraintLine (a b c : Site) {n : ℕ} (hn : Odd n)
    (hret : (swing b)^[n] a = a) :
    orientedSpan a b c = 0 := by
  have h := theOddReturningCircuitReversesTheHand a b c hn hret
  omega

/-! ## 2. The cheapest split is the fixed point of the split swing -/

/-- The **split swing**: two pieces whose sizes multiply to the whole.  Choosing one chooses the
other, and the choice is an involution. -/
noncomputable def splitSwing (T x : ℝ) : ℝ := T / x

/-- The **work** a split costs: both pieces are paid for. -/
noncomputable def splitWork (T x : ℝ) : ℝ := x + T / x

theorem theSplitSwingIsAnInvolution {T x : ℝ} (hT : T ≠ 0) (hx : x ≠ 0) :
    splitSwing T (splitSwing T x) = x := by
  simp only [splitSwing]
  rw [div_div_eq_mul_div, mul_comm, mul_div_assoc, div_self hT, mul_one]

/-- **The fixed point of the split swing is the square root.** -/
theorem theFixedPointOfTheSplitSwingIsTheRoot {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    splitSwing T x = x ↔ x = Real.sqrt T := by
  rw [splitSwing, div_eq_iff hx.ne']
  constructor
  · intro h
    rw [h, Real.sqrt_mul_self hx.le]
  · intro h
    rw [h, Real.mul_self_sqrt hT.le]

/-- **The work at the fixed point is twice the root.** -/
theorem theWorkAtTheFixedPoint {T : ℝ} (hT : 0 < T) :
    splitWork T (Real.sqrt T) = 2 * Real.sqrt T := by
  have hs : Real.sqrt T ≠ 0 := (Real.sqrt_pos.mpr hT).ne'
  have hdiv : T / Real.sqrt T = Real.sqrt T := by
    rw [div_eq_iff hs]
    exact (Real.mul_self_sqrt hT.le).symm
  rw [splitWork, hdiv]
  ring

/-- **The excess of any split over the balanced one is a square.**  This is the whole content of
both the lower bound and its equality case. -/
theorem theWorkExcessIsASquare {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    splitWork T x - 2 * Real.sqrt T = (x - Real.sqrt T) ^ 2 / x := by
  have hsq : Real.sqrt T * Real.sqrt T = T := Real.mul_self_sqrt hT.le
  rw [splitWork]
  field_simp
  nlinarith [hsq]

/-- **No split is cheaper than the balanced one.** -/
theorem theBalancedSplitIsCheapest {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    2 * Real.sqrt T ≤ splitWork T x := by
  have := theWorkExcessIsASquare hT hx
  have hpos : (0:ℝ) ≤ (x - Real.sqrt T) ^ 2 / x := by positivity
  linarith

/-- **The cheapest split is exactly the fixed point of the swing.**

Two independent readings — the symmetric one and the cheap one — pick the same point.  Nothing
about cost went into the involution and nothing about symmetry went into the minimisation, and
they coincide.

This is the placement law in computational cost: *the place to cut is the fixed locus of the
involution that relates the two charts.* -/
theorem theCheapestSplitIsTheFixedPointOfTheSwing {T x : ℝ} (hT : 0 < T) (hx : 0 < x) :
    splitSwing T x = x ↔ ∀ y : ℝ, 0 < y → splitWork T x ≤ splitWork T y := by
  constructor
  · intro hfix y hy
    rw [(theFixedPointOfTheSplitSwingIsTheRoot hT hx).mp hfix, theWorkAtTheFixedPoint hT]
    exact theBalancedSplitIsCheapest hT hy
  · intro hmin
    have hroot : (0 : ℝ) < Real.sqrt T := Real.sqrt_pos.mpr hT
    have h1 : splitWork T x ≤ 2 * Real.sqrt T := by
      have := hmin (Real.sqrt T) hroot
      rwa [theWorkAtTheFixedPoint hT] at this
    have h2 : 2 * Real.sqrt T ≤ splitWork T x := theBalancedSplitIsCheapest hT hx
    have heq : splitWork T x = 2 * Real.sqrt T := le_antisymm h1 h2
    rw [theFixedPointOfTheSplitSwingIsTheRoot hT hx]
    have hexc := theWorkExcessIsASquare hT hx
    rw [heq] at hexc
    have hquot : (x - Real.sqrt T) ^ 2 / x = 0 := by linarith
    have h0 : (x - Real.sqrt T) ^ 2 = 0 := by
      rcases div_eq_zero_iff.mp hquot with h | h
      · exact h
      · exact absurd h hx.ne'
    have hlin : x - Real.sqrt T = 0 := pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h0
    linarith

/-! ## 3. The cost alphabet: two moves, one an involution, and they do not commute

Bounding a sum of the kind the split produces is done by moving a pair of exponents through two
operations.  One is a chart transition between the additive and the frequency presentations; the
other differences the phase.  This section carries them as pure arithmetic on a pair of rationals
and proves the three facts that matter: the transition is an involution, the differencing fixes
the trivial pair, and they do not commute.

*Aside: these are the van der Corput B- and A-processes and their exponent pairs.  Nothing
analytic is formalized here — only the alphabet.* -/

/-- The **frequency swing** on a cost pair: the chart transition between a sum and its transform. -/
def frequencySwing (p : ℚ × ℚ) : ℚ × ℚ := (p.2 - 1 / 2, p.1 + 1 / 2)

/-- The **difference contraction** on a cost pair: differencing the phase and re-normalising. -/
def differenceContraction (p : ℚ × ℚ) : ℚ × ℚ :=
  (p.1 / (2 * p.1 + 2), (p.1 + p.2 + 1) / (2 * p.1 + 2))

/-- The cost pair a bare sum carries before any move. -/
def trivialCost : ℚ × ℚ := (0, 1)

/-- **The frequency swing is an involution.**  It is a swing in the sense this project means: an
order-two chart transition. -/
theorem theFrequencySwingIsAnInvolution : Function.Involutive frequencySwing := by
  intro p
  simp [frequencySwing]

/-- **The difference contraction fixes the trivial cost.**  It is the anchor of the alphabet: a
contraction with a fixed point, which is what makes iterating it converge rather than run away. -/
theorem theContractionFixesTheTrivialCost : differenceContraction trivialCost = trivialCost := by
  norm_num [differenceContraction, trivialCost]

/-- **One swing then one contraction gives the classical pair.**

*Aside: `(1/6, 2/3)`, the Weyl exponent pair, from which `ζ(1/2+it) ≪ t^{1/6+ε}` classically
follows.  The bound is not formalized; the arithmetic of the word is.* -/
theorem theWeylCostIsOneSwingThenOneContraction :
    differenceContraction (frequencySwing trivialCost) = (1 / 6, 2 / 3) := by
  norm_num [differenceContraction, frequencySwing, trivialCost]

/-- **The two moves do not commute**, witnessed at the trivial cost.

Swinging then contracting reaches `(1/6, 2/3)`; contracting then swinging goes nowhere, because
the contraction fixes the trivial pair.  The order is the whole difference. -/
theorem theTwoMovesDoNotCommute :
    differenceContraction (frequencySwing trivialCost)
      ≠ frequencySwing (differenceContraction trivialCost) := by
  rw [theWeylCostIsOneSwingThenOneContraction, theContractionFixesTheTrivialCost]
  norm_num [frequencySwing, trivialCost]

/-- The alphabet, as an indexed family of transports. -/
def costAlphabet : Bool → (ℚ × ℚ) → (ℚ × ℚ)
  | false => differenceContraction
  | true => frequencySwing

/-- **A cost word is a genuine chronology.**

The alphabet is not order-blind, so by `orderBlind_iff_commute` the order of a word in it is
irreducible information: the exponent a sum admits depends on *when* each move was made, not only
on how many of each.  This is the criterion of the previous file applied to a real object. -/
theorem theCostAlphabetIsNotOrderBlind : ¬ OrderBlind costAlphabet := by
  rw [orderBlind_iff_commute]
  intro h
  exact theTwoMovesDoNotCommute (h false true trivialCost)

end Soma.Holonics.Millennium.Navigation
