import Mathlib.Data.ZMod.Basic
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Tactic

/-!
# A tower, defined: a chain of prime-index rungs, and its rungs are half-turns

Brandon, 2026-08-23: *"Define 'Tower' mathematically… a tower is a winding lattice generally."*
He is right, and the coincidence is not semantic.

**The definition.**  A *tower* in a group `G` is a finite descending chain of subgroups

```text
G = G₀ ⊇ G₁ ⊇ ⋯ ⊇ G_h = 1 ,    G_{k+1} ⊴ G_k ,    [G_k : G_{k+1}] prime.
```

Its *height* is `h`, and by Jordan–Hölder the multiset of indices is an invariant of `G`, not of
the chain — which is why a height is a property of the object and a chain is a presentation of it.
A tower of fields is the same object read through the Galois correspondence, order-reversed.

**The tower this campaign runs on** is the 2-tower of `𝔽ₚˣ`, `G_k = (𝔽ₚˣ)^{2^k}`, the image of the
`2^k`-power map.  Every rung has index exactly `2` while `2^{k+1} ∣ p − 1`, so the height is
`v₂(p − 1)`.

**Why the rungs are half-turns, which is his "winding lattice".**  The `2^k`-power map has kernel
`μ_{2^k}`, the `2^k`-th roots of unity, so beside the descending tower of images there is an
*ascending* tower of kernels

```text
1 = μ₁ ⊆ μ₂ ⊆ μ₄ ⊆ ⋯ ⊆ μ_{2^h} ,     |G_k| · |μ_{2^k}| = p − 1 ,
```

and `μ_{2^{k+1}}` is generated by a rotation of half the angle that generates `μ_{2^k}`.
**Climbing one rung halves the turn.**  The height is therefore the number of times a full turn can
be halved inside the group before it closes — a winding count, exactly as he says, and the same
`√` half-density the corpus already carries at `2(θ + π) ≡ 2θ`.  The two towers are dual: the
product of the cards is constant, proved below.

**Procedural and structural are the same tower with the rung index as the parameter.**  Building a
rung *is* adjoining a square root, i.e. a degree-`2` covering with fibre `μ₂ = {±1}`; the unrolled
process is the covering tower and the deck group of the whole is `(ℤ/2)^h`.  That grading group,
graded by symmetric difference, is the crossing-word algebra the corpus already owns, and the
cross product is its lowest nontrivial grade — which is the joint he names between the swing and
the tower.

**And `prime` is not about `ℕ`.**  It is the indecomposable generator of any monoid with unique
factorization: primes of `ℕ` under multiplication, simple groups under composition series
(Jordan–Hölder), prime knots under connected sum (Schubert), prime ideals under intersection.  All
four are free generators of a factorization monoid — the prime axes, with `ℕ` one instance.  A
presentation such as `17 = 2^{2²} + 1` is one word among many for the same object; what the
quotient by re-presentation retains is a *modulus*, in the sense already deposited at
`research/records/2026-08-16_THE_JUNCTION_IS_A_HALF_TWIST_AND_A_MODULUS_IS_WHAT_A_DECLARED_QUOTIENT_RETAINS.md`.

Everything below is decided in the kernel at seventeen, the maximal case: `17 − 1 = 2^{2²}`, so the
whole group is one tower and there is nothing else in it.
-/

namespace Soma.Holonics.Millennium.PrimeTower

open Finset

/-- The `k`-th rung of the 2-tower at `p`: the image of the `2^k`-power map on `𝔽ₚˣ`. -/
def rung (p : ℕ) [NeZero p] (k : ℕ) : Finset (ZMod p) :=
  (univ.filter (fun x : ZMod p => x ≠ 0)).image (fun x => x ^ (2 ^ k))

/-- The `k`-th co-rung: the `2^k`-th roots of unity, the kernel of the same map. -/
def corung (p : ℕ) [NeZero p] (k : ℕ) : Finset (ZMod p) :=
  univ.filter (fun x : ZMod p => x ≠ 0 ∧ x ^ (2 ^ k) = 1)

/-! ## 1.  Seventeen is a single tower of height `2²` -/

/-- `17 − 1 = 2^{2²}`: the whole of `𝔽₁₇ˣ` is a 2-tower, with no other prime rung anywhere. -/
theorem theOrderIsAPureTwoPower : (17 : ℕ) - 1 = 2 ^ (2 ^ 2) := by norm_num

/-- **THE DESCENDING TOWER**, rung by rung: `16, 8, 4, 2, 1`. -/
theorem theRungCards :
    (rung 17 0).card = 16 ∧ (rung 17 1).card = 8 ∧ (rung 17 2).card = 4 ∧
    (rung 17 3).card = 2 ∧ (rung 17 4).card = 1 := by decide

/-- **THE ASCENDING CO-TOWER** of roots of unity: `1, 2, 4, 8, 16`. -/
theorem theCorungCards :
    (corung 17 0).card = 1 ∧ (corung 17 1).card = 2 ∧ (corung 17 2).card = 4 ∧
    (corung 17 3).card = 8 ∧ (corung 17 4).card = 16 := by decide

/-- **EVERY RUNG HAS INDEX `2`.**  That is what makes the chain a tower rather than a filtration:
each step is a single prime, so each step is one bit. -/
theorem theEveryRungHasIndexTwo :
    (rung 17 0).card = 2 * (rung 17 1).card ∧
    (rung 17 1).card = 2 * (rung 17 2).card ∧
    (rung 17 2).card = 2 * (rung 17 3).card ∧
    (rung 17 3).card = 2 * (rung 17 4).card := by decide

/-- **THE CHAIN DESCENDS.** -/
theorem theChainDescends :
    rung 17 1 ⊆ rung 17 0 ∧ rung 17 2 ⊆ rung 17 1 ∧
    rung 17 3 ⊆ rung 17 2 ∧ rung 17 4 ⊆ rung 17 3 := by decide

/-- **THE CO-TOWER ASCENDS.** -/
theorem theCoChainAscends :
    corung 17 0 ⊆ corung 17 1 ∧ corung 17 1 ⊆ corung 17 2 ∧
    corung 17 2 ⊆ corung 17 3 ∧ corung 17 3 ⊆ corung 17 4 := by decide

/-- **THE TWO TOWERS ARE DUAL.**  Image times kernel is the whole group at every rung — the
order-reversing correspondence that makes the winding reading and the subgroup reading one object.
Halving the turn `k` times is the same as taking `2^k`-th powers. -/
theorem theTowerAndItsWindingsAreDual :
    (rung 17 0).card * (corung 17 0).card = 16 ∧
    (rung 17 1).card * (corung 17 1).card = 16 ∧
    (rung 17 2).card * (corung 17 2).card = 16 ∧
    (rung 17 3).card * (corung 17 3).card = 16 ∧
    (rung 17 4).card * (corung 17 4).card = 16 := by decide

/-! ## 2.  Where `2` sits in the tower, and why that is the obstruction -/

/-- **`2` IS ON THE FIRST RUNG AND NOT THE SECOND.**  It is a square and not a fourth power: it
has climbed one half-turn and cannot climb the next.  That single rung is the seventeen
obstruction. -/
theorem theTwoSitsOnTheFirstRungAndNoDeeper :
    (2 : ZMod 17) ∈ rung 17 1 ∧ (2 : ZMod 17) ∉ rung 17 2 := by decide

/-- The generator sits on rung `0` and nowhere deeper, as a generator must. -/
theorem theGeneratorSitsOnlyOnTheGroundRung :
    (3 : ZMod 17) ∈ rung 17 0 ∧ (3 : ZMod 17) ∉ rung 17 1 := by decide

/-- **THE RUNG OF AN ELEMENT IS ITS WINDING DEPTH.**  `2` has order `2³`, so it generates rung `1`
— the eight squares — and the half-turn `2^{2²} = −1` marks that its order is exactly `2³`. -/
theorem theRungOfTwoIsItsOrder :
    (2 : ZMod 17) ^ (2 ^ 3) = 1 ∧ (2 : ZMod 17) ^ (2 ^ 2) = -1 ∧
    rung 17 1 = (univ.filter (fun x : ZMod 17 => x ≠ 0)).image (fun x => x ^ 2) := by decide

/-! ## 3.  A tower is a chain because the lattice is totally ordered here -/

/-- **THE RUNGS ARE TOTALLY ORDERED**, which is what distinguishes a tower from a tree: in a cyclic
`2`-group the subgroup lattice is a chain, so there is exactly one subgroup of each admissible
order and no branching.  Exhibited at seventeen by cardinality: the five rungs have five distinct
cards, so the chain is strict. -/
theorem theRungsAreStrictlyNested :
    rung 17 4 ⊂ rung 17 3 ∧ rung 17 3 ⊂ rung 17 2 ∧
    rung 17 2 ⊂ rung 17 1 ∧ rung 17 1 ⊂ rung 17 0 := by decide

/-- Past the height the tower is stationary at the trivial rung — the height is where building
stops. -/
theorem theTowerStopsAtItsHeight : rung 17 5 = rung 17 4 ∧ (rung 17 4).card = 1 := by decide

/-! ## 4.  What the height decides -/

/-- A Fermat prime: the tower accounts for the whole group. -/
def IsFermatPrime (p : ℕ) : Prop := p.Prime ∧ ∃ k : ℕ, p - 1 = 2 ^ k

/-- **A FERMAT PRIME IS EXACTLY ONE WHOSE ONLY RUNG IS `2`.**  The tower is the whole group iff no
other prime index occurs anywhere in it — a statement about the *chain*, matching Jordan–Hölder's
statement about the object. -/
theorem theFermatPrimesAreTheMaximalTowers {p : ℕ} (hp : p.Prime) (hp2 : p ≠ 2) :
    IsFermatPrime p ↔ ∀ q : ℕ, q.Prime → q ∣ (p - 1) → q = 2 := by
  have hp3 : 3 ≤ p := by
    have := hp.two_le
    rcases Nat.lt_or_ge p 3 with h | h
    · interval_cases p <;> simp_all
    · exact h
  constructor
  · rintro ⟨-, k, hk⟩ q hq hdvd
    rw [hk] at hdvd
    exact (Nat.prime_dvd_prime_iff_eq hq Nat.prime_two).1 (hq.dvd_of_dvd_pow hdvd)
  · intro h
    refine ⟨hp, ⟨(p - 1).primeFactorsList.length, ?_⟩⟩
    exact Nat.eq_prime_pow_of_unique_prime_dvd (n := p - 1) (p := 2) (by omega)
      (fun {d} hd hdvd => h d hd hdvd)

/-- **AT HEIGHT ONE THE QUARTIC SYMBOL IS NOT A NEW INVARIANT.**  When `p ≡ 3 (mod 4)` — tower
height `1` — every square is already a fourth power, witnessed explicitly by `x^{(p+1)/4}`.  So a
quartic residue symbol carries information only from height `2` upward, which is why seventeen,
at height `2²`, supports one and why the obstruction there could not have appeared at a prime
with a shorter tower. -/
theorem theQuarticSymbolCollapsesAtHeightOne {p : ℕ} (hp : p.Prime) (h4 : p % 4 = 3)
    (x : ZMod p) (hx : x ≠ 0) : ∃ z : ZMod p, z ≠ 0 ∧ z ^ 4 = x ^ 2 := by
  haveI : Fact p.Prime := ⟨hp⟩
  have hp2 : 2 ≤ p := hp.two_le
  obtain ⟨k, hk⟩ : ∃ k, p + 1 = 4 * k := ⟨(p + 1) / 4, by omega⟩
  refine ⟨x ^ k, pow_ne_zero _ hx, ?_⟩
  rw [← pow_mul]
  have hf : x ^ (p - 1) = 1 := ZMod.pow_card_sub_one_eq_one hx
  calc x ^ (k * 4) = x ^ (p - 1 + 2) := by congr 1; omega
    _ = x ^ (p - 1) * x ^ 2 := pow_add _ _ _
    _ = x ^ 2 := by rw [hf, one_mul]

/-- And at seventeen it does not collapse: `2` climbed one rung and not the next.  The two
theorems together say the quartic symbol is a genuine second bit exactly when the tower has a
second rung. -/
theorem theQuarticSymbolIsANewBitAtSeventeen :
    (2 : ZMod 17) ∈ rung 17 1 ∧ (2 : ZMod 17) ∉ rung 17 2 ∧ rung 17 2 ≠ rung 17 1 := by decide

end Soma.Holonics.Millennium.PrimeTower
