import Mathlib.Algebra.Group.Subgroup.Ker
import ElementaryHolonics.Millennium.Coupling
import ElementaryHolonics.Millennium.Paying

/-!
# The hollow triangle — a chain with a real homology, and a form that descends onto it

The previous iteration predicted that the doubling chain would be the first test of the descent
criterion and that the answer would be negative.  **The prediction was wrong in a more useful
way: the doubling chain is exact, so its homology is trivial and the question is vacuous there.**
A form descends to the zero group for free and nothing is learned.

So this file supplies the test the question actually needs: a chain whose homology is genuinely
nonzero, on the smallest real object that has one — the **hollow triangle**, three vertices and
three edges with no filled face.  Its loop is the kernel of the boundary and nothing realizes it,
so the obstruction group is a copy of the integers.

Then the criterion is applied, and it holds: the realized population is trivial, so it lies in the
radical, so **the form descends onto the homology and is positive there.**  That is the weld — a
chain, a nonzero homology, and a paying pairing on it, on one object.

Every `theorem` here is discharged.
-/

namespace Soma.Holonics.Millennium.Triangle

open Soma.Holonics.Millennium Soma.Holonics.Millennium.Coupling
open Soma.Holonics.Millennium.Paying

/-- Coefficients on the three edges, and on the three vertices. -/
abbrev Cells : Type := ℤ × ℤ × ℤ

/-- The **boundary** of an edge chain, in vertex coordinates.

The three edges run `v₀→v₁`, `v₁→v₂`, `v₂→v₀`, so the boundary sends the edge basis to the vertex
differences and the three of them close a loop. -/
def boundary : Cells →+ Cells where
  toFun e := (-e.1 + e.2.2, e.1 - e.2.1, e.2.1 - e.2.2)
  map_zero' := rfl
  map_add' a b := by
    simp only [Prod.fst_add, Prod.snd_add, Prod.mk_add_mk, Prod.mk.injEq]
    exact ⟨by ring, by ring, by ring⟩

@[simp] theorem boundary_apply (e : Cells) :
    boundary e = (-e.1 + e.2.2, e.1 - e.2.1, e.2.1 - e.2.2) := rfl

/-- **The loop is exactly the kernel of the boundary**, and it is generated by the chain that runs
each edge once. -/
theorem theLoopIsTheKernel (e : Cells) : e ∈ boundary.ker ↔ ∃ n : ℤ, e = (n, n, n) := by
  constructor
  · intro h
    rw [AddMonoidHom.mem_ker, boundary_apply, Prod.ext_iff, Prod.ext_iff] at h
    obtain ⟨h1, h2, h3⟩ := h
    simp only at h1 h2 h3
    exact ⟨e.1, by obtain ⟨a, b, c⟩ := e; simp_all; omega⟩
  · rintro ⟨n, rfl⟩
    rw [AddMonoidHom.mem_ker, boundary_apply]
    simp

/-- **The loop is not nothing.**  The witness is the chain that runs each edge once. -/
theorem theLoopIsInhabited : ((1, 1, 1) : Cells) ∈ boundary.ker := by
  rw [AddMonoidHom.mem_ker, boundary_apply]
  simp

/-- The **hollow triangle chain**: nothing fills the face, and the boundary carries the edges to
the vertices. -/
def hollowTriangleChain : TransportChain PUnit Cells Cells where
  into := 0
  outOf := boundary
  composite_zero := by intro a; simp

@[simp] theorem hollowRealized : hollowTriangleChain.realized = ⊥ := by
  ext x
  simp [TransportChain.realized, hollowTriangleChain]

@[simp] theorem hollowRetained : hollowTriangleChain.retained = boundary.ker := rfl

/-- **The hollow triangle chain does not glue.**  Its retained population contains the loop and its
realized population is nothing, so there is a genuine obstruction. -/
theorem theHollowTriangleDoesNotGlue : ¬ hollowTriangleChain.toPassage.Glues := by
  intro h
  have h2 : ((1, 1, 1) : Cells) ∈ hollowTriangleChain.realized := h theLoopIsInhabited
  rw [hollowRealized, AddSubgroup.mem_bot, Prod.mk.injEq] at h2
  exact one_ne_zero h2.1

/-- **So its obstruction group — its homology — is not trivial.**  This is the nonzero homology the
descent question needed and the doubling chain could not supply. -/
theorem theHollowTriangleHomologyIsNontrivial :
    ¬ Subsingleton hollowTriangleChain.toPassage.ObstructionGroup := fun h =>
  theHollowTriangleDoesNotGlue
    ((AdditivePassage.glues_iff_obstruction_subsingleton _).mpr h)

/-! ## The form, and its descent onto the homology -/

/-- The standard pairing on cell chains, one slot fixed. -/
def formOn (e : Cells) : Cells →+ ℚ :=
  AddMonoidHom.mk' (fun f => ((e.1 * f.1 + e.2.1 * f.2.1 + e.2.2 * f.2.2 : ℤ) : ℚ)) (by
    intro a b
    simp only [Prod.fst_add, Prod.snd_add]
    push_cast
    ring)

@[simp] theorem formOn_apply (e f : Cells) :
    formOn e f = ((e.1 * f.1 + e.2.1 * f.2.1 + e.2.2 * f.2.2 : ℤ) : ℚ) := rfl

/-- The standard pairing on cell chains, bilinear. -/
def standardForm : Cells →+ (Cells →+ ℚ) :=
  AddMonoidHom.mk' formOn (by
    intro a b
    ext f
    simp only [AddMonoidHom.add_apply, formOn_apply, Prod.fst_add, Prod.snd_add]
    push_cast
    ring)

@[simp] theorem standardForm_apply (e f : Cells) :
    standardForm e f = ((e.1 * f.1 + e.2.1 * f.2.1 + e.2.2 * f.2.2 : ℤ) : ℚ) := rfl

/-- **The hollow triangle, as a compressed positivity datum.**  The aperture admits nothing; the
retained remainder is the loop; the form is the standard pairing and it is positive there. -/
def hollowTriangleDatum : CompressedPositivity Cells where
  form := standardForm
  form_symm := by
    intro a b
    simp only [standardForm_apply]
    push_cast
    ring
  cutoff := ⊥
  remainder := boundary.ker
  orthogonal := by
    intro c hc v _
    rw [AddSubgroup.mem_bot] at hc
    subst hc
    simp
  sign := 1
  sign_unit := Or.inl rfl
  definite := by
    intro v _
    simp only [one_mul, standardForm_apply]
    have : (0 : ℤ) ≤ v.1 * v.1 + v.2.1 * v.2.1 + v.2.2 * v.2.2 := by
      nlinarith [mul_self_nonneg v.1, mul_self_nonneg v.2.1, mul_self_nonneg v.2.2]
    exact_mod_cast this

/-- **The criterion holds: what the chain realized lies in the radical.**

The realized population is nothing, so it pairs with everything retained to nothing, and by
`theFormDescendsIffTheQuotientedIsInTheRadical` the form descends onto the homology. -/
theorem theRealizedLiesInTheRadical :
    ∀ r ∈ hollowTriangleChain.realized, ∀ w ∈ hollowTriangleDatum.remainder,
      hollowTriangleDatum.form r w = 0 := by
  intro r hr w _
  rw [hollowRealized, AddSubgroup.mem_bot] at hr
  subst hr
  simp [hollowTriangleDatum]

/-- **Therefore the form descends onto the homology.** -/
theorem theFormDescendsOntoTheHomology :
    ∀ v ∈ hollowTriangleDatum.remainder, ∀ r ∈ hollowTriangleChain.realized,
      ∀ w ∈ hollowTriangleDatum.remainder,
        hollowTriangleDatum.form (v + r) w = hollowTriangleDatum.form v w :=
  (hollowTriangleDatum.theFormDescendsIffTheQuotientedIsInTheRadical
    hollowTriangleChain.realized (by rw [hollowRealized]; exact bot_le)).mpr
    theRealizedLiesInTheRadical

/-- **And it pays there.**  The loop class pairs with itself to three — one for each edge it
crosses — so the homology carries a strictly positive self-pairing and is seen. -/
theorem theLoopClassPaysThree :
    hollowTriangleDatum.form ((1, 1, 1) : Cells) ((1, 1, 1) : Cells) = 3 := by
  simp [hollowTriangleDatum]

/-- **The radical of the form on the loop is trivial**, so the datum is faithful and its paying
pairing exists: every nonzero loop class is seen. -/
theorem theLoopRadicalIsTrivial : ∀ v ∈ hollowTriangleDatum.radical, v = 0 := by
  rintro v ⟨hv, h0⟩
  have := h0 v hv
  simp only [hollowTriangleDatum, standardForm_apply] at this
  have hz : v.1 * v.1 + v.2.1 * v.2.1 + v.2.2 * v.2.2 = 0 := by exact_mod_cast this
  obtain ⟨a, b, c⟩ := v
  simp only at hz
  have ha : a = 0 := by nlinarith [mul_self_nonneg a, mul_self_nonneg b, mul_self_nonneg c]
  have hb : b = 0 := by nlinarith [mul_self_nonneg a, mul_self_nonneg b, mul_self_nonneg c]
  have hc : c = 0 := by nlinarith [mul_self_nonneg a, mul_self_nonneg b, mul_self_nonneg c]
  simp [ha, hb, hc]

/-! ## The boundary-pullback form: a nonzero radical, taken from the object

The trichotomy's interesting rows need a form whose radical is **not** trivial, and the radical
must come from the object rather than be authored onto it.  The boundary supplies one: pair two
edge chains by pairing their boundaries.  Its radical is then exactly the cycles, which is a
property of the complex and of nothing else. -/

/-- A sum of three integer squares vanishes only when each does. -/
private theorem sumSqZero {a b c : ℤ} (h : a * a + b * b + c * c = 0) :
    a = 0 ∧ b = 0 ∧ c = 0 := by
  refine ⟨?_, ?_, ?_⟩ <;>
    nlinarith [mul_self_nonneg a, mul_self_nonneg b, mul_self_nonneg c]

/-- The **boundary-pullback form**: pair two edge chains by pairing their boundaries. -/
def pullbackForm : Cells →+ (Cells →+ ℚ) :=
  AddMonoidHom.mk' (fun e => (standardForm (boundary e)).comp boundary) (by
    intro a b
    ext f
    simp only [AddMonoidHom.comp_apply, AddMonoidHom.add_apply, map_add, standardForm_apply,
      boundary_apply])

@[simp] theorem pullbackForm_apply (e f : Cells) :
    pullbackForm e f = standardForm (boundary e) (boundary f) := rfl

/-- **The hollow triangle under the boundary-pullback form**, with everything retained. -/
def pullbackDatum : CompressedPositivity Cells where
  form := pullbackForm
  form_symm := by
    intro a b
    simp only [pullbackForm_apply, standardForm_apply]
    push_cast
    ring
  cutoff := ⊥
  remainder := ⊤
  orthogonal := by
    intro c hc v _
    rw [AddSubgroup.mem_bot] at hc
    subst hc
    show pullbackForm 0 v = 0
    rw [map_zero]
    rfl
  sign := 1
  sign_unit := Or.inl rfl
  definite := by
    intro v _
    simp only [one_mul, pullbackForm_apply, standardForm_apply]
    have : (0 : ℤ) ≤ (boundary v).1 * (boundary v).1 + (boundary v).2.1 * (boundary v).2.1
        + (boundary v).2.2 * (boundary v).2.2 := by
      nlinarith [mul_self_nonneg (boundary v).1, mul_self_nonneg (boundary v).2.1,
        mul_self_nonneg (boundary v).2.2]
    exact_mod_cast this

/-- **The radical of the pullback form is exactly the cycles.**

A chain pairs with everything to nothing exactly when its own boundary vanishes.  The radical is
therefore a property the complex already had, not one the form was built to have. -/
theorem thePullbackRadicalIsTheCycles (e : Cells) :
    e ∈ pullbackDatum.radical ↔ e ∈ boundary.ker := by
  constructor
  · rintro ⟨-, h⟩
    have hself := h e (by trivial)
    simp only [pullbackDatum, pullbackForm_apply, standardForm_apply] at hself
    have hz : (boundary e).1 * (boundary e).1 + (boundary e).2.1 * (boundary e).2.1
        + (boundary e).2.2 * (boundary e).2.2 = 0 := by exact_mod_cast hself
    rw [AddMonoidHom.mem_ker]
    obtain ⟨h1, h2, h3⟩ := sumSqZero hz
    exact Prod.ext h1 (Prod.ext h2 h3)
  · intro h
    rw [AddMonoidHom.mem_ker] at h
    refine ⟨trivial, ?_⟩
    intro w _
    show pullbackForm e w = 0
    rw [pullbackForm_apply, h, map_zero]
    rfl

/-- **And that radical is not zero.**  The loop is a cycle, so it is in the radical, and it is not
the zero chain.  This is the nonzero radical the trichotomy's interesting rows required. -/
theorem thePullbackRadicalIsNonzero :
    ((1, 1, 1) : Cells) ∈ pullbackDatum.radical ∧ ((1, 1, 1) : Cells) ≠ 0 := by
  refine ⟨(thePullbackRadicalIsTheCycles _).mpr theLoopIsInhabited, ?_⟩
  intro h
  exact one_ne_zero (congrArg Prod.fst h)

/-! ### All three rows of the trichotomy, on this one object -/

/-- **Row one — outside the radical: the form does not descend.**  A single edge is not a cycle and
pairs with itself to two. -/
theorem theTopIsNotInTheRadical :
    ¬ (∀ r ∈ (⊤ : AddSubgroup Cells), ∀ w ∈ pullbackDatum.remainder,
        pullbackDatum.form r w = 0) := by
  intro h
  have := h ((1, 0, 0) : Cells) trivial ((1, 0, 0) : Cells) trivial
  simp only [pullbackDatum, pullbackForm_apply, boundary_apply, standardForm_apply] at this
  norm_num at this

/-- **Row two — strictly inside the radical: the form descends, and the quotient keeps a null
class.**  Doubling the loop stays in the radical, and the loop itself is null but is not a multiple
of twice the loop. -/
theorem theDoubledLoopIsStrictlyInside :
    (∀ r ∈ AddSubgroup.zmultiples ((2, 2, 2) : Cells), ∀ w ∈ pullbackDatum.remainder,
      pullbackDatum.form r w = 0)
    ∧ ((1, 1, 1) : Cells) ∉ AddSubgroup.zmultiples ((2, 2, 2) : Cells) := by
  constructor
  · rintro r ⟨n, rfl⟩ w _
    have hker : (n • ((2, 2, 2) : Cells)) ∈ boundary.ker := by
      rw [AddMonoidHom.mem_ker, map_zsmul]
      simp [boundary_apply]
    exact ((thePullbackRadicalIsTheCycles _).mpr hker).2 w trivial
  · rintro ⟨n, hn⟩
    simp only [Prod.ext_iff, Prod.smul_mk, smul_eq_mul] at hn
    omega

/-- **A null self-pairing on the retained cycles lies in the radical.**

This is the local null-cone criterion; no quotient object or faithfulness result is constructed here.
-/
theorem theCyclesHaveTheRadicalNullCriterion :
    ∀ v ∈ pullbackDatum.remainder, pullbackDatum.sign * pullbackDatum.form v v = 0 →
      v ∈ pullbackDatum.radical :=
  fun v hv h => pullbackDatum.theNullOnTheRemainderIsTheRadical hv h

end Soma.Holonics.Millennium.Triangle
