import CMZDiagonalLocal
import CMGraphPrincipalCharts
import Mathlib.RingTheory.Localization.Away.Basic

/-!
# The actual graph-diagonal equation on the restricted Z chart

This source starts with the actual Weierstrass coordinate ring and the actual
product-diagonal kernel. Pulling that kernel along graphReceiver gives the
fixed-difference ideal; on the open where u^2 - 1 is invertible, the fixed
ideal is generated by v, and v is regular by the actual AdjoinRoot domain.
No ambient-regularity-under-pullback principle is used.
-/
noncomputable section
set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option Elab.async false
namespace Holonics.Hodge.CMGraphSource

abbrev ActualRestrictedZRing := Localization.Away (u ^ 2 - 1)

private theorem span_pair_unit_mul {R : Type*} [CommRing R]
    (a b x y : R) (ha : IsUnit a) (hb : IsUnit b) :
    Ideal.span ({a * x, b * y} : Set R) = Ideal.span ({x, y} : Set R) := by
  apply le_antisymm
  · apply Ideal.span_le.mpr
    intro z hz
    rcases Set.mem_insert_iff.mp hz with hz | hz
    · rw [hz]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))
    · rw [Set.mem_singleton_iff.mp hz]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))
  · apply Ideal.span_le.mpr
    intro z hz
    rcases Set.mem_insert_iff.mp hz with hz | hz
    · rw [hz]
      apply (Ideal.mul_unit_mem_iff_mem (Ideal.span ({a * x, b * y} : Set R)) ha).mp
      simpa [mul_comm] using
        (Ideal.subset_span (by simp : a * x ∈ ({a * x, b * y} : Set R)))
    · rw [Set.mem_singleton_iff.mp hz]
      apply (Ideal.mul_unit_mem_iff_mem (Ideal.span ({a * x, b * y} : Set R)) hb).mp
      simpa [mul_comm] using
        (Ideal.subset_span (by simp : b * y ∈ ({a * x, b * y} : Set R)))

@[simp] theorem graphReceiver_diagonal_u_actual :
    graphReceiver diagonalUEquation = algebraMap ℂ CurveRing (-2) * u := by
  simp [diagonalUEquation, iota]
  norm_num only [map_neg, map_ofNat]
  ring

/-- The ambient diagonal kernel becomes the actual fixed-difference ideal on
its graph receiver, with the two explicit transported coordinate equations. -/
theorem actualGraphDiagonal_map_eq_fixedIdeal :
    diagonalIdeal.map graphReceiver.toRingHom = fixedIdeal := by
  rw [diagonalIdeal_eq_two_equations, diagonalTwoEquationIdeal, Ideal.map_span]
  simp only [Set.image_insert_eq, Set.image_singleton]
  change Ideal.span {graphReceiver diagonalUEquation, graphReceiver diagonalVEquation} = fixedIdeal
  rw [graphReceiver_diagonal_u_actual, graphReceiver_diagonal_v,
    fixedIdeal_eq_zeroPointIdeal, zeroPointIdeal]
  have ha : IsUnit (algebraMap ℂ CurveRing (-2 : ℂ)) :=
    IsUnit.map (algebraMap ℂ CurveRing)
      (isUnit_iff_ne_zero.mpr (by norm_num : (-2 : ℂ) ≠ 0))
  have hb : IsUnit (algebraMap ℂ CurveRing (Complex.I - 1)) := by
    apply IsUnit.map
    apply isUnit_iff_ne_zero.mpr
    intro h
    have him := congrArg Complex.im h
    norm_num at him
  simpa only [Algebra.smul_def] using
    (span_pair_unit_mul (algebraMap ℂ CurveRing (-2 : ℂ))
      (algebraMap ℂ CurveRing (Complex.I - 1)) u v ha hb)

/-- Exact equation from the Weierstrass curve after mapping to the Z open. -/
theorem actualRestrictedZ_relation :
    u * (u ^ 2 - 1) = v ^ 2 := by
  rw [curve_relation]
  ring

theorem actualRestrictedZ_fixedIdeal_eq_v :
    (fixedIdeal.map (algebraMap CurveRing ActualRestrictedZRing)) =
      Ideal.span ({algebraMap CurveRing ActualRestrictedZRing v} : Set ActualRestrictedZRing) := by
  rw [fixedIdeal_eq_zeroPointIdeal, zeroPointIdeal, Ideal.map_span]
  simp only [Set.image_insert_eq, Set.image_singleton]
  rw [Ideal.span_pair_comm]
  exact two_equations_principal_of_unit
    (algebraMap CurveRing ActualRestrictedZRing)
    v u v (u ^ 2 - 1)
    (by simpa only [pow_two] using actualRestrictedZ_relation.symm)
    (IsLocalization.Away.algebraMap_isUnit (u ^ 2 - 1))

private theorem actualRestrictedZ_v_ne_zero : v ≠ 0 := by
  have hdeg : (Polynomial.X : Polynomial (Polynomial ℂ)).natDegree <
      squareCurve.toAffine.polynomial.natDegree := by
    rw [squareCurve.toAffine.natDegree_polynomial, Polynomial.natDegree_X]
    norm_num
  exact AdjoinRoot.mk_ne_zero_of_natDegree_lt
    squareCurve.toAffine.monic_polynomial Polynomial.X_ne_zero hdeg

/-- The generator is a non-zero-divisor in the base curve ring, proved from
its defining AdjoinRoot polynomial, then preserved by localization. -/
theorem actualRestrictedZ_v_regular :
    IsRegular (algebraMap CurveRing ActualRestrictedZRing v) := by
  have hv : IsRegular v := IsRegular.of_ne_zero actualRestrictedZ_v_ne_zero
  apply isRegular_iff_mem_nonZeroDivisors.mpr
  have hvmem : v ∈ nonZeroDivisors CurveRing :=
    isRegular_iff_mem_nonZeroDivisors.mp hv
  exact IsLocalization.nonZeroDivisors_le_comap (R := CurveRing)
    (Submonoid.powers (u ^ 2 - 1 : CurveRing)) ActualRestrictedZRing hvmem

/-- The same restricted equation, expressed as the actual ambient diagonal
kernel pulled back along the actual graph receiver. -/
theorem actualRestrictedZ_graphDiagonal_eq_v :
    ((diagonalIdeal.map graphReceiver.toRingHom).map
      (algebraMap CurveRing ActualRestrictedZRing)) =
      Ideal.span ({algebraMap CurveRing ActualRestrictedZRing v} : Set ActualRestrictedZRing) := by
  rw [actualGraphDiagonal_map_eq_fixedIdeal]
  exact actualRestrictedZ_fixedIdeal_eq_v

#print axioms actualGraphDiagonal_map_eq_fixedIdeal
#print axioms actualRestrictedZ_relation
#print axioms actualRestrictedZ_fixedIdeal_eq_v
#print axioms actualRestrictedZ_v_regular
#print axioms actualRestrictedZ_graphDiagonal_eq_v
end Holonics.Hodge.CMGraphSource
