import CMActualRestrictedYEquation
import CMYFixedPoint
import CMRestrictedOriginQuotient

/-! The actual fixed-point ideal on the selected Y chart is carried into the
localized ring, identified with the residue-kernel ideal, and consumed by the
shared origin-quotient construction. The output is a local quotient length,
not an intersection number or a Hodge-class claim. -/
noncomputable section
set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option Elab.async false
namespace Holonics.Hodge.CMGraphSource

abbrev yRestrictedOriginLocalization := YRestrictedQAway

def yRestrictedFixedIdeal : Ideal yRestrictedOriginLocalization :=
  Ideal.map (algebraMap YChartCubicRing yRestrictedOriginLocalization)
    yFixedDifferenceIdeal

theorem yOriginReceiver_ker_eq_zeroPointIdeal :
    RingHom.ker yOriginReceiver = yZeroPointIdeal := by
  apply le_antisymm
  · intro r hr
    change yOriginReceiver r = 0 at hr
    have hmap : yZeroPointCoordinateEquiv
        (Ideal.Quotient.mk yZeroPointIdeal r) = yOriginReceiver r := by
      change yOriginQuotientReceiver (Ideal.Quotient.mk yZeroPointIdeal r) = _
      rw [yOriginQuotientReceiver, Ideal.Quotient.liftₐ_apply, Ideal.Quotient.lift_mk]
      rfl
    have hquot : yZeroPointCoordinateEquiv
        (Ideal.Quotient.mk yZeroPointIdeal r) = 0 := by
      rw [hmap]
      exact hr
    have hzero : Ideal.Quotient.mk yZeroPointIdeal r = 0 := by
      apply yZeroPointCoordinateEquiv.injective
      simpa using hquot
    exact Ideal.Quotient.eq_zero_iff_mem.mp hzero
  · exact yZeroPointIdeal_le_originKernel

theorem yRestrictedCurveRelation :
    yRestrictedA ^ 3 - yRestrictedA * yRestrictedB ^ 2 - yRestrictedB = 0 := by
  have h := congrArg (algebraMap YChartCubicRing yRestrictedOriginLocalization)
    yDerivative_source_relation
  simpa only [map_sub, map_mul, map_pow, map_zero, yDerivativeA, yDerivativeB] using h

theorem yRestrictedB_mem_spanA :
    yRestrictedB ∈ Ideal.span {yRestrictedA} := by
  have hcurve : yRestrictedA ^ 3 - yRestrictedA * yRestrictedB ^ 2 = yRestrictedB :=
    sub_eq_zero.mp yRestrictedCurveRelation
  have hb : yRestrictedB = yRestrictedA *
      (yRestrictedA ^ 2 - yRestrictedB ^ 2) := by
    calc
      yRestrictedB = yRestrictedA ^ 3 - yRestrictedA * yRestrictedB ^ 2 := hcurve.symm
      _ = yRestrictedA * (yRestrictedA ^ 2 - yRestrictedB ^ 2) := by ring
  rw [hb]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span (Set.mem_singleton _))

theorem yRestrictedZeroPointIdeal_eq_spanA :
    Ideal.map (algebraMap YChartCubicRing yRestrictedOriginLocalization)
      yZeroPointIdeal = Ideal.span {yRestrictedA} := by
  rw [yZeroPointIdeal, Ideal.map_span]
  simp only [Set.image_insert_eq, Set.image_singleton]
  apply le_antisymm
  · apply Ideal.span_le.mpr
    intro x hx
    rcases Set.mem_insert_iff.mp hx with rfl | ha
    · exact yRestrictedB_mem_spanA
    · rcases Set.mem_singleton_iff.mp ha with rfl
      exact Ideal.subset_span (Set.mem_singleton _)
  · apply Ideal.span_le.mpr
    intro x hx
    rcases Set.mem_singleton_iff.mp hx with rfl
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_singleton _))

theorem yRestrictedFixedIdeal_eq_spanA :
    yRestrictedFixedIdeal = Ideal.span {yRestrictedA} := by
  rw [yRestrictedFixedIdeal, yFixedDifferenceIdeal_eq_origin,
    yRestrictedZeroPointIdeal_eq_spanA]

/-- The actual fixed-chart difference ideal, after restriction to the genuine
principal-open chart, is generated by the selected coordinate. -/
theorem actualRestrictedY_fixedIdeal_eq_a :
    yFixedDifferenceIdeal.map
      (algebraMap YChartCubicRing YRestrictedQAway) =
        Ideal.span {yRestrictedA} :=
  yRestrictedFixedIdeal_eq_spanA

theorem yRestrictedFixedIdeal_eq_originKernelMap :
    yRestrictedFixedIdeal =
      Ideal.map (algebraMap YChartCubicRing yRestrictedOriginLocalization)
        (RingHom.ker yOriginReceiver) := by
  rw [yRestrictedFixedIdeal, yFixedDifferenceIdeal_eq_origin,
    ← yOriginReceiver_ker_eq_zeroPointIdeal]

theorem yRestrictedQ_origin_eq_one : yOriginReceiver yRestrictedQ = 1 := by
  rw [yRestrictedQ_formula]
  have hA : yOriginReceiver yAmbientA = 0 := by
    change yOriginReceiver yA = 0
    exact yOriginReceiver_v
  have hB : yOriginReceiver yAmbientB = 0 := by
    change yOriginReceiver yB = 0
    exact yOriginReceiver_u
  simp only [map_add, map_mul, map_one, hA, hB, mul_zero, add_zero]

theorem yRestrictedQ_origin_isUnit : IsUnit (yOriginReceiver yRestrictedQ) := by
  rw [yRestrictedQ_origin_eq_one]
  exact isUnit_one

noncomputable def yRestrictedOriginLift :
    yRestrictedOriginLocalization →ₐ[ℂ] ℂ :=
  restrictedOriginLift yOriginReceiver yRestrictedQ yRestrictedQ_origin_isUnit

theorem yRestrictedOriginLift_ker_eq_fixedIdeal :
    RingHom.ker yRestrictedOriginLift = yRestrictedFixedIdeal := by
  change RingHom.ker (restrictedOriginLift yOriginReceiver yRestrictedQ
    yRestrictedQ_origin_isUnit).toRingHom = yRestrictedFixedIdeal
  exact (restrictedOriginLift_ker_map yOriginReceiver yRestrictedQ
    yRestrictedQ_origin_isUnit).trans yRestrictedFixedIdeal_eq_originKernelMap.symm

noncomputable def yRestrictedFixedQuotientEquiv :
    (yRestrictedOriginLocalization ⧸ yRestrictedFixedIdeal) ≃ₐ[ℂ] ℂ := by
  rw [yRestrictedFixedIdeal_eq_originKernelMap]
  exact restrictedOriginQuotientEquiv yOriginReceiver yRestrictedQ
    yRestrictedQ_origin_isUnit

theorem yRestrictedFixedQuotient_length_eq_one :
    Module.length ℂ (yRestrictedOriginLocalization ⧸ yRestrictedFixedIdeal) = 1 := by
  rw [yRestrictedFixedIdeal_eq_originKernelMap]
  exact restrictedOriginQuotient_length_eq_one yOriginReceiver yRestrictedQ
    yRestrictedQ_origin_isUnit

#print axioms yOriginReceiver_ker_eq_zeroPointIdeal
#print axioms yRestrictedCurveRelation
#print axioms yRestrictedZeroPointIdeal_eq_spanA
#print axioms yRestrictedFixedIdeal_eq_originKernelMap
#print axioms yRestrictedFixedQuotientEquiv
#print axioms yRestrictedFixedQuotient_length_eq_one
end Holonics.Hodge.CMGraphSource
