#let prime-axis-root-closure = (
  key: "lemma:prime-axis-root-closure",
  kind: [Lemma],
  title: [Prime-axis transfers form the root lattice $A_(r-1)$],
  status: [Classical lattice identity; exact atlas transport law],
  depends: ("definition:prime-valuation-atlas",),
  claim: [
    Enumerate $S={p_1,dots,p_r}$ and let $e_p$ be the corresponding standard
    valuation axes.  Every degree-preserving integral displacement is in
    $
      A_(r-1)
      ={beta in ZZ^S:sum_p beta_p=0},
    $
    and this lattice is generated by the oriented transfers
    $
      alpha_(p q)=e_p-e_q.
    $
    In particular every oriented prime triangle closes:
    $
      alpha_(p q)+alpha_(q r)+alpha_(r p)=0.
    $
    Under the analytic specialization $Phi_s$, a legal transfer from $q$ to
    $p$ multiplies the observed amplitude by
    $
      Phi_s(alpha+e_p-e_q)/Phi_s(alpha)=(q/p)^s.
    $
  ],
  proof: [
    If $beta in ZZ^S$ has coordinate sum zero, select one base axis $p_0$.
    Then
    $
      beta=sum_(p != p_0) beta_p(e_p-e_(p_0)),
    $
    because the coefficient of $e_(p_0)$ is
    $-sum_(p != p_0)beta_p=beta_(p_0)$.  The triangular identity telescopes.
    The specialization formula follows by dividing the two Euler monomials.
  ],
  boundary: [
    The closed triangle is flat only inside one fixed valuation and analytic
    chart.  If the receiver, branch, completion, or admitted prime support
    changes along the sides, the transported triangle may carry a residual;
    that residual must be calculated from the transition laws and may not be
    inferred from the planar drawing.
  ],
)
