import ElementaryHolonics.Geometry.SixSphereTorusFibre
import Mathlib.Data.ZMod.Basic

/-!
# Source-ordered exceptional data for the six-sphere torus family

This file follows the construction order of §§4--5 of the source.  At the cusp it constructs the
two translation classes of triangles in the `A₂` triangulation, lifts their vertices to height one,
and proves the two cone determinants are `+1` and `-1`.  At the elliptic points it binds the
order-three and order-four dual actions to the actual twists `ε` and `-ε'`, proves those twists are
fixed, and discharges the arithmetic freeness gates used by the logarithmic transforms.

Truth status: `[proved-derived] [formal-checked]` for every theorem and for the two constructed input
receipts.  These are the exact finite geometric and arithmetic inputs to the exceptional fillings;
they are not the infinite toric variety, its properly discontinuous quotient, either analytic
logarithmic-transform threefold, a collar biholomorphism, or the completed manifold.
-/

namespace Soma.Holonics.Geometry.SixSphereExceptionalData

open Soma.Holonics.Geometry.SixSphereMonodromy

abbrev PlaneLattice := Fin 2 → ℤ
abbrev ConeLattice := Fin 3 → ℤ

/-! ## The cusp: the `A₂` triangulation and its height-one cone generators -/

def e1 : PlaneLattice := ![1, 0]
def e2 : PlaneLattice := ![0, 1]

/-- The first translation class of triangles: `{v, v+e₁, v+e₂}`. -/
def lowerTriangle (v : PlaneLattice) : Fin 3 → PlaneLattice :=
  ![v, v + e1, v + e2]

/-- The second translation class: `{v+e₁, v+e₂, v+e₁+e₂}`. -/
def upperTriangle (v : PlaneLattice) : Fin 3 → PlaneLattice :=
  ![v + e1, v + e2, v + e1 + e2]

/-- Every fan ray is generated by a lattice point at height one. -/
def heightOneLift (v : PlaneLattice) : ConeLattice := ![v 0, v 1, 1]

/-- The three lifted vertices are the columns of the local cone matrix. -/
def coneMatrix (triangle : Fin 3 → PlaneLattice) : Matrix (Fin 3) (Fin 3) ℤ :=
  fun i j ↦ heightOneLift (triangle j) i

def lowerConeMatrix (v : PlaneLattice) : Matrix (Fin 3) (Fin 3) ℤ :=
  !![v 0, v 0 + 1, v 0; v 1, v 1, v 1 + 1; 1, 1, 1]

def upperConeMatrix (v : PlaneLattice) : Matrix (Fin 3) (Fin 3) ℤ :=
  !![v 0 + 1, v 0, v 0 + 1; v 1, v 1 + 1, v 1 + 1; 1, 1, 1]

theorem coneMatrix_lowerTriangle (v : PlaneLattice) :
    coneMatrix (lowerTriangle v) = lowerConeMatrix v := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [coneMatrix, lowerConeMatrix, lowerTriangle, heightOneLift, e1, e2,
      Matrix.vecHead, Matrix.vecTail]

theorem coneMatrix_upperTriangle (v : PlaneLattice) :
    coneMatrix (upperTriangle v) = upperConeMatrix v := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [coneMatrix, upperConeMatrix, upperTriangle, heightOneLift, e1, e2,
      Matrix.vecHead, Matrix.vecTail]

/-- Every lower cone is unimodular. -/
theorem lowerCone_det (v : PlaneLattice) : (coneMatrix (lowerTriangle v)).det = 1 := by
  rw [coneMatrix_lowerTriangle]
  simp [lowerConeMatrix, Matrix.det_fin_three]
  ring

/-- Every upper cone is unimodular with the opposite ordered orientation. -/
theorem upperCone_det (v : PlaneLattice) : (coneMatrix (upperTriangle v)).det = -1 := by
  rw [coneMatrix_upperTriangle]
  simp [upperConeMatrix, Matrix.det_fin_three]
  ring

/-- Integral translation preserves the lower triangle family. -/
theorem lowerTriangle_translate (a v : PlaneLattice) :
    lowerTriangle (v + a) = fun i ↦ lowerTriangle v i + a := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [lowerTriangle, e1, e2, Matrix.vecHead, Matrix.vecTail] <;> ring

/-- Integral translation preserves the upper triangle family. -/
theorem upperTriangle_translate (a v : PlaneLattice) :
    upperTriangle (v + a) = fun i ↦ upperTriangle v i + a := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [upperTriangle, e1, e2, Matrix.vecHead, Matrix.vecTail] <;> ring

theorem coneGenerators_heightOne (triangle : Fin 3 → PlaneLattice) (j : Fin 3) :
    heightOneLift (triangle j) 2 = 1 := rfl

/-- The cell species surviving modulo integral translations. -/
inductive A2CellOrbit
  | vertex
  | edgeE1
  | edgeE2
  | edgeDiagonal
  | lowerFace
  | upperFace
  deriving DecidableEq, Fintype

def A2CellOrbit.dimension : A2CellOrbit → Fin 3
  | .vertex => 0
  | .edgeE1 | .edgeE2 | .edgeDiagonal => 1
  | .lowerFace | .upperFace => 2

/-- Modulo the translation lattice the triangulation has one vertex, three edges, and two faces. -/
theorem A2CellOrbit_census :
    Fintype.card {c : A2CellOrbit // c.dimension = 0} = 1 ∧
      Fintype.card {c : A2CellOrbit // c.dimension = 1} = 3 ∧
      Fintype.card {c : A2CellOrbit // c.dimension = 2} = 2 := by
  decide

/-! ## The elliptic points: logarithmic-transform twists -/

inductive EllipticFilling
  | orderThree
  | orderFour
  deriving DecidableEq, Fintype

def multiplicity : EllipticFilling → ℕ
  | .orderThree => 3
  | .orderFour => 4

def dualAction : EllipticFilling → LatticeEnd
  | .orderThree => A1
  | .orderFour => A2

def chosenTwist : EllipticFilling → Lattice
  | .orderThree => epsilon
  | .orderFour => -epsilon'

/-- The precise source arithmetic which makes the cyclic logarithmic action free. -/
def LogTwistAdmissible : EllipticFilling → Lattice → Prop
  | .orderThree, v => ¬ (3 : ℤ) ∣ gamma v
  | .orderFour, v => Odd (gamma v)

theorem chosenTwist_fixed (j : EllipticFilling) :
    (dualAction j).mulVec (chosenTwist j) = chosenTwist j := by
  cases j
  · exact distinguishedVectors_areFixed.1
  · simpa [dualAction, chosenTwist, Matrix.mulVec_neg] using
      congrArg Neg.neg distinguishedVectors_areFixed.2.1

theorem chosenTwist_admissible (j : EllipticFilling) :
    LogTwistAdmissible j (chosenTwist j) := by
  cases j
  · norm_num [LogTwistAdmissible, chosenTwist, gamma, epsilon]
  · refine ⟨-1, ?_⟩
    norm_num [LogTwistAdmissible, chosenTwist, gamma, epsilon']

theorem chosenTwist_gamma :
    gamma (chosenTwist .orderThree) = 1 ∧ gamma (chosenTwist .orderFour) = -1 :=
  chosenTwists

/-! ## Constructed input receipts, without pretending the analytic fillings already exist -/

/-- The exact finite input to the source's infinite toric cusp construction. -/
structure CuspToricInput where
  basisChange : Matrix (Fin 2) (Fin 2) ℤ
  basisChangeDet : basisChange.det = 1
  lowerUnimodular : ∀ v, (coneMatrix (lowerTriangle v)).det = 1
  upperUnimodular : ∀ v, (coneMatrix (upperTriangle v)).det = -1
  allRaysHeightOne : ∀ (triangle : Fin 3 → PlaneLattice) (j : Fin 3),
    heightOneLift (triangle j) 2 = 1

def cuspToricInput : CuspToricInput where
  basisChange := B0
  basisChangeDet := B0_isUnimodular
  lowerUnimodular := lowerCone_det
  upperUnimodular := upperCone_det
  allRaysHeightOne := coneGenerators_heightOne

/-- The exact finite input to one source logarithmic transform. -/
structure LogarithmicFillingInput where
  index : EllipticFilling
  action : LatticeEnd
  twist : Lattice
  action_eq : action = dualAction index
  twist_eq : twist = chosenTwist index
  fixed : action.mulVec twist = twist
  admissible : LogTwistAdmissible index twist

def logarithmicFillingInput (j : EllipticFilling) : LogarithmicFillingInput where
  index := j
  action := dualAction j
  twist := chosenTwist j
  action_eq := rfl
  twist_eq := rfl
  fixed := chosenTwist_fixed j
  admissible := chosenTwist_admissible j

/-! ## The finite phase is only a receiver probe -/

def latticePhaseModuloFour (v : Lattice) : Fin 4 → ZMod 4 := fun i ↦ v i

/-- The full lattice distinguishes a displacement which the finite phase receiver collapses. -/
theorem finitePhaseProbe_reopens_on_integralLattice :
    latticePhaseModuloFour ![(0 : ℤ), 0, 0, 0] =
        latticePhaseModuloFour ![(4 : ℤ), 0, 0, 0] ∧
      ![(0 : ℤ), 0, 0, 0] ≠ ![(4 : ℤ), 0, 0, 0] := by
  constructor
  · funext i
    fin_cases i <;> decide
  · decide

end Soma.Holonics.Geometry.SixSphereExceptionalData

section Audit
open Soma.Holonics.Geometry.SixSphereExceptionalData
#print axioms lowerCone_det
#print axioms upperCone_det
#print axioms lowerTriangle_translate
#print axioms upperTriangle_translate
#print axioms A2CellOrbit_census
#print axioms chosenTwist_fixed
#print axioms chosenTwist_admissible
#print axioms finitePhaseProbe_reopens_on_integralLattice
end Audit
