import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Rat.Lemmas
import Mathlib.Algebra.Category.ModuleCat.Basic

/-!
# The Hodge conjecture — cycle classes and their rational span

`LorentzianPerp.lean` and `Shadows.lean` own exact intersection-lattice consequences. They do not
contain a smooth projective complex variety, its rational cohomology, Hodge classes, or the
cycle-class map. This file imports those missing *problem objects* as a typed boundary.

The complete comparison from smooth projective complex varieties to singular cohomology, Hodge
decomposition, and algebraic cycle classes is a construction target of the source-specific files.
`Official` retains the typed admission boundary while those objects and comparison laws are built;
it is not a substitute lattice model. Absence of a prepackaged library theorem is never a stopping
condition. Once that realization is constructed, `TheHodgeConjectureIn` is the classical statement
that every rational Hodge class belongs to the rational span of algebraic cycle classes.

No theorem here asserts the conjecture.
-/

noncomputable section

namespace Soma.Holonics.Millennium.HodgeConjecture

universe u v

/-- One proposed realization of the Hodge problem at a variety and codimension.

`Official datum` is deliberately kept outside the structure: possessing vector spaces and a map
does not by itself make them the cohomology and cycle-class map of a smooth projective variety. -/
structure Datum where
  /-- The addressed variety carrier. -/
  Variety : Type u
  /-- The codimension `p`; the relevant cohomological degree is `2p`. -/
  codimension : ℕ
  /-- Rational combinations of codimension-`p` algebraic cycles. -/
  CycleSpace : ModuleCat.{v} ℚ
  /-- Rational cohomology in degree `2p`. -/
  Cohomology : ModuleCat.{v} ℚ
  /-- The linear cycle-class map into rational cohomology. -/
  cycleClass : CycleSpace ⟶ Cohomology
  /-- The rational cohomology subspace of Hodge type `(p,p)`. -/
  rationalHodgeClasses : Submodule ℚ Cohomology
  /-- The classical easy direction: algebraic cycle classes have Hodge type `(p,p)`. -/
  cycleClassesAreHodge : LinearMap.range cycleClass.hom ≤ rationalHodgeClasses

namespace Datum

/-- The rational subspace generated by algebraic cycle classes. -/
def algebraicSpan (D : Datum) : Submodule ℚ D.Cohomology :=
  LinearMap.range D.cycleClass.hom

/-- The Hodge conclusion for one admitted variety/codimension realization. -/
def Conclusion (D : Datum) : Prop :=
  D.rationalHodgeClasses = D.algebraicSpan

end Datum

/-- **The Hodge conjecture over a declared official realization family.**

`Official D` owes the smooth projective complex variety, the actual degree-`2p` rational
cohomology, Hodge decomposition, and the actual cycle-class map. Keeping that admission face
visible prevents an arbitrary rational vector space from being mistaken for the conjecture. -/
def TheHodgeConjectureIn (Official : Datum → Prop) : Prop :=
  ∀ D : Datum, Official D → D.Conclusion

/-- The unresolved population under a declared official realization family. -/
def OpenHodgeClasses (Official : Datum → Prop) : Set (Σ D : Datum, D.Cohomology) :=
  { situated | Official situated.1 ∧
      situated.2 ∈ situated.1.rationalHodgeClasses ∧
      situated.2 ∉ situated.1.algebraicSpan }

/-- The conjecture says exactly that the admitted unresolved population is empty. -/
theorem theHodgeConjecture_iff_noOpenHodgeClass (Official : Datum → Prop) :
    TheHodgeConjectureIn Official ↔ OpenHodgeClasses Official = ∅ := by
  constructor
  · intro h
    ext situated
    constructor
    · rintro ⟨hOfficial, hHodge, hOpen⟩
      rw [h situated.1 hOfficial] at hHodge
      exact (hOpen hHodge).elim
    · intro hEmpty
      exact hEmpty.elim
  · intro h D hOfficial
    apply le_antisymm
    · intro cohomologyClass hHodge
      by_contra hOpen
      have hopen : (⟨D, cohomologyClass⟩ : Σ D : Datum, D.Cohomology) ∈
          OpenHodgeClasses Official := ⟨hOfficial, hHodge, hOpen⟩
      rw [h] at hopen
      exact hopen
    · exact D.cycleClassesAreHodge

end Soma.Holonics.Millennium.HodgeConjecture
