import ElementaryHolonics.Millennium.NavierStokesPhysicalH2ClockedQuarticPrincipalSymbol

/-!
# A complete finite orbit witness for the clocked physical-H2 quartic symbol

**[proved-derived; formal-checked]** This file replaces the isolated principal-symbol occurrence
by one globally defined, finite, divergence-free, Fourier-real velocity mode.  Its eight occupied
frequencies are the reality closure of four addressed modes.  The principal population below is
the complete cyclic/exchange/reality orbit through the selected generated `p` pin: all three
insertion legs, both orders of the retained outer pair, both orders of the retained inner pair,
and both reality signs.  Thus its twenty-four occurrence slots are evaluated in one finite
receiver rather than being asserted from separate local amplitudes.

The returned scalar is a homogeneous principal-symbol receiver.  It is not the full support-wide
quartic sum, the complete inhomogeneous clocked source, an estimate, terminal control,
continuation, or an existence theorem for Navier--Stokes.
-/

noncomputable section

open scoped BigOperators ComplexConjugate

namespace Soma.Holonics.Millennium.NavierStokesPhysicalH2ClockedQuarticFullOrbitWitness

open Soma.Holonics.Millennium.NavierStokes
open Soma.Holonics.Millennium.NavierStokesCompleteTransportCofinalCancellation
open Soma.Holonics.Millennium.NavierStokesDyadicFlowCommutator
open Soma.Holonics.Millennium.NavierStokesFourierTriads
open Soma.Holonics.Millennium.NavierStokesMildFourierNonlinearity
open Soma.Holonics.Millennium.NavierStokesPhysicalFourierH2ProductionBridge
open Soma.Holonics.Millennium.NavierStokesPhysicalH2ClockedQuarticInteractionPullback
open Soma.Holonics.Millennium.NavierStokesPhysicalH2ClockedQuarticPrincipalSymbol
open Soma.Holonics.Millennium.NavierStokesPhysicalH2ClockedTriadNormalForm
open Soma.Holonics.Millennium.NavierStokesPhysicalH2ReciprocalClockRenormalization
open Soma.Holonics.Millennium.NavierStokesTorusFourier
open Soma.Holonics.Millennium.NavierStokesWeightedReality

/-! ## One finite, reality-closed velocity support -/

/-- The eight distinct occupied occurrences.  Positive/negative names retain reality lineage;
they are not a quotient by sign. -/
inductive FullOrbitSupportIndex where
  | q | negQ | r | negR | alpha | negAlpha | beta | negBeta
  deriving DecidableEq

instance : Fintype FullOrbitSupportIndex where
  elems := {.q, .negQ, .r, .negR, .alpha, .negAlpha, .beta, .negBeta}
  complete index := by
    cases index <;> simp

/-- The exact frequency presented by each occupied occurrence. -/
def fullOrbitSupportFrequency : FullOrbitSupportIndex → SpatialFrequency
  | .q => ![0, 1, 0]
  | .negQ => ![0, -1, 0]
  | .r => ![-1, -1, 0]
  | .negR => ![1, 1, 0]
  | .alpha => ![0, 0, 1]
  | .negAlpha => ![0, 0, -1]
  | .beta => ![1, 0, -1]
  | .negBeta => ![-1, 0, 1]

/-- The mode on each occupied occurrence.  The two members of a reality pair carry the same real
vector, hence conjugation transports one to the other. -/
def fullOrbitSupportMode : FullOrbitSupportIndex → ComplexVector
  | .q | .negQ | .r | .negR => ![0, 0, 1]
  | .alpha | .negAlpha => ![1, 0, 0]
  | .beta | .negBeta => ![0, 1, 0]

/-- Membership in one sign-pair of a frequency. -/
def inRealityPair (frequency representative : SpatialFrequency) : Prop :=
  frequency = representative ∨ frequency = -representative

instance (frequency representative : SpatialFrequency) :
    Decidable (inRealityPair frequency representative) := by
  unfold inRealityPair
  infer_instance

/-- The single global velocity mode.  Its `p = (1,0,0)` amplitude is zero: the nonzero `p`
occurrence below is generated by the inner quadratic source and inserted into the outer vertex. -/
def fullOrbitVelocityMode (frequency : SpatialFrequency) : ComplexVector :=
  if inRealityPair frequency (![0, 1, 0] : SpatialFrequency) then ![0, 0, 1]
  else if inRealityPair frequency (![-1, -1, 0] : SpatialFrequency) then ![0, 0, 1]
  else if inRealityPair frequency (![0, 0, 1] : SpatialFrequency) then ![1, 0, 0]
  else if inRealityPair frequency (![1, 0, -1] : SpatialFrequency) then ![0, 1, 0]
  else 0

@[simp]
theorem fullOrbitVelocityMode_supportFrequency (index : FullOrbitSupportIndex) :
    fullOrbitVelocityMode (fullOrbitSupportFrequency index) =
      fullOrbitSupportMode index := by
  cases index <;>
    norm_num [fullOrbitVelocityMode, fullOrbitSupportFrequency,
      fullOrbitSupportMode, inRealityPair]

@[simp]
theorem fullOrbitVelocityMode_p_zero :
    fullOrbitVelocityMode (![1, 0, 0] : SpatialFrequency) = 0 := by
  norm_num [fullOrbitVelocityMode, inRealityPair]

/-- Negation swaps the two occurrences in a reality pair. -/
theorem inRealityPair_neg_iff
    (frequency representative : SpatialFrequency) :
    inRealityPair (-frequency) representative ↔
      inRealityPair frequency representative := by
  constructor
  · rintro (h | h)
    · right
      have hneg := congrArg (fun value : SpatialFrequency ↦ -value) h
      simpa using hneg
    · left
      have hneg := congrArg (fun value : SpatialFrequency ↦ -value) h
      simpa using hneg
  · rintro (h | h)
    · right
      have hneg := congrArg (fun value : SpatialFrequency ↦ -value) h
      simpa using hneg
    · left
      have hneg := congrArg (fun value : SpatialFrequency ↦ -value) h
      simpa using hneg

/-- The global support is Fourier-real before any real-part receiver is applied. -/
theorem fullOrbitVelocityMode_reality (frequency : SpatialFrequency) :
    fullOrbitVelocityMode (-frequency) =
      fun component ↦ conj (fullOrbitVelocityMode frequency component) := by
  ext component
  fin_cases component <;>
    simp only [fullOrbitVelocityMode, inRealityPair_neg_iff] <;>
    split_ifs <;>
    norm_num

/-- Every occupied occurrence is divergence-free at its own addressed frequency. -/
theorem fullOrbitSupport_divergenceFree (index : FullOrbitSupportIndex) :
    complexDot (complexFrequencyVector (fullOrbitSupportFrequency index))
      (fullOrbitVelocityMode (fullOrbitSupportFrequency index)) = 0 := by
  rw [fullOrbitVelocityMode_supportFrequency]
  cases index <;>
    norm_num [fullOrbitSupportFrequency, fullOrbitSupportMode,
      complexDot, dotProduct, complexFrequencyVector, Fin.sum_univ_succ]

/-- The global velocity mode is divergence-free, including its zero complement. -/
theorem fullOrbitVelocityMode_divergenceFree (frequency : SpatialFrequency) :
    complexDot (complexFrequencyVector frequency)
      (fullOrbitVelocityMode frequency) = 0 := by
  unfold fullOrbitVelocityMode
  split_ifs with hq hr halpha hbeta
  · rcases hq with hq | hq <;> subst frequency <;>
      norm_num [complexDot, dotProduct, complexFrequencyVector,
        Fin.sum_univ_succ]
  · rcases hr with hr | hr <;> subst frequency <;>
      norm_num [complexDot, dotProduct, complexFrequencyVector,
        Fin.sum_univ_succ]
  · rcases halpha with halpha | halpha <;> subst frequency <;>
      norm_num [complexDot, dotProduct, complexFrequencyVector,
        Fin.sum_univ_succ]
  · rcases hbeta with hbeta | hbeta <;> subst frequency <;>
      norm_num [complexDot, dotProduct, complexFrequencyVector,
        Fin.sum_univ_succ]
  · simp [complexDot, dotProduct]

/-! ## Complete outer/inner occurrence population -/

/-- Given the two occupied outer modes which are not replaced, construct the ordered outer
address for each insertion leg. -/
def fullOrbitOuterAddress
    (leg : PhysicalH2InsertionLeg)
    (outerLeft outerRight : FullOrbitSupportIndex) : CompleteTransportAddress :=
  let left := fullOrbitSupportFrequency outerLeft
  let right := fullOrbitSupportFrequency outerRight
  match leg with
  | .advecting => (-(left + right), left)
  | .transported => (left, -(left + right))
  | .receiver => (left, right)

/-- The source pin selected by `fullOrbitOuterAddress` is the negative sum of its two retained
outer parents, independently of which of the three roles carries the insertion. -/
theorem fullOrbitInsertionFrequency_eq_neg_add
    (leg : PhysicalH2InsertionLeg)
    (outerLeft outerRight : FullOrbitSupportIndex) :
    physicalH2InsertionFrequency
        (fullOrbitOuterAddress leg outerLeft outerRight) leg =
      -(fullOrbitSupportFrequency outerLeft +
        fullOrbitSupportFrequency outerRight) := by
  cases leg <;>
    simp [fullOrbitOuterAddress, physicalH2InsertionFrequency,
      completeTransportReceiver] <;>
    ext component <;>
    simp <;>
    ring

/-- One retained four-parent join.  The equality is tested before evaluating its principal face;
failed joins remain explicit zero fibres. -/
def fullOrbitOuterAdvectingPresentationMode
    (leg : PhysicalH2InsertionLeg) (outerLeft : FullOrbitSupportIndex) : ComplexVector :=
  match leg with
  | .advecting => 0
  | .transported | .receiver => fullOrbitSupportMode outerLeft

def fullOrbitOuterTransportedPresentationMode
    (leg : PhysicalH2InsertionLeg)
    (outerLeft outerRight : FullOrbitSupportIndex) : ComplexVector :=
  match leg with
  | .advecting => fullOrbitSupportMode outerLeft
  | .transported => 0
  | .receiver => fullOrbitSupportMode outerRight

def fullOrbitOuterReceiverPresentationMode
    (leg : PhysicalH2InsertionLeg) (outerRight : FullOrbitSupportIndex) : ComplexVector :=
  match leg with
  | .advecting | .transported => fullOrbitSupportMode outerRight
  | .receiver => 0

/-- One retained four-parent join.  The two inner and two noninserted outer modes are read from the
single support table.  The presentation value at the inserted outer slot is set to zero because
that argument is definitionally unused by its selected insertion-leg constructor. -/
def fullOrbitPrincipalOccurrence
    (leg : PhysicalH2InsertionLeg)
    (outerLeft outerRight innerAlpha innerBeta : FullOrbitSupportIndex) : ℂ :=
  if fullOrbitSupportFrequency innerAlpha + fullOrbitSupportFrequency innerBeta +
        fullOrbitSupportFrequency outerLeft + fullOrbitSupportFrequency outerRight = 0 then
    let address := fullOrbitOuterAddress leg outerLeft outerRight
    normalizedClockedPhysicalH2QuarticPrincipalSymbol
      address leg (fullOrbitSupportFrequency innerAlpha)
      (fullOrbitSupportMode innerAlpha)
      (fullOrbitSupportMode innerBeta)
      (fullOrbitOuterAdvectingPresentationMode leg outerLeft)
      (fullOrbitOuterTransportedPresentationMode leg outerLeft outerRight)
      (fullOrbitOuterReceiverPresentationMode leg outerRight)
  else 0
/-! ## The complete cyclic/exchange/reality orbit through the generated p pin -/

/-- Both oriented inner parents over one inserted pin are retained. -/
def fullOrbitInnerOrientationPair
    (leg : PhysicalH2InsertionLeg)
    (outerLeft outerRight innerLeft innerRight : FullOrbitSupportIndex) : ℂ :=
  fullOrbitPrincipalOccurrence leg outerLeft outerRight innerLeft innerRight +
    fullOrbitPrincipalOccurrence leg outerLeft outerRight innerRight innerLeft

/-- The six cyclic/exchange presentations of one closed outer triad.  For each presentation the
insertion leg follows the same physical generated pin while its role changes. -/
def fullOrbitCyclicExchangePopulation
    (outerQ outerR innerAlphaIndex innerBetaIndex : FullOrbitSupportIndex) : ℂ :=
  fullOrbitInnerOrientationPair .advecting outerQ outerR innerAlphaIndex innerBetaIndex +
    fullOrbitInnerOrientationPair .advecting outerR outerQ innerAlphaIndex innerBetaIndex +
    fullOrbitInnerOrientationPair .transported outerQ outerR innerAlphaIndex innerBetaIndex +
    fullOrbitInnerOrientationPair .transported outerR outerQ innerAlphaIndex innerBetaIndex +
    fullOrbitInnerOrientationPair .receiver outerQ outerR innerAlphaIndex innerBetaIndex +
    fullOrbitInnerOrientationPair .receiver outerR outerQ innerAlphaIndex innerBetaIndex

/-- The six positive-frequency presentations together with their six reality reflections.  Each
presentation includes both ordered inner convolution parents, hence this receiver contains all
twenty-four induced occurrences of the chosen cyclic/exchange/reality orbit. -/
def fullOrbitCyclicExchangeRealityPopulation : ℂ :=
  fullOrbitCyclicExchangePopulation .q .r .alpha .beta +
    fullOrbitCyclicExchangePopulation .negQ .negR .negAlpha .negBeta

/-- The advancing presentation really is the original p/q/r address and its generated pin is p. -/
theorem fullOrbit_advecting_qr_address :
    fullOrbitOuterAddress .advecting .q .r =
      principalWitnessOuterAddress := by
  apply Prod.ext
  · funext component
    fin_cases component <;>
      norm_num [fullOrbitOuterAddress, fullOrbitSupportFrequency,
        principalWitnessOuterAddress]
  · funext component
    fin_cases component <;>
      norm_num [fullOrbitOuterAddress, fullOrbitSupportFrequency,
        principalWitnessOuterAddress]

/-- The empty tail of an explicit three-vector has one inhabitant and is the zero tail. -/
theorem finZeroFunction_eq_zero {Scalar : Type*} [Zero Scalar]
    (value : Fin 0 → Scalar) : value = 0 := by
  exact Subsingleton.elim _ _

theorem fullOrbitInnerOrientationPair_advecting_qr :
    fullOrbitInnerOrientationPair .advecting .q .r .alpha .beta =
      (3 / 4 : ℂ) := by
  norm_num [fullOrbitInnerOrientationPair, fullOrbitPrincipalOccurrence,
    fullOrbitOuterAddress, fullOrbitSupportFrequency, fullOrbitVelocityMode,
    fullOrbitSupportMode, fullOrbitOuterAdvectingPresentationMode,
    fullOrbitOuterTransportedPresentationMode,
    fullOrbitOuterReceiverPresentationMode,
    inRealityPair, normalizedClockedPhysicalH2QuarticPrincipalSymbol,
    physicalH2QuarticPrincipalExchangeSwing,
    normalizedPhysicalH2TriadClockSquare,
    normalizedPrincipalOuterInsertionFace,
    normalizedPrincipalProjectedSourceAtom, normalizedAdvectiveInteraction,
    physicalH2InsertionFrequency, completeTransportReceiver,
    transportedFrequencyAt, lerayProjectMode, frequencySquared,
    complexDot, dotProduct, complexFrequencyVector, Fin.sum_univ_succ,
    finZeroFunction_eq_zero]

/-- **Exact full-orbit noncancellation.**  The complete cyclic/exchange/reality selector is the
nonzero real face 3.  The reversed inner orientations and four cyclic presentations not visible in
the isolated witness are present and evaluate to zero rather than being omitted. -/
theorem fullOrbitCyclicExchangeRealityPopulation_eq_three :
    fullOrbitCyclicExchangeRealityPopulation = (3 : ℂ) := by
  norm_num [fullOrbitCyclicExchangeRealityPopulation,
    fullOrbitCyclicExchangePopulation, fullOrbitInnerOrientationPair,
    fullOrbitPrincipalOccurrence, fullOrbitOuterAddress,
    fullOrbitSupportFrequency, fullOrbitVelocityMode, fullOrbitSupportMode,
    fullOrbitOuterAdvectingPresentationMode,
    fullOrbitOuterTransportedPresentationMode,
    fullOrbitOuterReceiverPresentationMode, inRealityPair,
    normalizedClockedPhysicalH2QuarticPrincipalSymbol,
    physicalH2QuarticPrincipalExchangeSwing,
    normalizedPhysicalH2TriadClockSquare,
    normalizedPrincipalOuterInsertionFace,
    normalizedPrincipalProjectedSourceAtom, normalizedAdvectiveInteraction,
    physicalH2InsertionFrequency, completeTransportReceiver,
    transportedFrequencyAt, lerayProjectMode, frequencySquared,
    complexDot, dotProduct, complexFrequencyVector, Fin.sum_univ_succ,
    finZeroFunction_eq_zero]

/-- In particular the complete orbit does not cancel. -/
theorem fullOrbitCyclicExchangeRealityPopulation_ne_zero :
    fullOrbitCyclicExchangeRealityPopulation ≠ 0 := by
  rw [fullOrbitCyclicExchangeRealityPopulation_eq_three]
  norm_num

#print axioms fullOrbitVelocityMode_reality
#print axioms fullOrbitVelocityMode_divergenceFree
#print axioms fullOrbitCyclicExchangeRealityPopulation_eq_three
#print axioms fullOrbitCyclicExchangeRealityPopulation_ne_zero

end Soma.Holonics.Millennium.NavierStokesPhysicalH2ClockedQuarticFullOrbitWitness
