//! **The rigidity receiver: the constraint Jacobian and its two null spaces.**
//!
//! [definition] The physical ontology of
//! `research/records/2026-08-21_THE_FOLD_IS_A_CONSTRAINT_ECOLOGY_THE_ACTIVE_SITE_IS_A_CATALYTIC_RECEIVER_AND_THE_CODEC_RECOVERS_ARCHETYPES.md`
//! §5 represents a physical structure at one grain as
//!
//! ```text
//! P_eta = ( V, C_eta, q, F_eta, J_eta, G, E_eta, R_eta, Gamma_eta )
//! ```
//!
//! with `F_eta(q) = 0` the constraint system, `J_eta = D F_eta(q)` its rigidity Jacobian,
//! `ker J_eta` the infinitesimal motions and `ker J_eta^T` the self-stresses or constraint
//! reactions. This module owns that object exactly. It is the receiver **R4** of
//! `docs/plans/THE_RECEIVER_ATLAS_SEPARATES_WHAT_ONE_FACE_CANNOT.md` and the rigidity half of
//! **B7** in `docs/plans/THE_BIOLOGICAL_ECOLOGY_INSTANTIATES_THE_CARRIER.md`.
//!
//! # What the Jacobian is, and why it is exact
//!
//! [proved-derived; implemented-exact] One distance constraint between occurrences `i` and `j` is
//! `F_c(q) = |q_i − q_j|² − ℓ_c²`. Its differential is read off an exact algebraic expansion and
//! needs no analysis at all:
//!
//! ```text
//! F_c(q + t v) = F_c(q) + t · 2 ⟨q_i − q_j, v_i − v_j⟩ + t² · |v_i − v_j|²
//! ```
//!
//! so the row of `J = D F(q)` at `c` carries `2(q_i − q_j)` in block `i`, `−2(q_i − q_j)` in
//! block `j`, and zero elsewhere. Over exact rational coordinates every entry, every rank, every
//! kernel basis vector and every cluster verdict below is exact. **No float enters any of them.**
//! `ExactConfiguration::from_presented` refuses a presented position whose coordinate box has
//! width, by name, rather than choosing a representative inside it: an interval position is a
//! precision question and it is not a configuration.
//!
//! # The two null spaces
//!
//! [proved-standard] `ker J` is the infinitesimal motion space and `ker Jᵀ` is the self-stress —
//! equivalently constraint-reaction — space. Both come from
//! [`holonics::exact_linear::ExactRatMatrix`]: `kernel_basis` at `exact_linear.rs:770` and
//! `cokernel_annihilator` at `:814`, with `rank` at `:761`. Nothing here reimplements them.
//!
//! # The trivial motions are measured, never assumed
//!
//! [proved-derived; implemented-exact] A `d`-dimensional rigid body is usually said to have
//! `d(d+1)/2` trivial motions — `6` in three dimensions. **That number is a property of the
//! configuration, not of the dimension**, and this module never assumes it. The trivial space is
//! the span of `d` translation generators and `d(d−1)/2` rotation generators *linearized about the
//! given configuration `q`*: the rotation generated by the antisymmetric `Ω = E_ab − E_ba` assigns
//! occurrence `i` the velocity `Ω q_i`, which is a function of `q`. Its dimension is measured as
//! the exact rank of the generator matrix and is independently checked against the closed form
//!
//! ```text
//! dim T(q) = d + d(d−1)/2 − (d−k)(d−k−1)/2,    k = dim span{ q_i − q_0 }
//! ```
//!
//! derived from the kernel of `(t, Ω) ↦ (t + Ω q_i)_i`: that kernel is `{Ω ∈ so(d) : Ω|_W = 0}`
//! for `W` the linear span of the differences, and an antisymmetric map killing `W` is an
//! antisymmetric map of `W^⊥`. In three dimensions this is `6` for a spanning **or coplanar**
//! configuration, `5` for a collinear one, and `3` for a coincident one.
//! [`ConfigurationDegeneracy`] names which case the configuration is in, exactly, and
//! [`RigidityError::TrivialDimensionDisagrees`] refuses if the measured rank and the closed form
//! ever part company.
//!
//! [proved-derived; implemented-exact] That the trivial motions really are motions is **proved,
//! not asserted**: every generator is applied to `J` and the product is required to vanish
//! entry by entry, refusing with [`RigidityError::TrivialMotionOutsideKernel`] naming the
//! generator and the constraint. The mathematics behind it is one line —
//! `v_i − v_j = Ω(q_i − q_j)` and `⟨x, Ω x⟩ = 0` for antisymmetric `Ω` — and it is the Lean
//! theorem `rigid_motion_mem_ker`.
//!
//! # The Maxwell relation and where it is only a bound
//!
//! [proved-standard] Two identities hold unconditionally and are checked at every reading:
//!
//! ```text
//! rank J + dim ker J = d·n          (rank–nullity on the configuration space)
//! dim ker Jᵀ = m − rank J           (rank–nullity on the constraint space)
//! ```
//!
//! Subtracting gives the exact Maxwell relation `dim ker J − dim ker Jᵀ = d·n − m`. The *count*
//! `d·n − m` therefore equals `dim ker J` **only when there is no self-stress**, and is otherwise
//! a strict lower bound. [`MaxwellCount::count_is_a_bound_only`] says which case holds on the
//! actual data.
//!
//! [definition] A count is a necessary condition and never a sufficient one, and this module
//! claims **infinitesimal** rigidity at the given configuration and nothing else. Generic
//! rigidity is a statement about almost every configuration of a combinatorial structure; a
//! degenerate or redundant configuration breaks the passage from one to the other in both
//! directions, and [`RigidityReading::is_infinitesimally_rigid`] is named so that it cannot be
//! read as either generic or finite rigidity.
//!
//! # Rigid clusters and contact-removal sensitivity
//!
//! [proved-derived; implemented-exact] A pair `(i,j)` is **implied** when its separation is
//! first-order constant under every admitted infinitesimal motion, i.e. when its constraint row
//! `r_ij` annihilates `ker J` — equivalently when `r_ij` lies in the row space of `J`, since over
//! `ℚ` with the standard pairing `(ker J)^⊥ = row J`. A **rigid cluster** is a maximal set of
//! occurrences all of whose pairs are implied; every infinitesimal motion then restricts to a
//! rigid motion of that sub-configuration, and [`rigid_clusters`] verifies exactly that for every
//! returned cluster against every kernel basis vector. Clusters **overlap**: two rigid bodies
//! sharing a hinge are two clusters sharing an occurrence, and that is the phenomenon, not a
//! defect. Enumeration is bounded explicitly and refuses with
//! [`RigidityError::ClusterPopulationTooWide`] rather than exhausting the machine.
//!
//! [proved-derived; implemented-exact] Removing one constraint changes `dim ker J` **exactly
//! when that constraint carries no self-stress.** If some `w ∈ ker Jᵀ` has `w_c ≠ 0` then
//! `row_c = −w_c^{-1} Σ_{k≠c} w_k row_k` lies in the span of the others and the rank is unmoved;
//! conversely a dependent row yields such a `w` with `w_c = 1`. So the sensitivity question of
//! item 4 is answered by the self-stress space of item 2, with no second computation —
//! [`removal_sensitivity`] reads it off the cokernel basis, and
//! [`verify_removal_sensitivity`] re-derives a bounded sample by actually deleting the row and
//! recomputing the exact rank.
//! The law is formal-checked over this owner's own `selfStresses` and `rigidityMatrix` as
//! `Transport/EditRigidity.lean::dependent_iff_droppingLosesNothing`, with
//! `Transport/EditRigidity.lean::entanglement_is_self_stress_support` its edit-side reading.
//!
//! # The open family
//!
//! [definition] `crate::physical_constraint_grading` returns a **family** of complexes because an
//! `Open` contact is a 1-cell that may or may not exist, and different resolutions give different
//! homology. A constraint that may or may not exist makes the constraint *system* plural in the
//! same way, so the rigidity reading is a family too, indexed identically:
//! [`rigidity_family`] returns the `refusing` and `admitting` bounds of that indexing with their
//! open set retained, and never promotes or demotes an open contact. Admitting more constraints
//! can only shrink the motion space, so the two bounds bracket `dim ker J`; when they differ, the
//! open class is a **rigidity** question and not bookkeeping, and
//! [`RigidityFamily::bounds_differ_in_motion_dimension`] says so on the actual data.
//!
//! # Formal owner
//!
//! `formal/elementary-holonics/ElementaryHolonics/Foundation/RigidityReceiver.lean`, namespace
//! `Soma.Holonics.Foundation.RigidityReceiver`. The correspondence, both directions:
//!
//! | Rust | Lean |
//! |---|---|
//! | [`ExactConfiguration`], [`DistanceConstraint`] | `ConstraintSystem` (`left`, `right`, `place`) |
//! | [`DistanceConstraint::squared_length`] read from the configuration | `constraintMap`, `constraintMap_place` |
//! | the row law `2(q_i − q_j)` with opposite sign in the two blocks | `rigidityMatrix`, `bump`, `sum_bump`, `rigidityMatrix_mulVec` |
//! | `J = D F(q)` with no analysis, from the exact expansion | `constraint_expansion`, `jacobian_is_the_differential` |
//! | [`RigidityJacobian::matrix`] | `rigidityLin` |
//! | [`RigidityReading::motions`] = `ker J` | `infinitesimalMotions`, `mem_infinitesimalMotions_iff` |
//! | [`RigidityReading::self_stresses`] = `ker Jᵀ` | `selfStresses`, `self_stress_pairing` |
//! | `rank J + dim ker J = d·n`, checked at every reading | `rank_nullity`, `finrank_flat` |
//! | `dim ker Jᵀ = m − rank J`, checked at every reading | `self_stress_dimension` |
//! | [`MaxwellCount`] and [`MaxwellCount::count_is_a_bound_only`] | `maxwell_relation`, `motion_dimension_eq_count_of_no_self_stress` |
//! | [`TrivialMotionReading::generators`] linearized about `q` | `rigidMotion`, `IsSkew`, `delta_rigidMotion` |
//! | the kernel certificate run on every generator | `rigid_motion_mem_ker`, `translation_mem_ker`, `rotation_mem_ker`, `skew_quadratic_form_eq_zero` |
//! | [`RigidityError::TrivialExceedsKernel`] cannot fire | `rigidMotionSpace`, `rigidMotionSpace_le_motions` |
//! | [`RigidityReading::is_infinitesimally_rigid`] | `InfinitesimallyRigid`, `infinitesimallyRigid_iff_eq` |
//! | [`ConfigurationDegeneracy::Coincident`] keeps the rotations but loses their independence | `rotation_is_a_translation_of_coincident` |
//! | [`RigidityJacobian::coincident_constraints`] | `rigidityMatrix_row_eq_zero_of_coincident` |
//! | [`RigidityFamily`]'s two bounds bracket `dim ker J`, and [`RigidityError::MotionDimensionNotAntitone`] | `motions_antitone` |
//!
//! Every one of those elaborates with `#print axioms` returning
//! `[propext, Classical.choice, Quot.sound]` and no `sorryAx`.

use std::collections::{BTreeMap, BTreeSet};

use num_bigint::{BigInt, BigUint};
use num_traits::{One, Zero};
use holonics::geometry::Rat;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use holonics::exact_linear::{ExactLinearError, ExactRatMatrix};
use crate::physical_constraint_complex::{
    ConstraintEdge, ConstraintError, ConstraintVertexId, PhysicalConstraintComplex,
};
use crate::physical_constraint_grading::{
    ConstraintGradingError, EdgeProvenance, GradedConstraintComplex, OpenContact, OpenContactLaw,
    graded_constraint_family, graded_constraint_member,
};

fn two() -> Rat {
    Rat::from_integer(BigInt::from(2))
}

// -------------------------------------------------------------------------------------------
// the configuration
// -------------------------------------------------------------------------------------------

/// **An exact rational configuration: one point per addressed occurrence.**
///
/// The fields are private because the invariant — every place carries exactly `dimension`
/// coordinates, and there is at least one occurrence — is not expressible in the wire format.
/// A remounted value is re-checked by [`Self::validated`], which every public consumer calls
/// before it reads anything.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExactConfiguration {
    dimension: usize,
    places: BTreeMap<ConstraintVertexId, Vec<Rat>>,
}

impl ExactConfiguration {
    /// A declared configuration. The block order of the Jacobian is the ascending address order
    /// of this map, so it is determined by the addresses and never by insertion order.
    pub fn declared(
        dimension: usize,
        places: impl IntoIterator<Item = (ConstraintVertexId, Vec<Rat>)>,
    ) -> Result<Self, RigidityError> {
        let configuration = Self {
            dimension,
            places: places.into_iter().collect(),
        };
        configuration.validated()?;
        Ok(configuration)
    }

    /// The configuration a presented complex already carries — **when it carries one.**
    ///
    /// A presented position is a [`crate::physical_constraint_complex::CoordinateBox3`], and a box
    /// with width is not a point. A Jacobian entry built from an interval would be an interval,
    /// and then no rank, kernel or cluster verdict below would be exact. So a box with width is
    /// refused by name with its occurrence and axis rather than collapsed to a midpoint, an
    /// endpoint or a float.
    pub fn from_presented(complex: &PhysicalConstraintComplex) -> Result<Self, RigidityError> {
        let mut places = BTreeMap::new();
        for (id, vertex) in &complex.vertices {
            let axes = [
                &vertex.position.x,
                &vertex.position.y,
                &vertex.position.z,
            ];
            let mut place = Vec::with_capacity(3);
            for (axis, interval) in axes.into_iter().enumerate() {
                if !interval.is_point() {
                    return Err(RigidityError::ConfigurationIsNotAPoint {
                        occurrence: *id,
                        axis,
                    });
                }
                place.push(interval.lower.clone());
            }
            places.insert(*id, place);
        }
        Self::declared(3, places)
    }

    pub fn validated(&self) -> Result<(), RigidityError> {
        if self.dimension == 0 {
            return Err(RigidityError::ZeroDimension);
        }
        if self.places.is_empty() {
            return Err(RigidityError::EmptyConfiguration);
        }
        for (id, place) in &self.places {
            if place.len() != self.dimension {
                return Err(RigidityError::RaggedConfiguration {
                    occurrence: *id,
                    declared: self.dimension,
                    supplied: place.len(),
                });
            }
        }
        Ok(())
    }

    /// Every presented occurrence carries a declared place, and that place lies inside the
    /// presented coordinate box.
    ///
    /// This is the only thing that ties a declared configuration to a presentation whose boxes
    /// have width. Without it a caller could read a rigidity family off a presentation while
    /// supplying coordinates from somewhere else entirely.
    pub fn within_presented(
        &self,
        complex: &PhysicalConstraintComplex,
    ) -> Result<(), RigidityError> {
        self.validated()?;
        if self.dimension != 3 {
            return Err(RigidityError::PresentationDimensionDisagrees {
                supplied: self.dimension,
            });
        }
        for (id, vertex) in &complex.vertices {
            let place = self
                .places
                .get(id)
                .ok_or(RigidityError::OccurrenceAbsent(*id))?;
            let axes = [
                &vertex.position.x,
                &vertex.position.y,
                &vertex.position.z,
            ];
            for (axis, interval) in axes.into_iter().enumerate() {
                if place[axis] < interval.lower || place[axis] > interval.upper {
                    return Err(RigidityError::ConfigurationOutsideBox {
                        occurrence: *id,
                        axis,
                    });
                }
            }
        }
        Ok(())
    }

    pub fn dimension(&self) -> usize {
        self.dimension
    }

    pub fn occurrence_count(&self) -> usize {
        self.places.len()
    }

    /// The block order: ascending addresses.
    pub fn addresses(&self) -> Vec<ConstraintVertexId> {
        self.places.keys().copied().collect()
    }

    pub fn place(&self, occurrence: ConstraintVertexId) -> Result<&[Rat], RigidityError> {
        self.places
            .get(&occurrence)
            .map(Vec::as_slice)
            .ok_or(RigidityError::OccurrenceAbsent(occurrence))
    }

    /// The places in block order.
    pub fn ordered_places(&self) -> Vec<Vec<Rat>> {
        self.places.values().cloned().collect()
    }

    fn blocks(&self) -> BTreeMap<ConstraintVertexId, usize> {
        self.places
            .keys()
            .enumerate()
            .map(|(at, id)| (*id, at))
            .collect()
    }
}

// -------------------------------------------------------------------------------------------
// the constraint system and its Jacobian
// -------------------------------------------------------------------------------------------

/// One distance constraint `|q_i − q_j|² − ℓ² = 0`, addressed by the canonical 1-cell it comes
/// from.
///
/// `ℓ²` is **read from the configuration**, never supplied: the presented configuration satisfies
/// `F(q) = 0` by construction, and the receiver's question is the differential there, not whether
/// some exterior target length is met.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DistanceConstraint {
    pub edge: ConstraintEdge,
    pub provenance: EdgeProvenance,
    /// Block ordinal of `edge.lower` in the configuration's address order.
    pub lower_block: usize,
    /// Block ordinal of `edge.upper`.
    pub upper_block: usize,
    /// `|q_lower − q_upper|²`, exact.
    pub squared_length: Rat,
}

/// **`J_eta = D F_eta(q)`: the exact rational constraint Jacobian**, `m × (d·n)`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RigidityJacobian {
    pub schema: String,
    pub presentation_lineage: String,
    /// The configuration the differential is taken at. `J` is meaningless without it, so it
    /// travels with it.
    pub configuration: ExactConfiguration,
    /// The constraint population in canonical edge order; row `c` of `matrix` is constraint `c`.
    pub constraints: Vec<DistanceConstraint>,
    pub matrix: ExactRatMatrix,
    /// Constraints whose two occurrences are **coincident**. Their gradient row is identically
    /// zero, so they are not first-order restrictions at all. Named rather than dropped.
    pub coincident_constraints: Vec<ConstraintEdge>,
}

impl RigidityJacobian {
    /// The Jacobian of a declared constraint set at a declared configuration.
    pub fn found(
        presentation_lineage: impl Into<String>,
        configuration: &ExactConfiguration,
        constraints: &BTreeMap<ConstraintEdge, EdgeProvenance>,
    ) -> Result<Self, RigidityError> {
        configuration.validated()?;
        let dimension = configuration.dimension;
        let occurrences = configuration.occurrence_count();
        let blocks = configuration.blocks();
        let width = dimension
            .checked_mul(occurrences)
            .ok_or(ExactLinearError::ExtentOverflow)?;
        let coefficient = two();

        let mut rows = Vec::with_capacity(constraints.len());
        let mut population = Vec::with_capacity(constraints.len());
        let mut coincident = Vec::new();
        for (edge, provenance) in constraints {
            let lower_block = *blocks
                .get(&edge.lower)
                .ok_or(RigidityError::OccurrenceAbsent(edge.lower))?;
            let upper_block = *blocks
                .get(&edge.upper)
                .ok_or(RigidityError::OccurrenceAbsent(edge.upper))?;
            let lower_place = configuration.place(edge.lower)?;
            let upper_place = configuration.place(edge.upper)?;

            let mut row = vec![Rat::zero(); width];
            let mut squared_length = Rat::zero();
            let mut vanishes = true;
            for axis in 0..dimension {
                let difference = &lower_place[axis] - &upper_place[axis];
                squared_length += &difference * &difference;
                if !difference.is_zero() {
                    vanishes = false;
                }
                let entry = &coefficient * &difference;
                row[lower_block * dimension + axis] = entry.clone();
                row[upper_block * dimension + axis] = -entry;
            }
            // A constraint from an occurrence to itself writes `+2δ` and then `−2δ` into the same
            // block, leaving the row zero, which is the correct differential of a constant. The
            // canonical `ConstraintEdge` cannot hold one, but a remounted constraint set is not
            // bound by that, so the row law above is written to be right either way.
            if vanishes {
                coincident.push(*edge);
            }
            rows.push(row);
            population.push(DistanceConstraint {
                edge: *edge,
                provenance: *provenance,
                lower_block,
                upper_block,
                squared_length,
            });
        }

        let matrix = ExactRatMatrix::shaped(population.len(), width, rows)?;
        Ok(Self {
            schema: RIGIDITY_JACOBIAN_SCHEMA.to_owned(),
            presentation_lineage: presentation_lineage.into(),
            configuration: configuration.clone(),
            constraints: population,
            matrix,
            coincident_constraints: coincident,
        })
    }

    /// The Jacobian of one member of the open family: its 1-skeleton **is** its constraint set.
    pub fn from_member(
        member: &GradedConstraintComplex,
        configuration: &ExactConfiguration,
    ) -> Result<Self, RigidityError> {
        let mut constraints = BTreeMap::new();
        for edge in member.edge_cells.keys() {
            let provenance = member
                .edge_provenance
                .get(edge)
                .copied()
                .ok_or(RigidityError::ConstraintProvenanceAbsent(*edge))?;
            constraints.insert(*edge, provenance);
        }
        member.validate_structure()?;
        Self::found(
            member.presentation_lineage.clone(),
            configuration,
            &constraints,
        )
    }

    pub fn dimension(&self) -> usize {
        self.configuration.dimension
    }

    pub fn occurrence_count(&self) -> usize {
        self.configuration.occurrence_count()
    }

    pub fn constraint_count(&self) -> usize {
        self.constraints.len()
    }

    pub fn coordinate_freedoms(&self) -> usize {
        self.dimension().saturating_mul(self.occurrence_count())
    }

    /// The shape invariants a remounted value need not satisfy, checked by name.
    pub fn validated(&self) -> Result<(), RigidityError> {
        self.configuration.validated()?;
        let expected_columns = self.coordinate_freedoms();
        if self.matrix.rows() != self.constraints.len()
            || self.matrix.columns() != expected_columns
        {
            return Err(RigidityError::JacobianShapeDisagrees {
                rows: self.matrix.rows(),
                columns: self.matrix.columns(),
                expected_rows: self.constraints.len(),
                expected_columns,
            });
        }
        let occurrences = self.occurrence_count();
        for constraint in &self.constraints {
            if constraint.lower_block >= occurrences || constraint.upper_block >= occurrences {
                return Err(RigidityError::BlockOutsideConfiguration {
                    edge: constraint.edge,
                });
            }
        }
        Ok(())
    }
}

// -------------------------------------------------------------------------------------------
// the trivial motions
// -------------------------------------------------------------------------------------------

/// How the configuration's affine span sits inside the ambient dimension. This is what decides
/// the trivial motion count, so it is measured and named rather than assumed.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum ConfigurationDegeneracy {
    /// Every occurrence sits at one place: the span of differences is `{0}`. Every rotation
    /// generator vanishes and only the `d` translations remain.
    Coincident,
    /// The span of differences is a line, and the rotations fixing that line are lost.
    Collinear,
    /// A proper affine span of dimension at least two. In three dimensions this is the coplanar
    /// case, which loses **nothing**: a plane still carries all six rigid motions of space.
    Deficient,
    /// The occurrences affinely span the ambient space.
    Spanning,
}

/// **The trivial motions at this configuration, measured.**
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TrivialMotionReading {
    pub schema: String,
    pub dimension: usize,
    pub occurrences: usize,
    /// `k = dim span{ q_i − q_0 }`, exact.
    pub affine_span_dimension: usize,
    pub degeneracy: ConfigurationDegeneracy,
    /// `d` translation generators followed by the `d(d−1)/2` rotation generators `E_ab − E_ba`
    /// in ascending `(a,b)` order, each linearized about `q`.
    pub generators: Vec<Vec<Rat>>,
    /// Generators that are identically zero at this configuration.
    pub vanishing_generators: Vec<usize>,
    /// The exact rank of the generator span: the dimension of the trivial motion space.
    pub dimension_of_span: usize,
    /// An independent subfamily spanning it, by pivot order.
    pub basis: Vec<Vec<Rat>>,
    /// `d + d(d−1)/2 − (d−k)(d−k−1)/2`, computed from `k` alone and checked against
    /// `dimension_of_span`.
    pub closed_form: usize,
}

impl TrivialMotionReading {
    /// Measure the trivial space at a Jacobian's configuration **and prove it is in the kernel**.
    pub fn measure(jacobian: &RigidityJacobian) -> Result<Self, RigidityError> {
        jacobian.validated()?;
        let dimension = jacobian.dimension();
        let places = jacobian.configuration.ordered_places();
        let occurrences = places.len();
        let generators = trivial_generators(dimension, &places)?;

        for (ordinal, generator) in generators.iter().enumerate() {
            let image = jacobian.matrix.apply(generator)?;
            if let Some(constraint) = image.iter().position(|entry| !entry.is_zero()) {
                return Err(RigidityError::TrivialMotionOutsideKernel {
                    generator: ordinal,
                    constraint,
                });
            }
        }

        let vanishing_generators = generators
            .iter()
            .enumerate()
            .filter(|(_, generator)| generator.iter().all(Zero::is_zero))
            .map(|(ordinal, _)| ordinal)
            .collect();

        let width = dimension.saturating_mul(occurrences);
        let columns = column_matrix(width, &generators)?;
        let basis = columns.image_basis()?;
        let dimension_of_span = basis.len();

        let affine_span_dimension = affine_span_dimension(dimension, &places)?;
        let free = dimension - affine_span_dimension.min(dimension);
        let closed_form = dimension + dimension * dimension.saturating_sub(1) / 2
            - free * free.saturating_sub(1) / 2;
        if closed_form != dimension_of_span {
            return Err(RigidityError::TrivialDimensionDisagrees {
                measured: dimension_of_span,
                closed_form,
            });
        }

        let degeneracy = if affine_span_dimension == 0 {
            ConfigurationDegeneracy::Coincident
        } else if affine_span_dimension >= dimension {
            ConfigurationDegeneracy::Spanning
        } else if affine_span_dimension == 1 {
            ConfigurationDegeneracy::Collinear
        } else {
            ConfigurationDegeneracy::Deficient
        };

        Ok(Self {
            schema: TRIVIAL_MOTION_SCHEMA.to_owned(),
            dimension,
            occurrences,
            affine_span_dimension,
            degeneracy,
            generators,
            vanishing_generators,
            dimension_of_span,
            basis,
            closed_form,
        })
    }
}

/// The `d + d(d−1)/2` rigid generators of a point family, flattened into the `d·n` configuration
/// space in block order.
fn trivial_generators(
    dimension: usize,
    places: &[Vec<Rat>],
) -> Result<Vec<Vec<Rat>>, RigidityError> {
    let occurrences = places.len();
    let width = dimension
        .checked_mul(occurrences)
        .ok_or(ExactLinearError::ExtentOverflow)?;
    let mut generators = Vec::with_capacity(dimension + dimension * dimension.saturating_sub(1) / 2);
    for axis in 0..dimension {
        let mut generator = vec![Rat::zero(); width];
        for block in 0..occurrences {
            generator[block * dimension + axis] = Rat::one();
        }
        generators.push(generator);
    }
    for first in 0..dimension {
        for second in (first + 1)..dimension {
            // Ω = E_{first,second} − E_{second,first}: (Ω q)_first = q_second,
            // (Ω q)_second = −q_first, every other component zero.
            let mut generator = vec![Rat::zero(); width];
            for (block, place) in places.iter().enumerate() {
                generator[block * dimension + first] = place[second].clone();
                generator[block * dimension + second] = -place[first].clone();
            }
            generators.push(generator);
        }
    }
    Ok(generators)
}

/// `dim span{ q_i − q_0 }`, exact.
fn affine_span_dimension(
    dimension: usize,
    places: &[Vec<Rat>],
) -> Result<usize, RigidityError> {
    let Some((first, rest)) = places.split_first() else {
        return Ok(0);
    };
    let rows = rest
        .iter()
        .map(|place| {
            place
                .iter()
                .zip(first)
                .map(|(entry, origin)| entry - origin)
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    let differences = ExactRatMatrix::shaped(rows.len(), dimension, rows)?;
    Ok(differences.rank()?)
}

/// The vectors as **columns** of a `width × count` matrix, so `image_basis` returns an
/// independent subfamily of the vectors themselves.
fn column_matrix(width: usize, vectors: &[Vec<Rat>]) -> Result<ExactRatMatrix, RigidityError> {
    let rows = (0..width)
        .map(|row| {
            vectors
                .iter()
                .map(|vector| vector[row].clone())
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    Ok(ExactRatMatrix::shaped(width, vectors.len(), rows)?)
}

// -------------------------------------------------------------------------------------------
// the reading
// -------------------------------------------------------------------------------------------

/// The Maxwell counting relation, and the exact identity behind it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MaxwellCount {
    /// `d·n`.
    pub coordinate_freedoms: usize,
    /// `m`.
    pub constraints: usize,
    pub rank: usize,
    pub motion_dimension: usize,
    pub self_stress_dimension: usize,
    /// `d·n − m`. Equal to `dim ker J` exactly when there is no self-stress, and a strict lower
    /// bound otherwise.
    pub counted_freedom: i64,
    /// True when a self-stress exists, so the count alone under-reports the motion space and no
    /// rigidity verdict may be read from it.
    pub count_is_a_bound_only: bool,
}

/// **The complete rigidity reading of one constraint system at one configuration.**
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RigidityReading {
    pub schema: String,
    pub presentation_lineage: String,
    pub dimension: usize,
    pub occurrences: usize,
    pub constraint_count: usize,
    pub rank: usize,
    /// A basis of `ker J`: the infinitesimal motions, exhibited rather than counted.
    pub motions: Vec<Vec<Rat>>,
    pub motion_dimension: usize,
    /// A basis of `ker Jᵀ`: the self-stresses, equivalently the constraint reactions.
    pub self_stresses: Vec<Vec<Rat>>,
    pub self_stress_dimension: usize,
    pub trivial: TrivialMotionReading,
    /// `dim ker J − dim T(q)`: the motions that are not rigid motions of the whole configuration.
    pub internal_motion_dimension: usize,
    pub maxwell: MaxwellCount,
}

impl RigidityReading {
    /// **Infinitesimal** rigidity at this configuration: every infinitesimal motion is a rigid
    /// motion of the whole configuration.
    ///
    /// This is not generic rigidity — that is a statement about almost every configuration of a
    /// combinatorial structure — and it is not finite rigidity. A degenerate configuration can be
    /// infinitesimally flexible while its combinatorics are generically rigid, and the converse
    /// direction fails only through the degenerate locus.
    pub fn is_infinitesimally_rigid(&self) -> bool {
        self.internal_motion_dimension == 0
    }

    /// True when some constraint is dependent on the others.
    pub fn is_redundant(&self) -> bool {
        self.self_stress_dimension > 0
    }
}

/// The reading of one Jacobian: `rank J`, `ker J`, `ker Jᵀ`, the trivial space and the counts.
pub fn rigidity_reading(jacobian: &RigidityJacobian) -> Result<RigidityReading, RigidityError> {
    jacobian.validated()?;
    let dimension = jacobian.dimension();
    let occurrences = jacobian.occurrence_count();
    let constraint_count = jacobian.constraint_count();
    let coordinate_freedoms = jacobian.coordinate_freedoms();

    // One reading, not two: above the prime-image crossover `rank` and `kernel_basis` each decide
    // charts, lift and verify their own certificate over this same matrix.
    let (rank, motions) = jacobian.matrix.rank_and_kernel()?;
    let motion_dimension = motions.len();
    if rank + motion_dimension != coordinate_freedoms {
        return Err(RigidityError::RankNullityFails {
            rank,
            nullity: motion_dimension,
            coordinate_freedoms,
        });
    }
    let self_stresses = jacobian.matrix.cokernel_annihilator()?;
    let self_stress_dimension = self_stresses.len();
    if rank + self_stress_dimension != constraint_count {
        return Err(RigidityError::CokernelCountFails {
            rank,
            self_stress: self_stress_dimension,
            constraints: constraint_count,
        });
    }

    let trivial = TrivialMotionReading::measure(jacobian)?;
    if trivial.dimension_of_span > motion_dimension {
        return Err(RigidityError::TrivialExceedsKernel {
            trivial: trivial.dimension_of_span,
            kernel: motion_dimension,
        });
    }
    let internal_motion_dimension = motion_dimension - trivial.dimension_of_span;

    let counted_freedom = i64::try_from(coordinate_freedoms).unwrap_or(i64::MAX)
        - i64::try_from(constraint_count).unwrap_or(i64::MAX);
    let identity = i64::try_from(motion_dimension).unwrap_or(i64::MAX)
        - i64::try_from(self_stress_dimension).unwrap_or(i64::MAX);
    if identity != counted_freedom {
        return Err(RigidityError::MaxwellIdentityFails {
            motion: motion_dimension,
            self_stress: self_stress_dimension,
            counted: counted_freedom,
        });
    }

    Ok(RigidityReading {
        schema: RIGIDITY_READING_SCHEMA.to_owned(),
        presentation_lineage: jacobian.presentation_lineage.clone(),
        dimension,
        occurrences,
        constraint_count,
        rank,
        motions,
        motion_dimension,
        self_stresses,
        self_stress_dimension,
        trivial,
        internal_motion_dimension,
        maxwell: MaxwellCount {
            coordinate_freedoms,
            constraints: constraint_count,
            rank,
            motion_dimension,
            self_stress_dimension,
            counted_freedom,
            count_is_a_bound_only: self_stress_dimension > 0,
        },
    })
}

// -------------------------------------------------------------------------------------------
// rigid clusters
// -------------------------------------------------------------------------------------------

/// The pairs whose separation is first-order constant under every admitted infinitesimal motion.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RigidPairReading {
    pub schema: String,
    /// Block ordinal pairs `(i,j)`, `i < j`, with `r_ij ⟂ ker J`.
    pub implied_pairs: Vec<(usize, usize)>,
    /// Implied pairs that carry no constraint of their own: the constraint the structure holds
    /// without being told to.
    pub implied_without_constraint: Vec<(usize, usize)>,
    /// Implied pairs whose two occurrences are coincident. Their row is zero, so the criterion
    /// holds by degeneracy and not by rigidity; they are named so the distinction is not lost.
    pub coincident_pairs: Vec<(usize, usize)>,
}

/// Maximal sets of occurrences that move together.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RigidClusterReading {
    pub schema: String,
    /// Maximal sets of pairwise-implied occurrences, each ascending, the whole family ordered.
    /// **Clusters may overlap**: a hinge is exactly two clusters sharing an occurrence.
    pub clusters: Vec<Vec<usize>>,
    pub pairs: RigidPairReading,
    /// The enumeration ceiling this reading was taken under.
    pub bound: usize,
}

/// **Which occurrences move together under every admissible infinitesimal motion.**
///
/// Every returned cluster is verified: each kernel basis vector, restricted to the cluster, is
/// checked to lie in the trivial motion space of that sub-configuration, exactly.
pub fn rigid_clusters(
    jacobian: &RigidityJacobian,
    reading: &RigidityReading,
    bound: usize,
) -> Result<RigidClusterReading, RigidityError> {
    jacobian.validated()?;
    let dimension = jacobian.dimension();
    let places = jacobian.configuration.ordered_places();
    let occurrences = places.len();
    if reading.motions.iter().any(|motion| motion.len() != dimension * occurrences) {
        return Err(RigidityError::MotionWidthDisagrees {
            expected: dimension * occurrences,
        });
    }

    let constrained: BTreeSet<(usize, usize)> = jacobian
        .constraints
        .iter()
        .map(|constraint| {
            let (low, high) = (constraint.lower_block, constraint.upper_block);
            if low <= high { (low, high) } else { (high, low) }
        })
        .collect();

    let mut implied_pairs = Vec::new();
    let mut implied_without_constraint = Vec::new();
    let mut coincident_pairs = Vec::new();
    let mut adjacency = vec![BTreeSet::<usize>::new(); occurrences];
    for left in 0..occurrences {
        for right in (left + 1)..occurrences {
            let difference = (0..dimension)
                .map(|axis| &places[left][axis] - &places[right][axis])
                .collect::<Vec<_>>();
            let coincident = difference.iter().all(Zero::is_zero);
            let implied = reading.motions.iter().all(|motion| {
                let pairing = (0..dimension).fold(Rat::zero(), |sum, axis| {
                    let relative = &motion[left * dimension + axis]
                        - &motion[right * dimension + axis];
                    sum + &difference[axis] * &relative
                });
                pairing.is_zero()
            });
            if implied {
                implied_pairs.push((left, right));
                if !constrained.contains(&(left, right)) {
                    implied_without_constraint.push((left, right));
                }
                if coincident {
                    coincident_pairs.push((left, right));
                }
                adjacency[left].insert(right);
                adjacency[right].insert(left);
            }
        }
    }

    let mut clusters = Vec::new();
    let mut retained = Vec::new();
    bron_kerbosch(
        &adjacency,
        &mut retained,
        (0..occurrences).collect(),
        BTreeSet::new(),
        bound,
        &mut clusters,
    )?;
    clusters.sort();

    for (ordinal, cluster) in clusters.iter().enumerate() {
        if cluster.len() < 2 {
            continue;
        }
        let cluster_places = cluster
            .iter()
            .map(|block| places[*block].clone())
            .collect::<Vec<_>>();
        let generators = trivial_generators(dimension, &cluster_places)?;
        let width = dimension * cluster.len();
        let span = column_matrix(width, &generators)?;
        let span_rank = span.rank()?;
        for (motion_at, motion) in reading.motions.iter().enumerate() {
            let restricted = cluster
                .iter()
                .flat_map(|block| {
                    (0..dimension).map(move |axis| motion[block * dimension + axis].clone())
                })
                .collect::<Vec<_>>();
            let mut extended = generators.clone();
            extended.push(restricted);
            let widened = column_matrix(width, &extended)?;
            if widened.rank()? != span_rank {
                return Err(RigidityError::ClusterNotRigid {
                    cluster: ordinal,
                    motion: motion_at,
                });
            }
        }
    }

    Ok(RigidClusterReading {
        schema: RIGID_CLUSTER_SCHEMA.to_owned(),
        clusters,
        pairs: RigidPairReading {
            schema: RIGID_PAIR_SCHEMA.to_owned(),
            implied_pairs,
            implied_without_constraint,
            coincident_pairs,
        },
        bound,
    })
}

fn bron_kerbosch(
    adjacency: &[BTreeSet<usize>],
    retained: &mut Vec<usize>,
    mut candidates: BTreeSet<usize>,
    mut excluded: BTreeSet<usize>,
    bound: usize,
    clusters: &mut Vec<Vec<usize>>,
) -> Result<(), RigidityError> {
    if candidates.is_empty() && excluded.is_empty() {
        if clusters.len() >= bound {
            return Err(RigidityError::ClusterPopulationTooWide { bound });
        }
        let mut cluster = retained.clone();
        cluster.sort_unstable();
        clusters.push(cluster);
        return Ok(());
    }
    let pivot = candidates
        .union(&excluded)
        .copied()
        .max_by_key(|occurrence| adjacency[*occurrence].intersection(&candidates).count());
    let walk: Vec<usize> = match pivot {
        Some(chosen) => candidates
            .iter()
            .copied()
            .filter(|occurrence| !adjacency[chosen].contains(occurrence))
            .collect(),
        None => candidates.iter().copied().collect(),
    };
    for occurrence in walk {
        let next_candidates = candidates
            .intersection(&adjacency[occurrence])
            .copied()
            .collect();
        let next_excluded = excluded
            .intersection(&adjacency[occurrence])
            .copied()
            .collect();
        retained.push(occurrence);
        bron_kerbosch(
            adjacency,
            retained,
            next_candidates,
            next_excluded,
            bound,
            clusters,
        )?;
        retained.pop();
        candidates.remove(&occurrence);
        excluded.insert(occurrence);
    }
    Ok(())
}

// -------------------------------------------------------------------------------------------
// contact-removal sensitivity
// -------------------------------------------------------------------------------------------

/// What removing one constraint does to the motion space.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConstraintSensitivity {
    pub edge: ConstraintEdge,
    pub provenance: EdgeProvenance,
    /// Some self-stress has a nonzero coefficient here, so this row is dependent on the others
    /// and its removal leaves `rank J` — hence `dim ker J` — unchanged.
    pub carries_self_stress: bool,
    /// `dim ker J` after deleting this one constraint: `motion_dimension + 1` exactly when the
    /// constraint carries no self-stress, and `motion_dimension` otherwise.
    pub motion_dimension_after_removal: usize,
}

/// **Which single contact's removal changes `dim ker J`.**
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RemovalSensitivity {
    pub schema: String,
    pub motion_dimension: usize,
    pub constraints: Vec<ConstraintSensitivity>,
    /// Constraints whose removal raises the motion dimension by exactly one.
    pub load_bearing: Vec<ConstraintEdge>,
    /// Constraints whose removal moves nothing.
    pub redundant: Vec<ConstraintEdge>,
}

/// Read the sensitivity off the self-stress space. No rank is recomputed: a row is dependent on
/// the others **iff** some element of `ker Jᵀ` is supported at it.
pub fn removal_sensitivity(
    jacobian: &RigidityJacobian,
    reading: &RigidityReading,
) -> Result<RemovalSensitivity, RigidityError> {
    jacobian.validated()?;
    if reading.constraint_count != jacobian.constraint_count() {
        return Err(RigidityError::ReadingDisagreesWithJacobian {
            reading: reading.constraint_count,
            jacobian: jacobian.constraint_count(),
        });
    }
    if reading
        .self_stresses
        .iter()
        .any(|stress| stress.len() != reading.constraint_count)
    {
        return Err(RigidityError::SelfStressWidthDisagrees {
            expected: reading.constraint_count,
        });
    }
    let mut constraints = Vec::with_capacity(jacobian.constraints.len());
    let mut load_bearing = Vec::new();
    let mut redundant = Vec::new();
    for (at, constraint) in jacobian.constraints.iter().enumerate() {
        let carries_self_stress = reading
            .self_stresses
            .iter()
            .any(|stress| !stress[at].is_zero());
        let motion_dimension_after_removal = if carries_self_stress {
            redundant.push(constraint.edge);
            reading.motion_dimension
        } else {
            load_bearing.push(constraint.edge);
            reading.motion_dimension + 1
        };
        constraints.push(ConstraintSensitivity {
            edge: constraint.edge,
            provenance: constraint.provenance,
            carries_self_stress,
            motion_dimension_after_removal,
        });
    }
    Ok(RemovalSensitivity {
        schema: REMOVAL_SENSITIVITY_SCHEMA.to_owned(),
        motion_dimension: reading.motion_dimension,
        constraints,
        load_bearing,
        redundant,
    })
}

/// Re-derive a bounded prefix of the sensitivity by **actually deleting the row** and recomputing
/// the exact rank. The self-stress criterion is a theorem, so this cannot fire while the
/// elimination is correct; that is what it is for.
pub fn verify_removal_sensitivity(
    jacobian: &RigidityJacobian,
    sensitivity: &RemovalSensitivity,
    bound: usize,
) -> Result<usize, RigidityError> {
    jacobian.validated()?;
    if sensitivity.constraints.len() != jacobian.constraint_count() {
        return Err(RigidityError::ReadingDisagreesWithJacobian {
            reading: sensitivity.constraints.len(),
            jacobian: jacobian.constraint_count(),
        });
    }
    let width = jacobian.coordinate_freedoms();
    let rows = jacobian.matrix.to_rows();
    let checked = bound.min(rows.len());
    for (at, claimed) in sensitivity.constraints.iter().take(checked).enumerate() {
        let mut reduced = rows.clone();
        reduced.remove(at);
        let removed = ExactRatMatrix::shaped(reduced.len(), width, reduced)?;
        let measured = width - removed.rank()?;
        if measured != claimed.motion_dimension_after_removal {
            return Err(RigidityError::RemovalSensitivityDisagrees {
                constraint: at,
                predicted: claimed.motion_dimension_after_removal,
                measured,
            });
        }
    }
    Ok(checked)
}

// -------------------------------------------------------------------------------------------
// the open family
// -------------------------------------------------------------------------------------------

/// **The rigidity reading of a presentation whose contact set is plural.**
///
/// Indexed exactly as `physical_constraint_grading::ConstraintComplexFamily` is: by the
/// resolutions of the open set, with the two bounds of the 1-cell inclusion order constructed.
/// This is a computed summary receipt, not a remountable source presentation: its serialized
/// bounds retain the reading but not the original physical complex and configuration needed to
/// reproduce them. Consumers that need operative material must retain those source inputs.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RigidityFamily {
    pub schema: String,
    pub presentation_lineage: String,
    /// The exact open set, each contact with the interval and aperture that could not decide it.
    pub open_contacts: Vec<OpenContact>,
    /// Open readings whose 1-cell exists anyway under another aperture. Retained, not dropped.
    pub open_subsumed_by_inside: Vec<ConstraintEdge>,
    /// Every open contact refused: the member whose incidence is the presentation's own.
    pub refusing: RigidityReading,
    /// Every open contact founded.
    pub admitting: RigidityReading,
}

impl RigidityFamily {
    /// The presentation decides its own constraint set: the family is a singleton.
    pub fn is_determinate(&self) -> bool {
        self.open_contacts.is_empty()
    }

    /// `2^n` for `n` open contacts.
    pub fn cardinality(&self) -> BigUint {
        BigUint::from(1_u8) << self.open_contacts.len()
    }

    /// `(admitting, refusing)`: adding constraints can only shrink the motion space, so these
    /// bracket `dim ker J` over the whole family.
    pub fn motion_dimension_bounds(&self) -> (usize, usize) {
        (
            self.admitting.motion_dimension,
            self.refusing.motion_dimension,
        )
    }

    /// **The finding**: the open class is a rigidity question on this presentation.
    pub fn bounds_differ_in_motion_dimension(&self) -> bool {
        self.admitting.motion_dimension != self.refusing.motion_dimension
    }
}

/// The Jacobian of one named member of the open family.
pub fn rigidity_jacobian_member(
    complex: &PhysicalConstraintComplex,
    configuration: &ExactConfiguration,
    law: &OpenContactLaw,
) -> Result<RigidityJacobian, RigidityError> {
    configuration.within_presented(complex)?;
    let member = graded_constraint_member(complex, law)?;
    RigidityJacobian::from_member(&member, configuration)
}

/// The rigidity reading of one named member of the open family.
pub fn rigidity_member(
    complex: &PhysicalConstraintComplex,
    configuration: &ExactConfiguration,
    law: &OpenContactLaw,
) -> Result<RigidityReading, RigidityError> {
    let jacobian = rigidity_jacobian_member(complex, configuration, law)?;
    rigidity_reading(&jacobian)
}

/// **The family, with its open set and its two bounding readings.**
pub fn rigidity_family(
    complex: &PhysicalConstraintComplex,
    configuration: &ExactConfiguration,
) -> Result<RigidityFamily, RigidityError> {
    configuration.within_presented(complex)?;
    let family = graded_constraint_family(complex)?;
    let refusing = rigidity_reading(&RigidityJacobian::from_member(
        &family.refusing,
        configuration,
    )?)?;
    let admitting = rigidity_reading(&RigidityJacobian::from_member(
        &family.admitting,
        configuration,
    )?)?;
    if admitting.motion_dimension > refusing.motion_dimension {
        return Err(RigidityError::MotionDimensionNotAntitone {
            refusing: refusing.motion_dimension,
            admitting: admitting.motion_dimension,
        });
    }
    Ok(RigidityFamily {
        schema: RIGIDITY_FAMILY_SCHEMA.to_owned(),
        presentation_lineage: complex.presentation_lineage.clone(),
        open_contacts: family.open_contacts,
        open_subsumed_by_inside: family.open_subsumed_by_inside,
        refusing,
        admitting,
    })
}

// -------------------------------------------------------------------------------------------
// schemas and refusals
// -------------------------------------------------------------------------------------------

pub const RIGIDITY_JACOBIAN_SCHEMA: &str = "holonic-engine.rigidity-jacobian.v1";
pub const RIGIDITY_READING_SCHEMA: &str = "holonic-engine.rigidity-reading.v1";
pub const TRIVIAL_MOTION_SCHEMA: &str = "holonic-engine.rigidity-trivial-motions.v1";
pub const RIGID_PAIR_SCHEMA: &str = "holonic-engine.rigidity-implied-pairs.v1";
pub const RIGID_CLUSTER_SCHEMA: &str = "holonic-engine.rigidity-clusters.v1";
pub const REMOVAL_SENSITIVITY_SCHEMA: &str = "holonic-engine.rigidity-removal-sensitivity.v1";
pub const RIGIDITY_FAMILY_SCHEMA: &str = "holonic-engine.rigidity-family.v1";

#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum RigidityError {
    #[error("the presented constraint complex refused: {0}")]
    Constraint(#[from] ConstraintError),
    #[error("the graded constraint adapter refused: {0}")]
    Grading(#[from] ConstraintGradingError),
    #[error("the exact linear carrier refused: {0}")]
    Linear(#[from] ExactLinearError),
    #[error("a configuration in zero dimensions carries no motion and no constraint")]
    ZeroDimension,
    #[error("a configuration with no occurrence has no constraint Jacobian")]
    EmptyConfiguration,
    #[error(
        "occurrence {occurrence:?} carries {supplied} coordinates in a declared {declared}-dimensional configuration"
    )]
    RaggedConfiguration {
        occurrence: ConstraintVertexId,
        declared: usize,
        supplied: usize,
    },
    #[error(
        "the presented position of occurrence {occurrence:?} has width on axis {axis}; an interval is a precision reading and not a configuration, and a Jacobian entry may not be chosen inside it"
    )]
    ConfigurationIsNotAPoint {
        occurrence: ConstraintVertexId,
        axis: usize,
    },
    #[error(
        "the declared place of occurrence {occurrence:?} lies outside its presented coordinate box on axis {axis}"
    )]
    ConfigurationOutsideBox {
        occurrence: ConstraintVertexId,
        axis: usize,
    },
    #[error(
        "a presented complex carries three-dimensional coordinate boxes; the configuration declares {supplied} dimensions"
    )]
    PresentationDimensionDisagrees { supplied: usize },
    #[error("occurrence {0:?} carries no declared place in this configuration")]
    OccurrenceAbsent(ConstraintVertexId),
    #[error("the one-cell {0:?} carries a founded cell but no declared provenance")]
    ConstraintProvenanceAbsent(ConstraintEdge),
    #[error(
        "the Jacobian is {rows} x {columns} where its constraint population and configuration require {expected_rows} x {expected_columns}"
    )]
    JacobianShapeDisagrees {
        rows: usize,
        columns: usize,
        expected_rows: usize,
        expected_columns: usize,
    },
    #[error("the constraint {edge:?} addresses a block outside this configuration")]
    BlockOutsideConfiguration { edge: ConstraintEdge },
    #[error(
        "trivial generator {generator} is not annihilated by constraint {constraint}; a rigid motion of the whole configuration must lie in ker J"
    )]
    TrivialMotionOutsideKernel { generator: usize, constraint: usize },
    #[error(
        "the measured trivial dimension {measured} disagrees with the closed form {closed_form} derived from the affine span"
    )]
    TrivialDimensionDisagrees { measured: usize, closed_form: usize },
    #[error("the trivial space has dimension {trivial} inside a kernel of dimension {kernel}")]
    TrivialExceedsKernel { trivial: usize, kernel: usize },
    #[error("rank {rank} plus nullity {nullity} is not the configuration width {coordinate_freedoms}")]
    RankNullityFails {
        rank: usize,
        nullity: usize,
        coordinate_freedoms: usize,
    },
    #[error("rank {rank} plus self-stress dimension {self_stress} is not the constraint count {constraints}")]
    CokernelCountFails {
        rank: usize,
        self_stress: usize,
        constraints: usize,
    },
    #[error(
        "the Maxwell identity fails: dim ker J {motion} minus dim ker J^T {self_stress} is not the count {counted}"
    )]
    MaxwellIdentityFails {
        motion: usize,
        self_stress: usize,
        counted: i64,
    },
    #[error("an infinitesimal motion does not carry {expected} coordinates")]
    MotionWidthDisagrees { expected: usize },
    #[error("a self-stress does not carry {expected} coefficients")]
    SelfStressWidthDisagrees { expected: usize },
    #[error("the reading carries {reading} constraints where the Jacobian carries {jacobian}")]
    ReadingDisagreesWithJacobian { reading: usize, jacobian: usize },
    #[error(
        "the implied-pair graph carries more than {bound} maximal clusters; enumeration was bounded rather than exhausted"
    )]
    ClusterPopulationTooWide { bound: usize },
    #[error(
        "motion {motion} does not restrict to a rigid motion of cluster {cluster}, so the cluster is not one"
    )]
    ClusterNotRigid { cluster: usize, motion: usize },
    #[error(
        "removing constraint {constraint} leaves a motion dimension of {measured} where the self-stress support predicts {predicted}"
    )]
    RemovalSensitivityDisagrees {
        constraint: usize,
        predicted: usize,
        measured: usize,
    },
    #[error(
        "the admitting bound has motion dimension {admitting} above the refusing bound's {refusing}; founding a constraint cannot enlarge ker J"
    )]
    MotionDimensionNotAntitone { refusing: usize, admitting: usize },
}

#[cfg(test)]
#[path = "rigidity_receiver/tests.rs"]
mod tests;
