import Holonics.Foundation.FractalPacking
import Mathlib.NumberTheory.ArithmeticFunction.Moebius
import Mathlib.NumberTheory.LSeries.RiemannZeta
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.Complex.Log
import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.NumberTheory.Real.GoldenRatio

/-!
# Fractal strings: the string of holes, and hearing it multiplies by ζ

Brandon's first axiom (July 13): what gets bigger the more you take away is a hole, and "the music
is not in the sound itself, it is in the absence of sound in between the notes".  A **fractal
string** (Lapidus; Lapidus–van Frankenhuijsen, *Fractal Geometry, Complex Dimensions and Zeta
Functions*, 2nd ed., Springer 2013) is the family of lengths `ℓ_j > 0` of the complementary open
intervals — the holes — of a compact subset of an interval.  Each hole is the reflection half of a
ring of circumference `2ℓ_j`; its Dirichlet modes are that ring's reflection-reversing modes, whose
windings `k = 1, 2, …` sound at the normalized frequencies `k·ℓ_j⁻¹`.

This file owns the exact counting and zeta laws of that object.

* **The two counts.**  At scale `x` a receiver counts the holes of length at least `1/x`
  (`geometricCount`, the holes' face) and the harmonics of frequency at most `x` (`spectralCount`,
  what the receiver hears).  An infinite string has only finitely many holes of length at least
  `1/x`, so every count of it at scale `x` is the count of a finite family `J`; no infinite-string
  construction enters.
* **Hearing is exact** (`spectralCount_eq_sum_geometricCount`): `N_ν(x) = Σ_(k≥1) N_ℒ(x/k)`, the
  geometric count carried round every winding.
* **Listening is exact** (`geometricCount_eq_sum_moebius_spectralCount`):
  `N_ℒ(x) = Σ_(k≥1) μ(k)·N_ν(x/k)`.  Division by ζ is Möbius inversion, `1/ζ = Σ μ(n)·n^(−s)`, here
  in its finite real-variable form (`sum_moebius_smul_sum_mul`).
* **Hearing multiplies by ζ** (`spectralZeta_eq_riemannZeta_mul_geometricZeta`):
  `ζ_ν(s) = ζ(s)·ζ_ℒ(s)` for `Re s > 1`.
* **Self-similar strings** (`selfSimilarZeta_eq`): the string generated by ratios `r_i` and one gap
  `g` has `ζ_ℒ(s) = g^s / (1 − Σ r_i^s)`.
* **The Cantor string.**  `Foundation/FractalPacking` supplies the holes: the sibling gap of each
  addressed cell (`cantorGap`), of length `3^(−(n+1))` at depth `n` (`cantor_gap_length`), `2^n` of
  them (`cantor_depth_gaps`, from `length_words`).  It is the self-similar string with ratios
  `(⅓, ⅓)` and gap `⅓` (`cantor_depth_sum`), so `ζ_CS(s) = 3^(−s)/(1 − 2·3^(−s))`
  (`cantorStringZeta_eq`), whose poles, the complex dimensions, are exactly `D + i·2πk/log 3`
  with `D = log 2/log 3` (`cantor_complex_dimensions`, `cantor_moran_dimension`).

**Winding-guide objects touched.**  The helix: a hole's harmonics are its windings and hearing sums
the geometric count over them.  Faces and placement: the geometric zeta is the holes' face, and a
complex dimension is a dilation exponent `D` plus a rotation of period `2π/log 3` in the log chart.
The tower thread: the self-similar restriction of `FractalPacking`, one level per hand.  The pair,
cell holonomy and tube stay attached and are not used here.

Every count is an exact natural number and every identity is exact; the reals are Lean's exact
reals, and `ζ` enters only through its Dirichlet series on `Re s > 1`.
-/

namespace Holonics.Foundation.FractalString

open Finset
open scoped ArithmeticFunction.Moebius Real

/-! ## The two counts of a finite string -/

section Counts

variable {ι : Type*}

/-- [definition] **The geometric count** `N_ℒ(x) = #{j ∈ J : x·ℓ_j ≥ 1}`: the holes of length at
least `1/x`.  An infinite string has only finitely many such holes at each scale, so its count at
scale `x` is this count over the finite family `J` of those holes. -/
noncomputable def geometricCount (J : Finset ι) (ℓ : ι → ℝ) (x : ℝ) : ℕ :=
  (J.filter fun j => 1 ≤ x * ℓ j).card

/-- [definition] **The spectral count** `N_ν(x) = Σ_(j∈J) ⌊x·ℓ_j⌋₊`: for each hole `j`, the
harmonics `k ≥ 1` with frequency `k·ℓ_j⁻¹ ≤ x`, i.e. the windings `k ≤ x·ℓ_j`
(`spectralCount_eq_card_pairs`). -/
noncomputable def spectralCount (J : Finset ι) (ℓ : ι → ℝ) (x : ℝ) : ℕ :=
  ∑ j ∈ J, ⌊x * ℓ j⌋₊

/-- [proved-derived; formal-checked] One ring's windings inside a window: when `y < K + 1`, the
windings `k ∈ [1, K]` with `k ≤ y` are exactly `⌊y⌋₊` many. -/
theorem floor_eq_card_windings {y : ℝ} {K : ℕ} (hy : y < K + 1) :
    ⌊y⌋₊ = ((Icc 1 K).filter fun k : ℕ => (k : ℝ) ≤ y).card := by
  have hfloor : ⌊y⌋₊ ≤ K := by
    have := (Nat.floor_lt' (Nat.succ_ne_zero K)).2 (by exact_mod_cast hy)
    omega
  have hset : ((Icc 1 K).filter fun k : ℕ => (k : ℝ) ≤ y) = Icc 1 ⌊y⌋₊ := by
    ext k
    simp only [mem_filter, mem_Icc]
    constructor
    · rintro ⟨⟨hk1, -⟩, hky⟩
      exact ⟨hk1, (Nat.le_floor_iff' (by omega)).2 hky⟩
    · rintro ⟨hk1, hkf⟩
      exact ⟨⟨hk1, hkf.trans hfloor⟩, (Nat.le_floor_iff' (by omega)).1 hkf⟩
  rw [hset, Nat.card_Icc]
  omega

/-- [proved-derived; formal-checked] **The spectral count counts pairs.**  For any window `K` with
`x·ℓ_j < K + 1` on `J`, `N_ν(x)` is the number of pairs `(j, k)`, `j ∈ J`, `1 ≤ k`, with
`k ≤ x·ℓ_j`: a hole and one of its windings. -/
theorem spectralCount_eq_card_pairs (J : Finset ι) (ℓ : ι → ℝ) {x : ℝ} {K : ℕ}
    (hK : ∀ j ∈ J, x * ℓ j < K + 1) :
    spectralCount J ℓ x =
      ((J ×ˢ Icc 1 K).filter fun p : ι × ℕ => (p.2 : ℝ) ≤ x * ℓ p.1).card := by
  rw [spectralCount, card_filter, sum_product]
  refine sum_congr rfl fun j hj => ?_
  rw [floor_eq_card_windings (hK j hj), card_filter]

/-- [proved-derived; formal-checked] **Hearing is exact.**  For any window `K` with
`x·ℓ_j < K + 1` on `J`, `N_ν(x) = Σ_(k=1)^K N_ℒ(x/k)`: the `k`-th harmonic of hole `j` sounds at
or below `x` exactly when hole `j` is at least `1/(x/k)` long, so the spectrum is the geometric
count carried round every winding.  Neither the sign of `x` nor of the lengths is needed. -/
theorem spectralCount_eq_sum_geometricCount (J : Finset ι) (ℓ : ι → ℝ) {x : ℝ} {K : ℕ}
    (hK : ∀ j ∈ J, x * ℓ j < K + 1) :
    spectralCount J ℓ x = ∑ k ∈ Icc 1 K, geometricCount J ℓ (x / k) := by
  have hwind : ∀ k ∈ Icc 1 K, ∀ j, (1 ≤ x / k * ℓ j ↔ (k : ℝ) ≤ x * ℓ j) := by
    intro k hk j
    have hk0 : (0 : ℝ) < k := by exact_mod_cast (mem_Icc.1 hk).1
    rw [div_mul_eq_mul_div, one_le_div hk0]
  calc spectralCount J ℓ x
      = ∑ j ∈ J, ∑ k ∈ Icc 1 K, if (k : ℝ) ≤ x * ℓ j then 1 else 0 := by
        refine sum_congr rfl fun j hj => ?_
        rw [floor_eq_card_windings (hK j hj), card_filter]
    _ = ∑ k ∈ Icc 1 K, ∑ j ∈ J, if (k : ℝ) ≤ x * ℓ j then 1 else 0 := sum_comm
    _ = ∑ k ∈ Icc 1 K, geometricCount J ℓ (x / k) := by
        refine sum_congr rfl fun k hk => ?_
        rw [geometricCount, card_filter]
        refine sum_congr rfl fun j _ => ?_
        simp only [hwind k hk j]

/-- [proved-standard; formal-checked] **Möbius inversion in its finite real-variable form.**  If
`f N = 0` for every `N > K`, then `Σ_(k=1)^K μ(k)·Σ_(m=1)^K f(k·m) = f(1)`: the double sum
regroups by `N = k·m` into `Σ_(N ≤ K) f(N)·Σ_(k∣N) μ(k)`, and `Σ_(k∣N) μ(k) = [N = 1]`
(`ArithmeticFunction.moebius_mul_coe_zeta`).  This is `1/ζ · ζ = 1` read on the multiplicative
semigroup of windings. -/
theorem sum_moebius_smul_sum_mul {R : Type*} [AddCommGroup R] (K : ℕ) (f : ℕ → R)
    (hf : ∀ N, K < N → f N = 0) :
    ∑ k ∈ Icc 1 K, μ k • ∑ m ∈ Icc 1 K, f (k * m) = f 1 := by
  have multiples : ∀ k ∈ Icc 1 K,
      ∑ m ∈ Icc 1 K, f (k * m) = ∑ N ∈ Icc 1 K, if k ∣ N then f N else 0 := by
    intro k hk
    have hk1 : 1 ≤ k := (mem_Icc.1 hk).1
    refine sum_bij_ne_zero (fun m _ _ => k * m) ?_ ?_ ?_ ?_
    · intro m hm hfm
      have hm1 := (mem_Icc.1 hm).1
      refine mem_Icc.2 ⟨Nat.one_le_iff_ne_zero.2 (Nat.mul_ne_zero (by omega) (by omega)), ?_⟩
      by_contra hlt
      exact hfm (hf _ (not_le.1 hlt))
    · intro m₁ _ _ m₂ _ _ h
      exact Nat.eq_of_mul_eq_mul_left hk1 h
    · intro N hN hg
      have hdvd : k ∣ N := by
        by_contra h
        exact hg (if_neg h)
      obtain ⟨m, rfl⟩ := hdvd
      have hN1 := mem_Icc.1 hN
      have hm1 : 1 ≤ m := by
        rcases Nat.eq_zero_or_pos m with h | h
        · subst h
          simp at hN1
        · exact h
      refine ⟨m, mem_Icc.2 ⟨hm1, le_trans (Nat.le_mul_of_pos_left m hk1) hN1.2⟩, ?_, rfl⟩
      simpa [if_pos (dvd_mul_right k m)] using hg
    · intro m _ _
      rw [if_pos (dvd_mul_right k m)]
  have divisorSum : ∀ N ∈ Icc 1 K,
      ∑ k ∈ Icc 1 K, μ k • (if k ∣ N then f N else 0) = if N = 1 then f N else 0 := by
    intro N hN
    have hN1 := mem_Icc.1 hN
    have hdiv : (Icc 1 K).filter (· ∣ N) = N.divisors := by
      ext k
      simp only [mem_filter, mem_Icc, Nat.mem_divisors]
      constructor
      · rintro ⟨-, h⟩
        exact ⟨h, by omega⟩
      · rintro ⟨h, hN0⟩
        exact ⟨⟨Nat.pos_of_dvd_of_pos h (by omega), (Nat.le_of_dvd (by omega) h).trans hN1.2⟩, h⟩
    have hsum : ∑ k ∈ N.divisors, μ k = if N = 1 then 1 else 0 := by
      rw [← ArithmeticFunction.coe_mul_zeta_apply, ArithmeticFunction.moebius_mul_coe_zeta,
        ArithmeticFunction.one_apply]
    calc ∑ k ∈ Icc 1 K, μ k • (if k ∣ N then f N else 0)
        = ∑ k ∈ Icc 1 K, if k ∣ N then μ k • f N else 0 := by
          refine sum_congr rfl fun k _ => ?_
          split_ifs <;> simp
      _ = ∑ k ∈ (Icc 1 K).filter (· ∣ N), μ k • f N := (sum_filter _ _).symm
      _ = (∑ k ∈ N.divisors, μ k) • f N := by rw [hdiv, sum_smul]
      _ = if N = 1 then f N else 0 := by
          rw [hsum]
          split_ifs <;> simp
  calc ∑ k ∈ Icc 1 K, μ k • ∑ m ∈ Icc 1 K, f (k * m)
      = ∑ k ∈ Icc 1 K, ∑ N ∈ Icc 1 K, μ k • (if k ∣ N then f N else 0) := by
        refine sum_congr rfl fun k hk => ?_
        rw [multiples k hk, smul_sum]
    _ = ∑ N ∈ Icc 1 K, ∑ k ∈ Icc 1 K, μ k • (if k ∣ N then f N else 0) := sum_comm
    _ = ∑ N ∈ Icc 1 K, if N = 1 then f N else 0 := sum_congr rfl divisorSum
    _ = f 1 := by
        rw [sum_ite_eq']
        split_ifs with h
        · rfl
        · exact (hf 1 (by simp at h; omega)).symm

/-- [proved-derived; formal-checked] **Listening is exact.**  For any window `K` with
`x·ℓ_j < K + 1` on `J`, `N_ℒ(x) = Σ_(k=1)^K μ(k)·N_ν(x/k)`.  At full resolution the geometric count,
hence the length multiset (not the placement), is recovered exactly by finite Möbius inversion:
division by ζ.  The exact count has no nullity on the length multiset; every coarser receiver,
asymptotic or finite-resolution, has its own kernel. -/
theorem geometricCount_eq_sum_moebius_spectralCount (J : Finset ι) (ℓ : ι → ℝ) {x : ℝ} {K : ℕ}
    (hK : ∀ j ∈ J, x * ℓ j < K + 1) :
    (geometricCount J ℓ x : ℤ) = ∑ k ∈ Icc 1 K, μ k * (spectralCount J ℓ (x / k) : ℤ) := by
  set f : ℕ → ℤ := fun N => geometricCount J ℓ (x / N)
  have hf : ∀ N, K < N → f N = 0 := by
    intro N hN
    simp only [f, Nat.cast_eq_zero, geometricCount, card_eq_zero, filter_eq_empty_iff]
    intro j hj h1
    have hN0 : (0 : ℝ) < N := by exact_mod_cast Nat.zero_lt_of_lt hN
    rw [div_mul_eq_mul_div, one_le_div hN0] at h1
    have hKN : (K : ℝ) + 1 ≤ N := by exact_mod_cast hN
    linarith [hK j hj]
  have hear : ∀ k ∈ Icc 1 K, (spectralCount J ℓ (x / k) : ℤ) = ∑ m ∈ Icc 1 K, f (k * m) := by
    intro k hk
    have hk1 : (1 : ℝ) ≤ k := by exact_mod_cast (mem_Icc.1 hk).1
    have hK' : ∀ j ∈ J, x / k * ℓ j < K + 1 := by
      intro j hj
      rw [div_mul_eq_mul_div]
      rcases le_or_gt (x * ℓ j) 0 with h | h
      · have : x * ℓ j / k ≤ 0 := div_nonpos_of_nonpos_of_nonneg h (by linarith)
        have : (0 : ℝ) ≤ K := Nat.cast_nonneg K
        linarith
      · exact (div_le_self h.le hk1).trans_lt (hK j hj)
    rw [spectralCount_eq_sum_geometricCount J ℓ hK', Nat.cast_sum]
    refine sum_congr rfl fun m _ => ?_
    simp only [f, Nat.cast_mul, div_div]
  calc (geometricCount J ℓ x : ℤ) = f 1 := by simp [f]
    _ = ∑ k ∈ Icc 1 K, μ k • ∑ m ∈ Icc 1 K, f (k * m) := (sum_moebius_smul_sum_mul K f hf).symm
    _ = ∑ k ∈ Icc 1 K, μ k * (spectralCount J ℓ (x / k) : ℤ) := by
        refine sum_congr rfl fun k hk => ?_
        rw [hear k hk, smul_eq_mul]

end Counts

/-! ## Hearing multiplies by ζ -/

section Zeta

variable {ι : Type*}

/-- [proved-standard; formal-checked] One harmonic's power: for `a, b > 0`,
`(a/b)^(−s) = a^(−s)·b^s`. -/
private theorem div_cpow_neg_of_pos {a b : ℝ} (ha : 0 < a) (hb : 0 < b) (s : ℂ) :
    ((a : ℂ) / (b : ℂ)) ^ (-s) = (a : ℂ) ^ (-s) * (b : ℂ) ^ s := by
  rw [div_eq_mul_inv, ← Complex.ofReal_inv,
    Complex.mul_cpow_ofReal_nonneg ha.le (inv_nonneg.2 hb.le), Complex.ofReal_inv,
    Complex.inv_cpow _ _ (by rw [Complex.arg_ofReal_of_nonneg hb.le]; exact Real.pi_ne_zero.symm),
    Complex.cpow_neg (b : ℂ) s, inv_inv]

/-- [proved-standard; formal-checked] **The spectral zeta factors** (Lapidus–van Frankenhuijsen,
Ch. 1).  For `Re s > 1`, `ζ_ν(s) = Σ_(j∈J) Σ_(k≥1) (k·ℓ_j⁻¹)^(−s) = ζ(s)·Σ_(j∈J) ℓ_j^s`: what
a receiver hears is the holes' face `ζ_ℒ` multiplied by the Riemann zeta, one factor `k^(−s)` per
winding. -/
theorem spectralZeta_eq_riemannZeta_mul_geometricZeta (J : Finset ι) (ℓ : ι → ℝ)
    (hℓ : ∀ j ∈ J, 0 < ℓ j) {s : ℂ} (hs : 1 < s.re) :
    ∑ j ∈ J, ∑' k : ℕ, ((k + 1 : ℂ) / ℓ j) ^ (-s) = riemannZeta s * ∑ j ∈ J, (ℓ j : ℂ) ^ s := by
  rw [mul_sum]
  refine sum_congr rfl fun j hj => ?_
  have hk : ∀ k : ℕ, ((k + 1 : ℂ) / ℓ j) ^ (-s) = 1 / (k + 1 : ℂ) ^ s * (ℓ j : ℂ) ^ s := by
    intro k
    have hcast : (k + 1 : ℂ) = (((k : ℝ) + 1 : ℝ) : ℂ) := by push_cast; rfl
    rw [hcast, div_cpow_neg_of_pos (by positivity) (hℓ j hj), Complex.cpow_neg, one_div]
  simp_rw [hk]
  rw [tsum_mul_right, zeta_eq_tsum_one_div_nat_add_one_cpow hs]

end Zeta

/-! ## Self-similar strings -/

section SelfSimilar

variable {N : ℕ}

/-- [proved-standard; formal-checked] `(r^n)^s = (r^s)^n` for `r ≥ 0`. -/
private theorem ofReal_pow_cpow {r : ℝ} (hr : 0 ≤ r) (n : ℕ) (s : ℂ) :
    ((r ^ n : ℝ) : ℂ) ^ s = ((r : ℂ) ^ s) ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, Complex.ofReal_mul, Complex.mul_cpow_ofReal_nonneg (pow_nonneg hr n) hr, ih,
        pow_succ]

/-- [proved-standard; formal-checked] `(Π_i a_i)^s = Π_i a_i^s` for `a_i ≥ 0`. -/
private theorem ofReal_prod_cpow {n : ℕ} (a : Fin n → ℝ) (ha : ∀ i, 0 ≤ a i) (s : ℂ) :
    ((∏ i, a i : ℝ) : ℂ) ^ s = ∏ i, (a i : ℂ) ^ s := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Fin.prod_univ_succ, Fin.prod_univ_succ, Complex.ofReal_mul,
        Complex.mul_cpow_ofReal_nonneg (ha 0) (prod_nonneg fun i _ => ha _),
        ih _ fun i => ha _]

/-- [definition] The hole at address `w` of the self-similar string with ratios `r` and one gap
`g`: `g·Π_i r_(w_i)`, a word of `n` restrictions applied to the first gap. -/
def selfSimilarLength (r : Fin N → ℝ) (g : ℝ) {n : ℕ} (w : Fin n → Fin N) : ℝ :=
  g * ∏ i, r (w i)

/-- [proved-derived; formal-checked] **One tower level of the zeta face.**  The `N^n` holes at
depth `n` contribute `g^s·(Σ_i r_i^s)^n`: each level multiplies the face by `Σ_i r_i^s`. -/
theorem selfSimilar_depth_sum (r : Fin N → ℝ) (g : ℝ) (hr : ∀ i, 0 ≤ r i) (hg : 0 ≤ g)
    (n : ℕ) (s : ℂ) :
    ∑ w : Fin n → Fin N, (selfSimilarLength r g w : ℂ) ^ s =
      (g : ℂ) ^ s * (∑ i, (r i : ℂ) ^ s) ^ n := by
  have hterm : ∀ w : Fin n → Fin N,
      (selfSimilarLength r g w : ℂ) ^ s = (g : ℂ) ^ s * ∏ i, (r (w i) : ℂ) ^ s := by
    intro w
    rw [selfSimilarLength, Complex.ofReal_mul,
      Complex.mul_cpow_ofReal_nonneg hg (prod_nonneg fun i _ => hr _),
      ofReal_prod_cpow _ fun i => hr _]
  simp_rw [hterm]
  rw [← mul_sum, Fintype.sum_pow]

/-- [proved-standard; formal-checked] **The self-similar string's geometric zeta**
(Lapidus–van Frankenhuijsen, Ch. 2).  When `‖Σ_i r_i^s‖ < 1`,
`ζ_ℒ(s) = Σ_n Σ_(|w|=n) (g·Π r_(w_i))^s = g^s / (1 − Σ_i r_i^s)`: the tower of restrictions sums
as a geometric series, and the complex dimensions are the roots of the Moran equation
`Σ_i r_i^s = 1`. -/
theorem selfSimilarZeta_eq (r : Fin N → ℝ) (g : ℝ) (hr : ∀ i, 0 ≤ r i) (hg : 0 ≤ g) {s : ℂ}
    (hs : ‖∑ i, (r i : ℂ) ^ s‖ < 1) :
    ∑' n : ℕ, ∑ w : Fin n → Fin N, (selfSimilarLength r g w : ℂ) ^ s =
      (g : ℂ) ^ s / (1 - ∑ i, (r i : ℂ) ^ s) := by
  simp_rw [selfSimilar_depth_sum r g hr hg]
  rw [tsum_mul_left, tsum_geometric_of_norm_lt_one hs, div_eq_mul_inv]

/-- [proved-standard; formal-checked] `((2^(−t) : ℝ) : ℂ)^s = 2^(−t s)` for real `t`. -/
private theorem two_rpow_neg_cpow (t : ℝ) (s : ℂ) :
    (((2 : ℝ) ^ (-t) : ℝ) : ℂ) ^ s = (2 : ℂ) ^ (-(t : ℂ) * s) := by
  rw [Complex.ofReal_cpow (by norm_num)]
  push_cast
  have hlog : (Complex.log 2).im = 0 := by
    rw [Complex.log_im]
    simp
  have him : (Complex.log 2 * -(t : ℂ)).im = 0 := by
    simp [hlog]
  rw [Complex.cpow_mul _ (by rw [him]; linarith [Real.pi_pos]) (by rw [him]; exact Real.pi_pos.le)]

/-- [definition] **The golden string's ratios** (Lapidus–van Frankenhuijsen, the golden string):
`2^(−1)` and `2^(−φ)`, one first gap of length one. Its scaling ratios are nonlattice: their
logarithms stand in the golden ratio. -/
noncomputable def goldenRatios : Fin 2 → ℝ := ![(2 : ℝ) ^ (-(1 : ℝ)), (2 : ℝ) ^ (-Real.goldenRatio)]

/-- [proved-derived; formal-checked] **The golden string's geometric zeta.** Where
`‖2^(−s) + 2^(−φ s)‖ < 1`, `ζ_GS(s) = 1 / (1 − 2^(−s) − 2^(−φ s))`: the instance of
`selfSimilarZeta_eq`. [proved-standard, not proved here] Its complex dimensions, the poles of this
closed form, solve `2^(−ω) + 2^(−φ ω) = 1`, and the Fibonacci convergents of `φ` give its lattice
approximants (Lapidus–van Frankenhuijsen). The golden ratio enters as the ratio of the two
log-scales, not as a zero of ζ. -/
theorem goldenStringZeta_eq {s : ℂ}
    (hs : ‖(2 : ℂ) ^ (-s) + (2 : ℂ) ^ (-(Real.goldenRatio : ℂ) * s)‖ < 1) :
    ∑' n : ℕ, ∑ w : Fin n → Fin 2, (selfSimilarLength goldenRatios 1 w : ℂ) ^ s =
      1 / (1 - (2 : ℂ) ^ (-s) - (2 : ℂ) ^ (-(Real.goldenRatio : ℂ) * s)) := by
  have hr : ∀ i, 0 ≤ goldenRatios i := by
    intro i; fin_cases i <;> simp [goldenRatios] <;> positivity
  have hsum : ∑ i, (goldenRatios i : ℂ) ^ s =
      (2 : ℂ) ^ (-s) + (2 : ℂ) ^ (-(Real.goldenRatio : ℂ) * s) := by
    rw [Fin.sum_univ_two]
    simp only [goldenRatios, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_fin_one]
    rw [two_rpow_neg_cpow, two_rpow_neg_cpow]
    push_cast
    ring_nf
  rw [selfSimilarZeta_eq goldenRatios 1 hr zero_le_one (by rw [hsum]; exact hs), hsum]
  simp only [Complex.ofReal_one, Complex.one_cpow]
  ring

end SelfSimilar

/-! ## The Cantor string: the holes of `FractalPacking` -/

section Cantor

open Holonics.Foundation.FractalPacking

/-- [definition] **The Cantor hole** of the cell addressed by `w`: the open gap between its two
children, removed at the restriction that produces them. -/
def cantorGap (w : List Hand) : ℚ :=
  (rightChild (descend w root)).lower - (leftChild (descend w root)).upper

/-- [proved-derived; formal-checked] **The Cantor hole at depth `|w|` has length `3^(−(|w|+1))`**:
one third of the addressed cell's width (`sibling_gap`, `root_descend_width`). -/
theorem cantor_gap_length (w : List Hand) : cantorGap w = (1 / 3 : ℚ) ^ (w.length + 1) := by
  rw [cantorGap, sibling_gap, root_descend_width, pow_succ]
  ring

/-- [proved-derived; formal-checked] **The Cantor string at depth `n`**: exactly `2^n` holes, each
of length `3^(−(n+1))` (`length_words`, `cantor_gap_length`). -/
theorem cantor_depth_gaps (n : ℕ) :
    (words n).map cantorGap = List.replicate (2 ^ n) ((1 / 3 : ℚ) ^ (n + 1)) := by
  rw [List.map_congr_left fun w hw => by rw [cantor_gap_length, mem_words.1 hw],
    List.map_const', length_words]

/-- [proved-standard; formal-checked] `(⅓)^s = 3^(−s)`. -/
private theorem third_cpow (s : ℂ) : ((1 / 3 : ℝ) : ℂ) ^ s = (3 : ℂ) ^ (-s) := by
  have harg : (3 : ℂ).arg ≠ π := by
    rw [show (3 : ℂ) = ((3 : ℝ) : ℂ) by push_cast; rfl,
      Complex.arg_ofReal_of_nonneg (by norm_num)]
    exact Real.pi_ne_zero.symm
  rw [Complex.cpow_neg, ← Complex.inv_cpow _ _ harg]
  push_cast
  rw [one_div]

/-- [proved-derived; formal-checked] **The Cantor string is self-similar**: at each depth its
holes carry the same zeta face as the self-similar string with ratios `(⅓, ⅓)` and gap `⅓`. -/
theorem cantor_depth_sum (n : ℕ) (s : ℂ) :
    ((words n).map fun w => ((cantorGap w : ℝ) : ℂ) ^ s).sum =
      ∑ w : Fin n → Fin 2,
        (selfSimilarLength (fun _ => (1 / 3 : ℝ)) (1 / 3 : ℝ) w : ℂ) ^ s := by
  rw [selfSimilar_depth_sum _ _ (fun _ => by norm_num) (by norm_num)]
  have hterm : ∀ w ∈ words n,
      ((cantorGap w : ℝ) : ℂ) ^ s = (((1 / 3 : ℝ) : ℂ) ^ s) ^ (n + 1) := by
    intro w hw
    have hlen : (cantorGap w : ℝ) = (1 / 3 : ℝ) ^ (n + 1) := by
      rw [cantor_gap_length, mem_words.1 hw]
      push_cast
      ring
    rw [hlen, ofReal_pow_cpow (by norm_num)]
  rw [List.map_congr_left hterm, List.map_const', List.sum_replicate, length_words, nsmul_eq_mul,
    Fin.sum_const, nsmul_eq_mul]
  push_cast
  ring

/-- [proved-derived; formal-checked] **The convergence half-plane of the Cantor zeta.**
`‖2·3^(−s)‖ < 1 ⇔ Re s > log 2/log 3`. -/
theorem norm_two_mul_three_cpow_neg_lt_one_iff {s : ℂ} :
    ‖2 * (3 : ℂ) ^ (-s)‖ < 1 ↔ Real.log 2 / Real.log 3 < s.re := by
  have h3 : ‖(3 : ℂ) ^ (-s)‖ = (3 : ℝ) ^ (-s.re) := by
    have := Complex.norm_natCast_cpow_of_pos (n := 3) (by norm_num) (-s)
    simpa using this
  have hl3 : 0 < Real.log 3 := Real.log_pos (by norm_num)
  rw [norm_mul, h3, Complex.norm_two, Real.rpow_def_of_pos (by norm_num), div_lt_iff₀ hl3]
  constructor
  · intro h
    have hlt : Real.exp (Real.log 3 * -s.re) < Real.exp (-Real.log 2) := by
      rw [Real.exp_neg, Real.exp_log (by norm_num)]
      linarith
    have := Real.exp_lt_exp.1 hlt
    linarith
  · intro h
    have hlt : Real.log 3 * -s.re < -Real.log 2 := by linarith
    have := Real.exp_lt_exp.2 hlt
    rw [Real.exp_neg, Real.exp_log (by norm_num)] at this
    linarith

/-- [proved-derived; formal-checked] **The Cantor string's geometric zeta.**  For
`Re s > log 2/log 3`, `ζ_CS(s) = Σ_n Σ_(|w|=n) (gap w)^s = 3^(−s) / (1 − 2·3^(−s))`: the holes of
`FractalPacking` summed level by level up the tower. -/
theorem cantorStringZeta_eq {s : ℂ} (hs : Real.log 2 / Real.log 3 < s.re) :
    ∑' n : ℕ, ((words n).map fun w => ((cantorGap w : ℝ) : ℂ) ^ s).sum =
      (3 : ℂ) ^ (-s) / (1 - 2 * (3 : ℂ) ^ (-s)) := by
  have hsum : ∑ _i : Fin 2, ((1 / 3 : ℝ) : ℂ) ^ s = 2 * (3 : ℂ) ^ (-s) := by
    rw [Fin.sum_const, third_cpow, nsmul_eq_mul]
    push_cast
    ring
  have hnorm : ‖∑ _i : Fin 2, ((1 / 3 : ℝ) : ℂ) ^ s‖ < 1 := by
    rw [hsum]
    exact norm_two_mul_three_cpow_neg_lt_one_iff.2 hs
  simp_rw [cantor_depth_sum]
  rw [selfSimilarZeta_eq (fun _ => (1 / 3 : ℝ)) (1 / 3 : ℝ) (fun _ => by norm_num) (by norm_num)
    hnorm, hsum, third_cpow]

/-- [proved-derived; formal-checked] **The Moran dimension** `D = log 2/log 3` solves
`2·3^(−D) = 1`: two restrictions, each a dilation by `⅓`, exactly refill the unit. -/
theorem cantor_moran_dimension : 2 * (3 : ℝ) ^ (-(Real.log 2 / Real.log 3)) = 1 := by
  have hl3 : Real.log 3 ≠ 0 := (Real.log_pos (by norm_num)).ne'
  rw [Real.rpow_def_of_pos (by norm_num),
    show Real.log 3 * -(Real.log 2 / Real.log 3) = -Real.log 2 by field_simp,
    Real.exp_neg, Real.exp_log (by norm_num)]
  norm_num

/-- [proved-derived; formal-checked] `½ < log 2/log 3 < 1`: the Cantor dimension is strictly
between a half and one, so in particular it is not `½`. -/
theorem cantor_dimension_mem : 1 / 2 < Real.log 2 / Real.log 3 ∧ Real.log 2 / Real.log 3 < 1 := by
  have hl3 : 0 < Real.log 3 := Real.log_pos (by norm_num)
  have h23 : Real.log 2 < Real.log 3 := Real.log_lt_log (by norm_num) (by norm_num)
  have h34 : Real.log 3 < 2 * Real.log 2 := by
    rw [← Real.log_rpow (by norm_num)]
    exact Real.log_lt_log (by norm_num) (by norm_num)
  constructor
  · rw [lt_div_iff₀ hl3]
    linarith
  · rw [div_lt_one hl3]
    exact h23

/-- [proved-derived; formal-checked] **The complex dimensions of the Cantor string.**
`1 − 2·3^(−s) = 0 ⇔ s = log 2/log 3 + 2πik/log 3` for some `k ∈ ℤ`.  The real part is the Moran
dimension, a dilation exponent (`cantor_moran_dimension`); the imaginary part is a rotation of
period `2π/log 3` in the log chart, the geometry's oscillation.  All of them lie on one vertical
line, and it is not `Re s = ½` (`cantor_dimension_mem`). -/
theorem cantor_complex_dimensions (s : ℂ) :
    1 - 2 * (3 : ℂ) ^ (-s) = 0 ↔
      ∃ k : ℤ, s = Real.log 2 / Real.log 3 + 2 * π * Complex.I * k / Real.log 3 := by
  have hL : (Real.log 3 : ℂ) ≠ 0 := Complex.ofReal_ne_zero.2 (Real.log_pos (by norm_num)).ne'
  have hlog3 : Complex.log 3 = (Real.log 3 : ℂ) := by
    rw [Complex.ofReal_log (by norm_num)]
    push_cast
    rfl
  have hlog2 : Complex.exp (Real.log 2) = 2 := by
    rw [← Complex.ofReal_exp, Real.exp_log (by norm_num)]
    push_cast
    rfl
  have h3 : (3 : ℂ) ^ (-s) = Complex.exp (-(Real.log 3 * s)) := by
    rw [Complex.cpow_def_of_ne_zero (by norm_num), hlog3]
    ring_nf
  have key : 1 - 2 * (3 : ℂ) ^ (-s) = 0 ↔ Complex.exp (Real.log 2 - Real.log 3 * s) = 1 := by
    rw [h3, sub_eq_zero, sub_eq_add_neg, Complex.exp_add, hlog2, eq_comm]
  rw [key, Complex.exp_eq_one_iff]
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨-n, ?_⟩
    field_simp
    push_cast
    linear_combination -hn
  · rintro ⟨k, hk⟩
    refine ⟨-k, ?_⟩
    rw [hk]
    field_simp
    push_cast
    ring

end Cantor

section Audit

#print axioms floor_eq_card_windings
#print axioms spectralCount_eq_card_pairs
#print axioms spectralCount_eq_sum_geometricCount
#print axioms sum_moebius_smul_sum_mul
#print axioms geometricCount_eq_sum_moebius_spectralCount
#print axioms spectralZeta_eq_riemannZeta_mul_geometricZeta
#print axioms selfSimilar_depth_sum
#print axioms selfSimilarZeta_eq
#print axioms goldenStringZeta_eq
#print axioms cantor_gap_length
#print axioms cantor_depth_gaps
#print axioms cantor_depth_sum
#print axioms norm_two_mul_three_cpow_neg_lt_one_iff
#print axioms cantorStringZeta_eq
#print axioms cantor_moran_dimension
#print axioms cantor_dimension_mem
#print axioms cantor_complex_dimensions

end Audit

end Holonics.Foundation.FractalString
