//! Tests for D3 — *partition generates layout*: the generated tables, the adjoint identity, the
//! assembly identity against a directly assembled matrix, the two scatter receipts and their
//! refusals, the colouring and its properness, and the hostile-declaration refusals. All run on the
//! host. `holonics-cuda` cannot depend on `holonic-engine`, so case (c) builds an equivalent
//! irregular incidence here rather than importing a contact complex.

use super::*;
use holonics::ratio::ring::CheckedIntegers;
use crate::launch_law::{LaunchClause, LaunchLimits, ScatterLaw};
use crate::Dim3;

// ---------------------------------------------------------------------------------------------
// Fixtures — every one deterministic and exact; no float and no random source anywhere.
// ---------------------------------------------------------------------------------------------

/// **Case (a): a 1D chain of overlapping tiles.**  Region `r` covers `width` consecutive addresses
/// beginning at `r * (width - overlap)`, so consecutive regions share `overlap` addresses.
fn chain_1d(regions: usize, width: usize, overlap: usize) -> IncidenceDeclaration {
    assert!(regions > 0 && width > overlap, "a chain overlaps by less than its width");
    let stride = width - overlap;
    let global_extent = (regions - 1) * stride + width;
    let mut addresses = Vec::with_capacity(regions * width);
    for region in 0..regions {
        for slot in 0..width {
            addresses.push((region * stride + slot) as u32);
        }
    }
    IncidenceDeclaration::uniform(global_extent, width, addresses).expect("a lawful chain")
}

/// **Case (b): a 2D grid with 4-neighbour overlap.**  One region per interior cell, incident to the
/// cell and its four neighbours; adjacent regions therefore share addresses.
fn grid_2d(rows: usize, columns: usize) -> IncidenceDeclaration {
    assert!(rows > 2 && columns > 2, "a 4-neighbour stencil needs an interior");
    let global_extent = rows * columns;
    let mut addresses = Vec::new();
    for row in 1..(rows - 1) {
        for column in 1..(columns - 1) {
            let at = row * columns + column;
            addresses.push(at as u32);
            addresses.push((at - columns) as u32);
            addresses.push((at + columns) as u32);
            addresses.push((at - 1) as u32);
            addresses.push((at + 1) as u32);
        }
    }
    IncidenceDeclaration::uniform(global_extent, 5, addresses).expect("a lawful grid")
}

/// **Case (c): an irregular contact incidence**, structurally equivalent to a contact complex's
/// cell-to-vertex incidence: ragged widths between 2 and 6, addresses not in ascending order inside
/// a region, and an uneven address multiplicity so that some addresses are reached by one region
/// and others by five.  Generated by an exact integer recurrence, so it is reproducible and carries
/// no float.
fn irregular_contact(regions: usize, global_extent: usize) -> IncidenceDeclaration {
    assert!(regions > 0 && global_extent >= 8);
    let mut offsets = Vec::with_capacity(regions + 1);
    let mut addresses: Vec<u32> = Vec::new();
    // An exact linear congruential walk over the address space: deterministic, integral, and with
    // no arithmetic that could leave its wire (every operand is below 2^32 and the modulus is
    // applied before the next step).
    let mut state: u64 = 0x9E37_79B9;
    offsets.push(0usize);
    for region in 0..regions {
        let width = 2 + (region % 5);
        for _ in 0..width {
            state = (state.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407))
                >> 1;
            addresses.push((state % global_extent as u64) as u32);
        }
        offsets.push(addresses.len());
    }
    IncidenceDeclaration::new(global_extent, offsets, addresses).expect("a lawful irregular table")
}

/// A symmetric dense local operator over the device's own ring: `L[j][k] = 1 + j + k + j·k`,
/// canonical in `Z/(2^61 - 1)`.  Symmetric by construction, so
/// `SectionLayout.Incidence.assembled_symm` applies.
fn symmetric_operator(width: usize) -> LocalOperator<u64> {
    let ring = ModularWords::MERSENNE61;
    let mut entries = Vec::with_capacity(width * width);
    for row in 0..width {
        for column in 0..width {
            let value = 1 + row as u64 + column as u64 + (row as u64) * (column as u64);
            entries.push(ring.canonical(value));
        }
    }
    LocalOperator::dense(width, entries).expect("a lawful dense operator")
}

/// A deterministic exact global field.
fn field(extent: usize) -> Vec<u64> {
    let ring = ModularWords::MERSENNE61;
    (0..extent)
        .map(|at| ring.canonical(3 + 7 * at as u64 + (at as u64) * (at as u64)))
        .collect()
}

fn accumulated() -> ScatterRequest {
    ScatterRequest::Accumulated(AccumulationLaw::ModularAdd {
        modulus: section_cuda::MODULUS,
    })
}

// ---------------------------------------------------------------------------------------------
// The declaration and what it generates
// ---------------------------------------------------------------------------------------------

#[test]
fn a_uniform_declaration_generates_its_tile_extents_and_a_uniform_gather_partition() {
    let layout = SectionLayout::generate(chain_1d(6, 4, 2), accumulated()).expect("generated");
    let tile = layout.tile();
    assert_eq!(tile.regions(), 6);
    assert_eq!(tile.slots(), 24);
    assert_eq!(tile.max_width(), 4);
    assert_eq!(tile.uniform_width(), Some(4));
    // Generated, not authored: four exact 64-bit words.
    assert_eq!(tile.tile_bytes(), 32);

    let partition = layout.gather_partition().expect("a generated partition");
    assert_eq!(partition.regions(), 6);
    assert_eq!(partition.elements(), 24);
    assert_eq!(partition.region(0), Some(0..4));
    assert_eq!(partition.region(5), Some(20..24));
    partition
        .verify_pairwise_disjoint()
        .expect("the generated gather partition is disjoint");
}

#[test]
fn a_ragged_declaration_generates_an_offsets_gather_partition() {
    let layout = SectionLayout::generate(irregular_contact(9, 32), accumulated()).expect("generated");
    assert_eq!(layout.tile().uniform_width(), None);
    let partition = layout.gather_partition().expect("a generated partition");
    assert_eq!(partition.regions(), layout.regions());
    assert_eq!(partition.elements(), layout.slots());
    partition
        .verify_pairwise_disjoint()
        .expect("the generated gather partition is disjoint");
    // Every region's partition region is exactly its declared slot span.
    for region in 0..layout.regions() {
        let span = partition.region(region).expect("a region");
        assert_eq!(span.start, layout.incidence().offsets()[region]);
        assert_eq!(span.end, layout.incidence().offsets()[region + 1]);
    }
}

#[test]
fn the_generated_transpose_is_the_transpose_of_the_generated_gather() {
    let layout = SectionLayout::generate(grid_2d(5, 5), accumulated()).expect("generated");
    let transpose = layout.transpose();
    // Every (address, slot) of the gather table appears exactly once in the transpose.
    let mut seen = 0usize;
    for at in 0..transpose.touched().len() {
        let address = transpose.touched()[at];
        for slot in transpose.fibre(at).expect("a fibre") {
            assert_eq!(layout.gather_index()[*slot as usize], address);
            seen += 1;
        }
    }
    assert_eq!(seen, layout.slots());
    assert!(transpose.max_multiplicity() > 1, "the grid overlaps");
}

// ---------------------------------------------------------------------------------------------
// Hostile declarations — every one a typed refusal naming exactly one clause
// ---------------------------------------------------------------------------------------------

#[test]
fn a_zero_global_extent_is_refused() {
    let refusal = IncidenceDeclaration::new(0, vec![0, 1], vec![0]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::PositiveGlobalExtent);
}

#[test]
fn a_global_extent_past_the_index_wire_is_refused_rather_than_truncated() {
    let refusal = IncidenceDeclaration::new(u32::MAX as usize + 1, vec![0, 1], vec![0])
        .expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::GlobalExtentWire);
}

#[test]
fn an_address_past_the_declared_extent_is_refused() {
    let refusal = IncidenceDeclaration::new(4, vec![0, 2], vec![1, 9]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::AddressWithinExtent);
}

#[test]
fn a_descending_offsets_table_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![0, 3, 2], vec![0, 1, 2]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::RegionWidth);
}

#[test]
fn an_empty_region_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![0, 2, 2], vec![0, 1]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::RegionWidth);
}

#[test]
fn an_offsets_table_not_starting_at_zero_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![1, 3], vec![0, 1, 2]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::OffsetsLength);
}

#[test]
fn an_offsets_table_that_does_not_end_at_the_address_table_is_refused() {
    let refusal = IncidenceDeclaration::new(8, vec![0, 2], vec![0, 1, 2]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::OffsetsEnd);
}

#[test]
fn a_uniform_width_that_does_not_divide_the_address_table_is_refused() {
    let refusal = IncidenceDeclaration::uniform(8, 3, vec![0, 1, 2, 3]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::OffsetsEnd);
}

#[test]
fn a_local_operator_whose_table_is_not_its_declared_square_is_refused() {
    let refusal = LocalOperator::dense(3, vec![1u64; 8]).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::LocalOperatorWidth);
}

// ---------------------------------------------------------------------------------------------
// The scatter receipt: exactly one of two, never neither
// ---------------------------------------------------------------------------------------------

#[test]
fn a_colliding_incidence_claiming_injectivity_is_refused() {
    let incidence = IncidenceDeclaration::new(8, vec![0, 2, 4], vec![1, 2, 5, 2]).expect("lawful");
    let refusal =
        SectionLayout::generate(incidence, ScatterRequest::Injective).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::ScatterReceipt);
}

#[test]
fn the_same_colliding_incidence_is_admitted_under_a_declared_exact_accumulation() {
    let incidence = IncidenceDeclaration::new(8, vec![0, 2, 4], vec![1, 2, 5, 2]).expect("lawful");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    assert!(matches!(
        layout.receipt(),
        ScatterReceipt::Accumulated(AccumulationLaw::ModularAdd { .. })
    ));
    assert_eq!(layout.receipt().scatter_law(), ScatterLaw::Accumulated);
}

#[test]
fn an_injective_incidence_generates_the_injective_scatter_partition() {
    let incidence = IncidenceDeclaration::uniform(8, 2, vec![0, 1, 4, 5]).expect("lawful");
    let layout = SectionLayout::generate(incidence, ScatterRequest::Injective).expect("generated");
    assert_eq!(layout.receipt(), ScatterReceipt::Injective);
    let partition = layout.scatter_partition().expect("an injective partition");
    assert_eq!(partition.scatter_law(), Some(ScatterLaw::Injective));
    partition
        .verify_pairwise_disjoint()
        .expect("an injective scatter is disjoint");
}

#[test]
fn an_accumulating_receipt_has_no_whole_scatter_partition() {
    let layout = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    let refusal = layout.scatter_partition().expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::ScatterReceipt);
}

#[test]
fn an_injective_receipt_refuses_the_accumulating_launch_requirement_and_the_reverse() {
    let injective = SectionLayout::generate(
        IncidenceDeclaration::uniform(8, 2, vec![0, 1, 4, 5]).expect("lawful"),
        ScatterRequest::Injective,
    )
    .expect("generated");
    assert_eq!(
        injective.scatter_add_requirement(1).expect_err("refused").clause,
        SectionClause::ScatterReceipt
    );
    let accumulating = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    assert_eq!(
        accumulating.scatter_store_requirement().expect_err("refused").clause,
        SectionClause::ScatterReceipt
    );
}

#[test]
fn a_degenerate_modulus_does_not_name_a_ring() {
    let refusal = SectionLayout::generate(
        chain_1d(4, 4, 2),
        ScatterRequest::Accumulated(AccumulationLaw::ModularAdd { modulus: 1 }),
    )
    .expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::AccumulationLaw);
}

// ---------------------------------------------------------------------------------------------
// The exact arithmetic
// ---------------------------------------------------------------------------------------------

#[test]
fn a_checked_integer_sum_past_its_wire_is_refused_rather_than_wrapped() {
    let ring = CheckedIntegers;
    let layout = SectionLayout::generate(
        chain_1d(3, 2, 1),
        ScatterRequest::Accumulated(AccumulationLaw::IntegerAdd),
    )
    .expect("generated");
    let operator = LocalOperator::dense(2, vec![i64::MAX, 1, 1, 1]).expect("lawful");
    let x = vec![i64::MAX; layout.global_extent()];
    let refusal = layout
        .apply_reference(&ring, &operator, &x)
        .expect_err("the exact product leaves the wire");
    assert_eq!(refusal.clause, SectionClause::ExactArithmetic);
}

// ---------------------------------------------------------------------------------------------
// The adjoint and the assembly identity
// ---------------------------------------------------------------------------------------------

#[test]
fn scatter_is_the_transpose_of_gather_on_every_declared_case() {
    let ring = ModularWords::MERSENNE61;
    for layout in [
        SectionLayout::generate(chain_1d(7, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(11, 24), accumulated()).expect("generated"),
    ] {
        let x = field(layout.global_extent());
        let y: Vec<u64> = (0..layout.slots())
            .map(|slot| ring.canonical(5 + 11 * slot as u64))
            .collect();
        let (left, right) = layout.verify_adjoint(&ring, &x, &y).expect("witnessed");
        assert_eq!(
            left, right,
            "<gather x, y> and <x, scatterAdd y> disagree on a {}-region declaration",
            layout.regions()
        );
    }
}

#[test]
fn the_generated_operator_equals_the_directly_assembled_matrix() {
    let ring = ModularWords::MERSENNE61;
    for layout in [
        SectionLayout::generate(chain_1d(7, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(11, 24), accumulated()).expect("generated"),
    ] {
        let operator = symmetric_operator(layout.tile().max_width());
        let x = field(layout.global_extent());
        let generated = layout
            .apply_reference(&ring, &operator, &x)
            .expect("the generated operator applies");
        let matrix = layout
            .assemble_dense(&ring, &operator, 1 << 20)
            .expect("the direct assembly fits the declared ceiling");
        let assembled = layout
            .apply_assembled(&ring, &matrix, &x)
            .expect("the assembled matrix applies");
        assert_eq!(
            generated, assembled,
            "scatterAdd . applyLocal . gather is not the assembled operator on a {}-region \
             declaration",
            layout.regions()
        );
    }
}

#[test]
fn a_symmetric_local_operator_assembles_to_a_symmetric_global_matrix() {
    let ring = ModularWords::MERSENNE61;
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let operator = symmetric_operator(layout.tile().max_width());
    assert!(operator.is_symmetric());
    let extent = layout.global_extent();
    let matrix = layout
        .assemble_dense(&ring, &operator, 1 << 20)
        .expect("assembled");
    for row in 0..extent {
        for column in 0..extent {
            assert_eq!(
                matrix[row * extent + column],
                matrix[column * extent + row],
                "the assembled matrix is asymmetric at ({row}, {column})"
            );
        }
    }
}

#[test]
fn a_dense_assembly_past_the_declared_entry_ceiling_is_refused_before_it_allocates() {
    let ring = ModularWords::MERSENNE61;
    let layout = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    let operator = symmetric_operator(layout.tile().max_width());
    let refusal = layout
        .assemble_dense(&ring, &operator, 4)
        .expect_err("the ceiling refuses it");
    assert_eq!(refusal.clause, SectionClause::WorkCeiling);
}

#[test]
fn an_injective_scatter_reference_agrees_with_the_accumulating_one() {
    // `SectionLayout.Incidence.scatterAdd_of_injective`: through an injective incidence the
    // accumulation degenerates to a store, so the two device arms compute the same field.
    let ring = ModularWords::MERSENNE61;
    let addresses: Vec<u32> = (0..12u32).collect();
    let injective = SectionLayout::generate(
        IncidenceDeclaration::uniform(12, 3, addresses.clone()).expect("lawful"),
        ScatterRequest::Injective,
    )
    .expect("generated");
    let accumulating = SectionLayout::generate(
        IncidenceDeclaration::uniform(12, 3, addresses).expect("lawful"),
        accumulated(),
    )
    .expect("generated");
    let operator = symmetric_operator(3);
    let x = field(12);
    assert_eq!(
        injective.apply_reference(&ring, &operator, &x).expect("applies"),
        accumulating.apply_reference(&ring, &operator, &x).expect("applies")
    );
}

// ---------------------------------------------------------------------------------------------
// The colouring
// ---------------------------------------------------------------------------------------------

#[test]
fn the_scatter_reference_refuses_a_field_that_is_not_the_declared_extent() {
    // The public scatter mouth takes the destination field rather than allocating one, so this
    // owner never allocates from the *declared* global extent; the length is checked instead.
    let ring = ModularWords::MERSENNE61;
    let layout = SectionLayout::generate(chain_1d(4, 4, 2), accumulated()).expect("generated");
    let tile = vec![0u64; layout.slots()];
    let mut short = vec![0u64; layout.global_extent() - 1];
    assert_eq!(
        layout
            .scatter_reference(&ring, &tile, &mut short)
            .expect_err("refused")
            .clause,
        SectionClause::SpanExtent
    );
    let narrow_tile = vec![0u64; layout.slots() - 1];
    let mut field = vec![0u64; layout.global_extent()];
    assert_eq!(
        layout
            .scatter_reference(&ring, &narrow_tile, &mut field)
            .expect_err("refused")
            .clause,
        SectionClause::SpanExtent
    );
}

#[test]
fn the_generated_colouring_is_proper_on_every_declared_case() {
    for layout in [
        SectionLayout::generate(chain_1d(9, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(7, 6), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(17, 24), accumulated()).expect("generated"),
    ] {
        let colouring = layout.colouring(1 << 20).expect("a colouring");
        colouring
            .verify_proper(&layout)
            .expect("the greedy colouring is proper");
        assert!(colouring.colour_count() >= 1);
        // Every region carries exactly one colour and every colour class is non-empty.
        let mut counted = 0usize;
        for colour in 0..colouring.colour_count() {
            let class = colouring.class(colour).expect("a class");
            assert!(!class.is_empty());
            counted += class.len();
            for region in class {
                assert_eq!(colouring.colour_of(*region as usize), Some(colour as u32));
            }
        }
        assert_eq!(counted, layout.regions());
    }
}

#[test]
fn table_provenance_refuses_equal_size_different_incidence_and_offsets() {
    let operator = symmetric_operator(2);
    let layout_a = SectionLayout::generate(
        IncidenceDeclaration::uniform(4, 2, vec![0, 1, 2, 3]).expect("layout A incidence"),
        ScatterRequest::Injective,
    )
    .expect("layout A");
    let layout_b = SectionLayout::generate(
        IncidenceDeclaration::uniform(4, 2, vec![1, 0, 3, 2]).expect("layout B incidence"),
        ScatterRequest::Injective,
    )
    .expect("layout B");
    let staged = SectionTableProvenance {
        layout: &layout_a,
        _operator: &operator,
        colouring: None,
    };
    let refusal = staged
        .verify(&layout_b, None)
        .expect_err("equal-sized incidence tables must not be interchangeable");
    assert_eq!(refusal.clause, SectionClause::TableProvenance);

    let ragged_a = SectionLayout::generate(
        IncidenceDeclaration::new(4, vec![0, 1, 4], vec![0, 1, 2, 3]).expect("ragged A"),
        ScatterRequest::Injective,
    )
    .expect("ragged layout A");
    let ragged_b = SectionLayout::generate(
        IncidenceDeclaration::new(4, vec![0, 3, 4], vec![0, 1, 2, 3]).expect("ragged B"),
        ScatterRequest::Injective,
    )
    .expect("ragged layout B");
    let staged = SectionTableProvenance {
        layout: &ragged_a,
        _operator: &operator,
        colouring: None,
    };
    let refusal = staged
        .verify(&ragged_b, None)
        .expect_err("equal-sized offset tables must not be interchangeable");
    assert_eq!(refusal.clause, SectionClause::TableProvenance);
}

#[test]
fn table_provenance_refuses_a_different_proper_colouring() {
    let layout = SectionLayout::generate(chain_1d(3, 2, 1), accumulated()).expect("layout");
    let operator = symmetric_operator(2);
    let staged_colouring = RegionColouring {
        colours: vec![0, 1, 0],
        classes: vec![vec![0, 2], vec![1]],
        conflict_work: 0,
    };
    let presented_colouring = RegionColouring {
        colours: vec![1, 0, 1],
        classes: vec![vec![1], vec![0, 2]],
        conflict_work: 0,
    };
    staged_colouring
        .verify_proper(&layout)
        .expect("staged colouring is proper");
    presented_colouring
        .verify_proper(&layout)
        .expect("presented colouring is also proper");
    let staged = SectionTableProvenance {
        layout: &layout,
        _operator: &operator,
        colouring: Some(&staged_colouring),
    };
    let refusal = staged
        .verify(&layout, Some(&presented_colouring))
        .expect_err("proper colourings with different class assignments must not mix");
    assert_eq!(refusal.clause, SectionClause::TableProvenance);
}

#[test]
fn staging_refuses_an_improper_colouring_before_device_allocation() {
    let layout = SectionLayout::generate(chain_1d(3, 2, 1), accumulated()).expect("layout");
    let operator = symmetric_operator(2);
    let improper = RegionColouring {
        colours: vec![0, 1],
        classes: vec![vec![0], vec![1]],
        conflict_work: 0,
    };
    let refusal = SectionDeviceTables::stage(&layout, &operator, Some(&improper))
        .err().expect("staging must verify the colouring before allocating tables");
    assert_eq!(refusal.context, SectionClause::ColouringProper.name());
}

#[test]
fn colouring_refuses_an_incidence_past_the_declared_work_ceiling_before_it_colours() {
    // Every slot on one address: the conflict work is quadratic in the slot population, and the
    // ceiling refuses it *before* the colouring loop runs.
    let slots = 64usize;
    let incidence =
        IncidenceDeclaration::uniform(4, 1, vec![0u32; slots]).expect("a lawful hostile table");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    let refusal = layout.colouring(16).expect_err("the ceiling refuses it");
    assert_eq!(refusal.clause, SectionClause::WorkCeiling);
    // With a ceiling that admits the work, the same declaration colours and is proper.
    let colouring = layout.colouring(slots * slots).expect("a colouring");
    colouring.verify_proper(&layout).expect("proper");
    assert_eq!(colouring.colour_count(), slots, "every region conflicts with every other");
    assert_eq!(colouring.conflict_work(), slots * slots);
}

#[test]
fn every_colour_partition_is_an_injective_scatter_and_the_classes_cover_the_incidence() {
    let layout = SectionLayout::generate(grid_2d(7, 6), accumulated()).expect("generated");
    let colouring = layout.colouring(1 << 20).expect("a colouring");
    let mut covered = 0usize;
    for colour in 0..colouring.colour_count() {
        let partition = layout
            .colour_partition(&colouring, colour)
            .expect("a generated colour partition");
        assert_eq!(partition.scatter_law(), Some(ScatterLaw::Injective));
        partition
            .verify_pairwise_disjoint()
            .expect("a colour class scatters injectively");
        covered += colouring.class(colour).expect("a class").len();
    }
    assert_eq!(covered, layout.regions());
    assert_eq!(
        layout.colour_partition(&colouring, colouring.colour_count()).expect_err("refused").clause,
        SectionClause::ColourClass
    );
}

#[test]
fn the_colour_by_colour_scatter_equals_the_sequential_scatter() {
    // The executable witness of `SectionLayout.Incidence.colour_schedule`: accumulating one colour
    // class at a time into a running field leaves exactly what the whole scatter leaves.
    let ring = ModularWords::MERSENNE61;
    for layout in [
        SectionLayout::generate(chain_1d(9, 4, 2), accumulated()).expect("generated"),
        SectionLayout::generate(grid_2d(7, 6), accumulated()).expect("generated"),
        SectionLayout::generate(irregular_contact(17, 24), accumulated()).expect("generated"),
    ] {
        let colouring = layout.colouring(1 << 20).expect("a colouring");
        let tile: Vec<u64> = (0..layout.slots())
            .map(|slot| ring.canonical(13 + 17 * slot as u64))
            .collect();
        let mut sequential = vec![0u64; layout.global_extent()];
        layout
            .scatter_reference(&ring, &tile, &mut sequential)
            .expect("the whole scatter");

        let mut running = vec![0u64; layout.global_extent()];
        for colour in 0..colouring.colour_count() {
            for region in colouring.class(colour).expect("a class") {
                let lo = layout.incidence().offsets()[*region as usize];
                let hi = layout.incidence().offsets()[*region as usize + 1];
                for (address, value) in layout.gather_index()[lo..hi].iter().zip(&tile[lo..hi]) {
                    let at = *address as usize;
                    running[at] = ring.add(running[at], *value).expect("exact");
                }
            }
        }
        assert_eq!(running, sequential);
    }
}

// ---------------------------------------------------------------------------------------------
// The generated launch requirements
// ---------------------------------------------------------------------------------------------

/// Synthetic device limits, `cfg(test)` only, so no production path can author a device bound.
fn synthetic_limits(warp: u32, block_cap: u32, shared: u32) -> LaunchLimits {
    LaunchLimits::synthetic(
        block_cap,
        Some(block_cap),
        Some(Dim3 {
            x: 2_147_483_647,
            y: 65_535,
            z: 65_535,
        }),
        Some(Dim3 {
            x: block_cap,
            y: block_cap,
            z: 64,
        }),
        Some(shared),
        Some(warp),
    )
}

#[test]
fn the_apply_requirement_generates_its_block_and_shared_extent_from_the_tile_and_the_card() {
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let limits = synthetic_limits(32, 1024, 49_152);
    let requirement = layout
        .apply_requirement(&limits, layout.tile().max_width())
        .expect("a generated requirement");
    // Tile width 5, rounded up to one 32-lane warp; shared is five exact words.
    assert_eq!(requirement.block.exact, Some(Dim3::x(32)));
    assert!(requirement.block.warp_multiple);
    assert_eq!(requirement.shared.per_block_bytes, 40);
    assert_eq!(requirement.shared.per_thread_bytes, 0);
    assert_eq!(requirement.extent, layout.regions() as u64 * 32);
    assert!(matches!(requirement.coverage, Coverage::Exact));

    // The derived shape is submitted to the same proof any caller-authored shape faces.
    let shape = requirement.cover_with(&limits).expect("a derived shape");
    assert_eq!(shape.grid, Dim3::x(layout.regions() as u32));
    assert_eq!(shape.block, Dim3::x(32));
    assert_eq!(shape.shared_bytes, 40);
}

#[test]
fn a_tile_wider_than_the_block_cap_generates_the_widest_lawful_warp_multiple() {
    let incidence = IncidenceDeclaration::uniform(
        4096,
        300,
        (0..(300u32 * 3)).map(|at| at % 4096).collect(),
    )
    .expect("lawful");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    let limits = synthetic_limits(32, 128, 49_152);
    let requirement = layout
        .apply_requirement(&limits, 300)
        .expect("a generated requirement");
    assert_eq!(requirement.block.exact, Some(Dim3::x(128)));
    assert_eq!(requirement.shared.per_block_bytes, 2400);
}

#[test]
fn the_apply_requirement_refuses_a_local_operator_of_the_wrong_width() {
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let limits = synthetic_limits(32, 1024, 49_152);
    let refusal = layout.apply_requirement(&limits, 4).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::LocalOperatorWidth);
}

#[test]
fn the_apply_requirement_refuses_evidence_that_carries_no_warp() {
    let layout = SectionLayout::generate(grid_2d(6, 5), accumulated()).expect("generated");
    let limits = LaunchLimits::synthetic(1024, Some(1024), None, None, None, None);
    let refusal = layout.apply_requirement(&limits, 5).expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::LaunchDerivation);
}

#[test]
fn a_shared_extent_past_the_card_is_refused_by_the_launch_law_rather_than_clipped() {
    // A 8192-slot tile wants 65_536 shared octets; the card in this fixture has 49_152.
    let width = 8192usize;
    let incidence = IncidenceDeclaration::uniform(
        65_536,
        width,
        (0..(width as u32 * 2)).map(|at| at % 65_536).collect(),
    )
    .expect("lawful");
    let layout = SectionLayout::generate(incidence, accumulated()).expect("generated");
    let limits = synthetic_limits(32, 1024, 49_152);
    let requirement = layout.apply_requirement(&limits, width).expect("a requirement");
    assert_eq!(requirement.shared.per_block_bytes, 65_536);
    let shape = requirement.cover_with(&limits).expect("a derived shape");
    let refusal = crate::launch_law::LawfulLaunch::prove(&requirement, &limits, shape, &[])
        .expect_err("the shared extent exceeds the card");
    assert_eq!(refusal.clause, LaunchClause::SharedWithinDevice);
}

#[test]
fn the_gather_and_scatter_requirements_declare_the_entry_symbols_and_extents_they_generate() {
    let layout = SectionLayout::generate(chain_1d(5, 4, 2), accumulated()).expect("generated");
    let gather = layout.gather_requirement();
    assert_eq!(gather.kernel, section_cuda::GATHER_ENTRY_SYMBOL);
    assert_eq!(gather.extent, layout.slots() as u64);
    assert_eq!(gather.arguments.len(), 3);
    assert_eq!(gather.scalars.len(), 1);
    assert!(matches!(gather.stream, StreamRequirement::Ordered));

    let colouring = layout.colouring(1 << 20).expect("a colouring");
    let class = colouring.class(0).expect("a class");
    let scatter = layout
        .scatter_add_requirement(class.len())
        .expect("a requirement");
    assert_eq!(scatter.kernel, section_cuda::SCATTER_ADD_ENTRY_SYMBOL);
    assert_eq!(scatter.extent, class.len() as u64);
    assert_eq!(scatter.arguments.len(), 5);
    assert_eq!(
        layout.scatter_add_requirement(0).expect_err("refused").clause,
        SectionClause::ColourClass
    );
}

// ---------------------------------------------------------------------------------------------
// The canonicality boundary
// ---------------------------------------------------------------------------------------------

/// A coefficient table lawful in its width and everywhere canonical **except one named index**.
/// Built through the generic [`LocalOperator::dense`], which carries no representation clause — that
/// is the point: the representation clause lives at the device boundary, and this fixture is what
/// the boundary is held against.
fn operator_with_one_non_canonical_entry(width: usize, at: usize, word: u64) -> LocalOperator<u64> {
    let mut entries = symmetric_operator(width).entries().to_vec();
    entries[at] = word;
    LocalOperator::dense(width, entries).expect("the width clause is untouched")
}

#[test]
fn a_non_canonical_coefficient_is_refused_at_every_staging_mouth() {
    let layout = SectionLayout::generate(chain_1d(6, 4, 2), accumulated()).expect("generated");
    let width = layout.tile().max_width();
    let ring = ModularWords::MERSENNE61;

    // A lawful declaration passes every mouth of the boundary.
    let lawful = symmetric_operator(width);
    lawful.verify_canonical(&ring).expect("a canonical operator is admitted");
    LocalOperator::dense_canonical(width, lawful.entries().to_vec(), &ring)
        .expect("a canonical operator is admitted at construction");
    verify_canonical_words(&ring, &field(layout.global_extent()), "global field")
        .expect("a canonical field is admitted");

    // `p` itself is the first non-canonical word and `u64::MAX` the widest; the refusal is raised
    // through all three mouths, and `stage` raises it before any driver call.
    for (at, word) in [
        (0usize, section_cuda::MODULUS),
        (9, section_cuda::MODULUS + 1),
        (width * width - 1, u64::MAX),
    ] {
        let operator = operator_with_one_non_canonical_entry(width, at, word);
        let refusal = operator.verify_canonical(&ring).expect_err("refused");
        assert_eq!(refusal.clause, SectionClause::CanonicalWord);
        let constructed = LocalOperator::dense_canonical(width, operator.entries().to_vec(), &ring)
            .expect_err("refused at construction");
        assert_eq!(constructed.clause, SectionClause::CanonicalWord);
        let error = match SectionDeviceTables::stage(&layout, &operator, None) {
            Ok(_) => panic!("the staging boundary admitted a non-canonical coefficient"),
            Err(error) => error,
        };
        assert_eq!(error.context, SectionClause::CanonicalWord.name());
    }

    // The same clause holds the global-field mouth, the other host table that crosses.
    let mut x = field(layout.global_extent());
    x[2] = section_cuda::MODULUS;
    let refusal = verify_canonical_words(&ring, &x, "global field").expect_err("refused");
    assert_eq!(refusal.clause, SectionClause::CanonicalWord);
}
