import ElementaryHolonics.Computation.HolonicFermiHubbard
import ElementaryHolonics.Computation.HolonicDiffusionCharts
import ElementaryHolonics.Millennium.HolonicPortResolvedBoundaryTransport
import Physlib.QuantumMechanics.FiniteTarget

/-!
# Real time, imaginary time, stochastic sampling, physical diffusion, and open return are distinct

**[proved-derived]** Physlib's finite self-adjoint Hamiltonian supplies a unitary real-time group.
The imaginary-time exponential is a separate nonunitary semigroup.  The standing Holonics Markov
kernel preserves probability mass, while the standing port-resolved physical passage telescopes
stored quantity, incoming current, and addressed boundary return.  Open-system transport has its own
typed channel carrier.

The types deliberately provide no coercion among these passages.  Wick rotation, stochastic
representation, hydrodynamic limits, and analytic continuation remain separate bridge obligations.
-/

noncomputable section

namespace Soma.Holonics.Computation.HolonicEvolutionKinds

open scoped BigOperators
open Soma.Holonics.Computation.HolonicDiffusionCharts
open Soma.Holonics.Computation.HolonicFermionicOccupation
open Soma.Holonics.Millennium.HolonicPortResolvedBoundaryTransport
open QuantumMechanics

/-! ## Real-time finite Hamiltonian evolution -/

variable {Hilbert : Type*} [NormedAddCommGroup Hilbert] [InnerProductSpace ℂ Hilbert]
  [CompleteSpace Hilbert] [FiniteDimensional ℂ Hilbert]

/-- Finite self-adjoint Hamiltonian evolution preserves the Hilbert norm exactly. -/
theorem realTime_norm_conserved {dimension : ℕ}
    (target : FiniteTarget Hilbert dimension) (time : ℝ) (state : Hilbert) :
    ‖target.timeEvolution time state‖ = ‖state‖ := by
  change ‖target.unitaryTimeEvolution time state‖ = ‖state‖
  exact ContinuousLinearMap.norm_map_of_mem_unitary
    (target.unitaryTimeEvolution.mem_unitary time) state

/-- Real-time transport composes by addition of physical time. -/
theorem realTime_add {dimension : ℕ}
    (target : FiniteTarget Hilbert dimension) (first second : ℝ) :
    target.timeEvolution (first + second) =
      target.timeEvolution first * target.timeEvolution second := by
  change target.unitaryTimeEvolution (first + second) =
    target.unitaryTimeEvolution first * target.unitaryTimeEvolution second
  exact target.unitaryTimeEvolution.toAddChar.map_add_eq_mul first second

/-! ## Imaginary-time semigroup -/

/-- [definition] Euclidean/imaginary-time evolution generated by one bounded Hamiltonian.  It is
not assigned a unitary witness. -/
def imaginaryTime (hamiltonian : Hilbert →L[ℂ] Hilbert) (beta : ℝ) :
    Hilbert →L[ℂ] Hilbert :=
  NormedSpace.exp ((-(beta : ℂ)) • hamiltonian)

/-- Imaginary-time evolution composes as a semigroup. -/
theorem imaginaryTime_add (hamiltonian : Hilbert →L[ℂ] Hilbert) (first second : ℝ) :
    imaginaryTime hamiltonian (first + second) =
      imaginaryTime hamiltonian first * imaginaryTime hamiltonian second := by
  letI : NormedAlgebra ℚ (Hilbert →L[ℂ] Hilbert) :=
    .restrictScalars ℚ ℂ (Hilbert →L[ℂ] Hilbert)
  have commute : Commute ((-(first : ℂ)) • hamiltonian) ((-(second : ℂ)) • hamiltonian) :=
    ((Commute.refl hamiltonian).smul_left _).smul_right _
  rw [imaginaryTime, imaginaryTime, imaginaryTime,
    ← NormedSpace.exp_add_of_commute commute]
  congr 1
  rw [← add_smul]
  congr 1
  push_cast
  ring

@[simp] theorem imaginaryTime_zero (hamiltonian : Hilbert →L[ℂ] Hilbert) :
    imaginaryTime hamiltonian 0 = 1 := by
  simp [imaginaryTime]

/-! ## Signed histories -/

/-- [definition] A finite worldline retains every occupation slice and the permutation parity which
produces its fermionic sign. -/
structure FermionicWorldlineHistory (Mode : Type*) [DecidableEq Mode] where
  slices : List (Occupation Mode)
  oddPermutation : Bool
  amplitude : ℂ

namespace FermionicWorldlineHistory

def signedAmplitude {Mode : Type*} [DecidableEq Mode]
    (history : FermionicWorldlineHistory Mode) : ℂ :=
  if history.oddPermutation then -history.amplitude else history.amplitude

@[simp] theorem signedAmplitude_odd {Mode : Type*} [DecidableEq Mode]
    (slices : List (Occupation Mode)) (amplitude : ℂ) :
    signedAmplitude ⟨slices, true, amplitude⟩ = -amplitude := rfl

@[simp] theorem signedAmplitude_even {Mode : Type*} [DecidableEq Mode]
    (slices : List (Occupation Mode)) (amplitude : ℂ) :
    signedAmplitude ⟨slices, false, amplitude⟩ = amplitude := rfl

end FermionicWorldlineHistory

/-- [definition] A finite diagram history retains order, topology incidences, external legs, and its
signed/complex weight; no drawing or scalar sum replaces that occurrence. -/
structure FermionicDiagramHistory (Vertex Edge External : Type*) where
  order : ℕ
  source : Edge → Vertex
  target : Edge → Vertex
  externalVertex : External → Vertex
  oddPermutation : Bool
  symmetryFactor : ℚ
  amplitude : ℂ

/-! ## Stochastic, physical, and open-system passages -/

/-- A stochastic configuration-space step preserves total probability mass. -/
theorem markov_mass_preserved
    {Source Target : Type*} [Fintype Source] [Fintype Target]
    (kernel : MarkovKernel Source Target) (probability : FiniteProbabilitySection Source) :
    ∑ target, (kernel.pushforward probability).mass target = 1 :=
  (kernel.pushforward probability).normalized

/-- The physical boundary passage returns its independent stored/current/boundary balance. -/
theorem physical_boundary_balance
    {Port Quantity : Type*} [Fintype Port] [AddCommGroup Quantity]
    (history : PortResolvedBoundaryHistory Port Quantity) (steps : ℕ) :
    history.storage steps - history.storage 0 +
        ∑ time ∈ Finset.range steps, ∑ port, history.returned port time =
      ∑ time ∈ Finset.range steps, history.incoming time :=
  history.telescopes steps

/-- [definition] Open-system evolution is a separately typed channel family with chronology.  Its
normalization, positivity, complete positivity, or Lindblad generator must be supplied by the
particular later realization. -/
structure OpenSystemPassage (State : Type*) where
  evolve : ℝ → State → State
  zero : evolve 0 = id
  add : ∀ first second, evolve (first + second) = evolve second ∘ evolve first

/-- [definition] The five evolution species remain a tagged exterior comparison face only.  The
tags do not provide conversions among their payloads. -/
inductive EvolutionSpecies where
  | realTimeUnitary
  | imaginaryTimeSemigroup
  | stochasticConfiguration
  | physicalConstitutiveDiffusion
  | openSystem
  deriving DecidableEq

section Audit

#print axioms realTime_norm_conserved
#print axioms realTime_add
#print axioms imaginaryTime_add
#print axioms imaginaryTime_zero
#print axioms FermionicWorldlineHistory.signedAmplitude_odd
#print axioms markov_mass_preserved
#print axioms physical_boundary_balance

end Audit

end Soma.Holonics.Computation.HolonicEvolutionKinds
