import ElementaryHolonics.Foundation.Receiver
import Mathlib.LinearAlgebra.Prod
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Tactic

/-!
# A finite paired-current constitutive fibre

The paired samples retain their complete vertical relation in a submodule of `V × W`.  A declared
local linear constitutive map may then be checked on the presented generators and extended over that
span.  This is a local chart over the admitted sample fibre, not a global linearity claim about text,
an HNA, or any other exterior population.
-/

namespace Soma.Holonics.Computation.HolonicConstitutiveFibre

open Soma.Holonics

universe uI uV uW

variable {I : Type uI} {V : Type uV} {W : Type uW}
variable [AddCommGroup V] [AddCommGroup W]
variable [Module ℚ V] [Module ℚ W]
variable {V' : Type*} {W' : Type*}
variable [AddCommGroup V'] [AddCommGroup W']
variable [Module ℚ V'] [Module ℚ W']

/-- The complete paired-current relation generated by the actually presented samples. -/
def pairedCurrentSubmodule (x : I → V) (y : I → W) : Submodule ℚ (V × W) :=
  Submodule.span ℚ (Set.range fun i ↦ (x i, y i))

/-- The admitted source domain generated by the actually presented source currents. -/
def sourceSpan (x : I → V) : Submodule ℚ V :=
  Submodule.span ℚ (Set.range x)

/-- Every presented source is a generator of its admitted source span. -/
theorem mem_sourceSpan (x : I → V) (i : I) : x i ∈ sourceSpan x := by
  exact Submodule.subset_span ⟨i, rfl⟩

/-- A declared local linear constitutive map is exact on every paired-current span element. -/
theorem paired_span_return
    (x : I → V) (y : I → W) (M : V →ₗ[ℚ] W)
    (sample_exact : ∀ i, y i = M (x i))
    {v : V} {w : W}
    (paired : (v, w) ∈ pairedCurrentSubmodule x y) :
    w = M v := by
  change (v, w) ∈ Submodule.span ℚ (Set.range fun i ↦ (x i, y i)) at paired
  refine Submodule.span_induction
    (p := fun pair _ ↦ pair.2 = M pair.1) ?_ ?_ ?_ ?_ paired
  · rintro pair ⟨i, rfl⟩
    exact sample_exact i
  · simp
  · intro left right hleft hright left_exact right_exact
    change left.2 + right.2 = M (left.1 + right.1)
    rw [left_exact, right_exact, M.map_add]
  · intro scalar pair hpair pair_exact
    change scalar • pair.2 = M (scalar • pair.1)
    rw [pair_exact, M.map_smul]

/-- The source projection of every paired-span element lies in the admitted source span. -/
theorem paired_span_source_mem_sourceSpan
    (x : I → V) (y : I → W)
    {v : V} {w : W}
    (paired : (v, w) ∈ pairedCurrentSubmodule x y) :
    v ∈ sourceSpan x := by
  change (v, w) ∈ Submodule.span ℚ (Set.range fun i ↦ (x i, y i)) at paired
  refine Submodule.span_induction
    (p := fun pair _ ↦ pair.1 ∈ sourceSpan x) ?_ ?_ ?_ ?_ paired
  · rintro pair ⟨i, rfl⟩
    exact mem_sourceSpan x i
  · exact (sourceSpan x).zero_mem
  · intro left right hleft hright left_mem right_mem
    change left.1 + right.1 ∈ sourceSpan x
    exact (sourceSpan x).add_mem left_mem right_mem
  · intro scalar pair hpair pair_mem
    change scalar • pair.1 ∈ sourceSpan x
    exact (sourceSpan x).smul_mem scalar pair_mem

/-- Every admitted source-span point has at least one paired return in the complete relation. -/
theorem sourceSpan_exists_paired
    (x : I → V) (y : I → W)
    {v : V} (source_mem : v ∈ sourceSpan x) :
    ∃ w, (v, w) ∈ pairedCurrentSubmodule x y := by
  change v ∈ Submodule.span ℚ (Set.range x) at source_mem
  refine Submodule.span_induction
    (p := fun source _ ↦ ∃ w, (source, w) ∈ pairedCurrentSubmodule x y) ?_ ?_ ?_ ?_ source_mem
  · rintro source ⟨i, rfl⟩
    exact ⟨y i, Submodule.subset_span ⟨i, rfl⟩⟩
  · exact ⟨0, (pairedCurrentSubmodule x y).zero_mem⟩
  · intro left right hleft hright left_paired right_paired
    rcases left_paired with ⟨left_return, left_mem⟩
    rcases right_paired with ⟨right_return, right_mem⟩
    refine ⟨left_return + right_return, ?_⟩
    simpa using (pairedCurrentSubmodule x y).add_mem left_mem right_mem
  · intro scalar source hsource source_paired
    rcases source_paired with ⟨source_return, source_mem⟩
    refine ⟨scalar • source_return, ?_⟩
    simpa using (pairedCurrentSubmodule x y).smul_mem scalar source_mem

/-- The source projection of the paired relation is exactly the span of presented sources. -/
theorem sourceSpan_iff_paired_source
    (x : I → V) (y : I → W) {v : V} :
    v ∈ sourceSpan x ↔ ∃ w, (v, w) ∈ pairedCurrentSubmodule x y := by
  constructor
  · exact sourceSpan_exists_paired x y
  · rintro ⟨w, paired⟩
    exact paired_span_source_mem_sourceSpan x y paired

/-- In any paired-current submodule, one vertical fibre is translated by its zero-source part. -/
theorem vertical_fibre_iff_zero_source_difference
    (R : Submodule ℚ (V × W)) {v : V} {w₀ w : W}
    (base : (v, w₀) ∈ R) :
    (v, w) ∈ R ↔ (0, w - w₀) ∈ R := by
  constructor
  · intro target
    have difference := R.sub_mem target base
    simpa using difference
  · intro vertical
    have restored := R.add_mem vertical base
    simpa using restored

/-- The source and return charts after adjoining one newly admitted paired current. -/
def sumUnitSource (x : I → V) (newSource : V) : Sum I Unit → V
  | Sum.inl i => x i
  | Sum.inr _ => newSource

def sumUnitReturn (y : I → W) (newTarget : W) : Sum I Unit → W
  | Sum.inl i => y i
  | Sum.inr _ => newTarget

/-- The exact relation join for one new paired current. -/
def addPairedCurrentSubmodule
    (x : I → V) (y : I → W) (newSource : V) (newTarget : W) : Submodule ℚ (V × W) :=
  pairedCurrentSubmodule x y ⊔ Submodule.span ℚ {(newSource, newTarget)}

theorem pairedCurrentSubmodule_sumUnit_eq_add
    (x : I → V) (y : I → W) (newSource : V) (newTarget : W) :
    pairedCurrentSubmodule (sumUnitSource x newSource) (sumUnitReturn y newTarget) =
      addPairedCurrentSubmodule x y newSource newTarget := by
  change Submodule.span ℚ
      (Set.range fun i ↦ (sumUnitSource x newSource i, sumUnitReturn y newTarget i)) =
    Submodule.span ℚ (Set.range fun i ↦ (x i, y i)) ⊔
      Submodule.span ℚ {(newSource, newTarget)}
  rw [← Submodule.span_union]
  congr 1
  ext pair
  constructor
  · rintro ⟨index, rfl⟩
    cases index with
    | inl index => exact Or.inl ⟨index, rfl⟩
    | inr index => exact Or.inr (by simp [sumUnitSource, sumUnitReturn])
  · intro membership
    rcases membership with old | new
    · rcases old with ⟨index, rfl⟩
      exact ⟨Sum.inl index, rfl⟩
    · rw [Set.mem_singleton_iff] at new
      rcases new with rfl
      exact ⟨Sum.inr (), rfl⟩

/-- The explicit rechart equivalence on a paired source/return carrier. -/
def pairRechartEquiv
    (sourceEquiv : V ≃ₗ[ℚ] V') (returnEquiv : W ≃ₗ[ℚ] W') :
    (V × W) ≃ₗ[ℚ] (V' × W') where
  toFun pair := (sourceEquiv pair.1, returnEquiv pair.2)
  invFun pair := (sourceEquiv.symm pair.1, returnEquiv.symm pair.2)
  left_inv pair := by simp
  right_inv pair := by simp
  map_add' left right := by ext <;> simp
  map_smul' scalar pair := by ext <;> simp

/-- Rechart an admitted paired relation by an explicit source/return equivalence. -/
def rechartedPairedSubmodule
    (sourceEquiv : V ≃ₗ[ℚ] V') (returnEquiv : W ≃ₗ[ℚ] W')
    (R : Submodule ℚ (V × W)) : Submodule ℚ (V' × W') :=
  Submodule.map (pairRechartEquiv sourceEquiv returnEquiv).toLinearMap R

/-- Forming the paired relation commutes with explicitly recharting its actual generators. -/
theorem pairedCurrentSubmodule_rechart
    (sourceEquiv : V ≃ₗ[ℚ] V') (returnEquiv : W ≃ₗ[ℚ] W')
    (x : I → V) (y : I → W) :
    pairedCurrentSubmodule (fun i ↦ sourceEquiv (x i)) (fun i ↦ returnEquiv (y i)) =
      rechartedPairedSubmodule sourceEquiv returnEquiv (pairedCurrentSubmodule x y) := by
  unfold rechartedPairedSubmodule pairedCurrentSubmodule
  rw [Submodule.map_span]
  congr 1
  ext pair
  constructor
  · rintro ⟨i, rfl⟩
    exact ⟨(x i, y i), ⟨i, rfl⟩, rfl⟩
  · rintro ⟨original, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩

/-- Recharted membership is exactly inverse-transformed membership in the original relation. -/
theorem mem_rechartedPairedSubmodule_iff
    (sourceEquiv : V ≃ₗ[ℚ] V') (returnEquiv : W ≃ₗ[ℚ] W')
    (R : Submodule ℚ (V × W)) (pair : V' × W') :
    pair ∈ rechartedPairedSubmodule sourceEquiv returnEquiv R ↔
      (pairRechartEquiv sourceEquiv returnEquiv).symm pair ∈ R := by
  constructor
  · intro membership
    rcases (Submodule.mem_map.mp membership) with ⟨original, original_mem, mapped⟩
    have inverse_mapped : original =
        (pairRechartEquiv sourceEquiv returnEquiv).symm pair := by
      simpa using congrArg (pairRechartEquiv sourceEquiv returnEquiv).symm mapped
    rw [← inverse_mapped]
    exact original_mem
  · intro membership
    apply Submodule.mem_map.mpr
    refine ⟨(pairRechartEquiv sourceEquiv returnEquiv).symm pair, membership, ?_⟩
    exact (pairRechartEquiv sourceEquiv returnEquiv).apply_symm_apply pair

theorem mem_rechartedPairedSubmodule_forward_iff
    (sourceEquiv : V ≃ₗ[ℚ] V') (returnEquiv : W ≃ₗ[ℚ] W')
    (R : Submodule ℚ (V × W)) (original : V × W) :
    pairRechartEquiv sourceEquiv returnEquiv original ∈
        rechartedPairedSubmodule sourceEquiv returnEquiv R ↔
      original ∈ R := by
  rw [mem_rechartedPairedSubmodule_iff]
  simp

/-- The local linear face on the admitted source span. -/
def sourceSpanReturn (x : I → V) (M : V →ₗ[ℚ] W) : sourceSpan x → W :=
  fun source ↦ M source.1

/-- The complete paired fibre has at most one returned face over each admitted source. -/
theorem unique_return_on_sourceSpan
    (x : I → V) (y : I → W) (M : V →ₗ[ℚ] W)
    (sample_exact : ∀ i, y i = M (x i))
    {v : sourceSpan x} {left right : W}
    (left_paired : (v.1, left) ∈ pairedCurrentSubmodule x y)
    (right_paired : (v.1, right) ∈ pairedCurrentSubmodule x y) :
    left = right := by
  exact (paired_span_return x y M sample_exact left_paired).trans
    (paired_span_return x y M sample_exact right_paired).symm

/-- The same constitutive law gives an exact receiver transformer on the presented source range. -/
def receiverTransformerOfLinearMap
    (x : I → V) (y : I → W) (M : V →ₗ[ℚ] W)
    (sample_exact : ∀ i, y i = M (x i)) :
    ReceiverTransformer x y where
  transform face := M face.1
  exact occurrence := (sample_exact occurrence).symm

/-- Exact receiver transformers over one presented source range have the same returned face. -/
theorem receiverTransformer_unique_on_sourceRange
    (x : I → V) (y : I → W)
    (left right : ReceiverTransformer x y) :
    left.transform = right.transform := by
  funext face
  rcases face.2 with ⟨occurrence, hoccurrence⟩
  let canonical : Set.range x := ⟨x occurrence, ⟨occurrence, rfl⟩⟩
  have hcanonical : canonical = face := Subtype.ext hoccurrence
  rw [← hcanonical, left.exact, right.exact]

/-! ## A two-axis obstruction to forgetting the returned direction -/

namespace TwoAxisControl

/-- The observed source keeps only the first axis of a two-dimensional current. -/
def firstAxis : (ℚ × ℚ) →ₗ[ℚ] ℚ where
  toFun := Prod.fst
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The candidate returned face is the second axis. -/
def secondAxis : (ℚ × ℚ) →ₗ[ℚ] ℚ where
  toFun := Prod.snd
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Two paired observations share the first axis while differing on the second. -/
def states : Bool → ℚ × ℚ :=
  fun branch ↦ if branch then (0, 1) else (0, 0)

def observedFirst (branch : Bool) : ℚ := firstAxis (states branch)

def returnedSecond (branch : Bool) : ℚ := secondAxis (states branch)

theorem zeroSource_nonzeroTarget :
    observedFirst true = 0 ∧ returnedSecond true = 1 := by
  norm_num [observedFirst, returnedSecond, states, firstAxis, secondAxis]

theorem sameObservedFirst_differentReturnedSecond :
    observedFirst false = observedFirst true ∧
      returnedSecond false ≠ returnedSecond true := by
  norm_num [observedFirst, returnedSecond, states, firstAxis, secondAxis]

/-- The two paired observations are an exact receiver insufficiency witness. -/
def firstAxisInsufficiency : ReceiverInsufficiency observedFirst returnedSecond where
  left := false
  right := true
  sameEntering := sameObservedFirst_differentReturnedSecond.1
  differentReturned := sameObservedFirst_differentReturnedSecond.2

/-- Forgetting the second axis cannot define a returned face on this presented range. -/
theorem secondAxis_not_determined_by_first :
    ¬ Nonempty (ReceiverTransformer observedFirst returnedSecond) := by
  rintro ⟨transformer⟩
  exact transformer.excludesInsufficiency firstAxisInsufficiency

/-- The zero-source/nonzero-target pair directly obstructs every linear first-axis return map. -/
theorem zeroSource_nonzeroTarget_obstructsLinearMap :
    ¬ ∃ M : ℚ →ₗ[ℚ] ℚ, ∀ branch, returnedSecond branch = M (observedFirst branch) := by
  rintro ⟨M, exact_return⟩
  have contradiction : (1 : ℚ) = 0 := by
    calc
      (1 : ℚ) = returnedSecond true := by
        norm_num [returnedSecond, states, secondAxis]
      _ = M (observedFirst true) := exact_return true
      _ = 0 := by
        rw [show observedFirst true = 0 by
          norm_num [observedFirst, states, firstAxis], M.map_zero]
  exact one_ne_zero contradiction

/-- One observed source sample, whose span does not contain the second-axis direction. -/
def observedSources : Unit → ℚ × ℚ := fun _ ↦ (1, 0)

theorem secondAxis_zero_on_observedSourceSpan {value : ℚ × ℚ}
    (value_mem : value ∈ sourceSpan observedSources) :
    secondAxis value = 0 := by
  change value ∈ Submodule.span ℚ (Set.range observedSources) at value_mem
  refine Submodule.span_induction
    (p := fun value _ ↦ secondAxis value = 0) ?_ ?_ ?_ ?_ value_mem
  · rintro value ⟨_, rfl⟩
    norm_num [observedSources, secondAxis]
  · simp
  · intro left right hleft hright left_zero right_zero
    rw [secondAxis.map_add, left_zero, right_zero, add_zero]
  · intro scalar value hvalue value_zero
    rw [secondAxis.map_smul, value_zero, smul_zero]

theorem unobserved_secondAxis_direction_not_in_observedSourceSpan :
    (0, 1) ∉ sourceSpan observedSources := by
  intro value_mem
  have zero := secondAxis_zero_on_observedSourceSpan value_mem
  norm_num [secondAxis] at zero

/-- Two explicit linear maps agree on the observed first-axis sample. -/
def zeroMap : (ℚ × ℚ) →ₗ[ℚ] ℚ := 0

theorem maps_agree_on_observed_first_axis_sample :
    zeroMap (1, 0) = secondAxis (1, 0) := by
  norm_num [zeroMap, secondAxis]

/-- The same maps differ on the unobserved source direction. -/
theorem maps_differ_on_unobserved_second_axis :
    zeroMap (0, 1) ≠ secondAxis (0, 1) := by
  norm_num [zeroMap, secondAxis]

theorem explicit_maps_are_distinct : zeroMap ≠ secondAxis := by
  intro equal_maps
  exact maps_differ_on_unobserved_second_axis
    (congrArg (fun map : (ℚ × ℚ) →ₗ[ℚ] ℚ ↦ map (0, 1)) equal_maps)

end TwoAxisControl

end Soma.Holonics.Computation.HolonicConstitutiveFibre

section Audit
open Soma.Holonics.Computation.HolonicConstitutiveFibre
#print axioms paired_span_return
#print axioms pairedCurrentSubmodule_rechart
#print axioms sourceSpan_exists_paired
#print axioms sourceSpan_iff_paired_source
#print axioms vertical_fibre_iff_zero_source_difference
#print axioms pairedCurrentSubmodule_sumUnit_eq_add
#print axioms mem_rechartedPairedSubmodule_iff
#print axioms mem_rechartedPairedSubmodule_forward_iff
#print axioms unique_return_on_sourceSpan
#print axioms receiverTransformerOfLinearMap
#print axioms receiverTransformer_unique_on_sourceRange
#print axioms TwoAxisControl.secondAxis_not_determined_by_first
#print axioms TwoAxisControl.zeroSource_nonzeroTarget_obstructsLinearMap
#print axioms TwoAxisControl.unobserved_secondAxis_direction_not_in_observedSourceSpan
#print axioms TwoAxisControl.explicit_maps_are_distinct
end Audit
