set(R34_POSITIVE "${PROJECT_SOURCE_DIR}/apparatus/cards/R34_POSITIVE_TRIPLES.card")
set(R34_SIGNED "${PROJECT_SOURCE_DIR}/apparatus/cards/R34_SIGNED_TRIPLES.card")
set(R34_RECHARTED "${PROJECT_SOURCE_DIR}/apparatus/cards/R34_RECHARTED_TRIPLES.card")
set(R34_HELDOUT "${PROJECT_SOURCE_DIR}/apparatus/cards/R34_HELDOUT_ORIENTED_SYSTEM.card")
set(R34_FORMAL_ROOT "${PROJECT_SOURCE_DIR}/formal/elementary-holonics")
set(R34_TOOLCHAIN "${R34_FORMAL_ROOT}/lean-toolchain")
set(R34_FORMAL_MANIFEST "${R34_FORMAL_ROOT}/lake-manifest.json")
set(R34_LITERATURE_SOURCE
  "${PROJECT_SOURCE_DIR}/reference/external/R34_RANK_THREE_TRACE_LITERATURE_SOURCE.md")

holonic_found(NAME r34.trace_fiber_discovery_device_deed
  EXECUTABLE r34_trace_fiber_discovery_device_deed
  COMMAND
    "${R34_DISC_DEED}" "${R33_FINAL_REST}" "${R34_INTERMEDIATE_REST}" "${R34_POSITIVE}"
    "${R34_SIGNED}" "${R34_RECHARTED}" "${R34_DISC_SOURCE}" "${R34_DISC_OLEAN}"
    "${R34_DISC_STDOUT}" "${R34_DISC_STDERR}" "${R34_FORMAL_ROOT}" "${R34_TOOLCHAIN}"
    "${R34_FORMAL_MANIFEST}" "${PROJECT_BINARY_DIR}/artifacts" "${R34_WORD_ATLAS}"
    "${R34_TRIPLE_ATLAS}" "${R34_GROUP_ATLAS}" "${R34_LAW_ATLAS}")
holonic_found(NAME r34.trace_fiber_application_device_deed
  EXECUTABLE r34_trace_fiber_application_device_deed
  COMMAND
    "${R34_APP_DEED}" "${R34_INTERMEDIATE_REST}" "${R34_FINAL_REST}" "${R34_HELDOUT}"
    "${R34_APP_SOURCE}" "${R34_APP_OLEAN}" "${R34_APP_STDOUT}" "${R34_APP_STDERR}"
    "${R34_FORMAL_ROOT}" "${R34_TOOLCHAIN}" "${R34_FORMAL_MANIFEST}"
    "${PROJECT_BINARY_DIR}/artifacts" "${R34_DOSSIER}" "${R34_APP_ATLAS}")
holonic_found(NAME r34.trace_fiber_host_conformance
  EXECUTABLE r34_trace_fiber_host_conformance
  COMMAND
    "${R34_POSITIVE}" "${R34_SIGNED}" "${R34_RECHARTED}" "${R34_HELDOUT}"
    "${R34_WORD_ATLAS}" "${R34_TRIPLE_ATLAS}" "${R34_GROUP_ATLAS}" "${R34_LAW_ATLAS}"
    "${R34_APP_ATLAS}" "${R34_HOST_CONFORMANCE}")

add_library(r34_open_probe SHARED tests/apparatus/r34_open_probe.cpp)
target_link_libraries(r34_open_probe PRIVATE holonics_contract_options)
set_target_properties(r34_open_probe PROPERTIES PREFIX "")
set(R34_DISC_LOG "${PROJECT_BINARY_DIR}/artifacts/R34_DISCOVERY_OPEN_PATHS.txt")
set(R34_APP_LOG "${PROJECT_BINARY_DIR}/artifacts/R34_APPLICATION_OPEN_PATHS.txt")
holonic_found(NAME r34.source_access_audit
  COMMAND
    "${CMAKE_COMMAND}" -DDISC_EXEC=$<TARGET_FILE:r34_trace_fiber_discovery_device_deed>
    -DAPP_EXEC=$<TARGET_FILE:r34_trace_fiber_application_device_deed>
    -DPROBE=$<TARGET_FILE:r34_open_probe> -DDISC_LOG=${R34_DISC_LOG}
    -DAPP_LOG=${R34_APP_LOG} -DOUTPUT=${R34_SOURCE_AUDIT} -DDISC_DEED=${R34_DISC_DEED}
    -DAPP_DEED=${R34_APP_DEED} -DR33_REST=${R33_FINAL_REST}
    -DINTERMEDIATE=${R34_INTERMEDIATE_REST} -DFINAL_REST=${R34_FINAL_REST}
    -DPOSITIVE=${R34_POSITIVE} -DSIGNED=${R34_SIGNED} -DRECHARTED=${R34_RECHARTED}
    -DHELDOUT=${R34_HELDOUT} -DDISC_SOURCE=${R34_DISC_SOURCE} -DDISC_OLEAN=${R34_DISC_OLEAN}
    -DDISC_STDOUT=${R34_DISC_STDOUT} -DDISC_STDERR=${R34_DISC_STDERR}
    -DWORD_ATLAS=${R34_WORD_ATLAS} -DTRIPLE_ATLAS=${R34_TRIPLE_ATLAS}
    -DGROUP_ATLAS=${R34_GROUP_ATLAS} -DLAW_ATLAS=${R34_LAW_ATLAS}
    -DAPP_SOURCE=${R34_APP_SOURCE} -DAPP_OLEAN=${R34_APP_OLEAN}
    -DAPP_STDOUT=${R34_APP_STDOUT} -DAPP_STDERR=${R34_APP_STDERR} -DDOSSIER=${R34_DOSSIER}
    -DAPP_ATLAS=${R34_APP_ATLAS} -DFORMAL_ROOT=${R34_FORMAL_ROOT}
    -DTOOLCHAIN=${R34_TOOLCHAIN} -DMANIFEST=${R34_FORMAL_MANIFEST}
    -DARTIFACT_ROOT=${PROJECT_BINARY_DIR}/artifacts -P
    "${PROJECT_SOURCE_DIR}/cmake/R34SourceAccessAudit.cmake")

holonic_found(NAME r34.determinism
  WITHHOLD TMP
  COMMAND
    "${CMAKE_COMMAND}" -DDISC_EXEC=$<TARGET_FILE:r34_trace_fiber_discovery_device_deed>
    -DAPP_EXEC=$<TARGET_FILE:r34_trace_fiber_application_device_deed>
    -DTMP=${PROJECT_BINARY_DIR}/artifacts/r34-determinism -DR33_REST=${R33_FINAL_REST}
    -DPOSITIVE=${R34_POSITIVE} -DSIGNED=${R34_SIGNED} -DRECHARTED=${R34_RECHARTED}
    -DHELDOUT=${R34_HELDOUT} -DFORMAL_ROOT=${R34_FORMAL_ROOT} -DTOOLCHAIN=${R34_TOOLCHAIN}
    -DMANIFEST=${R34_FORMAL_MANIFEST} -DARTIFACT_ROOT=${PROJECT_BINARY_DIR}/artifacts
    -DDISC_DEED=${R34_DISC_DEED} -DAPP_DEED=${R34_APP_DEED}
    -DINTERMEDIATE=${R34_INTERMEDIATE_REST} -DFINAL_REST=${R34_FINAL_REST}
    -DDISC_SOURCE=${R34_DISC_SOURCE} -DDISC_STDOUT=${R34_DISC_STDOUT}
    -DDISC_STDERR=${R34_DISC_STDERR} -DWORD_ATLAS=${R34_WORD_ATLAS}
    -DTRIPLE_ATLAS=${R34_TRIPLE_ATLAS} -DGROUP_ATLAS=${R34_GROUP_ATLAS}
    -DLAW_ATLAS=${R34_LAW_ATLAS} -DAPP_SOURCE=${R34_APP_SOURCE}
    -DAPP_STDOUT=${R34_APP_STDOUT} -DAPP_STDERR=${R34_APP_STDERR} -DDOSSIER=${R34_DOSSIER}
    -DAPP_ATLAS=${R34_APP_ATLAS} -DOUTPUT=${R34_DETERMINISM} -P
    "${PROJECT_SOURCE_DIR}/cmake/R34Determinism.cmake")

holonic_found(NAME r34.seal
  COMMAND
    "${CMAKE_COMMAND}" -DOUTPUT=${R34_SEAL} -DSOURCE_AUDIT=${R34_SOURCE_AUDIT}
    -DDISC_DEED=${R34_DISC_DEED} -DAPP_DEED=${R34_APP_DEED}
    -DHOST_CONFORMANCE=${R34_HOST_CONFORMANCE} -DINTERMEDIATE=${R34_INTERMEDIATE_REST}
    -DFINAL_REST=${R34_FINAL_REST} -DDISC_SOURCE=${R34_DISC_SOURCE}
    -DDISC_OLEAN=${R34_DISC_OLEAN} -DWORD_ATLAS=${R34_WORD_ATLAS}
    -DTRIPLE_ATLAS=${R34_TRIPLE_ATLAS} -DGROUP_ATLAS=${R34_GROUP_ATLAS}
    -DLAW_ATLAS=${R34_LAW_ATLAS} -DAPP_SOURCE=${R34_APP_SOURCE} -DAPP_OLEAN=${R34_APP_OLEAN}
    -DDOSSIER=${R34_DOSSIER} -DAPP_ATLAS=${R34_APP_ATLAS} -DDETERMINISM=${R34_DETERMINISM}
    -P "${PROJECT_SOURCE_DIR}/cmake/R34Seal.cmake")

holonic_found(NAME r34.post_seal_literature_comparison
  COMMAND
    "${CMAKE_COMMAND}" -DSEAL=${R34_SEAL} -DSOURCE=${R34_DISC_SOURCE}
    -DLAW_ATLAS=${R34_LAW_ATLAS} -DLITERATURE=${R34_LITERATURE_SOURCE}
    -DOUTPUT=${R34_LITERATURE_COMPARISON} -P
    "${PROJECT_SOURCE_DIR}/cmake/R34LiteratureComparison.cmake")

add_test(NAME r34.forbidden_trace_fiber_copy COMMAND "${CMAKE_COMMAND}"
  -DCOMPILER=${CMAKE_CXX_COMPILER}
  -DSOURCE=${PROJECT_SOURCE_DIR}/tests/compile_contracts/forbidden_trace_fiber_copy.cpp
  -DINCLUDE_DIRECTORY=${PROJECT_SOURCE_DIR}/include "-DEXPECTED_TEXT=use of deleted function"
  -P "${PROJECT_SOURCE_DIR}/cmake/ExpectCompileFailure.cmake")
