set(R35_PRIMARY "${PROJECT_SOURCE_DIR}/apparatus/cards/R35_PRIMARY_REBASE.card")
set(R35_SIGNED "${PROJECT_SOURCE_DIR}/apparatus/cards/R35_SIGNED_REBASE.card")
set(R35_RECHARTED "${PROJECT_SOURCE_DIR}/apparatus/cards/R35_RECHARTED_REBASE.card")
set(R35_HELDOUT "${PROJECT_SOURCE_DIR}/apparatus/cards/R35_HELDOUT_REBASE_PATH.card")
set(R35_FORMAL_ROOT "${PROJECT_SOURCE_DIR}/formal/elementary-holonics")
set(R35_TOOLCHAIN "${R35_FORMAL_ROOT}/lean-toolchain")
set(R35_FORMAL_MANIFEST "${R35_FORMAL_ROOT}/lake-manifest.json")
set(R35_LITERATURE_SOURCE
  "${PROJECT_SOURCE_DIR}/reference/external/R35_TRACE_REBASE_LITERATURE_SOURCE.md")

add_test(NAME r35.trace_rebase_discovery_device_deed
  COMMAND r35_trace_rebase_discovery_device_deed "${R35_DISC_DEED}" "${R34_FINAL_REST}"
    "${R35_INTERMEDIATE_REST}" "${R35_PRIMARY}" "${R35_SIGNED}" "${R35_RECHARTED}"
    "${R35_DISC_SOURCE}" "${R35_DISC_OLEAN}" "${R35_DISC_STDOUT}" "${R35_DISC_STDERR}"
    "${R35_FORMAL_ROOT}" "${R35_TOOLCHAIN}" "${R35_FORMAL_MANIFEST}"
    "${PROJECT_BINARY_DIR}/artifacts" "${R35_STATE_ATLAS}" "${R35_EDGE_ATLAS}"
    "${R35_TANGENT_ATLAS}" "${R35_LAW_ATLAS}")
set_tests_properties(r35.trace_rebase_discovery_device_deed PROPERTIES
  DEPENDS "r34.trace_fiber_application_device_deed" TIMEOUT 1800)
add_test(NAME r35.trace_rebase_application_device_deed
  COMMAND r35_trace_rebase_application_device_deed "${R35_APP_DEED}"
    "${R35_INTERMEDIATE_REST}" "${R35_FINAL_REST}" "${R35_HELDOUT}"
    "${R35_APP_SOURCE}" "${R35_APP_OLEAN}" "${R35_APP_STDOUT}" "${R35_APP_STDERR}"
    "${R35_FORMAL_ROOT}" "${R35_TOOLCHAIN}" "${R35_FORMAL_MANIFEST}"
    "${PROJECT_BINARY_DIR}/artifacts" "${R35_DOSSIER}" "${R35_APP_ATLAS}")
set_tests_properties(r35.trace_rebase_application_device_deed PROPERTIES
  DEPENDS "r35.trace_rebase_discovery_device_deed" TIMEOUT 1800)
add_test(NAME r35.trace_rebase_host_conformance COMMAND r35_trace_rebase_host_conformance
  "${R35_PRIMARY}" "${R35_SIGNED}" "${R35_RECHARTED}" "${R35_HELDOUT}"
  "${R35_STATE_ATLAS}" "${R35_EDGE_ATLAS}" "${R35_TANGENT_ATLAS}"
  "${R35_LAW_ATLAS}" "${R35_APP_ATLAS}" "${R35_HOST_CONFORMANCE}")
set_tests_properties(r35.trace_rebase_host_conformance PROPERTIES
  DEPENDS "r35.trace_rebase_application_device_deed" TIMEOUT 1800)

add_library(r35_open_probe SHARED tests/apparatus/r35_open_probe.cpp)
target_link_libraries(r35_open_probe PRIVATE holonics_contract_options)
set_target_properties(r35_open_probe PROPERTIES PREFIX "")
set(R35_DISC_LOG "${PROJECT_BINARY_DIR}/artifacts/R35_DISCOVERY_OPEN_PATHS.txt")
set(R35_APP_LOG "${PROJECT_BINARY_DIR}/artifacts/R35_APPLICATION_OPEN_PATHS.txt")
add_test(NAME r35.source_access_audit COMMAND "${CMAKE_COMMAND}"
  -DDISC_EXEC=$<TARGET_FILE:r35_trace_rebase_discovery_device_deed>
  -DAPP_EXEC=$<TARGET_FILE:r35_trace_rebase_application_device_deed>
  -DPROBE=$<TARGET_FILE:r35_open_probe> -DDISC_LOG=${R35_DISC_LOG} -DAPP_LOG=${R35_APP_LOG}
  -DOUTPUT=${R35_SOURCE_AUDIT} -DDISC_DEED=${R35_DISC_DEED} -DAPP_DEED=${R35_APP_DEED}
  -DR34_REST=${R34_FINAL_REST} -DINTERMEDIATE=${R35_INTERMEDIATE_REST}
  -DFINAL_REST=${R35_FINAL_REST} -DPRIMARY=${R35_PRIMARY} -DSIGNED=${R35_SIGNED}
  -DRECHARTED=${R35_RECHARTED} -DHELDOUT=${R35_HELDOUT} -DDISC_SOURCE=${R35_DISC_SOURCE}
  -DDISC_OLEAN=${R35_DISC_OLEAN} -DDISC_STDOUT=${R35_DISC_STDOUT}
  -DDISC_STDERR=${R35_DISC_STDERR} -DSTATE_ATLAS=${R35_STATE_ATLAS}
  -DEDGE_ATLAS=${R35_EDGE_ATLAS} -DTANGENT_ATLAS=${R35_TANGENT_ATLAS}
  -DLAW_ATLAS=${R35_LAW_ATLAS} -DAPP_SOURCE=${R35_APP_SOURCE} -DAPP_OLEAN=${R35_APP_OLEAN}
  -DAPP_STDOUT=${R35_APP_STDOUT} -DAPP_STDERR=${R35_APP_STDERR} -DDOSSIER=${R35_DOSSIER}
  -DAPP_ATLAS=${R35_APP_ATLAS} -DFORMAL_ROOT=${R35_FORMAL_ROOT} -DTOOLCHAIN=${R35_TOOLCHAIN}
  -DMANIFEST=${R35_FORMAL_MANIFEST} -DARTIFACT_ROOT=${PROJECT_BINARY_DIR}/artifacts
  -P "${PROJECT_SOURCE_DIR}/cmake/R35SourceAccessAudit.cmake")
set_tests_properties(r35.source_access_audit PROPERTIES
  DEPENDS "r35.trace_rebase_host_conformance" TIMEOUT 1800)

add_test(NAME r35.determinism COMMAND "${CMAKE_COMMAND}"
  -DDISC_EXEC=$<TARGET_FILE:r35_trace_rebase_discovery_device_deed>
  -DAPP_EXEC=$<TARGET_FILE:r35_trace_rebase_application_device_deed>
  -DTMP=${PROJECT_BINARY_DIR}/artifacts/r35-determinism -DR34_REST=${R34_FINAL_REST}
  -DPRIMARY=${R35_PRIMARY} -DSIGNED=${R35_SIGNED} -DRECHARTED=${R35_RECHARTED}
  -DHELDOUT=${R35_HELDOUT} -DFORMAL_ROOT=${R35_FORMAL_ROOT} -DTOOLCHAIN=${R35_TOOLCHAIN}
  -DMANIFEST=${R35_FORMAL_MANIFEST} -DARTIFACT_ROOT=${PROJECT_BINARY_DIR}/artifacts
  -DDISC_DEED=${R35_DISC_DEED} -DAPP_DEED=${R35_APP_DEED}
  -DINTERMEDIATE=${R35_INTERMEDIATE_REST} -DFINAL_REST=${R35_FINAL_REST}
  -DDISC_SOURCE=${R35_DISC_SOURCE} -DDISC_STDOUT=${R35_DISC_STDOUT}
  -DDISC_STDERR=${R35_DISC_STDERR} -DSTATE_ATLAS=${R35_STATE_ATLAS}
  -DEDGE_ATLAS=${R35_EDGE_ATLAS} -DTANGENT_ATLAS=${R35_TANGENT_ATLAS}
  -DLAW_ATLAS=${R35_LAW_ATLAS} -DAPP_SOURCE=${R35_APP_SOURCE}
  -DAPP_STDOUT=${R35_APP_STDOUT} -DAPP_STDERR=${R35_APP_STDERR} -DDOSSIER=${R35_DOSSIER}
  -DAPP_ATLAS=${R35_APP_ATLAS} -DOUTPUT=${R35_DETERMINISM}
  -P "${PROJECT_SOURCE_DIR}/cmake/R35Determinism.cmake")
set_tests_properties(r35.determinism PROPERTIES DEPENDS "r35.source_access_audit" TIMEOUT 1200)

add_test(NAME r35.seal COMMAND "${CMAKE_COMMAND}" -DOUTPUT=${R35_SEAL}
  -DSOURCE_AUDIT=${R35_SOURCE_AUDIT} -DDISC_DEED=${R35_DISC_DEED} -DAPP_DEED=${R35_APP_DEED}
  -DHOST_CONFORMANCE=${R35_HOST_CONFORMANCE} -DINTERMEDIATE=${R35_INTERMEDIATE_REST}
  -DFINAL_REST=${R35_FINAL_REST} -DDISC_SOURCE=${R35_DISC_SOURCE} -DDISC_OLEAN=${R35_DISC_OLEAN}
  -DSTATE_ATLAS=${R35_STATE_ATLAS} -DEDGE_ATLAS=${R35_EDGE_ATLAS}
  -DTANGENT_ATLAS=${R35_TANGENT_ATLAS} -DLAW_ATLAS=${R35_LAW_ATLAS}
  -DAPP_SOURCE=${R35_APP_SOURCE} -DAPP_OLEAN=${R35_APP_OLEAN}
  -DDOSSIER=${R35_DOSSIER} -DAPP_ATLAS=${R35_APP_ATLAS} -DDETERMINISM=${R35_DETERMINISM}
  -P "${PROJECT_SOURCE_DIR}/cmake/R35Seal.cmake")
set_tests_properties(r35.seal PROPERTIES DEPENDS "r35.determinism")
add_test(NAME r35.post_seal_literature_comparison COMMAND "${CMAKE_COMMAND}"
  -DSEAL=${R35_SEAL} -DSOURCE=${R35_DISC_SOURCE} -DLAW_ATLAS=${R35_LAW_ATLAS}
  -DLITERATURE=${R35_LITERATURE_SOURCE} -DOUTPUT=${R35_LITERATURE_COMPARISON}
  -P "${PROJECT_SOURCE_DIR}/cmake/R35LiteratureComparison.cmake")
set_tests_properties(r35.post_seal_literature_comparison PROPERTIES DEPENDS "r35.seal")
add_test(NAME r35.forbidden_trace_rebase_copy COMMAND "${CMAKE_COMMAND}"
  -DCOMPILER=${CMAKE_CXX_COMPILER}
  -DSOURCE=${PROJECT_SOURCE_DIR}/tests/compile_contracts/forbidden_trace_rebase_copy.cpp
  -DINCLUDE_DIRECTORY=${PROJECT_SOURCE_DIR}/include "-DEXPECTED_TEXT=use of deleted function"
  -P "${PROJECT_SOURCE_DIR}/cmake/ExpectCompileFailure.cmake")
