import Mathlib.Tactic

/-!
# The section layout: a declared incidence generates gather, local application and scatter

This is the Lean owner paired with `crates/holonics-cuda/src/section_layout.rs`, and it continues
`ElementaryHolonics/Foundation/DeviceLaunchLaw.lean` (D1/D2 of
`docs/plans/THE_EXACT_DEVICE_LAW_IS_CONSTRUCTED.md`) into D3, *partition generates layout*.

A **section operator** is performed on device as three arms: a *gather* by region incidence into a
local tile, a *local application* of a material operator inside each tile, and a *transposed
scatter* back into the global field.  The shared-section work in `crates/holonic-engine/kernels/`
performs those three arms by hand, once per kernel.  What is formalized here is that the three arms
are **generated by one declaration**: an `Incidence`, which names for each local slot the global
address it reads and the region it belongs to.

Everything is stated over a `CommSemiring`, so it holds for the exact rings the device carries —
`ZMod p` for the modular arm and `ℤ` for the checked-integer arm — and never for a floating type,
whose addition is not associative and which therefore is not a semiring at all.  That is the
type-level reason the Rust `AccumulationLaw` has no floating variant.

## What is proved

* `Incidence.adjoint` — **scatter is the transpose of gather**: `⟨gather x, y⟩ = ⟨x, scatterAdd y⟩`.
  The Rust equivalent is `SectionLayout::verify_adjoint`.
* `Incidence.assembled_apply` — `scatterAdd ∘ applyLocal ∘ gather` **is** the assembled global
  operator, applied as the matrix `assembled I L`.  The Rust equivalent is
  `SectionLayout::apply_reference` tested against `SectionLayout::assemble_dense`.
* `Incidence.assembled_sum_regions` — that global matrix is `Σ_r P_rᵀ L_r P_r`, the finite-element
  assembly identity, when the local operator is block diagonal over the regions.
* `Incidence.assembled_symm` — it is symmetric when every local block is.
* `Incidence.scatterAdd_of_injective` — through an injective incidence the accumulation degenerates
  to a plain store, which is why `ScatterReceipt::Injective` admits plain device stores (and
  `DeviceLaunchLaw.DisjointPartition.scatter_perm` then supplies order-independence).
* `Incidence.colour_schedule` — **the colouring theorem**: launching colour class by colour class,
  each class adding its own partial scatter into the running device state, leaves exactly
  `σ + scatterAdd y`, the sequential result.  `Incidence.colour_fiber_single_region` is the
  companion that makes each class *injective*: under a proper colouring no two distinct regions of
  one colour reach the same global address, so each colour launch is an injective scatter and
  `DeviceLaunchLaw.DisjointPartition.scatter_perm` applies inside it.  Together they are why the
  accumulating device arm needs no atomic and no read-modify-write race.

A non-injective incidence with no accumulation is not formalized here as an admissible object at
all: `DeviceLaunchLaw.DisjointPartition.scatter_order_dependent` is the counterexample showing that
such a scatter has no well-defined result, and the Rust `SectionLayout::generate` refuses it.
-/

namespace Soma.Holonics.Foundation.SectionLayout

open Finset

universe u

variable {R : Type u} [CommSemiring R]
variable {n slots regions colours : ℕ}

/-- [definition] **The incidence declaration.**  There are `slots` ordered local slots.  Slot `s`
reads the global address `addr s` and belongs to region `region s`.  This is the whole of what the
Rust `IncidenceDeclaration` carries: its CSR `offsets` table supplies `region` and its `addresses`
table supplies `addr`, both validated exactly (in bounds, monotone, checked arithmetic). -/
structure Incidence (n slots regions : ℕ) where
  /-- The global address local slot `s` is incident to. -/
  addr : Fin slots → Fin n
  /-- The region local slot `s` belongs to. -/
  region : Fin slots → Fin regions

namespace Incidence

/-- [definition] **The gather arm.**  The local tile reads the global field through the incidence:
`(gather x) s = x (addr s)`.  This is `P = ⊕_r P_r`, the stacked restriction.  The Rust equivalent
is the generated gather index table and the `section_gather` device entry. -/
def gather (I : Incidence n slots regions) (x : Fin n → R) : Fin slots → R := fun s => x (I.addr s)

/-- [definition] **The scatter arm.**  Every slot incident to a global address contributes to it,
through the semiring's own addition: `(scatterAdd y) a = Σ_{s : addr s = a} y s`.  This is `Pᵀ`.
The Rust equivalent is the generated transposed scatter table and the `section_scatter_add` device
entry (or `section_scatter_store` when the incidence is injective). -/
def scatterAdd (I : Incidence n slots regions) (y : Fin slots → R) : Fin n → R :=
  fun a => ∑ s ∈ univ.filter (fun s => I.addr s = a), y s

/-- [proved-derived; formal-checked] **The adjoint identity: scatter is the transpose of gather.**
`⟨gather x, y⟩ = ⟨x, scatterAdd y⟩` over any commutative semiring.  This is the single law that
makes the generated scatter table *the* transpose of the generated gather table rather than a
second, independently authored map; the Rust `SectionLayout::verify_adjoint` witnesses it
executably on the generated tables. -/
theorem adjoint (I : Incidence n slots regions) (x : Fin n → R) (y : Fin slots → R) :
    ∑ s, (I.gather x) s * y s = ∑ a, x a * (I.scatterAdd y) a := by
  classical
  have hpoint : ∀ a : Fin n,
      x a * (I.scatterAdd y) a
        = ∑ s ∈ univ.filter (fun s => I.addr s = a), (I.gather x) s * y s := by
    intro a
    rw [scatterAdd, Finset.mul_sum]
    refine Finset.sum_congr rfl fun s hs => ?_
    have hsa : I.addr s = a := (Finset.mem_filter.mp hs).2
    simp [gather, hsa]
  rw [Finset.sum_congr rfl fun a _ => hpoint a]
  exact (Finset.sum_fiberwise univ I.addr (fun s => (I.gather x) s * y s)).symm

/-- [definition] **The local application arm.**  A material operator acting inside the tile:
`(applyLocal L u) s = Σ_t L s t * u t`.  The Rust equivalent is `LocalOperator`, a dense `w × w`
table of exact ring elements shared by every region, and the `section_apply` device entry. -/
def applyLocal (L : Fin slots → Fin slots → R) (u : Fin slots → R) : Fin slots → R :=
  fun s => ∑ t, L s t * u t

/-- [definition] The local operator is **block diagonal over the regions**: a slot of one region
never reads a slot of another.  This is what "local" means, and it is what the `section_apply`
entry realizes by giving each region its own block and its own tile. -/
def BlockDiagonal (I : Incidence n slots regions) (L : Fin slots → Fin slots → R) : Prop :=
  ∀ s t, I.region s ≠ I.region t → L s t = 0

/-- [definition] **The assembled global operator** as a matrix on the global field:
`A a b = Σ_{s : addr s = a} Σ_{t : addr t = b} L s t`.  The Rust equivalent is
`SectionLayout::assemble_dense`, which the reference implementation is tested against. -/
def assembled (I : Incidence n slots regions) (L : Fin slots → Fin slots → R) :
    Fin n → Fin n → R :=
  fun a b =>
    ∑ s ∈ univ.filter (fun s => I.addr s = a), ∑ t ∈ univ.filter (fun t => I.addr t = b), L s t

/-- [definition] The contribution of one region: `P_rᵀ L_r P_r`. -/
def regionBlock (I : Incidence n slots regions) (L : Fin slots → Fin slots → R) (r : Fin regions) :
    Fin n → Fin n → R :=
  fun a b =>
    ∑ s ∈ (univ.filter fun s => I.addr s = a).filter (fun s => I.region s = r),
      ∑ t ∈ (univ.filter fun t => I.addr t = b).filter (fun t => I.region t = r), L s t

/-- [proved-derived; formal-checked] **The three arms compose to the assembled operator.**
`scatterAdd ∘ applyLocal ∘ gather` applied to `x` is the matrix `assembled I L` applied to `x`.
This is the statement the Rust exact CPU reference realizes and the device result is compared
against bit for bit. -/
theorem assembled_apply (I : Incidence n slots regions) (L : Fin slots → Fin slots → R)
    (x : Fin n → R) :
    I.scatterAdd (applyLocal L (I.gather x)) = fun a => ∑ b, (assembled I L) a b * x b := by
  classical
  funext a
  rw [scatterAdd]
  have hright : ∑ b, (assembled I L) a b * x b
      = ∑ s ∈ univ.filter (fun s => I.addr s = a), ∑ t, L s t * x (I.addr t) := by
    have hb : ∀ b : Fin n, (assembled I L) a b * x b
        = ∑ s ∈ univ.filter (fun s => I.addr s = a),
            ∑ t ∈ univ.filter (fun t => I.addr t = b), L s t * x (I.addr t) := by
      intro b
      rw [assembled, Finset.sum_mul]
      refine Finset.sum_congr rfl fun s _ => ?_
      rw [Finset.sum_mul]
      refine Finset.sum_congr rfl fun t ht => ?_
      have htb : I.addr t = b := (Finset.mem_filter.mp ht).2
      rw [htb]
    rw [Finset.sum_congr rfl fun b _ => hb b, Finset.sum_comm]
    refine Finset.sum_congr rfl fun s _ => ?_
    exact Finset.sum_fiberwise univ I.addr (fun t => L s t * x (I.addr t))
  rw [hright]
  rfl

/-- [proved-derived; formal-checked] **The finite-element assembly identity.**  When the local
operator is block diagonal over the declared regions, the assembled global operator is exactly
`Σ_r P_rᵀ L_r P_r`: the sum over regions of each region's own restricted-operator-prolonged block.
This is the identity the Rust owner's per-region assembly reference reproduces. -/
theorem assembled_sum_regions (I : Incidence n slots regions) (L : Fin slots → Fin slots → R)
    (hL : BlockDiagonal I L) (a b : Fin n) :
    assembled I L a b = ∑ r, regionBlock I L r a b := by
  classical
  rw [assembled, ← Finset.sum_fiberwise_of_maps_to
    (g := I.region) (t := (univ : Finset (Fin regions))) (fun s _ => mem_univ _)]
  refine Finset.sum_congr rfl fun r _ => ?_
  refine Finset.sum_congr rfl fun s hs => ?_
  have hsr : I.region s = r := (Finset.mem_filter.mp hs).2
  refine (Finset.sum_filter_of_ne ?_).symm
  intro t _ hne
  by_contra hcon
  exact hne (hL s t (by rw [hsr]; exact fun h => hcon h.symm))

/-- [proved-derived; formal-checked] A block-diagonal operator symmetric **inside each block** is
symmetric everywhere: across blocks both entries are zero. -/
theorem symm_of_blocks (I : Incidence n slots regions) (L : Fin slots → Fin slots → R)
    (hL : BlockDiagonal I L) (hsymm : ∀ s t, I.region s = I.region t → L s t = L t s) :
    ∀ s t, L s t = L t s := by
  intro s t
  by_cases h : I.region s = I.region t
  · exact hsymm s t h
  · rw [hL s t h, hL t s (fun hts => h hts.symm)]

/-- [proved-derived; formal-checked] **The assembled operator is symmetric when every local block
is.**  Symmetry of the material law survives assembly, which is the property a section operator is
usually wanted for. -/
theorem assembled_symm (I : Incidence n slots regions) (L : Fin slots → Fin slots → R)
    (hL : BlockDiagonal I L) (hsymm : ∀ s t, I.region s = I.region t → L s t = L t s) (a b : Fin n) :
    assembled I L a b = assembled I L b a := by
  classical
  have hfull := symm_of_blocks I L hL hsymm
  rw [assembled, assembled, Finset.sum_comm]
  refine Finset.sum_congr rfl fun t _ => Finset.sum_congr rfl fun s _ => ?_
  exact hfull s t

/-- [proved-derived; formal-checked] **Through an injective incidence the accumulation is a plain
store.**  Every global address is reached by at most one slot, so the fibre sum has one term.  This
is the licence for `ScatterReceipt::Injective` to use plain device stores, whose order-independence
is `DeviceLaunchLaw.DisjointPartition.scatter_perm`. -/
theorem scatterAdd_of_injective (I : Incidence n slots regions)
    (hinj : Function.Injective I.addr) (y : Fin slots → R) (s : Fin slots) :
    I.scatterAdd y (I.addr s) = y s := by
  classical
  have hset : (univ.filter fun t => I.addr t = I.addr s) = {s} := by
    refine Finset.eq_singleton_iff_unique_mem.mpr ⟨?_, ?_⟩
    · simp
    · intro t ht
      exact hinj (Finset.mem_filter.mp ht).2
  rw [scatterAdd, hset, Finset.sum_singleton]

/-! ### The colouring: an accumulating scatter made race-free without atomics -/

/-- [definition] A colouring of the declared regions. -/
structure Colouring (regions colours : ℕ) where
  /-- The colour of each region. -/
  colour : Fin regions → Fin colours

/-- [definition] **A proper colouring for this incidence**: two *distinct* regions of the same
colour never reach the same global address.  The Rust equivalent is `RegionColouring`, computed
exactly by greedy colouring of the region conflict graph under a checked work bound, and verified
executably by `RegionColouring::verify_proper`. -/
def Proper (I : Incidence n slots regions) (C : Colouring regions colours) : Prop :=
  ∀ s t : Fin slots, I.region s ≠ I.region t →
    C.colour (I.region s) = C.colour (I.region t) → I.addr s ≠ I.addr t

/-- [definition] The partial scatter of one colour class. -/
def colourAdd (I : Incidence n slots regions) (C : Colouring regions colours) (y : Fin slots → R)
    (k : Fin colours) : Fin n → R :=
  fun a => ∑ s ∈ univ.filter (fun s => I.addr s = a ∧ C.colour (I.region s) = k), y s

/-- [definition] One colour launch: the running device state accumulates that colour's partial
scatter.  This is exactly what one `section_scatter_add` launch over one colour class performs. -/
def colourStep (I : Incidence n slots regions) (C : Colouring regions colours) (y : Fin slots → R)
    (σ : Fin n → R) (k : Fin colours) : Fin n → R :=
  fun a => σ a + colourAdd I C y k a

/-- [proved-derived; formal-checked] Folding colour launches accumulates their partial scatters. -/
theorem foldl_colourStep (I : Incidence n slots regions) (C : Colouring regions colours)
    (y : Fin slots → R) :
    ∀ (l : List (Fin colours)) (σ : Fin n → R) (a : Fin n),
      (l.foldl (colourStep I C y) σ) a = σ a + ((l.map fun k => colourAdd I C y k a).sum) := by
  intro l
  induction l with
  | nil => intro σ a; simp
  | cons k rest ih =>
    intro σ a
    rw [List.foldl_cons, ih (colourStep I C y σ k) a]
    simp [colourStep, add_assoc]

/-- [proved-derived; formal-checked] **The colouring theorem.**  Launching colour class by colour
class, each launch adding its own partial scatter into the running device state, leaves exactly the
state the *sequential* scatter leaves: `σ + scatterAdd y`.  Together with
`colour_fiber_single_region` — which makes each single colour launch an *injective* scatter, so
`DeviceLaunchLaw.DisjointPartition.scatter_perm` governs it internally — this is the whole
justification of the accumulating device arm, and it uses no atomic. -/
theorem colour_schedule (I : Incidence n slots regions) (C : Colouring regions colours)
    (y : Fin slots → R) (σ : Fin n → R) (a : Fin n) :
    ((List.finRange colours).foldl (colourStep I C y) σ) a = σ a + I.scatterAdd y a := by
  classical
  rw [foldl_colourStep I C y (List.finRange colours) σ a]
  congr 1
  have hlist : ((List.finRange colours).map fun k => colourAdd I C y k a).sum
      = ∑ k, colourAdd I C y k a := (Fin.sum_univ_def _).symm
  rw [hlist, scatterAdd]
  have hfilter : ∀ k : Fin colours,
      colourAdd I C y k a
        = ∑ s ∈ (univ.filter fun s => I.addr s = a).filter
            (fun s => C.colour (I.region s) = k), y s := by
    intro k
    rw [colourAdd, Finset.filter_filter]
  rw [Finset.sum_congr rfl fun k _ => hfilter k]
  exact Finset.sum_fiberwise_of_maps_to
    (g := fun s => C.colour (I.region s)) (t := (univ : Finset (Fin colours)))
    (fun s _ => mem_univ _) y

/-- [proved-derived; formal-checked] **Each colour launch is an injective scatter.**  Under a proper
colouring, every two slots of one colour reaching one global address belong to the *same* region.
One region is one device thread in the accumulating arm, so within a colour launch each global
address has exactly one writer and the read-modify-write is not a race — no atomic is required, and
the D2 injective-scatter partition is the one the launch presents. -/
theorem colour_fiber_single_region (I : Incidence n slots regions) (C : Colouring regions colours)
    (hproper : Proper I C) {k : Fin colours} {a : Fin n} {s t : Fin slots}
    (hs : I.addr s = a ∧ C.colour (I.region s) = k)
    (ht : I.addr t = a ∧ C.colour (I.region t) = k) :
    I.region s = I.region t := by
  by_contra hne
  exact hproper s t hne (hs.2.trans ht.2.symm) (hs.1.trans ht.1.symm)

end Incidence

end Soma.Holonics.Foundation.SectionLayout

/-! ## Kernel receipts

Only `propext`, `Classical.choice` and `Quot.sound` are admissible. -/

#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.adjoint
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.assembled_apply
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.assembled_sum_regions
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.symm_of_blocks
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.assembled_symm
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.scatterAdd_of_injective
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.foldl_colourStep
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.colour_schedule
#print axioms Soma.Holonics.Foundation.SectionLayout.Incidence.colour_fiber_single_region
