//! **Campaign 1's located failure: the diagnostics** (rebuild step 4, #73, campaign 1; design
//! "Step 4 design: the HNN law", (d) "The standing real cut", review E1): a notebook measurement,
//! run once in release, never a test. Campaign 1's exposure on the standing real cut does not beat
//! the online order-0 held-out bits (#73's receipt, read at the receiver's grain `L_R = 16`:
//! `7 + 9/16 + ε` bits a byte against order-0 KT's `4 + 12/16 + ε`, each `0 ≤ ε < 1/16`),
//! and E1 asks for the failure's located cause (source, relation, encoding or decoder) before
//! campaign 2 begins.
//!
//! ```sh
//! cargo run --release -p holonics --example hnn_diagnose -- cut-file .local/cuts/standing-real-cut-campaign-1.bin
//! cargo run --release -p holonics --example hnn_diagnose -- cut-file .local/cuts/standing-real-cut-campaign-1.bin windows 64   # a smoke
//! ```
//!
//! [definition] **What it runs.** The exposure protocol of `holonics::hnn::reference::expose`
//! (design (d)), step for step through the host reference's [`ExecutionPort`] (refine, compare,
//! deposit or discard, ingest, close the aeon at the joint clock's carry-out, locate keys on the
//! crib that closed it), with the readings below taken between the port's methods. It changes no
//! law and adds no accessor: every value it reads is a port return, the published constitution's
//! read face ([`ConstitutionRead`], `Constitution::{receiving_law, source_law}`) or the moment.
//! Its model and order-0 bits reproduce the exposure's (they are printed first, as the check).
//!
//! [definition] **Under Decision 27** the machine's face is the count face's grain logits plus the
//! wave (`hnn::receiving::ReceivingRead::combined`); the decoder's readings below read the wave
//! alone, the count face at the window's region taken out, so they diagnose `R` as before. The
//! located-failure record's receipt was taken under campaign 1's first law (the face on the change
//! alone), at `13d6bb92`.
//!
//! [definition] **The diagnostics**, one section per candidate cause:
//! 1. **The decoder** (the wave `f_j = R · P_R^(τ_R) v_R(e_j)`, no constant term). The
//!    read feature `z_j = P_R^(τ_R) v_R(e_j)` is the receiving map's own sample feature
//!    (`LinearLocus::Receiving`). Read: the mean logit vector over the reads and its code length
//!    as one static face on the held-out targets; the logits' common part; the rank of the
//!    features and their dormant (rotation-invariant) component on the receiving ring; and the
//!    oracle bound: since softmax reads `Re f` up to a common shift, `R = y wᵀ` with `w` the exact
//!    least-squares solution of `wᵀ z_j = 1` over the training reads is the least-squares fit of
//!    `R` to the order-0 log-frequencies `y` (each row `c` fits `y_c · 1`), so `f_j = s_j y` with
//!    `s_j = wᵀ z_j`, scored at the receiver's grain through the machine's own face
//!    ([`Face::of_read`]).
//! 2. **Learning** (the normal law's prox step on `R` and `E_0`). Per deposit: the exact update
//!    `Δ = (W' − W) + (r' − r) + e` (the carry's accounting, Lean
//!    `HNN/LatticeDeposit.lattice_deposit_accounting`), its size against the lattice unit, the
//!    entries it moved, the released tails' share, the leverage `h = zᵀ X̂' z` of each read feature
//!    under the successor's solved chart (the prox step moves the read logits by `γ g h`), and the
//!    logits' executed move `max_c |(R' − R) z|`; over the run, `Σ h` against its bound
//!    `ln det H_T` (log det is concave, so each deposit's `tr(H'⁻¹ ΔH)` is at most its log det's
//!    growth); the covector's phase share at the face and pulled back through `Rᵀ`; the held-out
//!    logits split into the declared prior's reading `R_0 z` and the learned part `(R − R_0) z`
//!    (every held-out read uses the final map); by aeon, the training bits against order-0 KT.
//! 3. **The keys** (the relation). Per key location and ring: the best partial closure of the
//!    crib's menu over injective plugboards (the fibre's own images), the configuration satisfying
//!    the most edges. The rotor gauge makes every key equivalent, so the key is absorbed: the best
//!    is exhaustive for `d ≤ 7`, a local search's for every ring, and by the port's own propagation
//!    from every root and seed image under every key. It is read against the same crib shuffled
//!    (its port histogram kept, its order destroyed). And on synthetic cribs generated by the
//!    declared ring with a true key and plugboard: whether location returns the truth, and whether
//!    the partial closure finds every edge.
//! 4. **The source and encoding.** The moment's capacity use against `n*`; the path's openness;
//!    whether the per-window context the word reads (the rings' phase classes) separates the next
//!    bytes (online KT per context against order-0); whether the source ring's bins separate the
//!    bytes they hold; and the share of the current bin the recent cells make.
//!
//! [definition] **Exact inside and at the print; no decimal** (a decimal is a collapse, CLAUDE.md's
//! exact-arithmetic law). Every value is an exact rational, an exact integer, or an enclosure with
//! exact endpoints (the code lengths, as the exposure reads them), and every print is exact:
//! - bits (code lengths a cell, logit spreads and moves, `log₂ det`) are read at the receiver's
//!   grain `L_R` (16 in campaign 1) through `GrainCell::of`, `n + k/L_R + ε`: the carry `n`, the
//!   phase class `k` and the fibre `0 ≤ ε < 1/L_R`, exact, or enclosed exactly when it is long;
//! - a dimensionless quantity (a share, a scale, a leverage, a mean over counts) is its reduced
//!   ratio with its integer quotient and remainder when short, and otherwise the exact enclosure
//!   between its continued-fraction convergent and semiconvergent with denominators at most `2^12`
//!   (`∈ [a/b, c/d]`), with the exact ratio's size in bits;
//! - a share of counts is the count over the count, never a percentage; a comparison is an exact
//!   ordering with its exact difference.
//!
//! The cut is private: only its scope and counts are printed, never a cell.
//!
//! [established-bounded; measured] **Its receipt and reading** are the located-failure record,
//! `research/records/2026-09-25_CAMPAIGN_ONE_LOCATED_FAILURE.md` (about 10 minutes on the host).

#[path = "exterior.rs"]
mod exterior;

use std::collections::{BTreeMap, BTreeSet};
use std::ops::Range;
use std::time::Instant;

use holonics::hnn::constitution::{CAMPAIGN_ONE_BUDGET, Carrier, LinearLocus, Locus, Steps};
use holonics::hnn::keys::{self, KeyLocation};
use holonics::hnn::port::{ExecutionPort, Handle, ReceiptDetail};
use holonics::hnn::ratio::{Face, interval_sum, log2_enclosure};
use holonics::hnn::receiving::{GrainCell, ReceivingRead};
use holonics::hnn::reference::{Cut, one_hot};
use holonics::hnn::{Constitution, ConstitutionRead, Current, Field, FieldDeclaration, Reference, SourceMoment};
use holonics::ratio::Rat;
use holonics::ratio::algebraic::ExactInterval;
use holonics::ratio::linear::ExactRatMatrix;
use num_bigint::{BigInt, BigUint};
use num_traits::{One, Signed, ToPrimitive, Zero};

use exterior::read_cut;

/// The standing real cut (THE_REBUILD Decision 23), written by `standing_cut.py`.
const STANDING_CUT: &str = ".local/cuts/standing-real-cut-campaign-1.bin";

/// [agent-inferred] **The null's shuffles per crib**: the crib's own cells in 32 orders drawn by
/// SplitMix64 from a seed, so the null keeps the crib's port histogram and destroys its order.
const NULL_SHUFFLES: usize = 32;

/// [agent-inferred] **The local search's random starts** per crib (injective plugboards).
const SEARCH_STARTS: usize = 48;

/// [agent-inferred] **Synthetic trials per ring and crib length**, each a key and plugboard drawn by
/// SplitMix64.
const SYNTHETIC_TRIALS: usize = 16;

/// [agent-inferred] **The oracle's scale ceiling**: a read whose fitted scale `|s_j|` passes it is
/// scored by the enclosure `log₂ Σ_c 2^(f_c − f_t) ∈ [max_c(f_c − f_t), max_c(f_c − f_t) + log₂|A|]`
/// instead of the grain face, whose carried powers would reach `2^(−|s| · 13)`. Counted and printed.
const SCALE_CEILING: i64 = 256;

// -------------------------------------------------------------------------------------------
// exact helpers and the print

/// SplitMix64, for the null's shuffles and the synthetic cribs.
struct Draw(u64);

impl Draw {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn below(&mut self, bound: usize) -> usize {
        (self.next() % bound as u64) as usize
    }

    fn permutation(&mut self, n: usize) -> Vec<usize> {
        let mut items: Vec<usize> = (0..n).collect();
        for i in (1..n).rev() {
            let j = self.below(i + 1);
            items.swap(i, j);
        }
        items
    }
}

fn int(value: i64) -> Rat {
    Rat::from_integer(BigInt::from(value))
}

fn count(value: usize) -> Rat {
    Rat::from_integer(BigInt::from(value))
}

fn dot(a: &[Rat], b: &[Rat]) -> Rat {
    a.iter().zip(b).map(|(x, y)| x * y).sum()
}

fn max_abs<'a>(values: impl IntoIterator<Item = &'a Rat>) -> Rat {
    values
        .into_iter()
        .map(Signed::abs)
        .max()
        .unwrap_or_else(Rat::zero)
}

/// [agent-inferred] **A short exact ratio**: one whose numerator and denominator together take at
/// most 64 bits prints whole; a fibre prints whole up to twice that. A presentation bound
/// (exterior), never a law.
const SHORT_BITS: u64 = 64;

/// [agent-inferred] **The convergent bound**: a longer exact ratio prints as the exact enclosure
/// between its last continued-fraction convergent with denominator at most `2^12` and the nearest
/// semiconvergent on the value's other side within the same bound (the best enclosure by ratios of
/// that denominator). A presentation bound (exterior), never a law.
const CONVERGENT_DENOMINATOR: u64 = 1 << 12;

/// The bits of an exact ratio's numerator and denominator together.
fn size(value: &Rat) -> u64 {
    value.numer().bits() + value.denom().bits()
}

/// **The convergent enclosure** of an exact ratio (see [`CONVERGENT_DENOMINATOR`]): the value
/// itself when its denominator is within the bound; otherwise `p_n/q_n`, the last convergent within
/// the bound, and `(p_(n−1) + t p_n)/(q_(n−1) + t q_n)` with the largest `t` keeping the
/// denominator within it, which lie on opposite sides of the value.
fn convergents(value: &Rat) -> ExactInterval {
    let bound = BigInt::from(CONVERGENT_DENOMINATOR);
    // (p_(n−1), q_(n−1)) and (p_n, q_n), from (p_(−2), q_(−2)) = (0, 1) and (p_(−1), q_(−1)) = (1, 0).
    let (mut before, mut last) = ((BigInt::zero(), BigInt::one()), (BigInt::one(), BigInt::zero()));
    let mut rest = value.clone();
    loop {
        let term = rest.floor().to_integer();
        let next = (&term * &last.0 + &before.0, &term * &last.1 + &before.1);
        if next.1 > bound {
            break;
        }
        before = std::mem::replace(&mut last, next);
        let fraction = &rest - Rat::from_integer(term);
        if fraction.is_zero() {
            return ExactInterval::point(Rat::new(last.0, last.1));
        }
        rest = fraction.recip();
    }
    let t = (&bound - &before.1) / &last.1;
    let near = Rat::new(last.0.clone(), last.1.clone());
    let other = Rat::new(&before.0 + &t * &last.0, &before.1 + &t * &last.1);
    if near <= other {
        ExactInterval::new(near, other).expect("ordered")
    } else {
        ExactInterval::new(other, near).expect("ordered")
    }
}

/// An exact rational printed as an integer, `n/2^e` on a dyadic denominator, `n/(2^e·m)` on a
/// denominator with a power-of-two factor, or `n/d`.
fn exact(value: &Rat) -> String {
    let denominator = value.denom().magnitude();
    if denominator.is_one() {
        return value.numer().to_string();
    }
    let twos = denominator.trailing_zeros().unwrap_or(0);
    let odd = denominator >> twos;
    if denominator.bits() <= 16 {
        format!("{}/{}", value.numer(), denominator)
    } else if odd.is_one() {
        format!("{}/2^{twos}", value.numer())
    } else if twos > 0 {
        format!("{}/(2^{twos}·{odd})", value.numer())
    } else {
        format!("{}/{}", value.numer(), denominator)
    }
}

/// **A quantity, exactly**: a short ratio reduced, with its integer quotient and remainder when it
/// passes one (`n/d (q rem r over d)`); a long one as its integer quotient `q` and the convergent
/// enclosure of its remainder with exact endpoints, `q + ε, ε ∈ [a/b, c/d]`, and its exact size in
/// bits.
fn quantity(value: &Rat) -> String {
    let quotient = value.floor();
    if size(value) > SHORT_BITS {
        let enclosure = convergents(&(value - &quotient));
        return format!(
            "{} + ε, ε ∈ [{}, {}] (an exact ratio of {} bits)",
            quotient.to_integer(),
            exact(&enclosure.lower),
            exact(&enclosure.upper),
            size(value)
        );
    }
    if value.is_integer() {
        return value.numer().to_string();
    }
    let quotient = quotient.to_integer();
    if quotient.is_zero() {
        return exact(value);
    }
    let remainder = value.numer() - &quotient * value.denom();
    format!("{} ({quotient} rem {remainder} over {})", exact(value), value.denom())
}

/// The exact ratio `a/b` of two exact quantities (a count over a count, or an energy over an
/// energy), as a [`quantity`].
fn share(a: &Rat, b: &Rat) -> String {
    if b.is_zero() {
        return "- (no denominator)".to_string();
    }
    quantity(&(a / b))
}

/// An enclosure with exact endpoints: whole when both are short, else outward on the endpoints'
/// convergent enclosures.
fn enclosed(interval: &ExactInterval) -> String {
    let (lower, upper) = if size(&interval.lower) > SHORT_BITS || size(&interval.upper) > SHORT_BITS {
        (convergents(&interval.lower).lower, convergents(&interval.upper).upper)
    } else {
        (interval.lower.clone(), interval.upper.clone())
    };
    format!("[{}, {}]", exact(&lower), exact(&upper))
}

/// A fibre `0 ≤ ε < 1/L`: exact up to twice [`SHORT_BITS`], else its convergent enclosure.
fn fibre(value: &Rat) -> ExactInterval {
    if size(value) > 2 * SHORT_BITS {
        convergents(value)
    } else {
        ExactInterval::point(value.clone())
    }
}

/// **A reading at the receiver's grain** `L_R` (`GrainCell::of`): `value = n + k/L_R + ε`, the carry
/// `n`, the phase class `k ∈ ℤ/L_R` and the unresolved fibre `0 ≤ ε < 1/L_R` (exact, or enclosed
/// exactly when long).
fn reading(value: &Rat, grain: u64) -> String {
    reading_of(&ExactInterval::point(value.clone()), grain)
}

/// **An enclosure read at the grain**: both endpoints' cells; when they share their carry and phase
/// class, that cell once with the enclosure of its fibre.
fn reading_of(interval: &ExactInterval, grain: u64) -> String {
    let (lower, upper) = (GrainCell::of(&interval.lower, grain), GrainCell::of(&interval.upper, grain));
    let (low, high) = (fibre(&lower.fibre).lower, fibre(&upper.fibre).upper);
    if lower.carry == upper.carry && lower.phase == upper.phase {
        if low == high {
            format!("{} + {}/{grain} + ε, ε = {} < 1/{grain}", lower.carry, lower.phase, exact(&low))
        } else {
            format!("{} + {}/{grain} + ε, ε ∈ [{}, {}] ⊂ [0, 1/{grain})", lower.carry, lower.phase, exact(&low), exact(&high))
        }
    } else {
        format!(
            "[{} + {}/{grain} + {}, {} + {}/{grain} + {}] (each fibre < 1/{grain})",
            lower.carry,
            lower.phase,
            exact(&low),
            upper.carry,
            upper.phase,
            exact(&high)
        )
    }
}

/// **The grain cell alone** `n + k/L_R` of a value, its fibre `< 1/L_R` unresolved (the compact
/// form of a list).
fn cell(value: &Rat, grain: u64) -> String {
    let cell = GrainCell::of(value, grain);
    format!("{}+{}/{grain}", cell.carry, cell.phase)
}

/// An enclosure of bits per cell: the exact ratios `lower/n` and `upper/n` read at the grain.
fn per_cell(interval: &ExactInterval, cells: usize, grain: u64) -> String {
    if cells == 0 {
        return "-".to_string();
    }
    let n = count(cells);
    reading_of(
        &ExactInterval {
            lower: &interval.lower / &n,
            upper: &interval.upper / &n,
        },
        grain,
    )
}

fn zero_interval() -> ExactInterval {
    ExactInterval::point(Rat::zero())
}

/// `−log₂((n_x + ½)/(n + |A|/2))`: the online Krichevsky–Trofimov code length, enclosed.
fn kt(count: u64, total: u64, alphabet: usize) -> ExactInterval {
    log2_enclosure(&Rat::new(
        BigInt::from(2 * total) + BigInt::from(alphabet),
        BigInt::from(2 * count + 1),
    ))
    .expect("a positive argument")
}

/// The median of a list of exact values (the lower median on an even count).
fn median(values: &[Rat]) -> Rat {
    if values.is_empty() {
        return Rat::zero();
    }
    let mut sorted = values.to_vec();
    sorted.sort();
    sorted[(sorted.len() - 1) / 2].clone()
}

// -------------------------------------------------------------------------------------------
// the records the exposure gathers

/// One receiving phase of one window: its cell and target, the window's class configuration, the
/// path's openness at the cut, the model's and order-0's code lengths, the read feature
/// `z = P_R^(τ_R) v_R(e_j)`, the logits' spread `max_c Re f_c − min_c Re f_c`, and the recency
/// reading of the source ring's current bin.
#[derive(Clone)]
struct Read {
    cell: usize,
    target: usize,
    held_out: bool,
    aeon: usize,
    config: Vec<u64>,
    open: bool,
    model: ExactInterval,
    order_zero: ExactInterval,
    feature: Vec<Rat>,
    spread: Rat,
}

/// One locus's update at one deposit, from the carry's accounting.
#[derive(Clone, Default)]
struct LocusUpdate {
    exact_l1: Rat,
    applied_l1: Rat,
    carried_l1: Rat,
    released_l1: Rat,
    exact_max: Rat,
    applied_max: Rat,
    exact_entries: u64,
    applied_entries: u64,
}

impl LocusUpdate {
    /// The update of one map: `W' − W`, `r' − r` and the released tails `e` per entry.
    fn of(before: &ExactRatMatrix, after: &ExactRatMatrix, rem_before: &ExactRatMatrix, rem_after: &ExactRatMatrix, released: &BTreeMap<usize, Rat>) -> Self {
        let mut update = Self::default();
        for (index, ((w0, w1), (r0, r1))) in before
            .entries()
            .iter()
            .zip(after.entries())
            .zip(rem_before.entries().iter().zip(rem_after.entries()))
            .enumerate()
        {
            let applied = w1 - w0;
            let carried = r1 - r0;
            let tail = released.get(&index).cloned().unwrap_or_else(Rat::zero);
            let exact = &applied + &carried + &tail;
            if !applied.is_zero() {
                update.applied_entries += 1;
                update.applied_l1 += applied.abs();
                if applied.abs() > update.applied_max {
                    update.applied_max = applied.abs();
                }
            }
            if !exact.is_zero() {
                update.exact_entries += 1;
                update.exact_l1 += exact.abs();
                if exact.abs() > update.exact_max {
                    update.exact_max = exact.abs();
                }
            }
            update.carried_l1 += carried.abs();
            update.released_l1 += tail.abs();
        }
        update
    }
}

/// One deposit's reading: its aeon, each read feature's leverage `zᵀ X̂' z`, the read logits'
/// executed move against the covector's size, and the two linear loci's updates.
#[derive(Clone)]
struct DepositRecord {
    aeon: usize,
    leverage: Vec<Rat>,
    moved: Rat,
    covector: Rat,
    receiving: LocusUpdate,
    source: LocusUpdate,
    stepped: u64,
    released_bits: u64,
}

/// A menu's partial closure over injective plugboards (the fibre's own images): its ports, edges
/// and components; the best satisfied edges by propagation from every root and seed image (the
/// port's forced assignment, kept only when injective), under every key; the best found by local
/// search; and, for `d ≤ 7`, the exhaustive best.
#[derive(Clone)]
struct Closure {
    ports: usize,
    edges: usize,
    components: usize,
    propagated: usize,
    key_invariant: bool,
    searched: usize,
    exhaustive: Option<usize>,
}

/// **A sum of nonnegative exact values enclosed on `2^(−64)ℤ`**: each term's floor and ceiling
/// there, summed as integers. A running exact sum of terms with unrelated denominators carries their
/// lcm; the enclosure keeps exact endpoints at a fixed size.
#[derive(Clone, Default)]
struct Enclosed {
    lower: BigInt,
    upper: BigInt,
}

impl Enclosed {
    fn add(&mut self, value: &Rat) {
        let scaled = value * Rat::from_integer(BigInt::one() << 64);
        self.lower += scaled.floor().to_integer();
        self.upper += scaled.ceil().to_integer();
    }

    /// The share `self / (self + other)`, enclosed from the endpoints, printed outward on the
    /// endpoints' convergent enclosures (exact endpoints).
    fn share_of(&self, other: &Self) -> String {
        let low_total = &self.lower + &other.lower;
        let high_total = &self.upper + &other.upper;
        if high_total.is_zero() || low_total.is_zero() {
            return "- (no energy)".to_string();
        }
        let lower = convergents(&Rat::new(self.lower.clone(), high_total)).lower;
        let upper = convergents(&Rat::new(self.upper.clone(), low_total)).upper;
        format!("∈ [{}, {}]", exact(&lower), exact(&upper))
    }
}

/// One ring at one key location: the port's fibre reading, the crib's closure, and the null.
struct RingLocation {
    ring: usize,
    fibre: usize,
    orbits: usize,
    fell_back: bool,
    failing: Option<usize>,
    closure: Closure,
    null: Vec<Closure>,
}

struct LocationRecord {
    cell: usize,
    crib: Range<usize>,
    rings: Vec<RingLocation>,
}

/// Running sums of the logits' real parts over one population of reads.
struct LogitSums {
    sum: Vec<Rat>,
    squares: Rat,
    centred_squares: Rat,
    reads: usize,
}

impl LogitSums {
    fn new(classes: usize) -> Self {
        Self {
            sum: vec![Rat::zero(); classes],
            squares: Rat::zero(),
            centred_squares: Rat::zero(),
            reads: 0,
        }
    }

    fn add(&mut self, real: &[Rat]) {
        let mut total = Rat::zero();
        let mut squares = Rat::zero();
        for (entry, value) in self.sum.iter_mut().zip(real) {
            *entry += value;
            total += value;
            squares += value * value;
        }
        let centred = &squares - &total * &total / count(real.len());
        self.squares += squares;
        self.centred_squares += centred;
        self.reads += 1;
    }

    fn mean(&self) -> Vec<Rat> {
        let n = count(self.reads.max(1));
        self.sum.iter().map(|value| value / &n).collect()
    }
}

/// Everything the exposure gathered.
struct Run {
    reads: Vec<Read>,
    deposits: Vec<DepositRecord>,
    locations: Vec<LocationRecord>,
    aeon_cells: Vec<usize>,
    training: LogitSums,
    held: LogitSums,
    recency: Vec<(u64, u64)>,
    /// Over the training reads: `Σ|g_Re|²`, `Σ|g_Im|²` at the face, and `Σ|Rᵀg_Re|²`, `Σ|Rᵀg_Im|²`
    /// at the receiving anchor, each an enclosure on `2^(−64)ℤ` ([`Enclosed`]).
    covector_energy: [Enclosed; 4],
    /// `det H_T` of R's carried Gram at the end.
    gram_determinant: Rat,
    /// The published receiving map at the end (the held-out reads' map: no deposit follows).
    receiving_map: ExactRatMatrix,
    moment: SourceMoment,
    windows: u64,
    open: u64,
    published: usize,
    complete: bool,
    wall_ms: u128,
}

// -------------------------------------------------------------------------------------------
// the keys: partial closure of a crib's menu

/// The connected components of the menu's edge graph over its ports.
fn components(ports: &[usize], edges: &[(usize, usize)], width: usize) -> Vec<Vec<usize>> {
    let mut of: Vec<Option<usize>> = vec![None; width];
    let mut found: Vec<Vec<usize>> = Vec::new();
    for &start in ports {
        if of[start].is_some() {
            continue;
        }
        let index = found.len();
        let mut members = vec![start];
        of[start] = Some(index);
        let mut cursor = 0;
        while cursor < members.len() {
            let port = members[cursor];
            cursor += 1;
            for &(a, b) in edges {
                for (here, there) in [(a, b), (b, a)] {
                    if here == port && of[there].is_none() {
                        of[there] = Some(index);
                        members.push(there);
                    }
                }
            }
        }
        found.push(members);
    }
    found
}

/// **A crib's menu at key 0, charted for the search**: the menu ports, each edge as the pair of its
/// ports' indices with its stage's images at key 0, the period, and the components. The rotor gauge
/// `(k, S) ↦ (k + 1, S − 1)` carries every stage covariantly (`Machine.stage_succ`), so a plugboard
/// satisfying an edge set under key `k` maps to one satisfying it under key 0: the search runs at
/// key 0, and [`Closure::key_invariant`] checks the best by propagation under every key.
struct Charted {
    ports: usize,
    period: usize,
    edges: Vec<(usize, usize, Vec<usize>)>,
    components: usize,
}

/// A charted menu with every key's stage images per edge, its menu ports and its edges' ports.
type ChartedMenu = (Charted, Vec<Vec<Vec<usize>>>, Vec<usize>, Vec<(usize, usize)>);

fn chart_menu(field: &Field, ring: usize, crib: &[usize], offset: usize, configurations: &[u64]) -> ChartedMenu {
    let menu = keys::crib_menu(field, ring, crib, offset, configurations).expect("the crib's menu");
    let candidates = keys::candidate_keys(field, ring).expect("the ring's keys");
    let d = field.ring(ring).period() as usize;
    let ports = menu.menu_ports();
    let edges: Vec<(usize, usize)> = menu.edges().iter().map(|edge| (edge.from(), edge.to())).collect();
    let tables: Vec<Vec<Vec<usize>>> = candidates
        .iter()
        .map(|key| {
            menu.edges()
                .iter()
                .map(|edge| edge.stage(key).expect("a stage").images().to_vec())
                .collect()
        })
        .collect();
    let index_of: BTreeMap<usize, usize> = ports.iter().enumerate().map(|(i, &port)| (port, i)).collect();
    let charted = Charted {
        ports: ports.len(),
        period: d,
        edges: edges
            .iter()
            .zip(&tables[0])
            .map(|(&(a, b), table)| (index_of[&a], index_of[&b], table.clone()))
            .collect(),
        components: components(&ports, &edges, d).len(),
    };
    (charted, tables, ports, edges)
}

/// The edges an injective plugboard `images` (menu port index → image) satisfies at key 0.
fn satisfied(charted: &Charted, images: &[usize]) -> usize {
    charted
        .edges
        .iter()
        .filter(|(a, b, table)| images[*b] == table[images[*a]])
        .count()
}

/// **The exhaustive best** over every injective plugboard of the menu ports (`d!/(d − P)!` of them).
fn exhaustive_best(charted: &Charted) -> usize {
    fn descend(charted: &Charted, images: &mut Vec<usize>, used: &mut [bool], best: &mut usize) {
        if images.len() == charted.ports {
            *best = (*best).max(satisfied(charted, images));
            return;
        }
        for value in 0..charted.period {
            if !used[value] {
                used[value] = true;
                images.push(value);
                descend(charted, images, used, best);
                images.pop();
                used[value] = false;
            }
        }
    }
    let mut best = 0;
    descend(charted, &mut Vec::with_capacity(charted.ports), &mut vec![false; charted.period], &mut best);
    best
}

/// **The best found by local search** over injective plugboards: `SEARCH_STARTS` random injective
/// starts, each improved by the best single move (a port to an unused image, or two ports' images
/// swapped) until none improves.
fn searched_best(charted: &Charted, draw: &mut Draw) -> usize {
    let (p, d) = (charted.ports, charted.period);
    let mut best = 0;
    for _ in 0..SEARCH_STARTS {
        let mut images: Vec<usize> = draw.permutation(d)[..p].to_vec();
        let mut score = satisfied(charted, &images);
        loop {
            let mut improved: Option<(usize, Vec<usize>)> = None;
            for port in 0..p {
                for value in 0..d {
                    if value == images[port] {
                        continue;
                    }
                    let mut next = images.clone();
                    if let Some(other) = images.iter().position(|&image| image == value) {
                        next.swap(port, other);
                    } else {
                        next[port] = value;
                    }
                    let candidate = satisfied(charted, &next);
                    if candidate > improved.as_ref().map_or(score, |(s, _)| *s) {
                        improved = Some((candidate, next));
                    }
                }
            }
            match improved {
                Some((candidate, next)) => {
                    score = candidate;
                    images = next;
                }
                None => break,
            }
        }
        best = best.max(score);
    }
    best
}

/// **The crib's partial closure for one ring** at the configurations it is located under
/// (`keys::crib_menu`, the port's own menu), over injective plugboards: the best satisfied edges
/// (exhaustive for `d ≤ 7`, else by local search), and the best a propagation from every root and
/// seed image reaches under each key (the port's own forced assignment, kept only when injective),
/// equal under every key by the gauge.
fn closure(field: &Field, ring: usize, crib: &[usize], offset: usize, configurations: &[u64], draw: &mut Draw) -> Closure {
    let (charted, tables, ports, edges) = chart_menu(field, ring, crib, offset, configurations);
    let d = charted.period;
    let comps = components(&ports, &edges, d);
    let mut adjacency: Vec<Vec<(usize, usize)>> = vec![Vec::new(); d];
    for (index, &(a, b)) in edges.iter().enumerate() {
        adjacency[a].push((b, index));
        if a != b {
            adjacency[b].push((a, index));
        }
    }
    let mut per_key = Vec::with_capacity(tables.len());
    for table in &tables {
        let mut total = 0usize;
        for comp in &comps {
            let inside: Vec<usize> = (0..edges.len()).filter(|&e| comp.contains(&edges[e].0)).collect();
            let mut best = 0usize;
            for &root in comp {
                for seed in 0..d {
                    let mut image: Vec<Option<usize>> = vec![None; d];
                    image[root] = Some(seed);
                    let mut queue = vec![root];
                    let mut cursor = 0;
                    while cursor < queue.len() {
                        let here = queue[cursor];
                        cursor += 1;
                        let value = image[here].expect("reached");
                        for &(there, edge) in &adjacency[here] {
                            if image[there].is_none() {
                                image[there] = Some(table[edge][value]);
                                queue.push(there);
                            }
                        }
                    }
                    let assigned: Vec<usize> = comp.iter().map(|&port| image[port].expect("reached")).collect();
                    let distinct: BTreeSet<usize> = assigned.iter().copied().collect();
                    if distinct.len() != assigned.len() {
                        continue;
                    }
                    let count = inside
                        .iter()
                        .filter(|&&e| {
                            let (a, b) = edges[e];
                            image[b] == Some(table[e][image[a].expect("reached")])
                        })
                        .count();
                    best = best.max(count);
                }
            }
            total += best;
        }
        per_key.push(total);
    }
    let propagated = per_key.iter().copied().max().unwrap_or(0);
    let exhaustive = (d <= 7).then(|| exhaustive_best(&charted));
    Closure {
        ports: charted.ports,
        edges: charted.edges.len(),
        components: charted.components,
        propagated,
        key_invariant: per_key.iter().all(|&value| value == propagated),
        searched: searched_best(&charted, draw),
        exhaustive,
    }
}

/// The null: the crib's own cells in `NULL_SHUFFLES` orders.
fn null_closures(field: &Field, ring: usize, crib: &[usize], offset: usize, configurations: &[u64], seed: u64) -> Vec<Closure> {
    let mut draw = Draw(seed);
    (0..NULL_SHUFFLES)
        .map(|_| {
            let order = draw.permutation(crib.len());
            let shuffled: Vec<usize> = order.iter().map(|&i| crib[i]).collect();
            closure(field, ring, &shuffled, offset, configurations, &mut draw)
        })
        .collect()
}

/// **A synthetic crib generated by the declared ring with a true key and plugboard** (ring
/// `ring`'s own relation only): `S(port(x_(k+1))) = W_(key + steps(k)) S(port(x_k))`, each next cell
/// a byte of the forced port class drawn uniformly. The earlier rings run at phase 0.
struct SyntheticTrial {
    in_fibre: bool,
    fibre: usize,
    orbits: usize,
    published: bool,
    gauge_fixed: bool,
    truth_itself: bool,
    earlier_fell_back: bool,
    closing_carried: bool,
    closes_every_edge: bool,
}

fn synthetic_trial(field: &Field, ring: usize, length: usize, draw: &mut Draw) -> SyntheticTrial {
    let geometry = field.ring(ring);
    let d = geometry.period() as usize;
    let machine = geometry.machine().expect("the ring's machine");
    let clocks = keys::candidate_keys(field, ring).expect("keys");
    let key = draw.below(d);
    let plug = draw.permutation(d);
    let mut inverse = vec![0usize; d];
    for (port, &image) in plug.iter().enumerate() {
        inverse[image] = port;
    }
    let mut configurations = vec![0u64; field.rings().len()];
    configurations[ring] = key as u64;
    let opening: Vec<BigInt> = configurations.iter().map(|c| BigInt::from(*c)).collect();
    let mut lift = opening.clone();
    let mut cells = vec![draw.below(field.alphabet())];
    let mut steps = 0u64;
    for k in 0..length - 1 {
        let position = machine.position(&clocks[key], &BigUint::from(steps));
        let stage = machine.stage(&position).expect("a stage");
        let port = geometry.port(cells[k]);
        let next = inverse[stage.apply(plug[port]).expect("a port")];
        steps += u64::from(field.selective_step(&mut lift, cells[k]).expect("a cell").ticks[ring]);
        let representatives = (field.alphabet() - 1 - next) / d + 1;
        cells.push(next + d * draw.below(representatives));
    }
    field.selective_step(&mut lift, cells[length - 1]).expect("a cell");
    let location = keys::locate_keys(field, &Current::at(field, opening).expect("a lift"), &cells, 1).expect("location");
    let located = &location.rings[ring];
    let in_fibre = located.fibre.iter().any(|candidate| {
        (candidate.key.ticks() % BigUint::from(d)).to_usize() == Some(key)
            && located.menu_ports.iter().all(|&port| candidate.images.image(port) == Some(plug[port]))
    });
    let fixed = (key + plug[located.menu_ports[0]]) % d;
    let closing = keys::locate_closing(field, &Current::at(field, lift).expect("a lift"), &cells, 1).expect("closing location");
    let ticks = keys::crib_ticks(field, ring, &cells, &closing.configurations()).expect("ticks");
    let measured = closure(field, ring, &cells, 1, &location.configurations(), draw);
    SyntheticTrial {
        in_fibre,
        fibre: located.fibre.len(),
        orbits: located.orbits,
        published: located.published.is_some(),
        gauge_fixed: located.published == Some(fixed as u64),
        truth_itself: located.published == Some(key as u64),
        earlier_fell_back: location.rings[..ring].iter().all(|r| r.fell_back),
        closing_carried: closing.rings[ring].carried == Some((fixed as u64 + ticks) % d as u64),
        closes_every_edge: measured.exhaustive.unwrap_or(measured.searched) == measured.edges,
    }
}

// -------------------------------------------------------------------------------------------
// the exposure with its readings

fn phase_of(field: &Field, lift: &[BigInt]) -> Vec<u64> {
    field
        .rings()
        .iter()
        .zip(lift)
        .map(|(ring, tau)| {
            let d = BigInt::from(ring.period());
            let mut phase = tau % &d;
            if phase.is_negative() {
                phase += &d;
            }
            phase.to_u64().expect("a phase")
        })
        .collect()
}

fn released_map(released: &[(Locus, Carrier, usize, Rat)], locus: Locus) -> BTreeMap<usize, Rat> {
    let mut map = BTreeMap::new();
    for (at, carrier, entry, residual) in released {
        if *at == locus && *carrier == Carrier::Map {
            *map.entry(*entry).or_insert_with(Rat::zero) += residual;
        }
    }
    map
}

fn expose(field: &Field, cut: &Cut, deadline: Option<u64>) -> Run {
    let clock = Instant::now();
    let port = Reference::campaign_one();
    let mut resident = port.mount(field, &Current::at_rest(field)).expect("the mount");
    let phases = resident.admitted()[0].clone();
    let family = resident.admitted().to_vec();
    let receiving = phases.ring();
    let source = field.sources()[0];
    let aperture = phases.aperture();
    let alphabet = field.alphabet();
    let crib = field.crib();
    let cells = &cut.cells;
    let held = |position: usize| cut.held_out.iter().any(|range| range.contains(&position));
    let (moment, _) = port.ingest(&mut resident, None, &[]).expect("open the moment");
    let mut reads = Vec::new();
    let mut deposits = Vec::new();
    let mut locations = Vec::new();
    let mut aeon_cells = Vec::new();
    let mut training = LogitSums::new(alphabet);
    let mut held_sums = LogitSums::new(alphabet);
    let mut recency = Vec::new();
    let mut covector_energy = [Enclosed::default(), Enclosed::default(), Enclosed::default(), Enclosed::default()];
    let mut order_zero = vec![0u64; alphabet];
    let mut seen = 0u64;
    let (mut windows, mut open_windows, mut compares) = (0u64, 0u64, 0u64);
    let mut published = 0usize;
    let mut aeon = 0usize;
    let mut aeon_start = 0usize;
    // The source ring's phase class and the cells since it last moved (the recency reading).
    let mut run_length = 0u64;
    let mut last_phase: Option<u64> = None;
    let mut complete = true;
    let mut position = 0usize;
    while position < cells.len() {
        let end = (position + aperture).min(cells.len());
        let window = &cells[position..end];
        if window.len() == aperture && deadline.is_some_and(|limit| compares >= limit) {
            complete = false;
            break;
        }
        if window.len() == aperture {
            let lift = resident.current().lift().to_vec();
            let config = phase_of(field, &lift);
            let open_moment = resident.moment(&moment).expect("the moment");
            let bin: u64 = open_moment
                .phase_counts(source, config[source] as usize)
                .expect("the source ring's bin")
                .iter()
                .sum();
            recency.push((run_length, bin));
            let (pending, refined) = port.refine(&mut resident, &moment, &phases).expect("refine");
            windows += 1;
            let open = match &refined.receipt.detail {
                ReceiptDetail::Refine { path, .. } => path.open,
                _ => false,
            };
            open_windows += u64::from(open);
            let (staged, compared) = port.compare(&mut resident, pending, &one_hot(window)).expect("compare");
            compares += 1;
            let deposit = compared.deposit.present().cloned().expect("a compare stages its deposit");
            let holon = compared.forward.into_present().expect("a compare returns its ratio");
            let receiving_samples = deposit
                .linear()
                .iter()
                .find(|step| step.locus == LinearLocus::Receiving(receiving))
                .map(|step| step.samples.clone())
                .expect("the receiving map's samples");
            let windowed = (0..window.len()).any(|offset| held(position + offset));
            // The decoder's readings are the wave's `R z`: the count face's grain logits (Decision
            // 27; the masses the compare read, at the window's region) are taken out of the face.
            let count = phases
                .count_face(resident.constitution(), resident.moment(&moment).expect("the moment"))
                .expect("the count face");
            let stored: Vec<Rat> = count.logits().into_iter().step_by(2).collect();
            for (offset, (phase, &code)) in holon.phases().iter().zip(window).enumerate() {
                let logits = &holon.faces().logits[offset];
                let real: Vec<Rat> = logits
                    .iter()
                    .step_by(2)
                    .zip(&stored)
                    .map(|(face, count)| face - count)
                    .collect();
                let spread = real.iter().max().expect("classes") - real.iter().min().expect("classes");
                let is_held = held(position + offset);
                if is_held {
                    held_sums.add(&real);
                } else {
                    training.add(&real);
                }
                let zero = kt(order_zero[code], seen, alphabet);
                order_zero[code] += 1;
                seen += 1;
                reads.push(Read {
                    cell: position + offset,
                    target: code,
                    held_out: is_held,
                    aeon,
                    config: config.clone(),
                    open,
                    model: phase.code_length.clone(),
                    order_zero: zero,
                    feature: receiving_samples[offset].feature.clone(),
                    spread,
                });
            }
            if windowed {
                port.discard(&mut resident, Handle::Staged(staged)).expect("discard");
            } else {
                // The covector's magnitude (Re f) and phase (Im f) parts, at the face and pulled
                // back through Rᵀ to the receiving anchor (the rotation keeps norms), where every
                // other locus's covector starts.
                let map = resident.constitution().receiving_map(receiving).expect("R");
                let columns = map.columns();
                for sample in &receiving_samples {
                    // Within one sample the entries share the face's normalizer, so its sums stay
                    // small; across samples the normalizers differ, so the run's sums are carried
                    // as dyadic enclosures (an exact sum's denominator would be their lcm).
                    let mut pulled = [vec![Rat::zero(); columns], vec![Rat::zero(); columns]];
                    let mut energy = [Rat::zero(), Rat::zero()];
                    for (row, value) in sample.covector.iter().enumerate() {
                        if value.is_zero() {
                            continue;
                        }
                        let part = row % 2;
                        energy[part] += value * value;
                        for (k, entry) in map.entries()[row * columns..(row + 1) * columns].iter().enumerate() {
                            if !entry.is_zero() {
                                pulled[part][k] += entry * value;
                            }
                        }
                    }
                    covector_energy[0].add(&energy[0]);
                    covector_energy[1].add(&energy[1]);
                    covector_energy[2].add(&dot(&pulled[0], &pulled[0]));
                    covector_energy[3].add(&dot(&pulled[1], &pulled[1]));
                }
                let theta = resident.constitution();
                let r_before = theta.receiving_map(receiving).expect("R").clone();
                let r_rem_before = theta.receiving_law(receiving).expect("R's law").map_remainder();
                let e_before = theta.source_port(source).expect("E").clone();
                let e_rem_before = theta.source_law(source).expect("E's law").map_remainder();
                let returned = port.deposit(&mut resident, staged).expect("deposit (no budget stop on this cut)");
                let reading = returned.deposit.present().cloned().expect("a deposit's reading");
                let theta = resident.constitution();
                let r_after = theta.receiving_map(receiving).expect("R").clone();
                let r_law = theta.receiving_law(receiving).expect("R's law");
                let solved = r_law.solved();
                let r_update = LocusUpdate::of(
                    &r_before,
                    &r_after,
                    &r_rem_before,
                    &r_law.map_remainder(),
                    &released_map(&reading.released, Locus::ReceivingMap(receiving)),
                );
                let e_update = LocusUpdate::of(
                    &e_before,
                    theta.source_port(source).expect("E"),
                    &e_rem_before,
                    &theta.source_law(source).expect("E's law").map_remainder(),
                    &released_map(&reading.released, Locus::SourcePort(source)),
                );
                let applied = r_after.subtract(&r_before).expect("one shape");
                let mut leverage = Vec::new();
                let mut moved = Rat::zero();
                let mut covector = Rat::zero();
                for sample in &receiving_samples {
                    let reach = solved.apply(&sample.feature).expect("one width");
                    leverage.push(dot(&sample.feature, &reach));
                    let change = applied.apply(&sample.feature).expect("one width");
                    moved = moved.max(max_abs(&change));
                    covector = covector.max(max_abs(&sample.covector));
                }
                deposits.push(DepositRecord {
                    aeon,
                    leverage,
                    moved,
                    covector,
                    receiving: r_update,
                    source: e_update,
                    stepped: reading.stepped,
                    released_bits: reading.released_bits,
                });
            }
        } else {
            for &code in window {
                order_zero[code] += 1;
                seen += 1;
            }
        }
        let mut fed = 0;
        while fed < window.len() {
            let (_, ingested) = port.ingest(&mut resident, Some(&moment), &one_hot(&window[fed..])).expect("ingest");
            let ingested = ingested.forward.into_present().expect("ingest returns");
            // The recency reading: the source ring's phase after each cell fed.
            let fed_now = ingested.cells;
            let phase = phase_of(field, resident.current().lift())[source];
            // Ingest stops at a carry-out, so the phase read after a batch is the phase of its last
            // cell; within a two-cell window a move at the first cell and none at the second is
            // read as a move (the run restarts at the batch's cells).
            if last_phase == Some(phase) {
                run_length += fed_now as u64;
            } else {
                run_length = fed_now as u64;
                last_phase = Some(phase);
            }
            fed += fed_now;
            if ingested.carry_out {
                let _boundary = port.close_aeon(&mut resident, &family).expect("close the aeon");
                let at = position + fed;
                aeon_cells.push(at - aeon_start);
                aeon += 1;
                let span = cut.closing_crib(aeon_start, at, crib.window);
                if span.len() > crib.offset {
                    let crib_codes: Vec<usize> = cells[span.clone()].to_vec();
                    let located = port.locate_keys(&mut resident, &one_hot(&crib_codes), crib.offset).expect("locate keys");
                    let (fibres, orbits, fell_back, failing) = match &located.receipt.detail {
                        ReceiptDetail::Keys { fibres, orbits, fell_back, failing_loops, .. } => (
                            fibres.clone(),
                            orbits.clone(),
                            fell_back.clone(),
                            failing_loops.iter().map(|walk| walk.as_ref().map(Vec::len)).collect::<Vec<_>>(),
                        ),
                        _ => unreachable!("a key location's receipt"),
                    };
                    let location: KeyLocation = located.forward.into_present().expect("a key location");
                    published += location.rings.iter().filter(|ring| ring.published.is_some()).count();
                    let configurations = location.configurations();
                    let rings = (0..field.rings().len())
                        .map(|g| RingLocation {
                            ring: g,
                            fibre: fibres[g],
                            orbits: orbits[g],
                            fell_back: fell_back[g],
                            failing: failing[g],
                            closure: closure(field, g, &crib_codes, crib.offset, &configurations, &mut Draw(0x5EA2_0000 + (at as u64) * 16 + g as u64)),
                            null: null_closures(field, g, &crib_codes, crib.offset, &configurations, 0x5EED_0000 + (at as u64) * 16 + g as u64),
                        })
                        .collect();
                    locations.push(LocationRecord { cell: at, crib: span, rings });
                }
                aeon_start = at;
            }
        }
        position = end;
    }
    let gram = resident
        .constitution()
        .receiving_law(receiving)
        .expect("R's law")
        .gram()
        .to_rows();
    Run {
        reads,
        deposits,
        locations,
        aeon_cells,
        training,
        held: held_sums,
        recency,
        covector_energy,
        gram_determinant: determinant(gram),
        receiving_map: resident.constitution().receiving_map(receiving).expect("R").clone(),
        moment: resident.moment(&moment).expect("the moment").clone(),
        windows,
        open: open_windows,
        published,
        complete,
        wall_ms: clock.elapsed().as_millis(),
    }
}

// -------------------------------------------------------------------------------------------
// scoring a static or scaled face at the receiver's grain

/// **The face of a real logit vector at the grain**, the machine's own ([`Face::of_read`]), its
/// imaginary parts zero (the phase part does not enter a code length).
fn face_of(real: &[Rat], grain: u64) -> Face {
    let logits: Vec<Rat> = real.iter().flat_map(|value| [value.clone(), Rat::zero()]).collect();
    let read = ReceivingRead {
        cells: real.iter().map(|value| GrainCell::of(value, grain)).collect(),
        phases: vec![Rat::zero(); real.len()],
        logits,
    };
    Face::of_read(&read, grain).expect("a face")
}

/// The code length of a target under `f = s · y` at the grain: the machine's face when `|s|` is
/// within the ceiling; otherwise the enclosure `[m, m + log₂|A|]`, `m = max_c (f_c − f_t)`.
fn scaled_code(scale: &Rat, y: &[Rat], target: usize, grain: u64) -> (ExactInterval, bool) {
    if scale.abs() <= int(SCALE_CEILING) {
        let real: Vec<Rat> = y.iter().map(|value| scale * value).collect();
        (face_of(&real, grain).code_length(target).expect("a code length"), false)
    } else {
        let at = scale * &y[target];
        let top = y.iter().map(|value| scale * value - &at).max().expect("classes").max(Rat::zero());
        let width = log2_enclosure(&count(y.len())).expect("log2 |A|");
        (ExactInterval::new(top.clone(), top + width.upper).expect("ordered"), true)
    }
}

/// The exact determinant of a square rational matrix by Gaussian elimination over ℚ.
fn determinant(mut rows: Vec<Vec<Rat>>) -> Rat {
    let n = rows.len();
    let mut det = Rat::one();
    for column in 0..n {
        let Some(pivot) = (column..n).find(|&row| !rows[row][column].is_zero()) else {
            return Rat::zero();
        };
        if pivot != column {
            rows.swap(pivot, column);
            det = -det;
        }
        let head = rows[column][column].clone();
        det *= &head;
        let pivot_row = rows[column].clone();
        for row in rows.iter_mut().skip(column + 1) {
            if row[column].is_zero() {
                continue;
            }
            let factor = &row[column] / &head;
            for (entry, top) in row.iter_mut().zip(&pivot_row).skip(column) {
                *entry -= &factor * top;
            }
        }
    }
    det
}

/// Euclid's greatest common divisor of two integers.
fn gcd(a: &BigInt, b: &BigInt) -> BigInt {
    let (mut a, mut b) = (a.abs(), b.abs());
    while !b.is_zero() {
        let r = &a % &b;
        a = b;
        b = r;
    }
    a
}

/// The exact least-squares solution `w` of `wᵀ z_j = 1` over a population of features (a particular
/// solution of `G w = b`, `G = Σ z zᵀ`, `b = Σ z`), with the Gram's rank and the reach
/// `bᵀw / N = 1 − residual/N`. The sums are formed over integers on the features' common
/// denominator (they lie on the word's dyadic lattice) and each entry normalized once.
fn constant_fit(features: &[Vec<Rat>]) -> (Vec<Rat>, usize, Rat) {
    let n = features.first().map_or(0, Vec::len);
    let mut denominator = BigInt::one();
    for feature in features {
        for value in feature {
            let d = value.denom();
            if !(&denominator % d).is_zero() {
                denominator = &denominator / gcd(&denominator, d) * d;
            }
        }
    }
    let scale = Rat::from_integer(denominator.clone());
    let mut g_int = vec![vec![BigInt::zero(); n]; n];
    let mut b_int = vec![BigInt::zero(); n];
    for feature in features {
        let integers: Vec<BigInt> = feature.iter().map(|value| (value * &scale).to_integer()).collect();
        for i in 0..n {
            if integers[i].is_zero() {
                continue;
            }
            b_int[i] += &integers[i];
            for j in i..n {
                g_int[i][j] += &integers[i] * &integers[j];
            }
        }
    }
    let square = &denominator * &denominator;
    let mut gram = vec![vec![Rat::zero(); n]; n];
    let b: Vec<Rat> = b_int.iter().map(|value| Rat::new(value.clone(), denominator.clone())).collect();
    for i in 0..n {
        for j in i..n {
            let value = Rat::new(g_int[i][j].clone(), square.clone());
            gram[i][j] = value.clone();
            gram[j][i] = value;
        }
    }
    let matrix = ExactRatMatrix::new(gram).expect("a square Gram");
    let rank = matrix.rank().expect("a rank");
    let w = matrix
        .preimage_fibre(&b)
        .expect("a fibre")
        .map(|(particular, _)| particular)
        .expect("b lies in the Gram's image");
    let reach = dot(&b, &w) / count(features.len().max(1));
    (w, rank, reach)
}

// -------------------------------------------------------------------------------------------
// the report

fn main() {
    let arguments: Vec<String> = std::env::args().skip(1).collect();
    let mut path = STANDING_CUT.to_string();
    let mut deadline: Option<u64> = None;
    for pair in arguments.chunks(2) {
        match pair {
            [key, value] if key == "cut-file" => path = value.clone(),
            [key, value] if key == "windows" => deadline = Some(value.parse().expect("a deadline in windows")),
            _ => {
                println!("usage: hnn_diagnose [cut-file <path>] [windows <deadline>]");
                return;
            }
        }
    }
    let (bytes, population, held_range) = read_cut(&path);
    assert_eq!(bytes.len(), population, "the cut file's length is the manifest's population");
    let field = Field::declare(FieldDeclaration::campaign_one(population as u64)).expect("campaign 1's field");
    let cut = Cut {
        cells: bytes.iter().map(|&byte| usize::from(byte)).collect(),
        held_out: vec![held_range.clone()],
    };
    // The receiver's grain L_R = ⌈1/ε_bits⌉ (16 in campaign 1), at which every bit count is read.
    let grain: u64 = field.receivers()[0]
        .tolerance
        .recip()
        .ceil()
        .to_integer()
        .try_into()
        .expect("a grain fits a machine word");
    let receiving = field.receivers()[0].ring;
    let width = field.ring(receiving).width();
    println!("hnn_diagnose: campaign 1's declared field over the cut file {path}");
    println!(
        "cut: {population} cells (n* = {}), held out {}..{} ({} cells); receiving ring {receiving} (d = {}, realified width {width}), grain L_R = {grain}",
        field.capacity().n_star(),
        held_range.start,
        held_range.end,
        held_range.len(),
        field.ring(receiving).period()
    );

    // ---- keys on synthetic cribs (fast, independent of the exposure) ----
    println!();
    println!("== 3b. keys on synthetic cribs generated by the declared ring (a true key and plugboard; the earlier rings at phase 0) ==");
    let mut draw = Draw(0x00C0_FFEE);
    for length in [field.crib().window, 512] {
        for ring in 0..field.rings().len() {
            let trials: Vec<SyntheticTrial> = (0..SYNTHETIC_TRIALS).map(|_| synthetic_trial(&field, ring, length, &mut draw)).collect();
            let tally = |f: fn(&SyntheticTrial) -> bool| trials.iter().filter(|t| f(t)).count();
            let fibres: Vec<usize> = trials.iter().map(|t| t.fibre).collect();
            let orbits: Vec<usize> = trials.iter().map(|t| t.orbits).collect();
            println!(
                "crib {length} cells, ring {ring} (d = {}): truth in the fibre {}/{}; empty fibres {}; one orbit and published {}/{}; published = the truth's gauge-fixed member {}/{}; published = the truth's own key {}/{}; carried to the boundary correctly (locate_closing) {}/{}; earlier rings fell back {}/{}; the injective partial closure finds every edge satisfied {}/{}; fibre sizes min {} max {}; orbits min {} max {}",
                field.ring(ring).period(),
                tally(|t| t.in_fibre),
                trials.len(),
                trials.iter().filter(|t| t.fibre == 0).count(),
                tally(|t| t.published),
                trials.len(),
                tally(|t| t.gauge_fixed),
                trials.len(),
                tally(|t| t.truth_itself),
                trials.len(),
                tally(|t| t.closing_carried),
                trials.len(),
                tally(|t| t.earlier_fell_back),
                trials.len(),
                tally(|t| t.closes_every_edge),
                trials.len(),
                fibres.iter().min().unwrap_or(&0),
                fibres.iter().max().unwrap_or(&0),
                orbits.iter().min().unwrap_or(&0),
                orbits.iter().max().unwrap_or(&0),
            );
        }
    }

    // ---- the exposure ----
    println!();
    let run = expose(&field, &cut, deadline);
    println!(
        "== the exposure (the port's protocol, step for step): {} ms wall (exterior); {} windows, {} deposits, {} aeon boundaries, {} key locations, {} keys published; {} ==",
        run.wall_ms,
        run.windows,
        run.deposits.len(),
        run.aeon_cells.len(),
        run.locations.len(),
        run.published,
        if run.complete { "complete" } else { "INCOMPLETE at its deadline" }
    );
    let training: Vec<&Read> = run.reads.iter().filter(|r| !r.held_out).collect();
    let held: Vec<&Read> = run.reads.iter().filter(|r| r.held_out).collect();
    let sum = |reads: &[&Read], f: fn(&Read) -> &ExactInterval| {
        reads.iter().fold(zero_interval(), |total, read| interval_sum(&total, f(read)).expect("a sum"))
    };
    let (model_train, zero_train) = (sum(&training, |r| &r.model), sum(&training, |r| &r.order_zero));
    let (model_held, zero_held) = (sum(&held, |r| &r.model), sum(&held, |r| &r.order_zero));
    println!(
        "check against #73's receipt: held-out model {} bits a cell, order-0 KT {}; training model {}, order-0 KT {}",
        per_cell(&model_held, held.len(), grain),
        per_cell(&zero_held, held.len(), grain),
        per_cell(&model_train, training.len(), grain),
        per_cell(&zero_train, training.len(), grain)
    );

    // ---- 1. the decoder ----
    println!();
    println!("== 1. the decoder: the receiving face f_j = R · P_R^(τ_R) v_R(e_j), no constant term ==");
    let targets_held: Vec<usize> = held.iter().map(|r| r.target).collect();
    let score_static = |real: &[Rat], targets: &[usize]| -> ExactInterval {
        let face = face_of(real, grain);
        let mut cache: BTreeMap<usize, ExactInterval> = BTreeMap::new();
        targets.iter().fold(zero_interval(), |total, &t| {
            let code = cache.entry(t).or_insert_with(|| face.code_length(t).expect("a code length")).clone();
            interval_sum(&total, &code).expect("a sum")
        })
    };
    for (label, sums) in [("training reads", &run.training), ("held-out reads", &run.held)] {
        let mean = sums.mean();
        let n = count(sums.reads.max(1));
        let mean_squares: Rat = mean.iter().map(|x| x * x).sum::<Rat>() * &n;
        let mean_total: Rat = mean.iter().sum();
        let mean_centred = &mean_squares - &mean_total * &mean_total / count(mean.len()) * &n;
        let spread = mean.iter().max().expect("classes") - mean.iter().min().expect("classes");
        let code = score_static(&mean, &targets_held);
        println!(
            "mean logit vector over the {} {label}: spread max_c − min_c {} bits; its static face on the held-out targets {} bits a cell; common part of the logits' energy N|f̄|²/Σ|f|² {}; of the class-centred energy {}",
            sums.reads,
            reading(&spread, grain),
            per_cell(&code, targets_held.len(), grain),
            share(&mean_squares, &sums.squares),
            share(&mean_centred, &sums.centred_squares)
        );
    }
    let spreads: Vec<Rat> = held.iter().map(|r| r.spread.clone()).collect();
    println!(
        "each held-out read's own spread max_c Re f_c − min_c Re f_c: median {} bits, largest {} bits",
        reading(&median(&spreads), grain),
        reading(&spreads.iter().max().cloned().unwrap_or_else(Rat::zero), grain)
    );

    // Order-0 log-frequencies of the training cells, KT prior, read at 2^-20 (exterior target).
    let alphabet = field.alphabet();
    let mut counts = vec![0u64; alphabet];
    for read in &training {
        counts[read.target] += 1;
    }
    let total = training.len() as u64;
    let unit = BigInt::from(1u64 << 20);
    let y: Vec<Rat> = counts
        .iter()
        .map(|&c| {
            let bits = log2_enclosure(&Rat::new(BigInt::from(2 * c + 1), BigInt::from(2 * total) + BigInt::from(alphabet))).expect("log2");
            Rat::new((&bits.lower * Rat::from_integer(unit.clone())).floor().to_integer(), unit.clone())
        })
        .collect();
    let static_code = score_static(&y, &targets_held);
    println!(
        "static order-0 face (the training cells' KT frequencies as log2 logits y, read at the grain): held-out {} bits a cell; the spread of y {} bits",
        per_cell(&static_code, targets_held.len(), grain),
        reading(&(y.iter().max().expect("classes") - y.iter().min().expect("classes")), grain)
    );

    // Features: rank, dormant component, energy by aeon.
    let train_features: Vec<Vec<Rat>> = training.iter().map(|r| r.feature.clone()).collect();
    let held_features: Vec<Vec<Rat>> = held.iter().map(|r| r.feature.clone()).collect();
    let (w, rank, reach) = constant_fit(&train_features);
    let nodes = width / 2;
    // The receiving ring's dormant mode: the rotation-invariant sums over its nodes, real and
    // imaginary (the kernel of its unit-weight cycle Laplacian), `u = (Σ_i z_(2i), Σ_i z_(2i+1))`.
    let dormant_of = |z: &[Rat]| -> Vec<Rat> {
        vec![z.iter().step_by(2).sum::<Rat>(), z.iter().skip(1).step_by(2).sum::<Rat>()]
    };
    let mut dormant_energy = Rat::zero();
    let mut energy = Rat::zero();
    let (mut mean_re, mut mean_im, mut mean_sq) = (Rat::zero(), Rat::zero(), Rat::zero());
    for z in &train_features {
        let u = dormant_of(z);
        dormant_energy += (&u[0] * &u[0] + &u[1] * &u[1]) / count(nodes);
        energy += dot(z, z);
        mean_re += &u[0];
        mean_im += &u[1];
        mean_sq += &u[0] * &u[0] + &u[1] * &u[1];
    }
    let n_train = count(train_features.len().max(1));
    let zeros = train_features.iter().filter(|z| z.iter().all(Zero::is_zero)).count();
    println!(
        "read features z (training, {} reads): rank {} of {width}; identically zero on {} reads; the dormant (rotation-invariant) component's share of their energy {}; its stability |Σu|²/(N Σ|u|²) {}",
        train_features.len(),
        rank,
        zeros,
        share(&dormant_energy, &energy),
        share(&(&mean_re * &mean_re + &mean_im * &mean_im), &(&mean_sq * &n_train)),
    );
    let mut by_aeon: BTreeMap<usize, (Rat, usize, Rat, Rat)> = BTreeMap::new();
    for read in &run.reads {
        let e = dot(&read.feature, &read.feature);
        let entry = by_aeon.entry(read.aeon).or_insert_with(|| (Rat::zero(), 0, e.clone(), e.clone()));
        entry.0 += &e;
        entry.1 += 1;
        if e < entry.2 {
            entry.2 = e.clone();
        }
        if e > entry.3 {
            entry.3 = e;
        }
    }
    for (aeon, (sum_e, n, least, most)) in &by_aeon {
        println!(
            "  aeon {aeon}: mean |z|² {} over {n} reads (least {}, largest {})",
            quantity(&(sum_e / count(*n))),
            quantity(least),
            quantity(most)
        );
    }

    // The oracle: R = y wᵀ, f_j = s_j y.
    let dormant_features: Vec<Vec<Rat>> = train_features.iter().map(|z| dormant_of(z)).collect();
    let (_, rank_dormant, reach_dormant) = constant_fit(&dormant_features);
    println!(
        "the constant's reach from the features (bᵀw/N = 1 − the least-squares residual of wᵀz_j = 1 per read, training reads): {} from all {width} coordinates; {} from the dormant component alone (rank {rank_dormant})",
        share(&reach, &Rat::one()),
        share(&reach_dormant, &Rat::one())
    );
    let (w_held, rank_held, reach_held) = constant_fit(&held_features);
    println!(
        "on the held-out reads alone (in-sample, the final medium): rank {rank_held}; reach {}",
        share(&reach_held, &Rat::one())
    );
    for (label, weights) in [("w fitted on the training reads", &w), ("w fitted on the held-out reads (in-sample bound)", &w_held)] {
        let scales: Vec<Rat> = held.iter().map(|r| dot(weights, &r.feature)).collect();
        let negative = scales.iter().filter(|s| s.is_negative()).count();
        let near = scales.iter().filter(|s| **s >= Rat::new(BigInt::one(), BigInt::from(2)) && **s <= int(2)).count();
        let mut total_code = zero_interval();
        let mut ceiling = 0usize;
        for (read, scale) in held.iter().zip(&scales) {
            let (code, over) = scaled_code(scale, &y, read.target, grain);
            ceiling += usize::from(over);
            total_code = interval_sum(&total_code, &code).expect("a sum");
        }
        let open_scales: Vec<Rat> = held.iter().zip(&scales).filter(|(r, _)| r.open).map(|(_, s)| s.clone()).collect();
        let shut_scales: Vec<Rat> = held.iter().zip(&scales).filter(|(r, _)| !r.open).map(|(_, s)| s.clone()).collect();
        println!(
            "oracle R = y wᵀ ({label}): held-out {} bits a cell through the grain face; scales s_j = wᵀz_j on the held-out reads: median {}, least {}, largest {}, negative {}/{}, within [1/2, 2] {}/{}; median on open-path reads {}, on shielded reads {}; reads past the scale ceiling {}",
            per_cell(&total_code, held.len(), grain),
            quantity(&median(&scales)),
            quantity(&scales.iter().min().cloned().unwrap_or_else(Rat::zero)),
            quantity(&scales.iter().max().cloned().unwrap_or_else(Rat::zero)),
            negative,
            scales.len(),
            near,
            scales.len(),
            quantity(&median(&open_scales)),
            quantity(&median(&shut_scales)),
            ceiling
        );
    }

    // The held-out logits split into the declared prior's reading and the learned part: every
    // held-out read uses the final map (no deposit follows), so f = R z = R_0 z + (R − R_0) z.
    let initial = Constitution::initial(&field, Steps::campaign_one(), CAMPAIGN_ONE_BUDGET).expect("the initial constitution");
    let prior = initial.receiving_map(receiving).expect("R_0").clone();
    let learned = run.receiving_map.subtract(&prior).expect("one shape");
    let centred = |values: &[Rat]| -> Vec<Rat> {
        let mean = values.iter().sum::<Rat>() / count(values.len());
        values.iter().map(|value| value - &mean).collect()
    };
    let real_rows = |map: &ExactRatMatrix, z: &[Rat]| -> Vec<Rat> { map.apply(z).expect("one width").into_iter().step_by(2).collect() };
    let (mut prior_code, mut learned_code, mut total_code) = (zero_interval(), zero_interval(), zero_interval());
    let (mut prior_energy, mut learned_energy, mut total_energy, mut cross) = (Rat::zero(), Rat::zero(), Rat::zero(), Rat::zero());
    let mut marginal_prior = Rat::zero();
    let mut marginal_learned = Rat::zero();
    let y_centred = centred(&y);
    let y_energy = dot(&y_centred, &y_centred);
    for read in &held {
        let p = centred(&real_rows(&prior, &read.feature));
        let l = centred(&real_rows(&learned, &read.feature));
        let t: Vec<Rat> = p.iter().zip(&l).map(|(a, b)| a + b).collect();
        prior_code = interval_sum(&prior_code, &face_of(&p, grain).code_length(read.target).expect("a code length")).expect("a sum");
        learned_code = interval_sum(&learned_code, &face_of(&l, grain).code_length(read.target).expect("a code length")).expect("a sum");
        total_code = interval_sum(&total_code, &face_of(&t, grain).code_length(read.target).expect("a code length")).expect("a sum");
        prior_energy += dot(&p, &p);
        learned_energy += dot(&l, &l);
        total_energy += dot(&t, &t);
        cross += dot(&p, &l);
        marginal_prior += dot(&p, &y_centred);
        marginal_learned += dot(&l, &y_centred);
    }
    if !held.is_empty() && !total_energy.is_zero() {
    println!(
        "the held-out logits (class-centred) split into f = R_0 z + (R − R_0) z: the declared sign prior's reading R_0 z alone codes the held-out targets in {} bits a cell, the learned part (R − R_0) z alone in {}, the sum in {} (the machine's own read, a check); energy shares over Σ|f|²: Σ|R_0 z|² {}, Σ|(R − R_0) z|² {}, their inner product 2⟨R_0 z, (R − R_0) z⟩ {}; alignment with the order-0 log-frequencies y (Σ⟨part, ȳ⟩ over Σ|ȳ|² per read): prior {}, learned {}",
        per_cell(&prior_code, held.len(), grain),
        per_cell(&learned_code, held.len(), grain),
        per_cell(&total_code, held.len(), grain),
        quantity(&(&prior_energy / &total_energy)),
        quantity(&(&learned_energy / &total_energy)),
        quantity(&(&cross * int(2) / &total_energy)),
        quantity(&(&marginal_prior / (&y_energy * count(held.len())))),
        quantity(&(&marginal_learned / (&y_energy * count(held.len())))),
    );
    }

    // ---- 2. learning ----
    println!();
    println!("== 2. learning: the normal law's prox step on R (ring {receiving}) and E_0, per deposit ==");
    let r_unit = field.lattice(Locus::ReceivingMap(receiving)).expect("R's lattice").unit();
    let e_unit = field.lattice(Locus::SourcePort(field.sources()[0])).expect("E's lattice").unit();
    println!("lattice units: R {}, E_0 {}", exact(&r_unit), exact(&e_unit));
    let mut totals: BTreeMap<usize, Vec<&DepositRecord>> = BTreeMap::new();
    for record in &run.deposits {
        totals.entry(record.aeon).or_default().push(record);
    }
    let summarize = |records: &[&DepositRecord], label: &str| {
        let n = count(records.len().max(1));
        let leverage: Vec<Rat> = records.iter().flat_map(|r| r.leverage.iter().cloned()).collect();
        let leverage_sum: Rat = leverage.iter().sum();
        let moved: Vec<Rat> = records.iter().map(|r| r.moved.clone()).collect();
        let ratio: Vec<Rat> = records
            .iter()
            .filter(|r| !r.covector.is_zero())
            .map(|r| &r.moved / &r.covector)
            .collect();
        let pick = |f: fn(&LocusUpdate) -> &Rat, which: fn(&DepositRecord) -> &LocusUpdate| -> Rat {
            records.iter().map(|r| f(which(r)).clone()).sum()
        };
        let r_exact = pick(|u| &u.exact_l1, |r| &r.receiving);
        let r_applied = pick(|u| &u.applied_l1, |r| &r.receiving);
        let r_released = pick(|u| &u.released_l1, |r| &r.receiving);
        let e_exact = pick(|u| &u.exact_l1, |r| &r.source);
        let e_applied = pick(|u| &u.applied_l1, |r| &r.source);
        let e_released = pick(|u| &u.released_l1, |r| &r.source);
        let r_entries: u64 = records.iter().map(|r| r.receiving.applied_entries).sum();
        let r_exact_entries: u64 = records.iter().map(|r| r.receiving.exact_entries).sum();
        let e_entries: u64 = records.iter().map(|r| r.source.applied_entries).sum();
        let e_exact_entries: u64 = records.iter().map(|r| r.source.exact_entries).sum();
        let r_max: Vec<Rat> = records.iter().map(|r| &r.receiving.exact_max / &r_unit).collect();
        let e_max: Vec<Rat> = records.iter().map(|r| &r.source.exact_max / &e_unit).collect();
        println!(
            "{label} ({} deposits): leverage h = zᵀX̂'z per read feature: median {}, mean {}, sum {}; the read logits' executed move max_c|(R'−R)z|: median {} bits, largest {}; against the covector's max|g|: median ratio {}",
            records.len(),
            quantity(&median(&leverage)),
            quantity(&(&leverage_sum / count(leverage.len().max(1)))),
            quantity(&leverage_sum),
            reading(&median(&moved), grain),
            reading(&moved.iter().max().cloned().unwrap_or_else(Rat::zero), grain),
            quantity(&median(&ratio)),
        );
        println!(
            "    R: entries moved on the lattice per deposit {} (mean, of 11,264; exact update nonzero on {} mean); exact update's largest entry per deposit, in lattice units: median {}, largest {}; applied share of the exact update's l1 {}; released tails' share {}",
            quantity(&(count(r_entries as usize) / &n)),
            quantity(&(count(r_exact_entries as usize) / &n)),
            quantity(&median(&r_max)),
            quantity(&r_max.iter().max().cloned().unwrap_or_else(Rat::zero)),
            share(&r_applied, &r_exact),
            share(&r_released, &r_exact),
        );
        println!(
            "    E_0: entries moved on the lattice per deposit {} (mean, of 2,560; exact update nonzero on {} mean); exact update's largest entry per deposit, in lattice units: median {}, largest {}; applied share of the exact update's l1 {}; released tails' share {}",
            quantity(&(count(e_entries as usize) / &n)),
            quantity(&(count(e_exact_entries as usize) / &n)),
            quantity(&median(&e_max)),
            quantity(&e_max.iter().max().cloned().unwrap_or_else(Rat::zero)),
            share(&e_applied, &e_exact),
            share(&e_released, &e_exact),
        );
        let stepped: u64 = records.iter().map(|r| r.stepped).sum();
        let released_bits: u64 = records.iter().map(|r| r.released_bits).sum();
        println!(
            "    every locus: entries whose lattice coordinate moved {} per deposit (mean); released residuals' exact bits {} per deposit (mean)",
            quantity(&(count(stepped as usize) / &n)),
            quantity(&(count(released_bits as usize) / &n))
        );
    };
    let everything: Vec<&DepositRecord> = run.deposits.iter().collect();
    summarize(&everything, "all deposits");
    // The prox step's total leverage is bounded by the Gram's growth: log det is concave, so
    // log det H' − log det H ≥ tr(H'⁻¹ ΔH) = Σ_j f_jᵀ H'⁻¹ f_j at every deposit, and over the run
    // Σ h ≤ ln det H_T (H_0 = I); the read logits' executed move is γ g h per read.
    let leverage_total: Rat = run.deposits.iter().flat_map(|r| r.leverage.iter()).sum();
    let log_det = log2_enclosure(&run.gram_determinant).expect("a positive determinant");
    // ln 2 ∈ [445/642, 1143/1649]: consecutive continued-fraction convergents of ln 2, on opposite
    // sides of it (the convergents of [0; 1, 2, 3, 1, 6, 3, 1, 1, 2, …]).
    let ln_det = ExactInterval::new(
        &log_det.lower * Rat::new(BigInt::from(445), BigInt::from(642)),
        &log_det.upper * Rat::new(BigInt::from(1143), BigInt::from(1649)),
    )
    .expect("det H_T ≥ 1 (H_0 = I and the Gram only grows)");
    let leverage_point = ExactInterval::point(leverage_total.clone());
    let side = if leverage_point.upper < ln_det.lower {
        "below"
    } else if leverage_point.lower > ln_det.upper {
        "ABOVE"
    } else {
        "undecided against"
    };
    println!(
        "the prox step's leverage budget: Σ h over every read {} against ln det H_T = log2 det H_T · ln 2 ∈ {} (R's carried Gram at the end; log2 det H_T: {} bits, at L_R = {grain}: {}; ln 2 ∈ [445/642, 1143/1649]); Σ h is {side} its bound, ln det H_T − Σ h ∈ {}",
        quantity(&leverage_total),
        enclosed(&ln_det),
        enclosed(&log_det),
        reading_of(&log_det, grain),
        enclosed(&ExactInterval {
            lower: &ln_det.lower - &leverage_total,
            upper: &ln_det.upper - &leverage_total,
        })
    );
    let [re, im, pulled_re, pulled_im] = &run.covector_energy;
    println!(
        "the covector over the training reads (sums enclosed on 2^-64): phase (Im f) share of its energy at the face {}; at the receiving anchor, pulled back through Rᵀ (where every other locus's covector starts, E_0's included), the phase share {}",
        im.share_of(re),
        pulled_im.share_of(pulled_re)
    );
    for (aeon, records) in &totals {
        summarize(records, &format!("aeon {aeon}"));
    }
    println!("training bits by aeon (the model against online order-0 KT on the same cells), and the held-out reads:");
    let mut aeons: BTreeMap<(usize, bool), (ExactInterval, ExactInterval, usize, Rat)> = BTreeMap::new();
    for read in &run.reads {
        let entry = aeons.entry((read.aeon, read.held_out)).or_insert_with(|| (zero_interval(), zero_interval(), 0, Rat::zero()));
        entry.0 = interval_sum(&entry.0, &read.model).expect("a sum");
        entry.1 = interval_sum(&entry.1, &read.order_zero).expect("a sum");
        entry.2 += 1;
        entry.3 += &read.spread;
    }
    for ((aeon, is_held), (model, zero, n, spread)) in &aeons {
        println!(
            "  aeon {aeon} {}: {n} cells; model {} bits a cell, order-0 KT {}; mean logit spread {} bits",
            if *is_held { "held out" } else { "training" },
            per_cell(model, *n, grain),
            per_cell(zero, *n, grain),
            reading(&(spread / count(*n)), grain)
        );
    }
    println!(
        "training bits a cell by block of 512 cells (model | order-0 KT; the grain cells n+k/{grain} of the lower endpoints, each fibre < 1/{grain} unresolved):"
    );
    let mut line = String::new();
    for block in training.chunks(512) {
        let model = block.iter().fold(zero_interval(), |t, r| interval_sum(&t, &r.model).expect("sum"));
        let zero = block.iter().fold(zero_interval(), |t, r| interval_sum(&t, &r.order_zero).expect("sum"));
        let n = count(block.len());
        line.push_str(&format!(
            " {}|{}",
            cell(&(&model.lower / &n), grain),
            cell(&(&zero.lower / &n), grain)
        ));
    }
    println!(" {line}");
    println!("aeon lengths (cells): {:?}", run.aeon_cells);

    // ---- 3. the keys on the real cut ----
    println!();
    println!("== 3a. keys on the standing cut: per key location and ring, the crib's best partial closure against its shuffles ==");
    for location in &run.locations {
        println!("key location at cell {} (crib {}..{}, {} cells):", location.cell, location.crib.start, location.crib.end, location.crib.len());
        for ring in &location.rings {
            let c = &ring.closure;
            let best_of = |closure: &Closure| closure.exhaustive.unwrap_or(closure.searched);
            let best = best_of(c);
            let forest = c.ports - c.components;
            let loops = c.edges - forest;
            let null: Vec<usize> = ring.null.iter().map(best_of).collect();
            let null_mean = count(null.iter().sum()) / count(null.len().max(1));
            let at_least = null.iter().filter(|&&value| value >= best).count();
            println!(
                "  ring {} (d = {}): port fibre {} in {} orbits, {}; shortest failing loop {} edges. Menu: {} ports, {} edges, {} component(s), {} independent loops. Injective plugboards: best satisfied edges {}/{} ({} by {}), so {} of the {} loops beyond a spanning forest close; by propagation {}, equal under every key: {}; local search {}. The crib shuffled ({} orders): best mean {} (share {}), largest {}; shuffles at or above the crib's best: {}/{}",
                ring.ring,
                field.ring(ring.ring).period(),
                ring.fibre,
                ring.orbits,
                if ring.fell_back { "fell back" } else { "published" },
                ring.failing.map_or("-".to_string(), |n| n.to_string()),
                c.ports,
                c.edges,
                c.components,
                loops,
                best,
                c.edges,
                if c.exhaustive.is_some() { "exhaustive" } else { "local search" },
                if c.exhaustive.is_some() { "every injective plugboard" } else { "48 starts" },
                best.saturating_sub(forest),
                loops,
                c.propagated,
                c.key_invariant,
                c.searched,
                ring.null.len(),
                quantity(&null_mean),
                quantity(&(&null_mean / count(c.edges.max(1)))),
                null.iter().max().unwrap_or(&0),
                at_least,
                null.len(),
            );
        }
    }

    // ---- 4. the source and encoding ----
    println!();
    println!("== 4. the source and encoding ==");
    let capacity = field.capacity();
    for n in [64u64, 512, 2048, 4096, 4958, capacity.n_star() - 1, capacity.n_star()] {
        let bits = capacity.state_bits(n);
        println!(
            "  n = {n}: counted source state ceil(log2 N(n)) = {bits} bits against the source's 8n = {} ({}); lossy by counting: {}",
            8 * n,
            share(&count(bits as usize), &count(8 * n as usize)),
            capacity.lossy_at(n)
        );
    }
    println!(
        "  the moment's dense bits at the end: {} over {} cells ({} per source bit)",
        run.moment.dense_bits(),
        run.moment.cells(),
        share(&count(run.moment.dense_bits() as usize), &count(8 * run.moment.cells() as usize))
    );
    let open_train = training.iter().filter(|r| r.open).count();
    let open_held = held.iter().filter(|r| r.open).count();
    println!(
        "  the source-to-receiver path open at the cut: {} of {} windows ({} of {} training reads, {} of {} held-out reads)",
        run.open,
        run.windows,
        open_train,
        training.len(),
        open_held,
        held.len()
    );
    for (label, reads) in [("training", &training), ("held out", &held)] {
        for open in [true, false] {
            let chosen: Vec<&Read> = reads.iter().copied().filter(|r| r.open == open).collect();
            let model = sum(&chosen, |r| &r.model);
            let zero = sum(&chosen, |r| &r.order_zero);
            println!(
                "    {label}, path {}: {} reads; model {} bits a cell, order-0 KT {}",
                if open { "open" } else { "shielded" },
                chosen.len(),
                per_cell(&model, chosen.len(), grain),
                per_cell(&zero, chosen.len(), grain)
            );
        }
    }
    // Contexts: what the word reads per window beyond the cumulative moment.
    type Context = fn(&Read, &[usize]) -> Vec<u64>;
    let contexts: [(&str, Context); 6] = [
        ("none (order-0 KT)", |_, _| Vec::new()),
        ("the source ring's phase τ_0 mod 5", |r, _| vec![r.config[0]]),
        ("the receiving ring's phase τ_2 mod 11", |r, _| vec![r.config[2]]),
        ("the class configuration (τ_0, τ_1, τ_2, τ_3)", |r, _| r.config.clone()),
        ("the configuration with the path's openness", |r, _| {
            let mut c = r.config.clone();
            c.push(u64::from(r.open));
            c
        }),
        ("the previous cell (order-1 KT, for reference)", |r, cells| vec![if r.cell == 0 { 0 } else { cells[r.cell - 1] as u64 }]),
    ];
    let configs: BTreeSet<Vec<u64>> = run.reads.iter().map(|r| r.config.clone()).collect();
    let bytes_seen: BTreeSet<usize> = run.reads.iter().map(|r| r.target).collect();
    println!(
        "  the per-window context the word reads: {} distinct class configurations over {} windows (of 5·7·11·13 = 5,005); {} distinct next bytes",
        configs.len(),
        run.windows,
        bytes_seen.len()
    );
    for (label, context) in contexts {
        let mut tables: BTreeMap<Vec<u64>, (Vec<u64>, u64)> = BTreeMap::new();
        let (mut train_code, mut held_code) = (zero_interval(), zero_interval());
        for read in &run.reads {
            let key = context(read, &cut.cells);
            let (table, seen) = tables.entry(key).or_insert_with(|| (vec![0u64; alphabet], 0));
            let code = kt(table[read.target], *seen, alphabet);
            table[read.target] += 1;
            *seen += 1;
            if read.held_out {
                held_code = interval_sum(&held_code, &code).expect("a sum");
            } else {
                train_code = interval_sum(&train_code, &code).expect("a sum");
            }
        }
        println!(
            "    online KT given {label}: {} contexts; training {} bits a cell, held out {}",
            tables.len(),
            per_cell(&train_code, training.len(), grain),
            per_cell(&held_code, held.len(), grain)
        );
    }
    // The source ring's bins: does the bin a byte lands in separate it?
    let source = field.sources()[0];
    let mut lift: Vec<BigInt> = Current::at_rest(&field).lift().to_vec();
    let mut binned: Vec<(Vec<u64>, u64)> = vec![(vec![0u64; alphabet], 0); field.ring(source).period() as usize];
    let mut pooled = (vec![0u64; alphabet], 0u64);
    let (mut bin_code, mut pool_code) = (zero_interval(), zero_interval());
    for &code in cut.cells.iter() {
        field.selective_step(&mut lift, code).expect("a cell");
        let phase = phase_of(&field, &lift)[source] as usize;
        let (table, seen) = &mut binned[phase];
        bin_code = interval_sum(&bin_code, &kt(table[code], *seen, alphabet)).expect("a sum");
        table[code] += 1;
        *seen += 1;
        pool_code = interval_sum(&pool_code, &kt(pooled.0[code], pooled.1, alphabet)).expect("a sum");
        pooled.0[code] += 1;
        pooled.1 += 1;
    }
    println!(
        "  the source ring's bins (each cell coded online by KT within the bin it lands in, against pooled order-0; no key was published, so the lift is the declared stepping): binned {} bits a cell, pooled {}; the bins' final populations {:?}",
        per_cell(&bin_code, cut.cells.len(), grain),
        per_cell(&pool_code, cut.cells.len(), grain),
        binned.iter().map(|(_, seen)| *seen).collect::<Vec<_>>()
    );
    let fractions: Vec<Rat> = run
        .recency
        .iter()
        .filter(|(_, bin)| *bin > 0)
        .map(|(run_length, bin)| Rat::new(BigInt::from(*run_length.min(bin)), BigInt::from(*bin)))
        .collect();
    let bins: Vec<Rat> = run.recency.iter().map(|(_, bin)| count(*bin as usize)).collect();
    let runs: Vec<Rat> = run.recency.iter().map(|(r, _)| count(*r as usize)).collect();
    println!(
        "  recency: the cells since the source ring last moved (the only recent cells in its current bin): median {}; the current bin's count: median {}; their share of the bin: median {}, mean {}",
        quantity(&median(&runs)),
        quantity(&median(&bins)),
        quantity(&median(&fractions)),
        quantity(&(fractions.iter().sum::<Rat>() / count(fractions.len().max(1))))
    );
}
