# H4: the data -> menu map, runnable and non-circular.
#  ports      : Z/d, the ring's nodes; port(x) = x mod d (declared exterior residue chart, known).
#  stepping   : steps(k) = #{j < k : port(x_j) in N}, N the declared lock: needs no key, no plugboard.
#  stage      : the reflected return at the earlier cell's position, rho^-m F rho^m, m = key + steps(k)
#               (compression::keys::ReflectorMachine::stage / position).  One stage per contact.
#  menu edge  : cells (x_k, x_{k+1}) at offset 1 -> edge port(x_k) -- port(x_{k+1}) labelled k;
#               every pair of the crib window enters; no admission depends on the key.
#  candidate  : key in Z/d with the plugboard images S at the menu's ports.
#  propagation: for each key and each image of one seed port per component, S(v) = stage_k S(u)
#               along edges; refuse on a conflict or a repeated image (the diagonal board).
# Checked against brute force over all d! plugboards.  Synthetic cut generated by a true machine.
import itertools, random

d = 7
rho = [(i + 1) % d for i in range(d)]
def power(p, m):
    out = list(range(d))
    for _ in range(m % d): out = [p[i] for i in out]
    return out
def inv(p):
    q = [0] * d
    for i, v in enumerate(p): q[v] = i
    return q
def comp(p, q): return [p[q[i]] for i in range(d)]           # p after q
F_ = [1, 0, 3, 2, 5, 4, 6]                                     # reflector: an involution of Z/7
def stage(m): return comp(inv(power(rho, m)), comp(F_, power(rho, m)))
N = {1, 4}                                                     # declared lock on the port chart

def synth(key, S, n, rng):
    Sinv = inv(S); p = [rng.randrange(d)]; steps = 0; st = []
    for k in range(n - 1):
        st.append(steps)
        p.append(Sinv[stage(key + steps)[S[p[k]]]])
        steps += 1 if p[k] in N else 0
    return p, st

def edges_of(p, st): return [(p[k], p[k + 1], st[k]) for k in range(len(p) - 1)]

def brute(E, ports):
    out = []
    for key in range(d):
        for S in itertools.permutations(range(d)):
            if all(S[v] == stage(key + s)[S[u]] for u, v, s in E): out.append((key, tuple(S[x] for x in ports)))
    return sorted(set(out)), d * 5040

def propagate(E, ports):
    adj = {x: [] for x in ports}
    for u, v, s in E: adj[u].append((v, s)); adj[v].append((u, s))   # stages are involutions
    comps, seen = [], set()
    for x in ports:
        if x in seen: continue
        c, stack = [], [x]; seen.add(x)
        while stack:
            y = stack.pop(); c.append(y)
            for z, _ in adj[y]:
                if z not in seen: seen.add(z); stack.append(z)
        comps.append(sorted(c))
    out, work = [], 0
    for key in range(d):
        partial = [dict()]
        for c in comps:
            nxt = []
            for img in range(d):
                S = {c[0]: img}; queue = [c[0]]; ok = True
                while queue and ok:
                    y = queue.pop()
                    for z, s in adj[y]:
                        work += 1
                        w = stage(key + s)[S[y]]
                        if z in S:
                            ok = S[z] == w
                            if not ok: break
                        else: S[z] = w; queue.append(z)
                if ok and len(set(S.values())) == len(S): nxt.append(S)
            partial = [{**a, **b} for a in partial for b in nxt
                       if not set(a.values()) & set(b.values())]
        out += [(key, tuple(S[x] for x in ports)) for S in partial]
    return out, work

rng = random.Random(4)
for n in (6, 10, 16, 40):
    key, S = 3, [4, 0, 6, 2, 1, 5, 3]
    p, st = synth(key, S, n, rng)
    E = edges_of(p, st); ports = sorted(set(p))
    b, bw = brute(E, ports); pr, pw = propagate(E, ports)
    truth = (key, tuple(S[x] for x in ports))
    fixed = [c for c in pr if c[1][0] == 0]                     # gauge fixed: S(least port) = 0
    print(f"n={n:3d} ports={len(ports)} edges={len(E)}: brute {len(b)} == propagation {len(pr)}: "
          f"{sorted(b) == sorted(pr)}; truth in fibre {truth in pr}; work {pw} vs {bw}; "
          f"gauge-fixed members {len(fixed)}")
# a cut the machine did not produce: random ports
p = [rng.randrange(d) for _ in range(40)]
st = [sum(1 for j in range(k) if p[j] in N) for k in range(39)]
pr, pw = propagate(edges_of(p, st), sorted(set(p)))
print("random (unproduced) cut of 40 cells: fibre size", len(pr), "-> fallback to the declared configuration")

# A crib of independent pairs: at each position k a cell x_k and its reflected return y_k
# (the Bombe's plaintext/ciphertext pairs); positions advance by the lock on x_k's port.
print("independent crib pairs (edges port(x_k) -- port(y_k) at position k):")
for n in (4, 8, 16):
    key, S = 3, [4, 0, 6, 2, 1, 5, 3]; Sinv = inv(S); steps = 0; E = []
    for k in range(n):
        x = rng.randrange(d); y = Sinv[stage(key + steps)[S[x]]]
        E.append((x, y, steps)); steps += 1 if x in N else 0
    ports = sorted({u for u, _, _ in E} | {v for _, v, _ in E})
    b, bw = brute(E, ports); pr, pw = propagate(E, ports)
    truth = (key, tuple(S[x] for x in ports))
    orbit = {((key + t) % d, tuple(power(inv(rho), t)[S[x]] for x in ports)) for t in range(d)}
    fixed = [c for c in pr if c[1][0] == 0]
    print(f"  n={n:3d} ports={len(ports)}: brute {len(b)} == propagation {len(pr)}: {sorted(b) == sorted(pr)}; "
          f"truth in {truth in pr}; fibre == rotor-gauge orbit of truth: {set(pr) == orbit}; "
          f"gauge-fixed members {len(fixed)}; work {pw} vs {bw}")
